// Code generated by "pipeline"; DO NOT EDIT.

// passive: Millennial Hymn # Weapon_Catalyst_MenulisRing
//
//	When the equipping character's Elemental Skill deals Hydro or Dendro DMG, they will
//	gain Prayer of the Far North: Elemental Mastery is increased by 60 for 4.5s. When
//	nearby party members trigger Lunar-Bloom reactions, the equipping character gains
//	New Moon Verse: Elemental Mastery is increased by 60 for 10s. When both Prayer of
//	the Far North and New Moon Verse are in effect, all nearby party members' Bloom DMG
//	is increased by 120%, their Hyperbloom and Burgeon DMG is increased by 80%, and their
//	Lunar-Bloom DMG is increased by 40%. This effect cannot stack. The aforementioned
//	effects can be triggered even if the equipping character is off-field.
package nightweavers

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.NightweaversLookingGlass, NewWeapon)
}
