package_name: venti
genshin_id: 10000022
key: venti
icd_groups:
  - group_name: ICDGroupVenti
    reset_timer: 60
    ele_app_sequence:
      [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
  attack:
    aim:
      - 6 # Aimed Shot|{param6:F1P}
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}+{param0:F1P}
      - 0 # 1-Hit DMG|{param0:F1P}+{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    attack_4:
      - 3 # 4-Hit DMG|{param3:F1P}+{param3:F1P}
      - 3 # 4-Hit DMG|{param3:F1P}+{param3:F1P}
    attack_5:
      - 4 # 5-Hit DMG|{param4:F1P}
    attack_6:
      - 5 # 6-Hit DMG|{param5:F1P}
    fullaim:
      - 7 # Fully-Charged Aimed Shot|{param7:P}
    highPlunge:
      - 10 # Low/High Plunge DMG|{param9:P}/{param10:P}
  skill:
    skillHold:
      - 2 # Hold DMG|{param2:P}
    skillPress:
      - 0 # #{LAYOUT_MOBILE#Tap}{LAYOUT_PC#Press}{LAYOUT_PS#Press} DMG|{param0:P}
  burst:
    burstAbsorbDot:
      - 1 # Additional Elemental DMG|{param1:F1P}
    burstDot:
      - 0 # DoT|{param0:F1P}
