id: 10000022
key: "venti"
rarity: QUALITY_ORANGE
body: BODY_BOY
region: ASSOC_TYPE_MONDSTADT
element: Wind
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Venti"
stats: {
   base_hp: 819.8552
   base_atk: 20.482
   base_def: 52.0521
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 702.9517
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 44.631
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 17.56018
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1202.4174
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 76.3425
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 30.03715
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.08
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1868.3716
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 118.6245
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 46.67311
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.16
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2367.8374
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 150.336
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 59.15008
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.16
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2867.303
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 182.0475
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 71.62705
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.24
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3366.7688
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 213.759
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 84.10402
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.32
      }
   }
}
skill_details: {
   skill: 10224
   burst: 10225
   attack: 10221
   burst_energy_cost: 60
}
name_text_hash_map: 2466140362
