// Code generated by "pipeline"; DO NOT EDIT.

// set2: Gladiator's Finale
//
//	ATK +18%.
//
// set4: Gladiator's Finale # Relic_MeleeAttackUp
//
//	If the wielder of this artifact set uses a Sword, Claymore or Polearm, increases
//	their Normal Attack DMG by 35%.
package gladiator

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterSetFunc(keys.GladiatorsFinale, NewSet)
}
