// Code generated by "pipeline"; DO NOT EDIT.

// passive: Kaidan: Rainfall Earthbinder # Weapon_Sword_Kasabouzu
//
//	After an attack hits opponents, it will inflict an instance of Cursed Parasol upon
//	one of them for 10s. This effect can be triggered once every 15s. If this opponent
//	is defeated during Cursed Parasol's duration, Cursed Parasol's CD will be refreshed
//	immediately. The character wielding this weapon will deal 16% more DMG to the opponent
//	affected by Cursed Parasol.
package toukaboushigure

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.ToukabouShigure, NewWeapon)
}
