// Code generated by "pipeline"; DO NOT EDIT.

// passive: Cadence of Days Gone By # Weapon_Pole_GlintstonePolearm
//
//	Triggering an Elemental Reaction regenerates 4 Elemental Energy for the equipping
//	character. This effect can trigger once every 9s. On the other hand, triggering a
//	Stellar Glimmer reaction increases their ATK by 20% for 12s. The aforementioned effects
//	can trigger even when the character is not on the field.
package songofthevigil

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.SongOfTheVigil, NewWeapon)
}
