use: pipeline
kind: character
name: xilonen

shortcuts:
  - xilo

combat:
  icd_tags:
    - XilonenSkate

talents:
  - attack:
      - attack(1-Hit DMG)
      - - attack(2-Hit DMG)
        - attack(2-Hit DMG|1)
      - attack(3-Hit DMG)
  - ca: attack(Charged Attack DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)
  - attackE:
      - attack(Blade Roller 1-Hit DMG)
      - attack(Blade Roller 2-Hit DMG)
      - attack(Blade Roller 3-Hit DMG)
      - attack(Blade Roller 4-Hit DMG)

  - skillDMG: skill(Rush DMG)
  - skillShred: skill(Elemental RES Decrease)

  - burstDMG: burst(Skill DMG)
  - burstHealPer: burst(Continuous Healing)
  - burstHealBase: burst(Continuous Healing|1)
  - burstFollowDMG: burst(Follow-Up Beat DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/18E4Aa-DlVSUdM_B8LQOsIDraX_ghxuNaM59zpAo1mLc/edit?usp=sharing
      count_credit: shizukayuki
      video: https://youtu.be/lyzsRRzBogE
      video_credit: shizukayuki

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 2.1
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2-1
        shape: Circle
        center: Player
        offset: [0, -0.5]
        fan_angle: 150
        radius: 2.5
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2-2
        shape: Circle
        center: Player
        offset: [0, -0.5]
        fan_angle: 150
        radius: 2.7
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Circle
        center: Player
        offset: [0, -0.5]
        fan_angle: 160
        radius: 3.2
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: E-N1
        shape: Circle
        center: Player
        offset: [0, 0.7]
        fan_angle: 270
        radius: 2.7
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: E-N2
        shape: Box
        center: Player
        offset: [0, -0.5]
        box: [5, 3.7]
        hitlag: {time: 0.03, scale: 0.01}

      - name: E-N3
        shape: Box
        center: Player
        offset: [0, -0.5]
        box: [3.5, 4.5]
        hitlag: {time: 0.03, scale: 0.01}

      - name: E-N4
        shape: Circle
        center: Player
        offset: [0, 0.6]
        fan_angle: 270
        radius: 3.5
        hitlag: {time: 0.06, scale: 0.01}

  - name: charge
    note: Need to use attack right before charge. Cannot charge in nightsoul blessing
    hitbox:
      - name: CA
        shape: Box
        center: Player
        offset: [0, -1.8]
        box: [2, 4.5]

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example. Cannot low plunge in nightsoul blessing.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.

  - name: skill
    hitbox:
      - name: E
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 0.8
        hitlag: {scale: 0.01, defense_halt: true, deployable: true}

  - name: burst
    hitbox:
      - name: Q
        shape: Circle
        center: Player
        radius: 7
