use: pipeline
kind: character
name: chiori

override:
  icd_group:
    ChioriSkill:
      name: Chiori_ElementArt

combat:
  icd_tags:
    - ChioriSkill
  icd_groups:
    - ChioriSkill

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG|1)
      - attack(4-Hit DMG)
  - charge:
      - attack(Charged Attack DMG)
      - attack(Charged Attack DMG|1)
  - plunge: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - turretAtkScaling: skill(Tamoto DMG)
  - turretDefScaling: skill(Tamoto DMG|1)
  - turretDuration: skill(Tamoto Duration)
  - turretInterval: skill(Tamoto Attack Interval)
  - thrustAtkScaling: skill(Upward Sweep Attack DMG)
  - thrustDefScaling: skill(Upward Sweep Attack DMG|1)

  - burstAtkScaling: burst(Skill DMG)
  - burstDefScaling: burst(Skill DMG|1)
  - burstCD: burst(CD)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1XHPuw9CDIFaeiJ1xQAH7VOPqKAIqipyL62RHxp9hbNg/edit?usp=sharing
      count_credit: shizukayuki
      video: https://youtu.be/T_qhsR5X8dw
      video_credit: clevernt
    - count: https://docs.google.com/spreadsheets/d/1XHPuw9CDIFaeiJ1xQAH7VOPqKAIqipyL62RHxp9hbNg/edit?usp=sharing
      count_credit: shizukayuki
      video: https://youtu.be/yQqwL9vAmLQ
      video_credit: shizukayuki

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 1.6
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.8
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3-1
        shape: Box
        center: Player
        offset: [0, -0.6]
        box: [1.8, 3.6]
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N3-2
        shape: Box
        center: Player
        offset: [0, -0.6]
        box: [1.8, 3.6]

      - name: N4
        shape: Circle
        center: Player
        offset: [0, 0.9]
        radius: 2.8
        hitlag: {scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA-1
        shape: Circle
        center: Player
        offset: [0, 1.4]
        radius: 2.3

      - name: CA-2
        shape: Circle
        center: Player
        offset: [0, 1.6]
        radius: 2.4
        hitlag: {scale: 0.01, defense_halt: true}

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be skill[hold=1].

  - name: skill
    params:
      hold: 0 for Tap (default), 1 for Hold.
    hitbox:
      - name: E-UpwardThrust
        shape: Box
        center: Player
        box: [5.5, 3.5]

      - name: E-Tamoto
        shape: Circle
        center: PrimaryTarget
        radius: 1.2

  - name: burst
    hitbox:
      - name: Q
        note: This is an approximation because we do not actually know the real AoE.
        shape: Circle
        center: Player
        radius: 12

  - name: asc
    hitbox:
      - name: A1-Tapestry
        note: Spawns on target that A1 Tapestry proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 2.5

  - name: cons
    hitbox:
      - name: Kinu
        shape: Circle
        center: PrimaryTarget
        radius: 1.2

  - name: walk
    note: Everything except normal followed by walk has proper frames.
