id: 10000094
key: "chiori"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_INAZUMA
element: Rock
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Chiori"
stats: {
   base_hp: 890.4009
   base_atk: 25.137
   base_def: 74.1892
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 763.43823
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 63.612
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.55113
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1305.8812
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 108.81
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 36.863773
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2029.1385
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 169.074
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 57.280636
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2571.5815
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 214.272
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 72.59328
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3114.0244
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 259.47
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 87.90592
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3656.4673
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 304.668
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 103.21857
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10942
   burst: 10945
   attack: 10941
   burst_energy_cost: 50
}
name_text_hash_map: 1944606922
