id: 10000094
key: "chiori"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_INAZUMA
element: Rock
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Chiori"
stats: {
   base_hp: 890.40087890625
   base_atk: 25.136999130249023
   base_def: 74.18920135498047
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 763.438232421875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 63.61199951171875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.551130294799805
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1305.8812255859375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 108.80999755859375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 36.863773345947266
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.04800000041723251
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2029.1385498046875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 169.07400512695312
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 57.280635833740234
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.09600000083446503
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2571.58154296875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 214.27200317382812
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 72.59327697753906
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.09600000083446503
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3114.0244140625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 259.4700012207031
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 87.90592193603516
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.14399999380111694
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3656.46728515625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 304.6679992675781
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 103.21856689453125
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.19200000166893005
      }
   }
}
skill_details: {
   skill: 10942
   burst: 10945
   attack: 10941
   burst_energy_cost: 50
}
name_text_hash_map: 1944606922
