package_name: sara
genshin_id: 10000056
key: sara
skill_data_mapping:
    attack:
        aim:
            - 5 # Aimed Shot|{param5:F1P}
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        attack_5:
            - 4 # 5-Hit DMG|{param4:F1P}
        fullaim:
            - 6 # Fully-Charged Aimed Shot|{param6:P}
    skill:
        atkBuff:
            - 1 # ATK Bonus Ratio|{param1:P}
        skill:
            - 0 # Tengu Juurai: Ambush DMG|{param0:F1P}
    burst:
        burstCluster:
            - 1 # Tengu Juurai: Stormcluster DMG|{param1:F1P}
        burstMain:
            - 0 # Tengu Juurai: Titanbreaker DMG|{param0:F1P}
