id: 10000089
key: "furina"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_FONTAINE
element: Water
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Furina"
stats: {
   base_hp: 1191.65
   base_atk: 18.9924
   base_def: 54.14615
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1021.7321
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 46.4265
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 16.283075
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1747.6997
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 79.41375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 27.85263
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2715.6565
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 123.39675
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 43.2787
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3441.624
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 156.384
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 54.848255
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4167.592
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 189.37125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 66.41781
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4893.559
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 222.3585
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 77.987366
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10892
   burst: 10895
   attack: 10891
   burst_energy_cost: 60
}
name_text_hash_map: 2180900234
