package_name: furina
genshin_id: 10000089
key: furina
action_param_keys:
    low_plunge:
      - param: "collision"
    high_plunge:
      - param: "collision"
icd_tags:
  - ICDTagFurinaChevalmarin
  - ICDTagFurinaUsher
icd_groups:
  - group_name: ICDGroupFurinaSalonSolitaire
    reset_timer: 1800
    ele_app_sequence:
      [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
  attack:
    arkhe:
      - 9 # Spiritbreath Thorn/Surging Blade DMG|{param9:F1P}
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    attack_4:
      - 3 # 4-Hit DMG|{param3:F1P}
    charge:
      - 4 # Charged Attack DMG|{param4:F1P}
    collision:
      - 6 # Plunge DMG|{param6:F1P}
    lowPlunge:
      - 7 # Low/High Plunge DMG|{param7:P}/{param8:P}
    highPlunge:
      - 8 # Low/High Plunge DMG|{param7:P}/{param8:P}
  skill:
    skillChevalmarin:
      - 3 # Surintendante Chevalmarin DMG|{param3:F2P} Max HP
    skillCrabaletta:
      - 4 # Mademoiselle Crabaletta DMG|{param4:F2P} Max HP
    skillOusiaBubble:
      - 0 # Ousia Bubble DMG|{param0:F1P} Max HP
    skillSingerHealFlat:
      - 9 # Singer of Many Waters Healing|{param8:F2P} Max HP+{param9:I}
    skillSingerHealScale:
      - 8 # Singer of Many Waters Healing|{param8:F2P} Max HP+{param9:I}
    skillUsher:
      - 2 # Gentilhomme Usher DMG|{param2:F2P} Max HP
  burst:
    burstDMG:
      - 0 # Skill DMG|{param0:F1P} Max HP
    burstFanfareDMGRatio:
      - 4 # Fanfare to DMG Increase Conversion Ratio|{param4:F2P}
    burstFanfareHBRatio:
      - 5 # Fanfare to Incoming Healing Bonus Conversion Ratio|{param5:F2P}

documentation:
  fields_data:
    - fields: [.furina.ousia]
      desc: Whether Furina is in the Ousia Arke.
    - fields: [.furina.fanfare]
      desc: Current amount of fanfare.
    - fields: [.furina.c6-count]
      desc: Number of c6 effects triggered.
