use: pipeline
kind: character
name: furina

override:
  icd_group:
    FurinaSalonSolitaire:
      # name: Furina_SeaHorse
      name: Furina_Octopus

shortcuts:
  - furinadefontaine

combat:
  icd_tags:
    - FurinaChevalmarin
    - FurinaUsher
  icd_groups:
    - FurinaSalonSolitaire

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - charge: attack(Charged Attack DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)
  - arkhe: attack(Spiritbreath Thorn/Surging Blade DMG)

  - skillOusiaBubble: skill(Ousia Bubble DMG)
  - skillUsher: skill(Gentilhomme Usher DMG)
  - skillChevalmarin: skill(Surintendante Chevalmarin DMG)
  - skillCrabaletta: skill(Mademoiselle Crabaletta DMG)
  - skillSingerHealScale: skill(Singer of Many Waters Healing)
  - skillSingerHealFlat: skill(Singer of Many Waters Healing|1)

  - burstDMG: burst(Skill DMG)
  - burstFanfareDMGRatio: burst(Fanfare to DMG Increase Conversion Ratio)
  - burstFanfareHBRatio: burst(Fanfare to Incoming Healing Bonus Conversion Ratio)

docs:
  fields:
    .furina.c6-count: Number of c6 effects triggered.
    .furina.fanfare: Current amount of fanfare.
    .furina.ousia: Whether Furina is in the Ousia Arke.
  frames:
    - count: https://docs.google.com/spreadsheets/d/1nNKfwu7BISm78JpPX6-fLFFRFU2r19a42hr15potaD0
      count_credit: caramielle
      video: https://youtu.be/stH8I5B0uIA
      video_credit: charliex3000
    - count: https://docs.google.com/spreadsheets/d/1nNKfwu7BISm78JpPX6-fLFFRFU2r19a42hr15potaD0
      count_credit: caramielle
      video: https://youtu.be/rPwZQatNV-w
      video_credit: caramielle
    - count: https://docs.google.com/spreadsheets/d/1nNKfwu7BISm78JpPX6-fLFFRFU2r19a42hr15potaD0
      count_credit: caramielle
      video: https://youtu.be/-RmtnM1HVAg
      video_credit: caramielle
    - count: https://docs.google.com/spreadsheets/d/1nNKfwu7BISm78JpPX6-fLFFRFU2r19a42hr15potaD0
      count_credit: caramielle
      video: https://youtu.be/teZtSWnvk50
      video_credit: caramielle
    - count: https://docs.google.com/spreadsheets/d/1nNKfwu7BISm78JpPX6-fLFFRFU2r19a42hr15potaD0
      count_credit: caramielle
      video: https://youtu.be/He2RwY0tN_s
      video_credit: caramielle
    - count: https://docs.google.com/spreadsheets/d/1nNKfwu7BISm78JpPX6-fLFFRFU2r19a42hr15potaD0
      count_credit: caramielle
      video: https://youtu.be/NoYh8PBf--E?si=bhr6iqS46Pl_oBBz
      video_credit: Eris
    - count: https://docs.google.com/spreadsheets/d/1nNKfwu7BISm78JpPX6-fLFFRFU2r19a42hr15potaD0
      count_credit: kolibri._.
      video: https://youtu.be/Xl4Mkb_9MIA
      video_credit: kolibri._.
    - count: https://docs.google.com/spreadsheets/d/18LP6xlqh1DJhu6H0cvSaw3XLHhhLH6Wi/edit#gid=449781477
      count_credit: charliex3000
      video: https://youtu.be/a3c7JjAsNwI
      video_credit: charliex3000
    - count: https://docs.google.com/spreadsheets/d/18LP6xlqh1DJhu6H0cvSaw3XLHhhLH6Wi/edit#gid=449781477
      count_credit: charliex3000
      video: https://youtu.be/dOduCa3Ck9E
      video_credit: freenek
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: charliex3000
      video: https://youtu.be/ZOPysOpqDgc
      video_credit: charliex3000

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.1]
        box: [1.5, 2.8]
        hitlag: {time: 0.01, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: PrimaryTarget
        offset: [0, 0.1]
        radius: 1.7
        hitlag: {time: 0.01, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Circle
        center: PrimaryTarget
        offset: [0, 0.5]
        radius: 1.9
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Box
        center: PrimaryTarget
        offset: [0, -2.5]
        box: [5, 6]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: N1-C6
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.1]
        box: [1.5, 3]

      - name: N2-C6
        shape: Circle
        center: PrimaryTarget
        offset: [0, 0.1]
        radius: 2.3

      - name: N3-C6
        shape: Circle
        center: PrimaryTarget
        offset: [0, 0.8]
        radius: 2.2

      - name: N4-C6
        shape: Box
        center: PrimaryTarget
        offset: [0, -2.5]
        box: [6, 7]

  - name: charge
    hitbox:
      - name: CA
        shape: Circle
        center: Player
        radius: 2.6
        hitlag: {time: 0.02, scale: 0.01}

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    hitbox:
      - name: E-Ousia-Bubble
        shape: Circle
        center: Player
        radius: 5

      - name: E-Surintendante-Chevalmarin
        note: Target aquisition range is not implemented.
        shape: Circle
        center: PrimaryTarget
        radius: 0.5

      - name: E-Gentilhomme-Usher
        note: Target aquisition range is not implemented.
        shape: Circle
        center: PrimaryTarget
        radius: 2.5

      - name: E-Mademoiselle-Crabaletta
        note: Target aquisition range is not implemented.
        shape: Circle
        center: PrimaryTarget
        radius: 3.5

  - name: burst
    hitbox:
      - name: Q
        shape: Circle
        center: Player
        radius: 5
