// Code generated by "pipeline"; DO NOT EDIT.

// passive: Gilding # Weapon_Catalyst_TeamHealAfterElementalBurst
//
//	Using an Elemental Burst regenerates 4 Energy every 2s for 6s. All party members
//	will regenerate 4% HP every 2s for this duration.
package prototype

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.PrototypeAmber, NewWeapon)
}
