// Code generated by "pipeline"; DO NOT EDIT.

// passive: Daylight's Augury # Weapon_Bow_Worldbane
//
//	Elemental Skill and Elemental Burst DMG increased by 12%. After a Normal Attack,
//	Charged Attack, Elemental Skill or Elemental Burst hits an opponent, 1 stack of Ashen
//	Nightstar will be gained for 12s. When 1/2/3/4 stacks of Ashen Nightstar are present,
//	ATK is increased by 10/20/30/48%. The stack of Ashen Nightstar created by the Normal
//	Attack, Charged Attack, Elemental Skill or Elemental Burst will be counted independently
//	of the others.
package polarstar

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.PolarStar, NewWeapon)
}
