use: pipeline
kind: character
name: raidenshogun

shortcuts:
  - herexcellencythealmightynarukamiogoshogodofthunder
  - raiden

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - - attack(4-Hit DMG)
        - attack(4-Hit DMG)
      - attack(5-Hit DMG)
  - charge: attack(Charged Attack DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skill: skill(Skill DMG)
  - skillTick: skill(Coordinated ATK DMG)
  - skillBurstBonus: skill(Elemental Burst DMG Bonus)

  - burstBase: burst(Musou no Hitotachi Base DMG)
  - resolveBaseBonus: burst(Resolve Bonus)
  - resolveBonus: burst(Resolve Bonus|1)
  - resolveStackGain: burst(Resolve Stacks Gained)
  - attackB:
      - burst(1-Hit DMG)
      - burst(2-Hit DMG)
      - burst(3-Hit DMG)
      - - burst(4-Hit DMG)
        - burst(4-Hit DMG|1)
      - burst(5-Hit DMG)
  - chargeSword:
      - burst(Charged Attack DMG)
      - burst(Charged Attack DMG|1)
  - burstRestore: burst(Musou Isshin Energy Restoration)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1ayeS2Yp32dbdVR-xqSyIeSk7CUDuIFSO6A8XrRCRNgY/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/70hVIt1_92Y
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ?t=1221
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: charliex3000
      video: https://youtu.be/rLu3Ki2VnAo
      video_credit: charliex3000

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Box
        center: Player
        offset: [0, -0.2]
        box: [1.8, 2.8]

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        fan_angle: 270
        radius: 2.5

      - name: N3
        shape: Box
        center: Player
        offset: [0, -1.2]
        box: [1.8, 4]

      - name: N4-1
        shape: Circle
        center: Player
        offset: [-0.5, 0.7]
        radius: 2.8

      - name: N4-2
        shape: Circle
        center: Player
        offset: [0.3, 0.7]
        radius: 2.8

      - name: N5
        shape: Circle
        center: Player
        radius: 3

      - name: Q-N1
        shape: Box
        center: Player
        offset: [0, -0.1]
        box: [3.8, 4.8]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: Q-N2
        shape: Box
        center: Player
        offset: [1, -1]
        box: [9.8, 4.5]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: Q-N3
        shape: Box
        center: Player
        offset: [0, -0.1]
        box: [3.2, 4.3]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: Q-N4-1
        shape: Box
        center: Player
        offset: [1, 0]
        box: [11, 6.6]

      - name: Q-N4-2
        shape: Box
        center: Player
        offset: [0.3, -1.5]
        box: [4.5, 8.5]

      - name: Q-N5
        shape: Box
        center: Player
        offset: [0, -0.1]
        box: [11, 5.5]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA
        shape: Box
        center: Player
        offset: [0, -0.1]
        box: [2.8, 4.8]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: Q-CA-1
        shape: Box
        center: Player
        offset: [0, -0.1]
        box: [7.5, 8]

      - name: Q-CA-2
        shape: Box
        center: Player
        offset: [0, -0.1]
        box: [7.5, 8]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Q-Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

      - name: Q-Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: Q-High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    hitbox:
      - name: E-Skill
        shape: Circle
        center: Player
        radius: 5

      - name: E-CoordinatedATK
        note: Spawns on target that E proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 4

  - name: burst
    hitbox:
      - name: Q-Start
        note: not implemented yet
        shape: Circle
        center: Player
        radius: 3

      - name: Q-Initial
        shape: Box
        center: Player
        offset: [0, -0.1]
        box: [13, 8]

  - name: walk
    note: No action followed by walk (except low_plunge and high_plunge) has proper frames.
