id: 10000052
key: "raiden"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_INAZUMA
element: Electric
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Shougun"
stats: {
   base_hp: 1004.79926
   base_atk: 26.2542
   base_def: 61.44541
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 861.52454
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 52.6851
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.508959
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1473.6604
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 90.11925
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 38.502167
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.08
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2289.8416
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 140.03145
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 59.826443
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.16
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2901.9773
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 177.4656
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 75.81965
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.16
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3514.1133
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 214.89975
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 91.81286
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.24
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4126.249
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 252.3339
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 107.80606
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.32
      }
   }
}
skill_details: {
   skill: 10522
   burst: 10525
   attack: 10521
   burst_energy_cost: 90
}
name_text_hash_map: 3024507506
