use: pipeline
kind: character
name: yaoyao

override:
  icd_group:
    YaoyaoRadishBurst:
      name: Yaoyao_ElementalBurst
    YaoyaoRadishSkill:
      name: Yaoyao_GrassAttack

combat:
  icd_groups:
    - YaoyaoRadishBurst
    - YaoyaoRadishSkill

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG|1)
      - attack(4-Hit DMG)
  - nc: attack(Charged Attack DMG)

  - skillRadishDMG: skill(White Jade Radish DMG)
  - skillRadishHealing:
      - skill(White Jade Radish Healing)
      - skill(White Jade Radish Healing|1)

  - burstRadishDMG: burst(Adeptal Legacy White Jade Radish DMG)
  - burstRadishHealing:
      - burst(Adeptal Legacy White Jade Radish Healing)
      - burst(Adeptal Legacy White Jade Radish Healing|1)
  - burstDMG: burst(Skill DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1A28CI10iM5URyU8PIH8fo99C8ksnUIINevzC28W4ml4/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/meKPwfxJha8
      video_credit: Kolibri#7675

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Box
        center: Player
        box: [1.2, 3]
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        fan_angle: 270
        radius: 2
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N3-1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        fan_angle: 270
        radius: 2

      - name: N3-2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        fan_angle: 270
        radius: 2
        hitlag: {time: 0.01, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Circle
        center: Player
        offset: [0, 1.5]
        radius: 2.2
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 0.8
        hitlag: {scale: 0.01, defense_halt: true, deployable: true}

  - name: skill
    hitbox:
      - name: E-Radish
        shape: Circle
        center: PrimaryTarget
        radius: 2
        hitlag: {defense_halt: true, deployable: true}

  - name: burst
    hitbox:
      - name: Q-Initial
        shape: Circle
        center: Player
        radius: 3
        hitlag: {time: 0.02, scale: 0.05}

      - name: Q-Radish
        shape: Circle
        center: PrimaryTarget
        radius: 2
        hitlag: {defense_halt: true, deployable: true}

  - name: asc
    hitbox:
      - name: A1-Radish
        note: Spawns on target within 8m radius of Player.
        shape: Circle
        center: PrimaryTarget
        radius: 2
        hitlag: {defense_halt: true, deployable: true}

  - name: cons
    hitbox:
      - name: C6-Radish
        shape: Circle
        center: PrimaryTarget
        radius: 4
        hitlag: {defense_halt: true, deployable: true}
