package_name: yaoyao
genshin_id: 10000077
key: yaoyao
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
            - 3 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
        attack_4:
            - 4 # 4-Hit DMG|{param4:F1P}
        nc:
            - 5 # Charged Attack DMG|{param5:F1P}
    skill:
        skillRadishDMG:
            - 0 # White Jade Radish DMG|{param0:F1P}
        skillRadishHealing:
            - 1 # White Jade Radish Healing|{param1:F2P} Max HP+{param2:I}
            - 2 # White Jade Radish Healing|{param1:F2P} Max HP+{param2:I}
    burst:
        burstDMG:
            - 3 # Skill DMG|{param3:F1P}
        burstRadishDMG:
            - 0 # Adeptal Legacy White Jade Radish DMG|{param0:F1P}
        burstRadishHealing:
            - 1 # Adeptal Legacy White Jade Radish Healing|{param1:F2P} Max HP+{param2:I}
            - 2 # Adeptal Legacy White Jade Radish Healing|{param1:F2P} Max HP+{param2:I}
