id: 10000031
key: "fischl"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_MONDSTADT
element: Electric
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Fischl"
stats: {
   base_hp: 770.4634
   base_atk: 20.4792
   base_def: 49.78575
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 575.5756
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 37.1925
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 15.29937
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 984.53723
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 63.61875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 26.169975
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1529.8193
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 98.85375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.664116
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1938.781
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 125.28
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 51.53472
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2347.7427
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 151.70625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 62.405327
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2756.704
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 178.1325
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 73.27593
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10312
   burst: 10313
   attack: 10311
   burst_energy_cost: 60
}
name_text_hash_map: 3277782506
