use: pipeline
kind: weapon
name: aquilafavonia

shortcuts:
  - aquila

abilities:
  - name: default
    hitbox:
      - name: Aquila Favonia
        shape: Circle
        center: Player
        radius: 6
