use: pipeline
kind: character
name: luminegeo

override:
  id: 10000007
  depot: 706

shortcuts:
  - travelergeo

combat:
  icd_tags:
    - TravelerWakeOfEarth

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1S7cJszsMoQF6ShCvA7hMjiXMuOCoDRwgW1rseP0uC8k/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/VaIaa4MW9eI
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1IQWPPH4rVSe9fvy2hpvufS1xi7Ni_jfZ7SL4aSudPuM/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/2VGB-csNGnI
      video_credit: Kolibri#7675

abilities:
  - name: default
    params:
      base_atk_buff: 0 for no +3 base atk, 1 (default) for +3 base atk. Set via '+params=[base_atk_buff=...]' in the char's line.
      skirk_story_buff: 0 for no buffs, 1 (default) for +7 base atk, +15 EM, +50 base HP. Set via '+params=[skirk_story_buff=...]' in the char's line.

  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1.6
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Box
        center: Player
        box: [1.4, 2.2]
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Circle
        center: Player
        offset: [0, 0.7]
        radius: 1.5
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Circle
        center: Player
        offset: [0, 0.7]
        radius: 1.5
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N5
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1.6
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA-1
        shape: Circle
        center: Player
        radius: 2.2

      - name: CA-2
        shape: Circle
        center: Player
        radius: 2.2

  - name: skill
    params:
      no_meteorite: If 1, no meteorite will be created. Default 0.
      short_hold: 0 for Tap (default), 1 for Short Hold. The Short Hold version is the shortest possible Hold.
    hitbox:
      - name: E-Skill
        shape: Circle
        center: PrimaryTarget
        radius: 3
        hitlag: {time: 0.05, scale: 0.05, defense_halt: true, deployable: true}

  - name: burst
    params:
      construct_limit: Number of Stone Walls to spawn. Default 4. Using a value < 4 starts not spawning Stone Walls starting from top left going counterclockwise.
      hits: Number of shockwave attacks to perform. Default 4.
    hitbox:
      - name: Q-Shockwave
        note: C1 has a detection area of 7m around the position of this hitbox.
        shape: Circle
        center: Player
        radius: 6

  - name: asc
    hitbox:
      - name: A4
        shape: Circle
        center: Player
        offset: [0, 1.2]
        radius: 2.4

  - name: cons
    hitbox:
      - name: C2
        note: Spawns at the E-Skill position.
        shape: Circle
        center: GlobalValue
        radius: 3
        hitlag: {time: 0.05, scale: 0.05, defense_halt: true, deployable: true}

  - name: walk
    note: No action followed by walk has proper frames.
