package_name: lanyan
genshin_id: 10000108
key: lanyan
action_param_keys:
  skill:
    - param: "hold"
icd_tags:
  - ICDTagLanyanRingAttack
  - ICDTagLanyanRingAttackMix
icd_groups:
  - group_name: ICDGroupLanyanRingAttack
    reset_timer: 150
    ele_app_sequence:
      [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  - group_name: ICDGroupLanyanRingAttackMix
    reset_timer: 150
    ele_app_sequence:
      [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param1:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param2:F1P}+{param3:F1P}
            - 2 # 2-Hit DMG|{param2:F1P}+{param3:F1P}
        attack_3:
            - 3 # 3-Hit DMG|{param4:F1P}+{param5:F1P}
            - 4 # 3-Hit DMG|{param4:F1P}+{param5:F1P}
        attack_4:
            - 5 # 4-Hit DMG|{param6:F1P}
        charge:
            - 6 # Charged Attack DMG|{param7:F1P}×3
    skill:
        ring:
            - 0 # Feathermoon Ring DMG|{param1:F1P}
        shieldAmt:
            - 1 # Shield DMG Absorption|{param2:F1P} ATK+{param3:I}
        shieldFlat:
            - 2 # Shield DMG Absorption|{param2:F1P} ATK+{param3:I}
    burst:
        burst:
            - 0 # Skill DMG|{param1:F1P}×3
