name: "Deploy DB"
description: "builds and deploys the gcsim DB to cloudflare. Assumes pnpm setup has already ran"
inputs:
  apiToken:
    required: true
    description: cloudflare api token
  accountId:
    required: true
    description: cloudflare account id

runs:
  using: composite
  steps:
  - name: Build DB
    working-directory: ./ui
    shell: bash
    run: pnpm build:db

  - name: List DB dist
    working-directory: ./ui/packages/db/dist
    shell: bash
    run: ls -lh

  - name: Deploy to Cloudflare Workers
    uses: cloudflare/wrangler-action@v4
    with:
      apiToken: ${{ inputs.apiToken }}
      accountId: ${{ inputs.accountId }}
      workingDirectory: './ui/packages/db'
      command: deploy
