id: 10000111
key: "varesa"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_NATLAN
element: Electric
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Varesa"
stats: {
   base_hp: 988.59283
   base_atk: 27.7438
   base_def: 60.84711
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 847.62897
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 52.1721
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.786062
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1449.8916
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 89.24175
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.686684
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2252.9087
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 138.66795
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.220848
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2855.1714
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 175.7376
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 80.121475
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3457.434
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 212.80725
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 97.022095
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4059.6965
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 249.8769
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 113.922714
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 11112
   burst: 11115
   attack: 11111
   burst_energy_cost: 70
}
name_text_hash_map: 283438874
