use: pipeline
kind: weapon
name: theflute

shortcuts:
  - flute

abilities:
  - name: default
    hitbox:
      - name: The Flute
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 4
