// Code generated by "pipeline"; DO NOT EDIT.

// passive: An End Sublime # Weapon_Sword_Vorpal
//
//	When using an Elemental Skill, ATK will be increased by 12% for 15s, and a Bond of
//	Life worth 25% of Max HP will be granted. This effect can be triggered once every
//	10s. When the Bond of Life is cleared, a maximum of 150 ATK will be gained based
//	on 2.4% of the total amount of the Life Bond cleared, lasting for 15s.
package finaleofthedeep

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.FinaleOfTheDeep, NewWeapon)
}
