package_name: flins
genshin_id: 10000120
key: flins
skill_data_mapping:
    attack: # Pocztowy Demonspear
      attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
      attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
      attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
      attack_4:            
            - 3 # 4-Hit DMG|{param3:F1P}×2
            - 3 # 4-Hit DMG|{param3:F1P}×2
      attack_5:  
            - 4 # 5-Hit DMG|{param4:F1P}
      charge:
            - 5 # Charged Attack DMG|{param5:F1P}
      collision:
            - 7 # Plunge DMG|{param7:F1P}
      lowPlunge:
            - 8 # Low/High Plunge DMG|{param8:P}/{param9:P}
      highPlunge:
            - 9 # Low/High Plunge DMG|{param8:P}/{param9:P}
    skill: # Ancient Rite: Arcane Light
      skillAttack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
      skillAttack_2:      
            - 1 # 2-Hit DMG|{param1:F1P}
      skillAttack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
      skillAttack_4:
            - 3 # 4-Hit DMG|{param3:F1P}×2
            - 3 # 4-Hit DMG|{param3:F1P}×2
      skillAttack_5:
            - 4 # 5-Hit DMG|{param4:F1P}
      skillCharge:
            - 5 # Charged Attack DMG|{param5:F1P}
      skillDmg:
            - 6 # Northland Spearstorm DMG|{param6:F1P}
    burst: # Ancient Ritual: Cometh the Night
      burstInit:
            - 0 # Initial Skill DMG|{param0:F1P}
      burstMid:
            - 1 # Middle Phase Lunar-Charged DMG|{param1:F1P}
      burstFinal:
            - 2 # Final Phase Lunar-Charged DMG|{param2:F1P}
      symphony:
            - 5 # Thunderous Symphony DMG|{param5:F1P}
      symphonyExtra:
            - 6 # Thunderous Symphony Additional DMG|{param6:F1P}
