// Code generated by "pipeline"; DO NOT EDIT.
package jahoda

import (
	_ "embed"

	"fmt"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
	"slices"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData
var paramKeysValidation = map[action.Action][]string{
	1: {"travel", "cancel"},
	3: {"travel"},
	7: {"hold", "travel", "weakspot"},
}

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
	validation.RegisterCharParamValidationFunc(keys.Jahoda, ValidateParamKeys)
}

func ValidateParamKeys(a action.Action, keys []string) error {
	valid, ok := paramKeysValidation[a]
	if !ok {
		return nil
	}
	for _, v := range keys {
		if !slices.Contains(valid, v) {
			return fmt.Errorf("key %v is invalid for action %v", v, a.String())
		}
	}
	return nil
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][][]float64{
		{attack_1},
		attack_2,
		{attack_3},
	}
)

var (
	// attack: aim = [3]
	aim = []float64{
		0.4386,
		0.4743,
		0.51,
		0.561,
		0.5967,
		0.6375,
		0.6936,
		0.7497,
		0.8058,
		0.867,
		0.9282,
		0.9894,
		1.0506,
		1.1118,
		1.173,
	}
	// attack: attack_1 = [0]
	attack_1 = []float64{
		0.416739,
		0.450659,
		0.48458,
		0.533038,
		0.566959,
		0.605725,
		0.659029,
		0.712333,
		0.765636,
		0.823786,
		0.881936,
		0.940085,
		0.998235,
		1.056384,
		1.114534,
	}
	// attack: attack_2 = [1 1]
	attack_2 = [][]float64{
		{
			0.192313,
			0.207967,
			0.22362,
			0.245982,
			0.261635,
			0.279525,
			0.304123,
			0.328721,
			0.35332,
			0.380154,
			0.406988,
			0.433823,
			0.460657,
			0.487492,
			0.514326,
		},
		{
			0.192313,
			0.207967,
			0.22362,
			0.245982,
			0.261635,
			0.279525,
			0.304123,
			0.328721,
			0.35332,
			0.380154,
			0.406988,
			0.433823,
			0.460657,
			0.487492,
			0.514326,
		},
	}
	// attack: attack_3 = [2]
	attack_3 = []float64{
		0.511975,
		0.553648,
		0.59532,
		0.654852,
		0.696524,
		0.74415,
		0.809635,
		0.87512,
		0.940606,
		1.012044,
		1.083482,
		1.154921,
		1.226359,
		1.297798,
		1.369236,
	}
	// attack: fullaim = [4]
	fullaim = []float64{
		1.24,
		1.333,
		1.426,
		1.55,
		1.643,
		1.736,
		1.86,
		1.984,
		2.108,
		2.232,
		2.356,
		2.48,
		2.635,
		2.79,
		2.945,
	}
	// skill: filledFlask = [2]
	filledFlask = []float64{
		2.12,
		2.279,
		2.438,
		2.65,
		2.809,
		2.968,
		3.18,
		3.392,
		3.604,
		3.816,
		4.028,
		4.24,
		4.505,
		4.77,
		5.035,
	}
	// skill: meowball = [4]
	meowball = []float64{
		1.28,
		1.376,
		1.472,
		1.6,
		1.696,
		1.792,
		1.92,
		2.048,
		2.176,
		2.304,
		2.432,
		2.56,
		2.72,
		2.88,
		3.04,
	}
	// skill: unfilledFlask = [1]
	unfilledFlask = []float64{
		1.908,
		2.0511,
		2.1942,
		2.385,
		2.5281,
		2.6712,
		2.862,
		3.0528,
		3.2436,
		3.4344,
		3.6252,
		3.816,
		4.0545,
		4.293,
		4.5315,
	}
	// burst: burst = [0]
	burst = []float64{
		2.072,
		2.2274,
		2.3828,
		2.59,
		2.7454,
		2.9008,
		3.108,
		3.3152,
		3.5224,
		3.7296,
		3.9368,
		4.144,
		4.403,
		4.662,
		4.921,
	}
	// burst: burstAdditionalHealFlat = [6]
	burstAdditionalHealFlat = []float64{
		192.59721,
		211.8596,
		232.7272,
		255.2,
		279.27798,
		304.96118,
		332.2496,
		361.1432,
		391.642,
		423.74597,
		457.45517,
		492.76956,
		529.68915,
		568.214,
		608.34393,
	}
	// burst: burstAdditionalHealPP = [5]
	burstAdditionalHealPP = []float64{
		0.3072,
		0.33024,
		0.35328,
		0.384,
		0.40704,
		0.43008,
		0.4608,
		0.49152,
		0.52224,
		0.55296,
		0.58368,
		0.6144,
		0.6528,
		0.6912,
		0.7296,
	}
	// burst: burstHealFlat = [4]
	burstHealFlat = []float64{
		500.73764,
		550.81836,
		605.0725,
		663.5,
		726.1009,
		792.8752,
		863.8229,
		938.944,
		1018.23846,
		1101.7063,
		1189.3477,
		1281.1622,
		1377.1503,
		1477.3118,
		1581.6466,
	}
	// burst: burstHealPP = [3]
	burstHealPP = []float64{
		0.79872,
		0.858624,
		0.918528,
		0.9984,
		1.058304,
		1.118208,
		1.19808,
		1.277952,
		1.357824,
		1.437696,
		1.517568,
		1.59744,
		1.69728,
		1.79712,
		1.89696,
	}
	// burst: burstSkill = [1]
	burstSkill = []float64{
		0.172664,
		0.185614,
		0.198564,
		0.21583,
		0.22878,
		0.24173,
		0.258996,
		0.276262,
		0.293529,
		0.310795,
		0.328062,
		0.345328,
		0.366911,
		0.388494,
		0.410077,
	}
)
