use: pipeline
kind: character
name: kukishinobu

shortcuts:
  - kuki

talents:
  - auto:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - charge:
      - attack(Charged Attack DMG)
      - attack(Charged Attack DMG|1)

  - skill: skill(Skill DMG)
  - skillhealpp: skill(Grass Ring of Sanctification Healing)
  - skillhealflat: skill(Grass Ring of Sanctification Healing|1)
  - skilldot: skill(Grass Ring of Sanctification DMG)

  - burst: burst(Single Instance DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1cXejpod69F6HReq6jztxEvlpVzSGKssz5NNHIzqY4QY/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/kbdvX4Oy-u0
      video_credit: Kolibri#7675

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1.5
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.5
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Box
        center: Player
        offset: [0, -0.2]
        box: [6, 3.3]
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Circle
        center: Player
        offset: [0, 1.2]
        radius: 2.2
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA-1
        shape: Circle
        center: Player
        radius: 2.8

      - name: CA-2
        shape: Circle
        center: Player
        radius: 2.8
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

  - name: skill
    hitbox:
      - name: E-Skill
        shape: Circle
        center: Player
        radius: 4

      - name: E-Tick
        shape: Circle
        center: Player
        radius: 4

  - name: burst
    hitbox:
      - name: Q-HighHp
        shape: Circle
        center: PrimaryTarget
        radius: 4

      - name: Q-LowHp
        shape: Circle
        center: PrimaryTarget
        radius: 6

  - name: cons
    hitbox:
      - name: E-C4
        shape: Circle
        center: GlobalValue
        radius: 2

  - name: walk
    note: No action followed by walk has proper frames.
