package_name: kuki
genshin_id: 10000065
key: kuki
skill_data_mapping:
    attack:
        auto_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        auto_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        auto_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        auto_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        charge:
            - 4 # Charged Attack DMG|{param4:F1P}+{param5:F1P}
            - 5 # Charged Attack DMG|{param4:F1P}+{param5:F1P}
    skill:
        skill:
            - 0 # Skill DMG|{param0:P}
        skilldot:
            - 3 # Grass Ring of Sanctification DMG|{param3:F1P}
        skillhealflat:
            - 2 # Grass Ring of Sanctification Healing|{param1:F1P} Max HP+{param2:I}
        skillhealpp:
            - 1 # Grass Ring of Sanctification Healing|{param1:F1P} Max HP+{param2:I}
    burst:
        burst:
            - 0 # Single Instance DMG|{param0:F1P} Max HP
