id: 10000065
key: "kuki"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_INAZUMA
element: Electric
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Shinobu"
stats: {
   base_hp: 1030.3239
   base_atk: 17.808
   base_def: 62.9475
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 769.70465
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 47.025
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 13.3038
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1316.6001
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 80.4375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.7565
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2045.794
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 124.9875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 35.3601
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2592.6895
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 158.4
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 44.8128
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3139.5847
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 191.8125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 54.2655
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3686.4802
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 225.225
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.7182
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10652
   burst: 10655
   attack: 10651
   burst_energy_cost: 60
}
name_text_hash_map: 1940821986
