package_name: columbina
genshin_id: 10000125
key: columbina
skill_data_mapping:
    attack:
        # Moondew Cascade
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        charge:
            - 3 # Charged Attack DMG|{param3:F1P}
        chargeLB:
            - 5 # Moondew Cleanse DMG|{param5:F2P} Max HP ×3
    skill:
        # Eternal Tides
        skill:
            - 0 # Skill DMG|{param0:F1P} Max HP
        skillDoT:
            - 1 # Gravity Ripple: Continuous DMG|{param1:F1P} Max HP
        skillLC:
            - 2 # Gravity Interference: Lunar-Charged DMG|{param2:F2P} Max HP
        skillLB:
            - 3 # Gravity Interference: Lunar-Bloom DMG|{param3:F2P} Max HP ×5
        skillLCr:
            - 4 # Gravity Interference: Lunar-Crystallize DMG|{param4:F2P} Max HP
    burst:
        # Moonlit Melancholy
        burst:
            - 0 # Skill DMG|{param0:F1P} Max HP
        burstBuff:
            - 1 # Lunar Reaction DMG Bonus|{param1:F1P}
documentation:
    fields_data:
        - fields: [.columbina.gravity]
          desc: Amount of gravity accumulated.
        - fields: [.columbina.a1-stacks]
          desc: Number of A1 stacks.
