id: 10000125
key: "columbina"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_NODKRAI
element: Water
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Columbina"
stats: {
   base_hp: 1143.984
   base_atk: 7.448
   base_def: 40.0861
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 980.86285
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 34.371
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 6.38552
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1677.7917
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 58.7925
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 10.9226
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2607.0303
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 91.3545
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 16.97204
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3303.959
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 115.776
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.50912
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4000.888
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 140.1975
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 26.0462
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4697.817
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 164.619
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 30.58328
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 11252
   burst: 11255
   attack: 11251
   burst_energy_cost: 60
}
name_text_hash_map: 1888371106
