// Code generated by "pipeline"; DO NOT EDIT.

package columbina

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Columbina, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Columbina, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: MoondewCascade - 1-Hit DMG: {0}
			0.46792,
			0.503014,
			0.538108,
			0.5849,
			0.619994,
			0.655088,
			0.70188,
			0.748672,
			0.795464,
			0.842256,
			0.889048,
			0.93584,
			0.99433,
			1.05282,
			1.11131,
		},
		{ // attack: MoondewCascade - 2-Hit DMG: {1}
			0.366256,
			0.393725,
			0.421194,
			0.45782,
			0.485289,
			0.512758,
			0.549384,
			0.58601,
			0.622635,
			0.659261,
			0.695886,
			0.732512,
			0.778294,
			0.824076,
			0.869858,
		},
		{ // attack: MoondewCascade - 3-Hit DMG: {2}
			0.58484,
			0.628703,
			0.672566,
			0.73105,
			0.774913,
			0.818776,
			0.87726,
			0.935744,
			0.994228,
			1.052712,
			1.111196,
			1.16968,
			1.242785,
			1.31589,
			1.388995,
		},
	}
	// attack: MoondewCascade - Charged Attack DMG: {3}
	charge = []float64{
		1.1608,
		1.24786,
		1.33492,
		1.451,
		1.53806,
		1.62512,
		1.7412,
		1.85728,
		1.97336,
		2.08944,
		2.20552,
		2.3216,
		2.4667,
		2.6118,
		2.7569,
	}
	// attack: MoondewCascade - Moondew Cleanse DMG: {5} Max HP ×3
	chargeLB = []float64{
		0.015112,
		0.016245,
		0.017379,
		0.01889,
		0.020023,
		0.021157,
		0.022668,
		0.024179,
		0.02569,
		0.027202,
		0.028713,
		0.030224,
		0.032113,
		0.034002,
		0.035891,
	}
	// skill: EternalTides - Skill DMG: {0} Max HP
	skill = []float64{
		0.1672,
		0.17974,
		0.19228,
		0.209,
		0.22154,
		0.23408,
		0.2508,
		0.26752,
		0.28424,
		0.30096,
		0.31768,
		0.3344,
		0.3553,
		0.3762,
		0.3971,
	}
	// skill: EternalTides - Gravity Ripple: Continuous DMG: {1} Max HP
	skillDoT = []float64{
		0.0936,
		0.10062,
		0.10764,
		0.117,
		0.12402,
		0.13104,
		0.1404,
		0.14976,
		0.15912,
		0.16848,
		0.17784,
		0.1872,
		0.1989,
		0.2106,
		0.2223,
	}
	// skill: EternalTides - Gravity Interference: Lunar-Charged DMG: {2} Max HP
	skillLC = []float64{
		0.04704,
		0.050568,
		0.054096,
		0.0588,
		0.062328,
		0.065856,
		0.07056,
		0.075264,
		0.079968,
		0.084672,
		0.089376,
		0.09408,
		0.09996,
		0.10584,
		0.11172,
	}
	// skill: EternalTides - Gravity Interference: Lunar-Bloom DMG: {3} Max HP ×5
	skillLB = []float64{
		0.01408,
		0.015136,
		0.016192,
		0.0176,
		0.018656,
		0.019712,
		0.02112,
		0.022528,
		0.023936,
		0.025344,
		0.026752,
		0.02816,
		0.02992,
		0.03168,
		0.03344,
	}
	// skill: EternalTides - Gravity Interference: Lunar-Crystallize DMG: {4} Max HP
	skillLCr = []float64{
		0.08824,
		0.094858,
		0.101476,
		0.1103,
		0.116918,
		0.123536,
		0.13236,
		0.141184,
		0.150008,
		0.158832,
		0.167656,
		0.17648,
		0.18751,
		0.19854,
		0.20957,
	}
	// burst: MoonlitMelancholy - Skill DMG: {0} Max HP
	burst = []float64{
		0.3224,
		0.34658,
		0.37076,
		0.403,
		0.42718,
		0.45136,
		0.4836,
		0.51584,
		0.54808,
		0.58032,
		0.61256,
		0.6448,
		0.6851,
		0.7254,
		0.7657,
	}
	// burst: MoonlitMelancholy - Lunar Reaction DMG Bonus: {1}
	burstBuff = []float64{
		0.13,
		0.16,
		0.19,
		0.22,
		0.25,
		0.28,
		0.31,
		0.34,
		0.37,
		0.4,
		0.43,
		0.46,
		0.49,
		0.52,
		0.55,
	}
)
