use: pipeline
kind: character
name: nilou

override:
  icd_group:
    Nilou:
      name: Nilou_Sustained_Water

combat:
  icd_tags:
    - NilouTranquilityAura
  icd_groups:
    - Nilou

talents:
  - auto:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
  - charge:
      - attack(Charged Attack DMG)
      - attack(Charged Attack DMG|1)

  - skill: skill(Skill DMG)
  - whirlingSteps:
      - skill(Sword Dance/Whirling Steps 1-Hit DMG|1)
      - skill(Sword Dance/Whirling Steps 2-Hit DMG|1)
      - skill(Luminous Illusion/Water Wheel DMG|1)
  - swordDance:
      - skill(Sword Dance/Whirling Steps 1-Hit DMG)
      - skill(Sword Dance/Whirling Steps 2-Hit DMG)
      - skill(Luminous Illusion/Water Wheel DMG)

  - burst: burst(Skill DMG)
  - burstAeon: burst(Lingering Aeon DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1z0v3NT1o1iNrVppT_S0C542YDo6jhdKShLcPsnavfO8/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/5SIqzb-Lri4
      video_credit: Kolibri#7675

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Box
        center: Player
        box: [1.5, 2.2]
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 1.5
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 2.1
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: E-N1
        shape: Box
        center: Player
        box: [1.75, 2.2]

      - name: E-N2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 1.8

      - name: E-N3
        shape: Circle
        center: PrimaryTarget
        radius: 2

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA-1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 2.3

      - name: CA-2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 2.3

  - name: skill
    params:
      travel: Projectile travel time for Luminous Illusion. Default 0 frames.
    hitbox:
      - name: E-Initial
        shape: Circle
        center: Player
        radius: 2.5

      - name: E-1
        shape: Circle
        center: Player
        offset: [0, 0.3]
        radius: 2.7

      - name: E-2
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 2.7

      - name: E-3
        shape: Box
        center: Player
        offset: [0.2, -2]
        box: [2.7, 5.2]

      - name: E-TranquilityAura
        shape: Circle
        center: Player
        radius: 2.5

  - name: burst
    hitbox:
      - name: Q-Start
        note: not implemented yet
        shape: Circle
        center: Player
        radius: 3

      - name: Q-Initial
        shape: Circle
        center: Player
        radius: 3

      - name: Q-LingeringAeon
        note: Spawns on all enemies hit by Q-Initial.
        shape: Single
        center: GlobalValue

  - name: walk
    note: No action followed by walk has proper frames.
