package_name: nilou
genshin_id: 10000070
key: nilou
icd_tags:
  - ICDTagNilouTranquilityAura
icd_groups:
  - group_name: ICDGroupNilou
    reset_timer: 114
    ele_app_sequence: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
  attack:
    auto_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    auto_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    auto_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    charge:
      - 3 # Charged Attack DMG|{param3:F1P}+{param4:F1P}
      - 4 # Charged Attack DMG|{param3:F1P}+{param4:F1P}
  skill:
    skill:
      - 0 # Skill DMG|{param0:F2P} Max HP
    swordDance:
      - 5 # Sword Dance/Whirling Steps 1-Hit DMG|{param5:F2P}/{param1:F2P} Max HP
      - 6 # Sword Dance/Whirling Steps 2-Hit DMG|{param6:F2P}/{param2:F2P} Max HP
      - 3 # Luminous Illusion/Water Wheel DMG|{param3:F2P}/{param4:F2P} Max HP
    whirlingSteps:
      - 1 # Sword Dance/Whirling Steps 1-Hit DMG|{param5:F2P}/{param1:F2P} Max HP
      - 2 # Sword Dance/Whirling Steps 2-Hit DMG|{param6:F2P}/{param2:F2P} Max HP
      - 4 # Luminous Illusion/Water Wheel DMG|{param3:F2P}/{param4:F2P} Max HP
  burst:
    burst:
      - 0 # Skill DMG|{param0:F1P} Max HP
    burstAeon:
      - 1 # Lingering Aeon DMG|{param1:F1P} Max HP
