id: 10000070
key: "nilou"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_SUMERU
element: Water
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Nilou"
stats: {
   base_hp: 1182.1168
   base_atk: 17.8752
   base_def: 56.71884
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1013.5583
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 48.6324
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 15.325248
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1733.7181
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 83.187
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 26.21424
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2693.9312
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 129.2598
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.732895
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3414.091
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 163.8144
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 51.621887
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4134.251
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 198.369
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 62.51088
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4854.4106
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 232.9236
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 73.39987
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 10702
   burst: 10705
   attack: 10701
   burst_energy_cost: 70
}
name_text_hash_map: 3850149970
