use: pipeline
kind: weapon
name: frostbearer

abilities:
  - name: default
    hitbox:
      - name: Frostbearer
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 3
