version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - /containers/assets
      - /containers/embedgenerator
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - "*"
