package_name: collei
genshin_id: 10000067
key: collei
icd_tags:
  - ICDTagColleiSprout
icd_groups:
  - group_name: ICDGroupColleiBurst
    reset_timer: 180
    ele_app_sequence: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
  attack:
    aim:
      - 4 # Aimed Shot|{param4:F1P}
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    attack_4:
      - 3 # 4-Hit DMG|{param3:F1P}
    fullaim:
      - 5 # Fully-Charged Aimed Shot|{param5:P}
  skill:
    skill:
      - 0 # Skill DMG|{param0:F1P}
  burst:
    burstExplosion:
      - 0 # Explosion DMG|{param0:F1P}
    burstLeap:
      - 1 # Leap DMG|{param1:F1P}
