id: 10000067
key: "collei"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_SUMERU
element: Grass
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Collei"
stats: {
   base_hp: 820.6119
   base_atk: 16.73952
   base_def: 50.358
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 613.0391
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 37.62
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 12.505572
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1048.6195
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 64.35
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.39111
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1629.3934
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 99.99
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 33.238495
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2064.9739
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 126.72
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 42.12403
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2500.5542
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 153.45
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 51.00957
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2936.1348
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 180.18
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 59.895107
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10672
   burst: 10675
   attack: 10671
   burst_energy_cost: 60
}
name_text_hash_map: 2948362178
