// Code generated by "pipeline"; DO NOT EDIT.

// passive: Indomitable Chivalry # Weapon_Claymore_EnsisAquilonis
//
//	Increase ATK SPD by 10%. Every time the equipping character's Normal Attack(s) hit
//	opponent(s), when they cast their Elemental Skill, or when they begin their Charged
//	Attack(s), gain 1/2/2 stacks of Four Winds' Hymn respectively: DMG dealt is increased
//	by 7.5% for 4s. Max 4 stacks. This effect can be triggered once every 0.01s.
//	Additionally, when the party has the "Hexerei: Secret Rite" effect, each stack of
//	Four Winds' Hymn also increases the equipping character's CRIT DMG by 7.5%.
package gestofthemightywolf

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.GestOfTheMightyWolf, NewWeapon)
}
