// Code generated by "pipeline"; DO NOT EDIT.

// passive: Ironbone # Weapon_Sword_Machination
//
//	Increases Elemental Skill CRIT Rate by 8%. Additionally, increases Energy Recharge
//	by 16% for 5s after using an Elemental Skill.
package fleuvecendreferryman

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.FleuveCendreFerryman, NewWeapon)
}
