use: pipeline
kind: weapon
name: skywardpride

shortcuts:
  - pride

abilities:
  - name: default
    hitbox:
      - name: Skyward Pride
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Box
        center: GlobalValue
        box: [0.1, 0.1]
