version: "3.8"

services:
  # tunnel for the backend service
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: "tunnel --no-autoupdate run --token $CF_TUNNEL_TOKEN"
    volumes:
      - ./backend/cloudflared:/etc/cloudflared
    environment:
      - CF_TUNNEL_TOKEN
    depends_on:
      - jadechamber
    restart: unless-stopped
  mqtt:
    build:
      context: .
      dockerfile: ./backend/mosquitto/Dockerfile 
    environment:
      - MOSQUITTO_USERNAME=mosquitto
      - MOSQUITTO_PASSWORD=password
    container_name: mqtt
    restart: unless-stopped
    volumes:
      - ./backend/mosquitto/config:/mosquitto/config:ro
      - ./backend/mosquitto/data:/mosquitto/data
      - ./backend/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
  # generating embed for discord etc
  preview:
    container_name: preview
    build:
      context: .
      dockerfile: ./backend/cmd/preview/Dockerfile
    volumes:
      - ~/assets/assets:/assets
    environment:
      - ASSETS_DATA_PATH=/assets
    restart: unless-stopped
  share:
    container_name: share
    build:
      context: .
      dockerfile: ./backend/cmd/share/Dockerfile
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DATABASE=gcsim-database
      - MONGODB_COLLECTION=shares
      - MONGODB_USERNAME=root
      - MONOGDB_PASSWORD=root-password
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./backend/cmd/db/Dockerfile
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DATABASE=gcsim-database
      - MONGODB_COLLECTION=data
      - MONGODB_QUERY_VIEW=gcsimvaliddb
      - MONGODB_SUB_VIEW=gcsimsubs
      - MONGODB_USERNAME=root
      - MONOGDB_PASSWORD=root-password
      - SHARE_STORE_URL=share:3000
    # ports are exposed in order to access the grpc directly via localhost during dev
    ports:
      - 8082:3000
    restart: unless-stopped
    depends_on:
      - mongo
  jadechamber:
    container_name: jadechamber
    build:
      context: .
      dockerfile: ./backend/cmd/jadechamber/Dockerfile
    volumes:
      - ~/data:/data
      - ./keys.json:/keys.json
    environment:
      - COMPUTE_API_KEY
      - USER_DATA_PATH=/data/user
      - DISCORD_ID
      - DISCORD_SECRET
      - REDIRECT_URL
      - SHARE_STORE_URL=share:3000
      - DB_STORE_URL=db:3000
      - SUBMISSION_STORE_URL=submission:3000
      - PREVIEW_STORE_URL=preview:3000
      - SHARE_KEY_FILE=/keys.json
      - MQTT_URL=mqtt:1883
      - MQTT_USERNAME=mosquitto
      - MQTT_PASSWORD=password
    restart: unless-stopped
  # discord bot
  managerchan:
    container_name: managerchan
    build:
      context: .
      dockerfile: ./backend/cmd/managerchan/Dockerfile
    environment:
      - SHARE_STORE_URL=share:3000
      - DB_STORE_URL=db:3000
      - SUBMISSION_STORE_URL=submission:3000
      - MQTT_URL=mqtt:1883
      - MQTT_USERNAME=mosquitto
      - MQTT_PASSWORD=password
      - DISCORD_BOT_TOKEN
  # mongo server for db
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root-password
    volumes:
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ~/data/mongo:/data/db:rw
  # dev stuff
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root-password
      ME_CONFIG_MONGODB_URL: mongodb://root:root-password@mongo:27017/
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080