use: pipeline
kind: character
name: zhongli

shortcuts:
  - zhong
  - zl

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
      - attack(5-Hit DMG)
      - attack(6-Hit DMG)
  - charge: attack(Charged Attack DMG)

  - skill: skill(Stone Stele/Resonance DMG)
  - skillTick: skill(Stone Stele/Resonance DMG|1)
  - skillHold: skill(Hold DMG)
  - shieldBase: skill(Shield Base Absorption)
  - shieldPer: skill(Additional Shield Absorption)

  - burst: burst(Skill DMG)

docs:
  fields:
    .zhongli.shielded: Evaluates to 1 if player is currently shielded
  frames:
    - count: https://docs.google.com/spreadsheets/d/1NPOothWseChb-OzOHQqunBdi-M3udmQPqPop0kf7H-w/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/2TMxz446akc
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1NPOothWseChb-OzOHQqunBdi-M3udmQPqPop0kf7H-w/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/tb1bGGVNJoA?t=217
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/19dQSj8Y8LJ_2kLgWKPlkNp9y7sqvFiquO5h03R2YNXI/edit?usp=sharing
      count_credit: Kolibri#767
      video: https://youtu.be/diz7tQf8-yY
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ?t=1832
      video_credit: Kolibri#7675

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Box
        center: Player
        box: [1.5, 3.8]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.8]
        fan_angle: 180
        radius: 2
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Box
        center: Player
        offset: [0, 0.5]
        box: [1, 1.5]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Circle
        center: Player
        offset: [0, 1.8]
        radius: 1.7
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: N5
        shape: Box
        center: Player
        offset: [0, -1]
        box: [1, 4]

      - name: N6
        shape: Box
        center: Player
        offset: [0, 0.2]
        box: [1, 4]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 0.8
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true, deployable: true}

  - name: skill
    params:
      hold: 0 for Tap (default), 1 for Hold.
      hold_nostele: If 1, no Stone Stele will be created (i.e. shield only) and Hold will be performed. Default 0.
    hitbox:
      - name: E-Stele
        note: Stele spawns at the same position.
        shape: Circle
        center: Player
        offset: [0, 3]
        radius: 2

      - name: E-Resonance
        note: Spawns at the position of the resonating construct.
        shape: Box
        center: GlobalValue
        offset: [0, -4]
        box: [8, 8]

      - name: E-Hold
        shape: Circle
        center: Player
        radius: 10

  - name: burst
    hitbox:
      - name: Q-Start
        note: not implemented yet
        shape: Circle
        center: Player
        radius: 3

      - name: Q-ElementalBurst
        shape: Circle
        center: Player
        offset: [0, 5]
        radius: 6

  - name: walk
    note: No action followed by walk has proper frames.
