id: 10000030
key: "zhongli"
rarity: QUALITY_ORANGE
body: BODY_MALE
region: ASSOC_TYPE_LIYUE
element: Rock
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Zhongli"
stats: {
   base_hp: 1143.984
   base_atk: 19.551
   base_def: 57.4368
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 980.8628
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 49.248
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 16.762
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1677.7917
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 84.24
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 28.6718
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2607.0303
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 130.896
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 44.5516
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3303.959
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 165.888
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 56.4614
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4000.888
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 200.88
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 68.3713
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4697.817
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 235.872
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 80.2811
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 10302
   burst: 10303
   attack: 10301
   burst_energy_cost: 40
}
name_text_hash_map: 3862787418
