id: 10000006
key: "lisa"
rarity: QUALITY_PURPLE
body: BODY_LADY
region: ASSOC_TYPE_MONDSTADT
element: Electric
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Lisa"
stats: {
   base_hp: 802.3761
   base_atk: 19.41072
   base_def: 48.069
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 599.416
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 35.91
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 14.501142
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1025.3169
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 61.425
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 24.804585
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 24
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1593.1847
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 95.445
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 38.542507
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2019.0856
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 120.96
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 48.84595
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2444.9863
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 146.475
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 59.149395
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 72
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2870.8872
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 171.99
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 69.452835
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 96
      }
   }
}
skill_details: {
   skill: 10061
   burst: 10062
   attack: 10060
   burst_energy_cost: 80
}
name_text_hash_map: 3344622722
