use: pipeline
kind: character
name: candace

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG|1)
      - attack(4-Hit DMG)
  - charge: attack(Charged Attack DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skillDmg:
      - skill(Shield DMG Absorption)
      - skill(Charged Up DMG)
  - skillShieldPct: skill(Shield DMG Absorption)
  - skillShieldFlat: skill(Shield DMG Absorption|1)

  - burstDmg: burst(Skill DMG)
  - burstWaveDmg: burst(Skill DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1ZzXEM18EpmZcffzbVZNghpR7xrA39ypWwO1BTtiAQzc/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/SkL_R5-N5tQ
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1ieBa344vhM42FvxmlZLMSzlGm5PEykV8VMGQk9Haelk/edit?usp=sharing
      count_credit: GaspNAwe
      video: https://youtu.be/CR-fvyrIdo0
      video_credit: GaspNAwe

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, -0.3]
        radius: 2.5
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Box
        center: Player
        offset: [0, -0.1]
        box: [2.2, 3]
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3-1
        shape: Circle
        center: Player
        offset: [0, 0.3]
        fan_angle: 270
        radius: 2.5

      - name: N3-2
        shape: Circle
        center: Player
        offset: [0, 0.3]
        fan_angle: 270
        radius: 2.5
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Box
        center: Player
        offset: [0, -0.1]
        box: [2.2, 7]
        hitlag: {time: 0.04, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 0.8
        hitlag: {scale: 0.01, defense_halt: true, deployable: true}

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    params:
      hold: 0 for Tap (default), 1 for Hold.
      perfect: 0 for no A1 (default), non-zero value for A1. This sets hold to 1.
    hitbox:
      - name: E-Tap
        shape: Box
        center: Player
        offset: [0, -0.1]
        box: [3, 4.5]
        hitlag: {time: 0.05, scale: 0.01, defense_halt: true}

      - name: E-Hold
        note: Also used for perfect counter.
        shape: Circle
        center: Player
        offset: [0, 0.3]
        radius: 4
        hitlag: {time: 0.05, scale: 0.01, defense_halt: true}

  - name: burst
    hitbox:
      - name: Q-Initial
        shape: Circle
        center: Player
        radius: 3.5
        hitlag: {scale: 0.01, defense_halt: true}

      - name: Q-Wave
        shape: Circle
        center: Player
        radius: 3.5
        hitlag: {scale: 0.01, defense_halt: true}

  - name: cons
    hitbox:
      - name: Q-C6
        shape: Circle
        center: Player
        radius: 3.5
        hitlag: {scale: 0.01, defense_halt: true}

  - name: walk
    note: No action followed by walk (except low_plunge and high_plunge) has proper frames.
