id: 10000107
key: "citlali"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_NATLAN
element: Ice
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Layla"
stats: {
   base_hp: 906.0
   base_atk: 10.0
   base_def: 59.0
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 890.95044
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 53.865
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 19.795113
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1523.9941
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 92.1375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 33.86006
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 28.8
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2368.0525
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 143.1675
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 52.613323
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 57.6
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3001.0962
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 181.44
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 66.67827
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 57.6
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3634.14
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 219.7125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 80.74322
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 86.4
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4267.1836
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 257.985
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 94.80817
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 115.2
      }
   }
}
skill_details: {
   skill: 10402
   burst: 10403
   attack: 10401
   burst_energy_cost: 60
}
name_text_hash_map: 2876340530
