id: 10000037
key: "ganyu"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_LIYUE
element: Ice
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Ganyu"
stats: {
   base_hp: 762.656
   base_atk: 26.068
   base_def: 49.0606
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 653.90857
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 42.066
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.34932
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1118.5278
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 71.955
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 38.2291
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1738.0201
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 111.807
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 59.40214
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2202.6394
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 141.696
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 75.28192
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2667.2585
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 171.585
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 91.1617
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3131.878
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 201.474
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 107.04148
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 10372
   burst: 10373
   attack: 10371
   burst_energy_cost: 60
}
name_text_hash_map: 2679781122
