use: pipeline
kind: character
name: beidou

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
      - attack(5-Hit DMG)

  - shieldPer: skill(Shield DMG Absorption)
  - shieldBase: skill(Shield DMG Absorption|1)
  - skillbonus: skill(DMG Bonus on Hit Taken)

  - skillbase: burst(Skill DMG)
  - burstonhit: burst(Skill DMG)
  - burstproc: burst(Lightning DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1r8fwU2wMBbZsy5fqqSSf8aLvX8aFvJCvaDD8P3Lr2sI/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/mCDHSI1JhuI
      video_credit: Kolibri#7675

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        fan_angle: 270
        radius: 2
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Box
        center: Player
        box: [2, 2.5]
        hitlag: {time: 0.12, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 2
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Circle
        center: Player
        offset: [0, 1]
        fan_angle: 270
        radius: 2
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: N5
        shape: Box
        center: Player
        offset: [0, -0.5]
        box: [2, 3]
        hitlag: {time: 0.12, scale: 0.01, defense_halt: true}

  - name: charge
    hitbox:
      - name: CA-Spinning
        note: not implemented yet
        shape: Circle
        center: Player
        offset: [0, 0.3]
        radius: 3
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true, deployable: true}

      - name: CA-Final
        note: not implemented yet
        shape: Circle
        center: Player
        radius: 3.5
        hitlag: {time: 0.15, scale: 0.01, defense_halt: true, deployable: true}

  - name: skill
    params:
      counter: Number of counter hits. Default 0. 2 for perfect counter. Does not affect frames.
    hitbox:
      - name: E-Base
        shape: Circle
        center: Player
        radius: 6
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: E-Stage1
        shape: Circle
        center: Player
        radius: 7
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: E-Stage2
        note: Also used for perfect counter.
        shape: Circle
        center: Player
        radius: 8
        hitlag: {time: 0.15, scale: 0.01, defense_halt: true}

  - name: burst
    hitbox:
      - name: Q-Initial
        note: C6 has an detection area of 5m around Player.
        shape: Circle
        center: Player
        radius: 4
        hitlag: {time: 0.1, scale: 0.01}

      - name: Q-Lightning
        note: Is done as a chain of attacks starting at the target hit and moving on to a different, random enemy if such an enemy exists.
        shape: Single
        center: GlobalValue

  - name: cons
    hitbox:
      - name: Q-C4
        note: Spawns on target that C4 proc'd on.
        shape: Single
        center: GlobalValue

  - name: walk
    note: No action followed by walk has proper frames.
