id: 10000024
key: "beidou"
rarity: QUALITY_PURPLE
body: BODY_LADY
region: ASSOC_TYPE_LIYUE
element: Electric
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Beidou"
stats: {
   base_hp: 1094.1492
   base_atk: 18.87648
   base_def: 54.36375
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEC_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 817.3855
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 40.6125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 14.102028
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEC_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1398.1593
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 69.46875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 24.12189
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEC_ADD_HURT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2172.5247
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 107.94375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 37.481705
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEC_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2753.2983
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 136.8
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 47.501568
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEC_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3334.0723
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 165.65625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 57.52143
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEC_ADD_HURT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3914.8462
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 194.5125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 67.54129
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEC_ADD_HURT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10242
   burst: 10245
   attack: 10241
   burst_energy_cost: 80
}
name_text_hash_map: 2646367730
