package_name: kaeya
genshin_id: 10000015
key: kaeya
skill_data_mapping:
    attack:
        auto_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        auto_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        auto_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        auto_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        auto_5:
            - 4 # 5-Hit DMG|{param4:F1P}
        charge:
            - 5 # Charged Attack DMG|{param5:F1P}+{param6:F1P}
            - 6 # Charged Attack DMG|{param5:F1P}+{param6:F1P}
    skill:
        skill:
            - 0 # Skill DMG|{param0:P}
    burst:
        burst:
            - 0 # Skill DMG|{param0:F1P}
