id: 10000015
key: "kaeya"
rarity: QUALITY_PURPLE
body: BODY_MALE
region: ASSOC_TYPE_MONDSTADT
element: Ice
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Kaeya"
stats: {
   base_hp: 975.6164
   base_atk: 18.6984
   base_def: 66.381
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 728.8354
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 49.59
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 13.96899
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1246.6921
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 84.825
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.894325
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.0667
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1937.1677
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 131.805
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 37.128105
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.1333
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2455.0244
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 167.04
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 47.05344
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.1333
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2972.881
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 202.275
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 56.978775
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.2
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3490.7378
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 237.51
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 66.90411
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.2667
      }
   }
}
skill_details: {
   skill: 10074
   burst: 10075
   attack: 10073
   burst_energy_cost: 60
}
name_text_hash_map: 4119663210
