use: pipeline
kind: weapon
name: forestregalia

shortcuts:
  - regalia

abilities:
  - name: default
    params:
      pickup_delay: Number of frames until the Leaf is picked up by the active character after every proc.
