use: pipeline
kind: character
name: albedo

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
      - attack(5-Hit DMG)
  - charge:
      - attack(Charged Attack DMG)
      - attack(Charged Attack DMG|1)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skill: skill(Skill DMG)
  - skillTick: skill(Transient Blossom DMG)

  - burst: burst(Burst DMG)
  - burstPerBloom: burst(Fatal Blossom DMG)

docs:
  issues:
    - Burst ticks missing precise frame count
  fields:
    .<character>.mods.albedo-a4: Whether or not Albedo A4 buff is active on the specified character
    .albedo.c2stacks: Current number of C2 stacks
    .albedo.elevator: Evaluates to 1 if skill is currently active
  frames:
    - count: https://docs.google.com/spreadsheets/d/1WIejtwUZpZ2lqTNlK2_6cJPoDe0PUmCL6QKB05m_AQQ/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/BYr-3R-XpfE
      video_credit: Kolibri#7675 (special thanks to Xreejan#1180)
    - count: https://docs.google.com/spreadsheets/d/1WIejtwUZpZ2lqTNlK2_6cJPoDe0PUmCL6QKB05m_AQQ/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/tb1bGGVNJoA
      video_credit: Kolibri#7675 (special thanks to Xreejan#1180)
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ
      video_credit: Kolibri#7675 (special thanks to Xreejan#1180)
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: charliex3000
      video: https://youtu.be/wYS5eokd1qY
      video_credit: charliex3000

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 1.6
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.1]
        fan_angle: 180
        radius: 2
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Box
        center: Player
        offset: [0, -0.2]
        box: [3, 2.6]
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Box
        center: Player
        offset: [0, 0.1]
        box: [1.5, 3.7]
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: N5
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 2
        hitlag: {time: 0.12, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA-1
        shape: Circle
        center: Player
        offset: [0, 0.3]
        fan_angle: 270
        radius: 2.2

      - name: CA-2
        shape: Circle
        center: Player
        offset: [0, 0.3]
        fan_angle: 270
        radius: 2.2

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    hitbox:
      - name: E-Skill
        note: E/C4/C6 has a detection area of 10m around the position of this hitbox.
        shape: Circle
        center: Player
        offset: [0, 3]
        radius: 5

      - name: E-TransientBlossom
        note: Spawns on target that the E proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 3.4

  - name: burst
    hitbox:
      - name: Q-FatalBlossom
        note: Each blossom targets a separate enemy within the E detection area if possible, otherwise it randomly spawns in the E detection area.
        shape: Circle
        center: GlobalValue
        radius: 3

      - name: Q-Start
        note: not implemented yet
        shape: Circle
        center: Player
        radius: 3

      - name: Q-ElementalBurst
        shape: Circle
        center: Player
        fan_angle: 120
        radius: 8

  - name: walk
    note: No action followed by walk (except low_plunge and high_plunge) has proper frames.
