id: 10000038
key: "albedo"
rarity: QUALITY_ORANGE
body: BODY_BOY
region: ASSOC_TYPE_MONDSTADT
element: Rock
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Albedo"
stats: {
   base_hp: 1029.5856
   base_atk: 19.551
   base_def: 68.2062
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 882.77655
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 58.482
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 16.76199
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1510.0126
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 100.035
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 28.671825
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2346.3271
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 155.439
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 44.551605
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2973.5632
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 196.992
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 56.46144
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3600.799
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 238.545
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 68.37128
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4228.035
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 280.098
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 80.28111
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 10387
   burst: 10388
   attack: 10386
   burst_energy_cost: 40
}
name_text_hash_map: 4108620722
