package_name: heizou
genshin_id: 10000059
key: heizou
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}+{param4:F1P}+{param5:F1P}
            - 4 # 4-Hit DMG|{param3:F1P}+{param4:F1P}+{param5:F1P}
            - 5 # 4-Hit DMG|{param3:F1P}+{param4:F1P}+{param5:F1P}
        attack_5:
            - 6 # 5-Hit DMG|{param6:F1P}
        charge:
            - 7 # Charged Attack|{param7:F1P}
        hits:
            - 10 # FIXME: Low/High Plunge DMG|{param10:P}/{param11:P} -- old=1 new=1.136335
    skill:
        convicBonus:
            - 2 # Conviction DMG Bonus|{param2:F1P}
        decBonus:
            - 1 # Declension DMG Bonus|{param1:F1P}/stack
        skill:
            - 0 # Skill DMG|{param0:F1P}
    burst:
        burst:
            - 0 # Fudou Style Vacuum Slugger DMG|{param0:F1P}
        burstIris:
            - 1 # Windmuster Iris DMG|{param1:F1P}
