use: pipeline
kind: weapon
name: skywardblade

abilities:
  - name: default
    hitbox:
      - name: Skyward Blade
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Single
        center: GlobalValue
