use: pipeline
kind: character
name: aetherelectro

override:
  id: 10000005
  depot: 507

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/186FpS4ckDENVY4U60xxgevJZj_vdyYWZroIa7P_yDr4/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/2LnpQIVIszY
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1QNQwbrySIw6pY3rvmj-SB5dIEgUHWNz1q5zDbQrnwBo/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/M6gu5r5dV2M
      video_credit: Kolibri#7675

abilities:
  - name: default
    params:
      base_atk_buff: 0 for no +3 base atk, 1 (default) for +3 base atk. Set via '+params=[base_atk_buff=...]' in the char's line.
      skirk_story_buff: 0 for no buffs, 1 (default) for +7 base atk, +15 EM, +50 base HP. Set via '+params=[skirk_story_buff=...]' in the char's line.

  - name: attack
    hitbox:
      - name: N1
        shape: Box
        center: Player
        box: [1.4, 2.2]
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.6]
        fan_angle: 180
        radius: 1.7
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Box
        center: Player
        offset: [0, 0.4]
        box: [1.5, 2.2]
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.7
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: N5
        shape: Circle
        center: Player
        offset: [0, 0.6]
        fan_angle: 240
        radius: 1.75
        hitlag: {time: 0.12, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA-1
        shape: Circle
        center: Player
        radius: 2.2

      - name: CA-2
        shape: Circle
        center: Player
        radius: 2.2

  - name: skill
    params:
      amulet_delay: Delay until Abundance Amulets are picked up by the active character. Default 107 frames, minimum 107 frames.
      hits: Number of times Thunder Shadow hits. Default 1, maximum 3.
      max_amulets: Customize limit for number of Abudance Amulets generated. Default limit is 2/3 if C0/C1+, maximum is capped by the default limits.
    hitbox:
      - name: E-Skill
        shape: Box
        center: PrimaryTarget
        box: [0.1, 0.6]

  - name: burst
    hitbox:
      - name: Q-Initial
        shape: Circle
        center: Player
        radius: 5

      - name: Q-FallingThunder
        note: Spawns on target hit during Q.
        shape: Circle
        center: GlobalValue
        radius: 2

      - name: Q-FallingThunder-C6
        shape: Circle
        center: GlobalValue
        radius: 2.5

  - name: walk
    note: No action followed by walk has proper frames.
