id: 10000005
sub_id: 507
key: "aetherelectro"
rarity: QUALITY_ORANGE
body: BODY_BOY
region: ASSOC_TYPE_MAINACTOR
element: Electric
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_PlayerBoy"
stats: {
   base_hp: 911.791
   base_atk: 17.808
   base_def: 57.225
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 681.15454
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 42.75
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 13.3038
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1165.1328
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 73.125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.7565
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1810.4371
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 113.625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 35.3601
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2294.4153
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 144
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 44.8128
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2778.3936
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 174.375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 54.2655
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3262.3718
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 204.75
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.7182
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10602
   burst: 10605
   attack: 100546
   burst_energy_cost: 80
}
name_text_hash_map: 1533656818
