// Code generated by "pipeline"; DO NOT EDIT.

package aether

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.AetherElectro, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionSkill: {"amulet_delay", "hits", "max_amulets"},
	}
	validation.RegisterCharParamValidationFunc(keys.AetherElectro, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}
