id: 10000123
key: "durin"
rarity: QUALITY_ORANGE
body: BODY_BOY
region: ASSOC_TYPE_MONDSTADT
element: Fire
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Durin"
stats: {
   base_hp: 967.6198
   base_atk: 26.999
   base_def: 64.0181
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 829.6465
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 54.891
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.14751
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1419.1322
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 93.8925
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.594425
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2205.113
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 145.8945
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.523643
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2794.5986
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 184.896
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 77.97056
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3384.0842
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 223.8975
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 94.41747
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3973.57
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 262.899
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 110.86439
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 11232
   burst: 11235
   attack: 11231
   burst_energy_cost: 70
}
name_text_hash_map: 2801077538
