use: pipeline
kind: weapon
name: crescentpike

shortcuts:
  - cpike
  - pike

abilities:
  - name: default
    hitbox:
      - name: Crescent Pike
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Single
        center: GlobalValue
