// Code generated by "pipeline"; DO NOT EDIT.

// passive: Tip of the Spear # Weapon_Pole_Vorpal
//
//	When the wielder is healed, restore 8 Energy. This effect can be triggered once every
//	10s, and can occur even when the character is not on the field.
package rightfulreward

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.RightfulReward, NewWeapon)
}
