id: 10000121
key: "aino"
rarity: QUALITY_PURPLE
body: BODY_LOLI
region: ASSOC_TYPE_NODKRAI
element: Water
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Aino"
stats: {
   base_hp: 939.1447
   base_atk: 20.30112
   base_def: 50.93025
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 701.5892
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 38.0475
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 15.166332
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1200.0868
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 65.08125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 25.94241
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 24
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1864.7502
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 101.12625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.310513
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2363.2478
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 128.16
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 51.086594
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2861.7454
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 155.19376
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.86267
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 72
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3360.243
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 182.2275
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 72.63875
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 96
      }
   }
}
skill_details: {
   skill: 11212
   burst: 11215
   attack: 11211
   burst_energy_cost: 50
}
name_text_hash_map: 3887688410
