id: 10000034
key: "noelle"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_MONDSTADT
element: Rock
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Noel"
stats: {
   base_hp: 1012.088
   base_atk: 16.0272
   base_def: 66.95325
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 756.08154
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 50.0175
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 11.97342
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1293.2974
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 85.55625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 20.48085
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.075
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2009.5852
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 132.94125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 31.82409
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.15
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2546.801
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 168.48
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.33152
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.15
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3084.0168
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 204.01875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 48.83895
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.225
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3621.2327
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 239.5575
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 57.34638
      }
      add_props: {
         prop_type: FIGHT_PROP_DEFENSE_PERCENT
         value: 0.3
      }
   }
}
skill_details: {
   skill: 10342
   burst: 10343
   attack: 10341
   burst_energy_cost: 60
}
name_text_hash_map: 1921418842
