// Code generated by "pipeline"; DO NOT EDIT.

// set2: Thundering Fury
//
//	Electro DMG Bonus +15%
//
// set4: Thundering Fury # Relic_ReactionElectricEnhance
//
//	Increases the DMG caused by Overloaded, Electro-Charged, Superconduct, and Hyperbloom
//	by 40%, the DMG Bonus conferred by Aggravate by 20%, and the DMG caused by Lunar-Charged
//	and Stellar-Conduct by 20%. When Quicken or the aforementioned Elemental Reactions
//	are triggered, Elemental Skill CD is decreased by 1s. Can only occur once every 0.8s.
package thunderingfury

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterSetFunc(keys.ThunderingFury, NewSet)
}
