version: "3.8"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: "tunnel --no-autoupdate run --token $CF_TUNNEL_TOKEN"
    volumes:
      - ./cloudflared:/etc/cloudflared
    environment:
      - CF_TUNNEL_TOKEN
    depends_on:
      - jadechamber
    restart: unless-stopped
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root-password
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  jadechamber:
    container_name: jadechamber
    build:
      context: .
      dockerfile: ./cmd/jadechamber/Dockerfile
    volumes:
      - .:/app
      - ./data:/data
    environment:
      - USER_DATA_PATH=/data/user
      - DISCORD_ID
      - DISCORD_SECRET
      - REDIRECT_URL
      - RESULT_STORE_URL=result:3000
    depends_on:
      - result
    restart: unless-stopped
  preview:
    container_name: preview
    build:
      context: .
      dockerfile: ./cmd/preview/Dockerfile
    volumes:
      - ~/assets/assets:/assets
    environment:
      - ASSETS_DATA_PATH=/assets
      - RESULT_STORE_URL=result:3000
    restart: unless-stopped
  result:
    container_name: result
    build:
      context: .
      dockerfile: ./cmd/result/Dockerfile
    command: bash -c "./result"
    restart: unless-stopped
    volumes:
      - ./data/result:/data
    environment:
      - RESULT_DATA_PATH=/data
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./cmd/db/Dockerfile
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_DATABASE=gcsim-database
      - MONGODB_COLLECTION=data
      - MONGODB_USERNAME=gcsim
      - MONOGDB_PASSWORD=gcsim-password
    depends_on:
      - result
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root-password
      ME_CONFIG_MONGODB_URL: mongodb://root:root-password@mongo:27017/
