id: 10000131
key: "nicole"
rarity: QUALITY_ORANGE
body: BODY_LADY
element: Fire
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Nicole"
stats: {
   base_hp: 810.322
   base_atk: 26.6266
   base_def: 43.79556
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 694.77783
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 37.5516
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.828234
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1188.4358
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 64.233
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.048294
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1846.6464
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 99.8082
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 60.67504
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2340.3042
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 126.4896
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 76.8951
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2833.9622
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 153.171
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 93.115166
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3327.62
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 179.8524
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 109.33523
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 11312
   burst: 11315
   attack: 11311
   burst_energy_cost: 60
}
name_text_hash_map: 1711582634
