// Code generated by scripts/generate_missing_characters.py; DO NOT EDIT.

package ifa

import (
	"github.com/genshinsim/gcsim/internal/template/character/basicimport"
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/attributes"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() { core.RegisterCharFunc(keys.Ifa, NewChar) }

var generatedProfile = basicimport.Profile{
	Name: "Ifa", Element: attributes.Anemo, Weapon: "Catalyst",
	Energy: 60, SkillCD: 450, BurstCD: 900,
	Attack: []basicimport.Scaling{basicimport.Scaling{Values: []float64{0.536072, 0.576277, 0.616483, 0.67009, 0.710295, 0.750501, 0.804108, 0.857715, 0.911322, 0.96493, 1.018537, 1.072144, 1.139153, 1.206162, 1.273171}, UseDef: false, UseHP: false, UseEM: false}, basicimport.Scaling{Values: []float64{0.474672, 0.510272, 0.545873, 0.59334, 0.62894, 0.664541, 0.712008, 0.759475, 0.806942, 0.85441, 0.901877, 0.949344, 1.008678, 1.068012, 1.127346}, UseDef: false, UseHP: false, UseEM: false}, basicimport.Scaling{Values: []float64{0.747584, 0.803653, 0.859722, 0.93448, 0.990549, 1.046618, 1.121376, 1.196134, 1.270893, 1.345651, 1.42041, 1.495168, 1.588616, 1.682064, 1.775512}, UseDef: false, UseHP: false, UseEM: false}},
	Charge: basicimport.Scaling{Values: []float64{1.4704, 1.58068, 1.69096, 1.838, 1.94828, 2.05856, 2.2056, 2.35264, 2.49968, 2.64672, 2.79376, 2.9408, 3.1246, 3.3084, 3.4922}, UseDef: false, UseHP: false, UseEM: false}, Collision: basicimport.Scaling{Values: []float64{0.568288, 0.614544, 0.6608, 0.72688, 0.773136, 0.826, 0.898688, 0.971376, 1.044064, 1.12336, 1.202656, 1.281952, 1.361248, 1.440544, 1.51984}, UseDef: false, UseHP: false, UseEM: false}, LowPlunge: basicimport.Scaling{Values: []float64{1.136335, 1.228828, 1.32132, 1.453452, 1.545944, 1.65165, 1.796995, 1.94234, 2.087686, 2.246244, 2.404802, 2.563361, 2.721919, 2.880478, 3.039036}, UseDef: false, UseHP: false, UseEM: false}, HighPlunge: basicimport.Scaling{Values: []float64{1.419344, 1.534872, 1.6504, 1.81544, 1.930968, 2.063, 2.244544, 2.426088, 2.607632, 2.80568, 3.003728, 3.201776, 3.399824, 3.597872, 3.79592}, UseDef: false, UseHP: false, UseEM: false},
	Skill: basicimport.Scaling{Values: []float64{1.3336, 1.43362, 1.53364, 1.667, 1.76702, 1.86704, 2.0004, 2.13376, 2.26712, 2.40048, 2.53384, 2.6672, 2.8339, 3.0006, 3.1673}, UseDef: false, UseHP: false, UseEM: false}, Burst: basicimport.Scaling{Values: []float64{5.0848, 5.46616, 5.84752, 6.356, 6.73736, 7.11872, 7.6272, 8.13568, 8.64416, 9.15264, 9.66112, 10.1696, 10.8052, 11.4408, 12.0764}, UseDef: false, UseHP: false, UseEM: false},
}
