package_name: razor
genshin_id: 10000020
key: razor
action_param_keys:
    skill:
        - param: "hold"
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:P}
    skill:
        skillHold:
            - 1 # Hold Skill DMG|{param1:P}
        skillPress:
            - 0 # #{LAYOUT_MOBILE#Tap}{LAYOUT_PC#Press}{LAYOUT_PS#Press} Skill DMG|{param0:P}
    burst:
        burstATKSpeed:
            - 2 # Normal ATK SPD Bonus|{param2:P}
        burstDmg:
            - 0 # Burst DMG|{param0:P}
        wolfDmg:
            - 1 # Soul Companion DMG|{param1:F1P} Normal Attack DMG
