use: pipeline
kind: character
name: razor

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skillPress: skill(Press Skill DMG)
  - skillHold: skill(Hold Skill DMG)

  - burstDmg: burst(Burst DMG)
  - wolfDmg: burst(Soul Companion DMG)
  - burstATKSpeed: burst(Normal ATK SPD Bonus)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1Rceie6ATwNDSbnmIIKgZa1cVtXlBZE6earpJb42SHAM/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/CUXnqF1S2ps
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1ieBa344vhM42FvxmlZLMSzlGm5PEykV8VMGQk9Haelk/edit?usp=sharing
      count_credit: GaspNAwe
      video: https://youtu.be/6bDIKtm7ZDY
      video_credit: GaspNAwe

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 2
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Box
        center: Player
        offset: [0, 0.5]
        box: [3.2, 3]
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 2
        hitlag: {time: 0.1, scale: 0.05, defense_halt: true}

      - name: N4
        shape: Circle
        center: Player
        offset: [0, 1.8]
        radius: 2
        hitlag: {time: 0.15, scale: 0.01, defense_halt: true}

      - name: SoulCompanion-N1
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 2.4

      - name: SoulCompanion-N2
        shape: Box
        center: Player
        offset: [0, 0.5]
        box: [3.4, 3.4]

      - name: SoulCompanion-N3
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 2.4

      - name: SoulCompanion-N4
        shape: Circle
        center: Player
        offset: [0, 1.8]
        radius: 2.4

  - name: charge
    hitbox:
      - name: CA-Spinning
        note: not implemented yet
        shape: Circle
        center: Player
        offset: [0, 0.3]
        radius: 3
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true, deployable: true}

      - name: CA-Final
        note: not implemented yet
        shape: Circle
        center: Player
        radius: 3.5
        hitlag: {time: 0.15, scale: 0.01, defense_halt: true, deployable: true}

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    params:
      hold: 0 for Tap (default), 1 for Hold.
    hitbox:
      - name: E-Tap
        shape: Circle
        center: Player
        offset: [0, 1]
        fan_angle: 240
        radius: 2.4
        hitlag: {time: 0.1, scale: 0.03, defense_halt: true}

      - name: E-Tap-Q
        shape: Circle
        center: Player
        offset: [0, 1]
        fan_angle: 240
        radius: 3

      - name: E-Hold
        shape: Circle
        center: Player
        radius: 5

  - name: burst
    hitbox:
      - name: Q-ElementalBurst
        shape: Circle
        center: Player
        radius: 5

  - name: cons
    hitbox:
      - name: C6
        note: Spawns on target that C6 proc'd on.
        shape: Circle
        center: Player
        offset: [0, 0.7]
        radius: 1.5

  - name: walk
    note: No action followed by walk (except low_plunge and high_plunge) has proper frames.
