use: pipeline
kind: weapon
name: ashgravendrinkinghorn

shortcuts:
  - ashgraven

abilities:
  - name: default
    hitbox:
      - name: Ash-Graven Drinking Horn
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 3
