// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protos/backend/db.proto

package db

import (
	model "github.com/genshinsim/gcsim/pkg/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query *model.DBQueryOpt `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty" bson:"query,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_backend_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_protos_backend_db_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetQuery() *model.DBQueryOpt {
	if x != nil {
		return x.Query
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *model.DBEntries `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty" bson:"data,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_backend_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_protos_backend_db_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetData() *model.DBEntries {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateOrUpdateDBEntryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string         `protobuf:"bytes,1,opt,name=id,json=_id,proto3" json:"id,omitempty" bson:"_id,omitempty"`
	Data *model.DBEntry `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty" bson:"data,omitempty"`
}

func (x *CreateOrUpdateDBEntryRequest) Reset() {
	*x = CreateOrUpdateDBEntryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_backend_db_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateDBEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateDBEntryRequest) ProtoMessage() {}

func (x *CreateOrUpdateDBEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_db_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateDBEntryRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateDBEntryRequest) Descriptor() ([]byte, []int) {
	return file_protos_backend_db_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrUpdateDBEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrUpdateDBEntryRequest) GetData() *model.DBEntry {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateOrUpdateDBEntryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty" bson:"key,omitempty"`
}

func (x *CreateOrUpdateDBEntryResponse) Reset() {
	*x = CreateOrUpdateDBEntryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_backend_db_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateDBEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateDBEntryResponse) ProtoMessage() {}

func (x *CreateOrUpdateDBEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_db_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateDBEntryResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateDBEntryResponse) Descriptor() ([]byte, []int) {
	return file_protos_backend_db_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrUpdateDBEntryResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetComputeWorkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetComputeWorkRequest) Reset() {
	*x = GetComputeWorkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_backend_db_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetComputeWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComputeWorkRequest) ProtoMessage() {}

func (x *GetComputeWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_db_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComputeWorkRequest.ProtoReflect.Descriptor instead.
func (*GetComputeWorkRequest) Descriptor() ([]byte, []int) {
	return file_protos_backend_db_proto_rawDescGZIP(), []int{4}
}

type GetComputeWorkReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Work *model.ComputeWork `protobuf:"bytes,1,opt,name=work,proto3" json:"work,omitempty" bson:"work,omitempty"`
}

func (x *GetComputeWorkReponse) Reset() {
	*x = GetComputeWorkReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_backend_db_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetComputeWorkReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetComputeWorkReponse) ProtoMessage() {}

func (x *GetComputeWorkReponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_db_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetComputeWorkReponse.ProtoReflect.Descriptor instead.
func (*GetComputeWorkReponse) Descriptor() ([]byte, []int) {
	return file_protos_backend_db_proto_rawDescGZIP(), []int{5}
}

func (x *GetComputeWorkReponse) GetWork() *model.ComputeWork {
	if x != nil {
		return x.Work
	}
	return nil
}

var File_protos_backend_db_proto protoreflect.FileDescriptor

var file_protos_backend_db_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x64, 0x62, 0x1a, 0x15, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x64, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x44, 0x42, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x4f, 0x70, 0x74, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x33, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x44, 0x42, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x53, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x42, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0f, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x5f, 0x69,
	0x64, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x44, 0x42, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x42, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x57,
	0x6f, 0x72, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x77, 0x6f,
	0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x04, 0x77, 0x6f,
	0x72, 0x6b, 0x32, 0xdd, 0x01, 0x0a, 0x07, 0x44, 0x42, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x28,
	0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0e, 0x2e, 0x64, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x64, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x42, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x20, 0x2e, 0x64, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x42, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x42, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x19, 0x2e, 0x64, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x64, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_backend_db_proto_rawDescOnce sync.Once
	file_protos_backend_db_proto_rawDescData = file_protos_backend_db_proto_rawDesc
)

func file_protos_backend_db_proto_rawDescGZIP() []byte {
	file_protos_backend_db_proto_rawDescOnce.Do(func() {
		file_protos_backend_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_backend_db_proto_rawDescData)
	})
	return file_protos_backend_db_proto_rawDescData
}

var file_protos_backend_db_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_backend_db_proto_goTypes = []interface{}{
	(*GetRequest)(nil),                    // 0: db.GetRequest
	(*GetResponse)(nil),                   // 1: db.GetResponse
	(*CreateOrUpdateDBEntryRequest)(nil),  // 2: db.CreateOrUpdateDBEntryRequest
	(*CreateOrUpdateDBEntryResponse)(nil), // 3: db.CreateOrUpdateDBEntryResponse
	(*GetComputeWorkRequest)(nil),         // 4: db.GetComputeWorkRequest
	(*GetComputeWorkReponse)(nil),         // 5: db.GetComputeWorkReponse
	(*model.DBQueryOpt)(nil),              // 6: model.DBQueryOpt
	(*model.DBEntries)(nil),               // 7: model.DBEntries
	(*model.DBEntry)(nil),                 // 8: model.DBEntry
	(*model.ComputeWork)(nil),             // 9: model.ComputeWork
}
var file_protos_backend_db_proto_depIdxs = []int32{
	6, // 0: db.GetRequest.query:type_name -> model.DBQueryOpt
	7, // 1: db.GetResponse.data:type_name -> model.DBEntries
	8, // 2: db.CreateOrUpdateDBEntryRequest.data:type_name -> model.DBEntry
	9, // 3: db.GetComputeWorkReponse.work:type_name -> model.ComputeWork
	0, // 4: db.DBStore.Get:input_type -> db.GetRequest
	2, // 5: db.DBStore.CreateOrUpdateDBEntry:input_type -> db.CreateOrUpdateDBEntryRequest
	4, // 6: db.DBStore.GetComputeWork:input_type -> db.GetComputeWorkRequest
	1, // 7: db.DBStore.Get:output_type -> db.GetResponse
	3, // 8: db.DBStore.CreateOrUpdateDBEntry:output_type -> db.CreateOrUpdateDBEntryResponse
	5, // 9: db.DBStore.GetComputeWork:output_type -> db.GetComputeWorkReponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_backend_db_proto_init() }
func file_protos_backend_db_proto_init() {
	if File_protos_backend_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_backend_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_backend_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_backend_db_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateDBEntryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_backend_db_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateDBEntryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_backend_db_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetComputeWorkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_backend_db_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetComputeWorkReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_backend_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_backend_db_proto_goTypes,
		DependencyIndexes: file_protos_backend_db_proto_depIdxs,
		MessageInfos:      file_protos_backend_db_proto_msgTypes,
	}.Build()
	File_protos_backend_db_proto = out.File
	file_protos_backend_db_proto_rawDesc = nil
	file_protos_backend_db_proto_goTypes = nil
	file_protos_backend_db_proto_depIdxs = nil
}
