id: 10000081
key: "kaveh"
rarity: QUALITY_PURPLE
body: BODY_MALE
region: ASSOC_TYPE_SUMERU
element: Grass
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Kaveh"
stats: {
   base_hp: 1002.9701
   base_atk: 19.5888
   base_def: 62.9475
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 749.27
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 47.025
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 14.63418
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1281.6461
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 80.4375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 25.03215
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 24
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1991.4808
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 124.9875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 38.89611
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2523.857
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 158.4
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 49.29408
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3056.233
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 191.8125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 59.69205
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 72
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3588.6091
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 225.225
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 70.09002
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 96
      }
   }
}
skill_details: {
   skill: 10812
   burst: 10815
   attack: 10811
   burst_energy_cost: 80
}
name_text_hash_map: 466355514
