name: "Deploy gcsim Binary"
description: "builds the gcsim binary and deploys. Assumes go has already been setup"
inputs:
  shareKey:
    required: true
    description: "key for signing share results"
  prerelease:
    required: false
    description: "Set true to deploy nightly builds"
    default: "false"
  tag:
    required: true
    description: "tag"
runs:
  using: composite
  steps:
  - name: Build Binary
    shell: bash
    run: |
      # make file runnable, might not be necessary
      chmod +x "${GITHUB_WORKSPACE}/scripts/build.sh"
      # run the script
      "${GITHUB_WORKSPACE}/scripts/build.sh"
    env:
      GCSIM_SHARE_KEY: ${{ inputs.shareKey }}
  
  - name: Release Binary
    uses: softprops/action-gh-release@v1
    if: inputs.prerelease == 'true' || startsWith(github.ref, 'refs/tags/')
    with:
      prerelease: ${{ inputs.prerelease == 'true' }}
      tag_name: ${{ inputs.tag }}
      files: |
        LICENSE
        gcsim.exe
        server.exe