use: pipeline
kind: character
name: navia

override:
  icd_group:
    NaviaBurst:
      name: Avatar_Navia_Burst

shortcuts:
  - demoiselle

combat:
  icd_groups:
    - NaviaBurst

talents:
  - auto:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG)
        - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skillshotgun: skill(Rosula Shardshot Base DMG)
  - skillblade: skill(Surging Blade DMG)

  - burst:
      - burst(Skill DMG)
      - burst(Cannon Fire Support DMG)

docs:
  fields:
    .navia.shrapnel: Number of Crystal Shrapnel stacks.
  frames:
    - count: https://docs.google.com/spreadsheets/d/1M_FffTMTx11rbESklIbzgiSfm9RnWhgKcRlSEnJ08p4/edit#gid=0
      count_credit: shizukayuki
      video: https://youtu.be/qnWjXMmf6MM
      video_credit: shizukayuki
    - count: https://docs.google.com/spreadsheets/d/1M_FffTMTx11rbESklIbzgiSfm9RnWhgKcRlSEnJ08p4/edit#gid=0
      count_credit: shizukayuki
      video: https://youtu.be/BxIFv2HUob0
      video_credit: shizukayuki
    - count: https://docs.google.com/spreadsheets/d/1M_FffTMTx11rbESklIbzgiSfm9RnWhgKcRlSEnJ08p4/edit#gid=0
      count_credit: shizukayuki
      video: https://youtu.be/PJu7ulF0JJo
      video_credit: shizukayuki
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: caramielle.
      video: https://youtu.be/7pVAKVcPuSo
      video_credit: caramielle.

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 2
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Box
        center: Player
        offset: [0, -1.5]
        box: [2, 4.3]
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N3-1
        shape: Box
        center: Player
        offset: [0, 0.3]
        box: [3, 4.5]
        hitlag: {time: 0.01, scale: 0.01, deployable: true}

      - name: N3-2
        shape: Box
        center: Player
        offset: [0, 0.3]
        box: [3, 4.5]
        hitlag: {time: 0.01, scale: 0.01, deployable: true}

      - name: N3-3
        shape: Box
        center: Player
        offset: [0, 0.3]
        box: [3, 4.5]
        hitlag: {time: 0.01, scale: 0.01, deployable: true}

      - name: N4
        shape: Box
        center: Player
        offset: [0, -1.85]
        box: [2, 4.7]
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    params:
      hold: 0 for Tap (default), value between 1 and 241 for Hold. The number is added to the minimum holding frames for Tap to turn into Hold (41), subtracted by 1 to account for requiring a 1 to activate.
    hitbox:
      - name: E-1st-Bullet
        shape: Box
        center: Player
        box: [0.9, 11.5]

      - name: E-2nd-Bullet
        note: Box rotation angle is 7.911°.
        shape: Box
        center: Player
        box: [0.25, 11.5]

      - name: E-3rd-Bullet
        note: Box rotation angle is -1.826°.
        shape: Box
        center: Player
        box: [0.25, 11.5]

      - name: E-4th-Bullet
        note: Box rotation angle is -4.325°.
        shape: Box
        center: Player
        box: [0.25, 11.5]

      - name: E-5th-Bullet
        note: Box rotation angle is 0.733°.
        shape: Box
        center: Player
        box: [0.25, 11.5]

      - name: E-6th-Bullet
        note: Box rotation angle is 6.209°.
        shape: Box
        center: Player
        box: [0.25, 11.5]

      - name: E-7th-Bullet
        note: Box rotation angle is -2.752°.
        shape: Box
        center: Player
        box: [0.25, 11.5]

      - name: E-8th-Bullet
        note: Box rotation angle is 7.845°.
        shape: Box
        center: Player
        offset: [0.01, 0.01]
        box: [0.25, 11.5]

      - name: E-9th-Bullet
        note: Box rotation angle is -7.933°.
        shape: Box
        center: Player
        offset: [-0.01, -0.01]
        box: [0.25, 11.5]

      - name: E-10th-Bullet
        note: Box rotation angle is 2.626°.
        shape: Box
        center: Player
        box: [0.25, 11.5]

      - name: E-11th-Bullet
        note: Box rotation angle is -9.993°.
        shape: Box
        center: Player
        box: [0.25, 11.5]

      - name: E-Ceremonial-Crystalshot
        note: If any bullet hits a target, then this attack will spawn on them.
        shape: Single
        center: GlobalValue

  - name: burst
    hitbox:
      - name: Q-Initial
        shape: Box
        center: Player
        box: [5, 12]

      - name: Q-Fire-Support
        note: 'The Circle Spawns in a random position, within 1.2m of the centre of the enemy. If there are no enemies within 10m, then it will spawn in a random location between 1 and 6m from the player''s position + Y: 4m.'
        shape: Circle
        center: PrimaryTarget
        radius: 3

  - name: walk
    note: Normal Attacks do not have legal walk cancels recorded, but Skill, Burst and Low/High Plunge do.
