id: 10000091
key: "navia"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_FONTAINE
element: Rock
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Navia"
stats: {
   base_hp: 984.77954
   base_atk: 27.3714
   base_def: 61.74456
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 844.35944
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 52.9416
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.466785
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1444.2991
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 90.558
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.140556
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2244.2185
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 140.7132
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 62.372246
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2844.158
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 178.3296
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 79.04601
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3444.0977
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 215.946
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 95.71979
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4044.0374
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 253.5624
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 112.393555
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 10912
   burst: 10915
   attack: 10911
   burst_energy_cost: 60
}
name_text_hash_map: 2877588578
