use: pipeline
kind: weapon
name: lostprayertothesacredwinds

shortcuts:
  - lostprayer

abilities:
  - name: default
    params:
      stacks: Number of stacks to gain at the beginning. Default 0, maximum 4.
