package_name: kazuha
genshin_id: 10000047
key: kazuha
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
            - 3 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
        attack_4:
            - 4 # 4-Hit DMG|{param4:F1P}
        attack_5:
            - 5 # 5-Hit DMG|{param5:F1P}×3
            - 5 # 5-Hit DMG|{param5:F1P}×3
            - 5 # 5-Hit DMG|{param5:F1P}×3
        charge:
            - 6 # Charged Attack DMG|{param6:F1P}+{param7:F1P}
            - 7 # Charged Attack DMG|{param6:F1P}+{param7:F1P}
        highPlunge:
            - 11 # Low/High Plunge DMG|{param10:P}/{param11:P}
        plunge:
            - 9 # Plunge DMG|{param9:F1P}
    skill:
        skill:
            - 0 # #{LAYOUT_MOBILE#Tap}{LAYOUT_PC#Press}{LAYOUT_PS#Press} Skill DMG|{param0:P}
        skillHold:
            - 2 # Hold Skill DMG|{param2:P}
    burst:
        burstDot:
            - 1 # DoT|{param1:P}
        burstEleDot:
            - 2 # Additional Elemental DMG|{param2:P}
        burstSlash:
            - 0 # Slashing DMG|{param0:P}
