name = "gcsim-gateway"
main = "src/index.ts"
compatibility_date = "2022-11-06"

[[r2_buckets]]
  binding = 'GCSIM_ASSETS'
  bucket_name = 'gcsim'

[[r2_buckets]]
  binding = 'GCSIM_WASM'
  bucket_name = 'wasm'