use: pipeline
kind: character
name: sigewinne

override:
  icd_group:
    Sigewinne:
      damage: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      durability: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      timer: 2
    SigewinneBurst:
      damage: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      durability: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      timer: 1.9

combat:
  icd_groups:
    - Sigewinne
    - SigewinneBurst

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
  - aim: attack(Aimed Shot)
  - fullaim: attack(Fully-Charged Aimed Shot)
  - miniStrationBubbleDMG: attack(Mini-Stration Bubble DMG)

  - bolsteringBubblebalmDMG: skill(Bolstering Bubblebalm DMG)
  - bolsteringBubblebalmHealingPct: skill(Bolstering Bubblebalm Healing)
  - bolsteringBubblebalmHealingFlat: skill(Bolstering Bubblebalm Healing|1)
  - finalBounceHealing: skill(Final Bounce Healing)
  - surgingBladeDMG: skill(Surging Blade DMG)
  - suringBladeInterval: skill(Surging Blade Interval)

  - burstDMG: burst(Skill DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1JeEGa_nOSXkMwiL0iV1v7TnCERZ-361SUEDxTwVN1MY/edit?usp=sharing
      count_credit: ange1o5
      video: https://www.youtube.com/watch?v=SI7JjuCxCBQ
      video_credit: ange1o5 (special thanks to digimon666)

abilities:
  - name: attack
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: N1
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N2
        shape: Circle
        center: PrimaryTarget
        radius: 1

      - name: N3
        shape: Circle
        center: PrimaryTarget
        radius: 1

  - name: aim
    params:
      hold: 0 for Physical Aimed Shot, 1 for Fully-Charged Aimed Shot (default), 2 for Fully-Charged Aimed Shot with Mini-Bubble.
      travel: Projectile travel time. Default 10 frames.
      weakspot: Hit weakspot with aimed shot. Default 0 (false), 1 for true.
    hitbox:
      - name: Aim
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: Aim-Head
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]
        hitlag: {time: 0.12, scale: 0.01, deployable: true}

      - name: FullAim
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: FullAim-Head
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]
        hitlag: {time: 0.12, scale: 0.01, deployable: true}

      - name: Aim-Bubble
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.3, 0.3]

  - name: skill
    params:
      hold: 0 for Tap (default), 1 for short Hold (tier 1 bubble), 2 for Hold (tier 2 bubble).
    hitbox:
      - name: E-Bubblebalm
        shape: Circle
        center: PrimaryTarget
        radius: 1

      - name: E-Spiritbreath-Thorn
        shape: Circle
        center: PrimaryTarget
        radius: 3

  - name: burst
    params:
      ticks: Number of ticks for Elemental Burst. Default is maximum number of ticks, minimum 2. If the number of ticks is not the maximum, the next action must be Dash, or Jump.
    hitbox:
      - name: Q-Hit
        note: This is an approximation because we do not actually know the real AoE. The hitbox was taken from Neuvillette's CA and was made slightly wider.
        shape: Box
        center: Player
        box: [4, 10]

  - name: dash
    params:
      pickup_droplets: Number of picked up Sourcewater Droplets. Default 0.
