id: 10000096
key: "arlecchino"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_FATUI
element: Fire
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Arlecchino"
stats: {
   base_hp: 1020.0524
   base_atk: 26.6266
   base_def: 59.53085
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 874.6027
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 51.0435
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.828234
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1496.0309
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 87.31125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.048294
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2324.6018
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 135.66824
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 60.67504
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2946.03
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 171.936
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 76.8951
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3567.4585
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 208.20375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 93.115166
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4188.8867
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 244.4715
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 109.33523
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 10962
   burst: 10965
   attack: 10961
   burst_energy_cost: 60
}
name_text_hash_map: 167199474
