package_name: cyno
genshin_id: 10000071
key: cyno
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
            - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
        attack_4:
            - 4 # 4-Hit DMG|{param4:F1P}
        charge:
            - 5 # Charged Attack DMG|{param5:F1P}
    skill:
        skill:
            - 0 # Skill DMG|{param0:F1P}
        skillB:
            - 1 # Mortuary Rite DMG|{param1:F1P}
    burst:
        attackB_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attackB_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attackB_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attackB_4:
            - 3 # 4-Hit DMG|{param3:F1P}+{param4:F1P}
            - 3 # 4-Hit DMG|{param3:F1P}+{param4:F1P}
        attackB_5:
            - 5 # 5-Hit DMG|{param5:F1P}
        chargeB:
            - 6 # Charged Attack DMG|{param6:F1P}
