package_name: cyno
genshin_id: 10000071
key: cyno
action_param_keys:
    low_plunge:
      - param: "collision"
    high_plunge:
      - param: "collision"
icd_tags:
  - ICDTagCynoBolt
icd_groups:
  - group_name: ICDGroupCynoBolt
    reset_timer: 150
    ele_app_sequence: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
      - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
    attack_4:
      - 4 # 4-Hit DMG|{param4:F1P}
    charge:
      - 5 # Charged Attack DMG|{param5:F1P}
    collision:
      - 7 # Plunge DMG|{param6:F1P}
    lowPlunge:
      - 8 # Low/High Plunge DMG|{param7:P}/{param8:P}
    highPlunge:
      - 9 # Low/High Plunge DMG|{param7:P}/{param8:P}
  skill:
    skill:
      - 0 # Skill DMG|{param0:F1P}
    skillB:
      - 1 # Mortuary Rite DMG|{param1:F1P}
  burst:
    attackB_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attackB_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attackB_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    attackB_4:
      - 3 # 4-Hit DMG|{param3:F1P}+{param4:F1P}
      - 3 # 4-Hit DMG|{param3:F1P}+{param4:F1P}
    attackB_5:
      - 5 # 5-Hit DMG|{param5:F1P}
    chargeB:
      - 6 # Charged Attack DMG|{param6:F1P}
    collisionB:
      - 8 # Plunge DMG|{param6:F1P}
    lowPlungeB:
      - 9 # Low/High Plunge DMG|{param7:P}/{param8:P}
    highPlungeB:
      - 10 # Low/High Plunge DMG|{param7:P}/{param8:P}
