id: 10000071
key: "cyno"
rarity: QUALITY_ORANGE
body: BODY_BOY
region: ASSOC_TYPE_SUMERU
element: Electric
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Cyno"
stats: {
   base_hp: 972.3864
   base_atk: 24.7646
   base_def: 66.88994
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 833.7334
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 57.3534
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.231853
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1426.1229
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 98.1045
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 36.317646
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2215.9756
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 152.4393
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 56.432034
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2808.3652
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 193.1904
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 71.51782
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3400.7546
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 233.9415
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 86.603615
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3993.1443
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 274.6926
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 101.68941
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 10712
   burst: 10715
   attack: 10711
   burst_energy_cost: 80
}
name_text_hash_map: 1049891906
