use: pipeline
kind: weapon
name: swordofdescension

shortcuts:
  - descension

abilities:
  - name: default
    params:
      passive: 0 for passive disabled, 1 for enabled (default).
    hitbox:
      - name: Sword of Descension
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 1.5
