// Code generated by "pipeline"; DO NOT EDIT.

// passive: Phantom Flash # Weapon_Bow_Ilmarinen
//
//	Upon causing an Elemental Reaction, increases Elemental Mastery by 60 for 12s. Moonsign:
//	Ascendant Gleam: Elemental Mastery from this effect is further increased by 60. This
//	effect can be triggered even if the equipping character is off-field.
package snarehook

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.SnareHook, NewWeapon)
}
