id: 10000114
key: "skirk"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: 11
element: Ice
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_SkirkNew"
stats: {
   base_hp: 966.6665
   base_atk: 27.93
   base_def: 62.76167
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 828.8291
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 53.8137
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.9457
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1417.734
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 92.04975
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.95975
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2202.9404
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 143.03114
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.64515
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2791.8455
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 181.2672
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 80.6592
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3380.7502
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 219.50325
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 97.67325
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3969.6553
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 257.7393
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 114.6873
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 11142
   burst: 11145
   attack: 11141
}
name_text_hash_map: 123650890
