// Code generated by "pipeline"; DO NOT EDIT.

// passive: Echoes of the Plentiful Land # Weapon_Catalyst_Isikhulu
//
//	Using an Elemental Skill grants the Jade-Forged Crown effect: Every 1,000 Max HP
//	will increase the Normal Attack DMG dealt by the equipping character by 0.6% for
//	10s. Normal Attack DMG can be increased this way by a maximum of 16%.
package ringofyaxche

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.RingOfYaxche, NewWeapon)
}
