use: pipeline
kind: character
name: chasca

override:
  icd_group:
    ChascaBurst:
      damage: [1, 1, 1, 1, 1, 1]
      durability: [1, 0, 1, 0, 1, 0]
      timer: 1.5
    ChascaShadowhunt:
      damage: [1, 1]
      durability: [1, 0]
      timer: 1.5
    ChascaShining:
      damage: [1, 1, 1, 1, 1, 1]
      durability: [1, 0, 1, 0, 1, 0]
      timer: 1.5
    ChascaTap:
      damage: [1, 1]
      durability: [1, 0]
      timer: 1.5

combat:
  icd_tags:
    - ChascaBurst
    - ChascaShadowhunt
    - ChascaShining
    - ChascaTap
  icd_groups:
    - ChascaBurst
    - ChascaShadowhunt
    - ChascaShining
    - ChascaTap

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - aim: attack(Aimed Shot)
  - fullAim: attack(Fully-Charged Aimed Shot)
  - plunge: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)

  - skillResonance: skill(Resonance DMG)
  - skillNA: skill(Multitarget Fire Tap DMG)
  - skillShadowhunt: skill(Shadowhunt Shell DMG)
  - skillShining: skill(Shining Shadowhunt Shell DMG)

  - burstGalesplitting: burst(Galesplitting Soulseeker Shell DMG)
  - burstSoulseeker: burst(Soulseeker Shell DMG)
  - burstRadiant: burst(Radiant Soulseeker Shell DMG)

docs:
  issues:
    - Cannot jump while in Nightsoul Blessing
  frames:
    - count: https://docs.google.com/spreadsheets/d/1B8aZztSooNweTLe5VXG9KALMEGRn_xJHhAmRoC1v4pc/edit?usp=sharing
      count_credit: charliex3000
      video: https://youtu.be/_F2aJ5g8ScU
      video_credit: mystathi
    - count: https://docs.google.com/spreadsheets/d/1B8aZztSooNweTLe5VXG9KALMEGRn_xJHhAmRoC1v4pc/edit?usp=sharing
      count_credit: charliex3000
      video: https://youtu.be/lxql2A394EA
      video_credit: mystathi
    - count: https://docs.google.com/spreadsheets/d/1B8aZztSooNweTLe5VXG9KALMEGRn_xJHhAmRoC1v4pc/edit?usp=sharing
      count_credit: charliex3000
      video: https://youtu.be/xyu0zVPWI8k
      video_credit: mystathi
    - count: https://docs.google.com/spreadsheets/d/1B8aZztSooNweTLe5VXG9KALMEGRn_xJHhAmRoC1v4pc/edit?usp=sharing
      count_credit: charliex3000
      video: https://youtu.be/-AmUyp1F9_E
      video_credit: charliex3000
    - count: https://docs.google.com/spreadsheets/d/1B8aZztSooNweTLe5VXG9KALMEGRn_xJHhAmRoC1v4pc/edit?usp=sharing
      count_credit: charliex3000
      video: https://youtu.be/cGoXDD0TJ9U
      video_credit: charliex3000

abilities:
  - name: attack
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: N1
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N2
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N3
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N4
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: E-N1
        shape: Single
        center: PrimaryTarget

  - name: aim
    params:
      bullets: Number of bullets to fire. Default is maximum number of bullets. Must be between 1 and 6.
      hold: 0 for Physical Aimed Shot, 1 for Fully-Charged Aimed Shot (default).
      travel: Projectile travel time. Default 10 frames.
      weakspot: Hit weakspot with aimed shot. Default 0 (false), 1 for true.
    hitbox:
      - name: Aim
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: Aim-Head
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]
        hitlag: {time: 0.12, scale: 0.01, deployable: true}

      - name: FullAim
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: FullAim-Head
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]
        hitlag: {time: 0.12, scale: 0.01, deployable: true}

      - name: E-Aimed
        note: Target aquisition range is not implemented.
        shape: Single
        center: PrimaryTarget

  - name: plunge
    hitbox:
      - name: Low_Plunge
        shape: Circle
        center: Player
        radius: 3

  - name: low_plunge
    note: Must have just exited Nightsoul Blessing
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    hitbox:
      - name: E
        shape: Circle
        center: Player
        radius: 5.5

  - name: burst
    hitbox:
      - name: Q-Initial
        shape: Circle
        center: PrimaryTarget
        radius: 6

      - name: Q-SoulseekerShell
        shape: Single
        center: PrimaryTarget

  - name: cons
    hitbox:
      - name: C2
        shape: Circle
        center: PrimaryTarget
        radius: 5

      - name: C4
        note: This is an approximation because we do not actually know the real AoE. Based on C2 position.
        shape: Circle
        center: PrimaryTarget
        radius: 5
