// Code generated by "pipeline"; DO NOT EDIT.

// passive: Ever-Changing # Weapon_Catalyst_Outlaw
//
//	Hitting an opponent with a Normal Attack decreases the Stamina consumption of Sprint
//	or Alternate Sprint by 14% for 5s. Additionally, using a Sprint or Alternate Sprint
//	ability increases ATK by 20% for 5s.
package wine

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.WineAndSong, NewWeapon)
}
