use: pipeline
kind: weapon
name: debateclub

abilities:
  - name: default
    hitbox:
      - name: Debate Club
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 3
