use: pipeline
kind: character
name: bennett

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
      - attack(5-Hit DMG)
  - charge:
      - attack(Charged Attack DMG)
      - attack(Charged Attack DMG|1)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skill: skill(Press DMG)
  - skillHold:
      - - skill(Charge Level 1 DMG)
        - skill(Charge Level 1 DMG|1)
      - - skill(Charge Level 2 DMG)
        - skill(Charge Level 2 DMG|1)
  - explosion: skill(Explosion DMG)

  - burst: burst(Skill DMG)
  - bursthpp: burst(Continuous Regeneration Per Sec)
  - bursthp: burst(Continuous Regeneration Per Sec|1)
  - burstatk: burst(ATK Bonus Ratio)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1xjUpc3yUcpqaioep250lfxlpK-feDbdrBmD0TuvBcoA/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/d6X6yF4ffXM
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1xjUpc3yUcpqaioep250lfxlpK-feDbdrBmD0TuvBcoA/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/tb1bGGVNJoA?t=25
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: charliex3000
      video: https://youtu.be/9z8ZVBE-7H8
      video_credit: charliex3000

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 1.2
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 1.2
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Circle
        center: Player
        offset: [0, 0.6]
        fan_angle: 30
        radius: 2
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Box
        center: Player
        offset: [0, 0.3]
        box: [1, 3.5]
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: N5
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 2
        hitlag: {time: 0.12, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA-1
        shape: Circle
        center: Player
        radius: 2.2

      - name: CA-2
        shape: Circle
        center: Player
        radius: 2.2

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    params:
      hold: 0 for Tap (default), 1 for Hold Lv. 1, 2 for Hold Lv. 2.
      hold_c4: If 1, trigger C4. Default 0.
    hitbox:
      - name: E-Tap
        shape: Circle
        center: Player
        offset: [0, 0.8]
        fan_angle: 270
        radius: 2.5
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: E-Hold-Lv.1-1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 2.5
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: E-Hold-Lv.1-2
        shape: Box
        center: Player
        box: [3, 3]
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: E-Hold-Lv.1-C4
        shape: Box
        center: Player
        offset: [0, -1]
        box: [3, 4]
        hitlag: {time: 0.12, scale: 0.01, defense_halt: true}

      - name: E-Hold-Lv.2-1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 2.5
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: E-Hold-Lv.2-2
        shape: Box
        center: Player
        box: [3, 3]
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: E-Hold-Lv.2-Explosion
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3.5
        hitlag: {scale: 0.01, defense_halt: true}

  - name: burst
    hitbox:
      - name: Q-ElementalBurst
        note: Q has a detection area with the same hitbox.
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 6

  - name: walk
    note: No action followed by walk (except low_plunge and high_plunge) has proper frames.
