id: 10000032
key: "bennett"
rarity: QUALITY_PURPLE
body: BODY_BOY
region: ASSOC_TYPE_MONDSTADT
element: Fire
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Bennett"
stats: {
   base_hp: 1039.4418
   base_atk: 16.0272
   base_def: 64.66425
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 776.5162
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 48.3075
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 11.97342
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1328.2513
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 82.63125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 20.48085
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.0667
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2063.8984
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 128.39626
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 31.82409
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.1333
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2615.6335
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 162.72
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.33152
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.1333
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3167.3687
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 197.04375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 48.83895
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.2
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3719.104
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 231.3675
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 57.34638
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.2667
      }
   }
}
skill_details: {
   skill: 10322
   burst: 10323
   attack: 10321
   burst_energy_cost: 60
}
name_text_hash_map: 968893378
