id: 10000092
key: "gaming"
rarity: QUALITY_PURPLE
body: BODY_BOY
region: ASSOC_TYPE_LIYUE
element: Fire
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Gaming"
stats: {
   base_hp: 957.3805541992188
   base_atk: 25.2873592376709
   base_def: 58.941749572753906
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 715.2122802734375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 44.032501220703125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 18.891395568847656
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1223.389404296875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 75.3187484741211
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 32.314231872558594
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.05999999865889549
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1900.958984375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 117.03375244140625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 50.211341857910156
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.11999999731779099
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2409.13623046875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 148.32000732421875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.63417434692383
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.11999999731779099
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2917.313232421875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 179.6062469482422
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 77.0570068359375
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18000000715255737
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3425.490478515625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 210.8925018310547
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 90.47984313964844
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.23999999463558197
      }
   }
}
skill_details: {
   skill: 10922
   burst: 10925
   attack: 10921
   burst_energy_cost: 60
}
name_text_hash_map: 2822240322
