id: 10000092
key: "gaming"
rarity: QUALITY_PURPLE
body: BODY_BOY
region: ASSOC_TYPE_LIYUE
element: Fire
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Gaming"
stats: {
   base_hp: 957.38055
   base_atk: 25.28736
   base_def: 58.94175
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 715.2123
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 44.0325
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 18.891396
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1223.3894
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 75.31875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 32.31423
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1900.959
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 117.03375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 50.21134
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2409.1362
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 148.32
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.634174
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2917.3132
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 179.60625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 77.05701
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3425.4905
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 210.8925
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 90.47984
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10922
   burst: 10925
   attack: 10921
   burst_energy_cost: 60
}
name_text_hash_map: 2822240322
