use: pipeline
kind: character
name: dehya

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skill: skill(Indomitable Flame DMG)
  - skillReposition: skill(Ranging Flame DMG)
  - skillDotAtk: skill(Field DMG)
  - skillDotHP: skill(Field DMG|1)
  - skillMitigation: skill(Mitigation)

  - burstPunchAtk: burst(Flame-Mane's Fist DMG)
  - burstPunchHP: burst(Flame-Mane's Fist DMG|1)
  - burstKickAtk: burst(Incineration Drive DMG)
  - burstKickHP: burst(Incineration Drive DMG|1)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1KzU1x3IYldih1X4zBTEk4Gt1YuhRavY9g2wFR6KRuEs/edit?usp=sharing
      count_credit: Rare Possum#0511
      video: https://youtu.be/4-YlegX6H1I
      video_credit: Rare Possum#0511
    - count: https://docs.google.com/spreadsheets/d/1KzU1x3IYldih1X4zBTEk4Gt1YuhRavY9g2wFR6KRuEs/edit?usp=sharing
      count_credit: Rare Possum#0511
      video: https://youtu.be/0vlD_HKlMJ8
      video_credit: Rare Possum#0511
    - count: https://docs.google.com/spreadsheets/d/1KzU1x3IYldih1X4zBTEk4Gt1YuhRavY9g2wFR6KRuEs/edit?usp=sharing
      count_credit: Rare Possum#0511
      video: https://youtu.be/SgYaMQ2hauA
      video_credit: Rare Possum#0511
    - count: https://docs.google.com/spreadsheets/d/1KzU1x3IYldih1X4zBTEk4Gt1YuhRavY9g2wFR6KRuEs/edit?usp=sharing
      count_credit: Rare Possum#0511
      video: https://youtu.be/8Vo3onHdALg
      video_credit: Rare Possum#0511
    - count: https://docs.google.com/spreadsheets/d/1KzU1x3IYldih1X4zBTEk4Gt1YuhRavY9g2wFR6KRuEs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/hULyCxfdRzI
      video_credit: Rare Possum#0511
    - count: https://docs.google.com/spreadsheets/d/1KzU1x3IYldih1X4zBTEk4Gt1YuhRavY9g2wFR6KRuEs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/8JR-lHgVvUo
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: kolibri._.
      video: https://youtu.be/vZFTlvudpKg
      video_credit: kolibri._.

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 2.2
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Box
        center: Player
        offset: [0, -1.3]
        box: [2.3, 4.3]
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 1.8
        hitlag: {time: 0.08, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Box
        center: Player
        offset: [0, -0.8]
        box: [3, 4.3]
        hitlag: {time: 0.12, scale: 0.01, defense_halt: true}

  - name: charge
    hitbox:
      - name: CA-Spinning
        note: not implemented yet
        shape: Circle
        center: Player
        offset: [0, 0.3]
        radius: 3
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true, deployable: true}

      - name: CA-Final
        note: not implemented yet
        shape: Circle
        center: Player
        radius: 3.5
        hitlag: {time: 0.15, scale: 0.01, defense_halt: true, deployable: true}

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    hitbox:
      - name: E-Indomitable
        note: E has a detection area of 10m around the position of this hitbox.
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 5

      - name: E-Ranging
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 6
        hitlag: {time: 0.02, scale: 0.01}

      - name: E-Mitigation
        note: Applies to the Player.
        shape: Single
        center: Player

      - name: E-Field
        note: Spawns on target that the E proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 4.5
        hitlag: {time: 0.02, scale: 0.01, deployable: true}

  - name: burst
    hitbox:
      - name: Q-Incineration
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 6.5

      - name: Q-Fist
        shape: Box
        center: Player
        offset: [0, -2.8]
        box: [5, 7.8]

  - name: walk
    note: No action followed by walk (except low_plunge and high_plunge) has proper frames.
