package_name: dehya
genshin_id: 10000079
key: dehya
action_param_keys:
    low_plunge:
        - param: "collision"
    high_plunge:
        - param: "collision"
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        collision:
            - 8 # Plunge DMG|{param6:F1P}
        lowPlunge:
            - 9 # Low/High Plunge DMG|{param7:P}/{param8:P}
        highPlunge:
            - 10 # Low/High Plunge DMG|{param7:P}/{param8:P}
    skill:
        skill:
            - 0 # Indomitable Flame DMG|{param0:F1P}
        skillDotAtk:
            - 2 # Field DMG|{param2:F1P} ATK+{param3:F2P} Max HP
        skillDotHP:
            - 3 # Field DMG|{param2:F1P} ATK+{param3:F2P} Max HP
        skillMitigation:
            - 4 # Mitigation|{param4:P}
        skillReposition:
            - 1 # Ranging Flame DMG|{param1:F1P}
    burst:
        burstKickAtk:
            - 2 # Incineration Drive DMG|{param2:F1P} ATK+{param3:F2P} Max HP
        burstKickHP:
            - 3 # Incineration Drive DMG|{param2:F1P} ATK+{param3:F2P} Max HP
        burstPunchAtk:
            - 0 # Flame-Mane''s Fist DMG|{param0:F1P} ATK+{param1:F2P} Max HP
        burstPunchHP:
            - 1 # Flame-Mane''s Fist DMG|{param0:F1P} ATK+{param1:F2P} Max HP
