id: 10000079
key: "dehya"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_SUMERU
element: Fire
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Dehya"
stats: {
   base_hp: 1220.2496
   base_atk: 20.6682
   base_def: 48.88111
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1046.2537
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 41.9121
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 17.719818
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1789.6445
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 71.69175
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 30.310215
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2780.8323
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 111.39795
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 47.097412
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3524.223
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 141.1776
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 59.68781
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4267.614
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 170.95724
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 72.278206
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 5011.0044
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 200.7369
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 84.8686
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 10792
   burst: 10795
   attack: 10791
   burst_energy_cost: 70
}
name_text_hash_map: 2360533154
