use: pipeline
kind: character
name: jean

talents:
  - auto:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
      - attack(5-Hit DMG)
  - charge: attack(Charged Attack DMG)

  - skill: skill(Skill DMG)

  - burst: burst(Burst DMG)
  - burstEnter: burst(Field Entering/Exiting DMG)
  - burstInitialHealPer: burst(Field Activation Healing)
  - burstInitialHealFlat: burst(Field Activation Healing|1)
  - burstDotHealPer: burst(Continuous Regeneration)
  - burstDotHealFlat: burst(Continuous Regeneration|1)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1KQB8VOEyaCsRa3QulF-gAq3a1CxsqiauTNYuK2_paMY/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/HJrJkYgsg84
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ?t=725
      video_credit: Kolibri#7675

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 1.5]
        radius: 1.5
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, -0.5]
        fan_angle: 150
        radius: 2.2
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Circle
        center: Player
        offset: [0, -1]
        fan_angle: 30
        radius: 2.8
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.6
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N5
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.6
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA
        shape: Circle
        center: Player
        offset: [0, 1]
        fan_angle: 160
        radius: 1.8

  - name: skill
    params:
      hold: 0 for Tap (default), value between 1 and 300 for Hold. Triggering C1 requires hold >= 60.
    hitbox:
      - name: E
        shape: Box
        center: GlobalValue
        box: [4, 4.1]

  - name: burst
    params:
      enter: Number of times enemies enter or leave the field. Default 0 times.
      enter_delay: Time between enter/leave hits. Default 600 / enter (frames).
    hitbox:
      - name: Q-ElementalBurst
        note: Q/C4 detection area is the same as this hitbox.
        shape: Circle
        center: Player
        radius: 6

      - name: Q-InOut
        note: Enter/exit mechanics are not properly implemented yet.
        shape: Single
        center: GlobalValue

  - name: walk
    note: No action followed by walk has proper frames.
