package_name: jean
genshin_id: 10000003
key: jean
skill_data_mapping:
    attack:
        auto_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        auto_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        auto_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        auto_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        auto_5:
            - 4 # 5-Hit DMG|{param4:F1P}
        charge:
            - 5 # Charged Attack DMG|{param5:P}
    skill:
        skill:
            - 0 # Skill DMG|{param0:P}
    burst:
        burst:
            - 0 # Burst DMG|{param0:P}
        burstDotHealFlat:
            - 5 # Continuous Regeneration|{param4:F2P} ATK+{param5:I}/s
        burstDotHealPer:
            - 4 # Continuous Regeneration|{param4:F2P} ATK+{param5:I}/s
        burstEnter:
            - 1 # Field Entering/Exiting DMG|{param1:F1P}
        burstInitialHealFlat:
            - 3 # Field Activation Healing|{param2:P} ATK+{param3:I}
        burstInitialHealPer:
            - 2 # Field Activation Healing|{param2:P} ATK+{param3:I}
