id: 10000003
key: "jean"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_MONDSTADT
element: Wind
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Qin"
stats: {
   base_hp: 1143.984
   base_atk: 18.62
   base_def: 59.83
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 980.86285
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 51.3
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 15.9638
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1677.7917
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 87.75
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 27.3065
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
         value: 0.0554
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2607.0303
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 136.35
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 42.4301
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
         value: 0.1108
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3303.959
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 172.8
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 53.7728
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
         value: 0.1108
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4000.888
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 209.25
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 65.1155
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
         value: 0.1662
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4697.817
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 245.7
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 76.4582
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
         value: 0.2215
      }
   }
}
skill_details: {
   skill: 10033
   burst: 10034
   attack: 10031
   burst_energy_cost: 80
}
name_text_hash_map: 3221566250
