id: 10000130
key: "linnea"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_NODKRAI
element: Rock
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Linnea"
stats: {
   base_hp: 770.28253
   base_atk: 11.172
   base_def: 70.5994
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 660.44763
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 60.534
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 9.57828
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1129.7131
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 103.545
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 16.3839
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1755.4003
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 160.893
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 25.45806
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2224.6658
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 203.904
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 32.26368
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2693.9312
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 246.915
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.0693
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3163.1965
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 289.926
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 45.87492
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
