// Code generated by scripts/generate_missing_characters.py; DO NOT EDIT.

package linnea

import (
	"github.com/genshinsim/gcsim/internal/template/character/basicimport"
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/attributes"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() { core.RegisterCharFunc(keys.Linnea, NewChar) }

var generatedProfile = basicimport.Profile{
	Name: "Linnea", Element: attributes.Geo, Weapon: "Bow",
	Energy: 60, SkillCD: 1080, BurstCD: 900,
	Attack: []basicimport.Scaling{basicimport.Scaling{Values: []float64{0.589969, 0.637989, 0.68601, 0.754611, 0.802632, 0.857513, 0.932974, 1.008435, 1.083896, 1.166217, 1.248538, 1.330859, 1.413181, 1.495502, 1.577823}, UseDef: false, UseHP: false, UseEM: false}, basicimport.Scaling{Values: []float64{0.511519, 0.553155, 0.59479, 0.654269, 0.695904, 0.743488, 0.808914, 0.874341, 0.939768, 1.011143, 1.082518, 1.153893, 1.225267, 1.296642, 1.368017}, UseDef: false, UseHP: false, UseEM: false}, basicimport.Scaling{Values: []float64{0.816312, 0.882756, 0.9492, 1.04412, 1.110564, 1.1865, 1.290912, 1.395324, 1.499736, 1.61364, 1.727544, 1.841448, 1.955352, 2.069256, 2.18316}, UseDef: false, UseHP: false, UseEM: false}},
	Charge: basicimport.Scaling{Values: []float64{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, UseDef: false, UseHP: false, UseEM: false}, Collision: basicimport.Scaling{Values: []float64{0.568288, 0.614544, 0.6608, 0.72688, 0.773136, 0.826, 0.898688, 0.971376, 1.044064, 1.12336, 1.202656, 1.281952, 1.361248, 1.440544, 1.51984}, UseDef: false, UseHP: false, UseEM: false}, LowPlunge: basicimport.Scaling{Values: []float64{1.136335, 1.228828, 1.32132, 1.453452, 1.545944, 1.65165, 1.796995, 1.94234, 2.087686, 2.246244, 2.404802, 2.563361, 2.721919, 2.880478, 3.039036}, UseDef: false, UseHP: false, UseEM: false}, HighPlunge: basicimport.Scaling{Values: []float64{1.419344, 1.534872, 1.6504, 1.81544, 1.930968, 2.063, 2.244544, 2.426088, 2.607632, 2.80568, 3.003728, 3.201776, 3.399824, 3.597872, 3.79592}, UseDef: false, UseHP: false, UseEM: false},
	Skill: basicimport.Scaling{Values: []float64{0.96, 1.032, 1.104, 1.2, 1.272, 1.344, 1.44, 1.536, 1.632, 1.728, 1.824, 1.92, 2.04, 2.16, 2.28}, UseDef: true, UseHP: false, UseEM: false}, Burst: basicimport.Scaling{Values: []float64{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, UseDef: false, UseHP: false, UseEM: false},
}
