use: pipeline
kind: weapon
name: ultimateoverlordsmegamagicsword

shortcuts:
  - megamagicsword
  - melusineclaymore
  - uomms

abilities:
  - name: default
    params:
      melusines: Number of melusines that have been helped. Default 6, min 0, max 6. The atk% gained per melusine is 1/6 of the base atk% from the passive.
