// Code generated by "pipeline"; DO NOT EDIT.

// passive: Extinguishing Precept # Weapon_Pole_Santika
//
//	Gain 12% All Elemental DMG Bonus. Obtain Consummation for 20s after using an Elemental
//	Skill, causing ATK to increase by 3.2% per second. This ATK increase has a maximum
//	of 6 stacks. When the character equipped with this weapon is not on the field, Consummation's
//	ATK increase is doubled.
package calamity

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.CalamityQueller, NewWeapon)
}
