package_name: diona
genshin_id: 10000039
key: diona
skill_data_mapping:
    attack:
        aim:
            - 6 # Aimed Shot|{param6:F1P}
        auto_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        auto_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        auto_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        auto_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        auto_5:
            - 4 # 5-Hit DMG|{param4:F1P}
        fullaim:
            - 7 # Fully-Charged Aimed Shot|{param7:P}
    skill:
        paw:
            - 0 # Icy Paw DMG|{param0:F1P} per Paw
        pawShieldFlat:
            - 2 # Base Shield DMG Absorption|{param1:F1P} Max HP+{param2:I}
        pawShieldPer:
            - 1 # Base Shield DMG Absorption|{param1:F1P} Max HP+{param2:I}
        pawDur:
            - 5 # Duration|{param5:F1}s per Paw
    burst:
        burst:
            - 0 # Skill DMG|{param0:P}
        burstDot:
            - 1 # Continuous Field DMG|{param1:F1P}
        burstHealFlat:
            - 3 # HP Regeneration Over Time|{param2:F2P} Max HP+{param3:I}
        burstHealPer:
            - 2 # HP Regeneration Over Time|{param2:F2P} Max HP+{param3:I}
