id: 10000039
key: "diona"
rarity: QUALITY_PURPLE
body: BODY_LOLI
region: ASSOC_TYPE_MONDSTADT
element: Ice
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Diona"
stats: {
   base_hp: 802.3761
   base_atk: 17.808
   base_def: 50.358
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 599.416
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 37.62
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 13.3038
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1025.3169
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 64.35
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.7565
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1593.1847
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 99.99
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 35.3601
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2019.0854
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 126.72
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 44.8128
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2444.9863
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 153.45
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 54.2655
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2870.8872
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 180.18
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.7182
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10392
   burst: 10395
   attack: 10391
   burst_energy_cost: 80
}
name_text_hash_map: 1468367538
