package_name: dori
genshin_id: 10000068
key: dori
icd_tags:
  - ICDTagDoriC2
  - ICDTagDoriChargingStation
icd_groups:
  - group_name: ICDGroupDoriBurst
    reset_timer: 180
    ele_app_sequence: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
  attack:
    auto_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    auto_2:
      - 1 # 2-Hit DMG|{param1:F1P}+{param2:F1P}
      - 2 # 2-Hit DMG|{param1:F1P}+{param2:F1P}
    auto_3:
      - 3 # 3-Hit DMG|{param3:F1P}
    collision:
      - 8 # Plunge DMG|{param6:F1P}
    lowPlunge:
      - 9 # Low/High Plunge DMG|{param7:P}/{param8:P}
    highPlunge:
      - 10 # Low/High Plunge DMG|{param7:P}/{param8:P}
  skill:
    skill:
      - 0 # Troubleshooter Shot DMG|{param0:F1P}
    skillAfter:
      - 1 # After-Sales Service Round DMG|{param1:F1P}
  burst:
    burst:
      - 0 # Connector DMG|{param0:P}
    burstenergy:
      - 3 # Energy Regeneration|{param3:F1}
    bursthealflat:
      - 2 # Continuous Healing|{param1:F1P} Max HP+{param2:I}
    bursthealpp:
      - 1 # Continuous Healing|{param1:F1P} Max HP+{param2:I}
