package_name: charlotte
genshin_id: 10000088
key: charlotte
skill_data_mapping:
    attack:
        arkhe:
            - 8 # Spiritbreath Thorn DMG|{param8:F1P}
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        charge:
            - 3 # Charged Attack DMG|{param3:F1P}
    skill:
        skillHold:
            - 1 # Photo DMG (Hold)|{param1:F1P}
        skillHoldMark:
            - 5 # "Focused Impression" Mark DMG|{param5:F1P}
        skillPress:
            - 0 # #Photo DMG ({LAYOUT_MOBILE#Tap}{LAYOUT_PC#Press}{LAYOUT_PS#Press})|{param0:F1P}
        skillPressMark:
            - 2 # "Snappy Silhouette" Mark DMG|{param2:F1P}
    burst:
        burst:
            - 2 # Skill DMG|{param2:F1P}
        burstDot:
            - 5 # Kamera DMG|{param5:F1P}
        burstDotHealFlat:
            - 4 # Kamera Continuous Regeneration|{param3:F1P} ATK+{param4:I}
        burstDotHealPer:
            - 3 # Kamera Continuous Regeneration|{param3:F1P} ATK+{param4:I}
        burstInitialHealFlat:
            - 1 # Cast Healing|{param0:F1P} ATK+{param1:I}
        burstInitialHealPer:
            - 0 # Cast Healing|{param0:F1P} ATK+{param1:I}
