use: pipeline
kind: character
name: charlotte

override:
  icd_group:
    CharlotteKamera:
      name: Charlotte_BurstCamera
    CharlotteMark:
      name: Charlotte_ArtDot

combat:
  icd_tags:
    - CharlotteKamera
    - CharlotteMark
  icd_groups:
    - CharlotteKamera
    - CharlotteMark

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
  - charge: attack(Charged Attack DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)
  - arkhe: attack(Spiritbreath Thorn DMG)

  - skillPress: skill(Photo DMG (Press))
  - skillHold: skill(Photo DMG (Hold))
  - skillPressMark: skill("Snappy Silhouette" Mark DMG)
  - skillHoldMark: skill("Focused Impression" Mark DMG)

  - burstInitialHealPer: burst(Cast Healing)
  - burstInitialHealFlat: burst(Cast Healing|1)
  - burst: burst(Skill DMG)
  - burstDotHealPer: burst(Kamera Continuous Regeneration)
  - burstDotHealFlat: burst(Kamera Continuous Regeneration|1)
  - burstDot: burst(Kamera DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1gsiYO73cL5Xr7ZZa5FOK4p9hj7uDPo9Vlhq2TYsn2hY/edit?usp=sharing
      count_credit: ._keng
      video: https://youtu.be/fvFhhbcxSfA
      video_credit: ._keng
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: kolibri._.
      video: https://youtu.be/j4Mw5mc7rNY
      video_credit: kolibri._.

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: PrimaryTarget
        radius: 1

      - name: N2
        shape: Circle
        center: PrimaryTarget
        radius: 1

      - name: N3
        shape: Circle
        center: PrimaryTarget
        radius: 2

  - name: charge
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 2.5

      - name: CA-Spiritbreath-Thorn
        shape: Circle
        center: PrimaryTarget
        radius: 2.5

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        radius: 1.5

      - name: Low_Plunge
        shape: Circle
        center: Player
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        radius: 3.5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    params:
      hold: 0 for Tap (default), value between 1 and 809 for Hold. The number determines the E duration in frames.
    hitbox:
      - name: E-Tap
        shape: Box
        center: Player
        box: [4, 8]

      - name: E-Hold
        shape: Box
        center: Player
        offset: [1.3, 0]
        box: [4.5, 30]

      - name: E-Mark
        shape: Single
        center: GlobalValue

  - name: burst
    hitbox:
      - name: Q
        note: Heal is 7m instead of 6m.
        shape: Circle
        center: Player
        offset: [0, 4.5]
        radius: 6

  - name: cons
    hitbox:
      - name: C6
        note: Spawns on target that the C6 proc'd on. Heal is 5m instead of 3m.
        shape: Circle
        center: GlobalValue
        radius: 3.5
        hitlag: {scale: 0.02, defense_halt: true, deployable: true}
