id: 10000088
key: "charlotte"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_FONTAINE
element: Ice
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Charlotte"
stats: {
   base_hp: 902.6731
   base_atk: 14.51352
   base_def: 45.78
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 674.343
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 34.2
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 10.842597
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1153.4814
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 58.5
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 18.546547
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1792.3328
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 90.9
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 28.818481
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2271.4712
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 115.2
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 36.52243
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2750.6096
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 139.5
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 44.226383
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3229.748
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 163.8
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 51.930332
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10882
   burst: 10885
   attack: 10881
   burst_energy_cost: 80
}
name_text_hash_map: 3831162130
