id: 10000083
key: "lynette"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_FONTAINE
element: Wind
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Linette"
stats: {
   base_hp: 1039.4418
   base_atk: 19.41072
   base_def: 59.685677
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 776.5162
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 44.58825
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 14.501142
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1328.2513
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 76.26938
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 24.804585
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2063.8984
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 118.51087
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 38.542507
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2615.6335
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 150.192
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 48.84595
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3167.3687
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 181.87312
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 59.149395
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3719.104
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 213.55424
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 69.452835
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10832
   burst: 10835
   attack: 10831
   burst_energy_cost: 70
}
name_text_hash_map: 1225226258
