package_name: lynette
genshin_id: 10000083
key: lynette
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
            - 3 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
        attack_4:
            - 4 # 4-Hit DMG|{param4:F1P}
        charge:
            - 5 # Charged Attack DMG|{param5:F1P}+{param6:F1P}
            - 6 # Charged Attack DMG|{param5:F1P}+{param6:F1P}
        collision:
            - 8 # Plunge DMG|{param6:F1P}
        lowPlunge:
            - 9 # Low/High Plunge DMG|{param7:P}/{param8:P}
        highPlunge:
            - 10 # Low/High Plunge DMG|{param7:P}/{param8:P}
    skill:
        skill:
            - 0 # Enigma Thrust DMG|{param0:F1P}
        skillAligned:
            - 2 # Surging Blade DMG|{param2:F1P}
    burst:
        bogglecat:
            - 1 # Bogglecat Box DMG|{param1:F1P}
        burst:
            - 0 # Skill DMG|{param0:F1P}
        vivid:
            - 2 # Vivid Shot DMG|{param2:F1P}
