// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protos/backend/share.proto

package share

import (
	model "github.com/genshinsim/gcsim/pkg/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShareEntry struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,json=_id,proto3" json:"id,omitempty" bson:"_id,omitempty"`
	Result        *model.SimulationResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty" bson:"result,omitempty"`
	ExpiresAt     uint64                  `protobuf:"varint,3,opt,name=expires_at,proto3" json:"expires_at,omitempty" bson:"expires_at,omitempty"`
	Submitter     string                  `protobuf:"bytes,4,opt,name=submitter,proto3" json:"submitter,omitempty" bson:"submitter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareEntry) Reset() {
	*x = ShareEntry{}
	mi := &file_protos_backend_share_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareEntry) ProtoMessage() {}

func (x *ShareEntry) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_share_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareEntry.ProtoReflect.Descriptor instead.
func (*ShareEntry) Descriptor() ([]byte, []int) {
	return file_protos_backend_share_proto_rawDescGZIP(), []int{0}
}

func (x *ShareEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShareEntry) GetResult() *model.SimulationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ShareEntry) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ShareEntry) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Result        *model.SimulationResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty" bson:"result,omitempty"`
	ExpiresAt     uint64                  `protobuf:"varint,2,opt,name=expires_at,proto3" json:"expires_at,omitempty" bson:"expires_at,omitempty"`
	Submitter     string                  `protobuf:"bytes,3,opt,name=submitter,proto3" json:"submitter,omitempty" bson:"submitter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_protos_backend_share_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_share_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_protos_backend_share_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetResult() *model.SimulationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateRequest) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *CreateRequest) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_protos_backend_share_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_share_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_protos_backend_share_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_protos_backend_share_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_share_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_protos_backend_share_proto_rawDescGZIP(), []int{3}
}

func (x *ReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	Result        *model.SimulationResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty" bson:"result,omitempty"`
	ExpiresAt     uint64                  `protobuf:"varint,3,opt,name=expires_at,proto3" json:"expires_at,omitempty" bson:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_protos_backend_share_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_share_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_protos_backend_share_proto_rawDescGZIP(), []int{4}
}

func (x *ReadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadResponse) GetResult() *model.SimulationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReadResponse) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type UpdateRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	Result        *model.SimulationResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty" bson:"result,omitempty"`
	ExpiresAt     uint64                  `protobuf:"varint,3,opt,name=expires_at,proto3" json:"expires_at,omitempty" bson:"expires_at,omitempty"`
	Submitter     string                  `protobuf:"bytes,4,opt,name=submitter,proto3" json:"submitter,omitempty" bson:"submitter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_protos_backend_share_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_share_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_protos_backend_share_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequest) GetResult() *model.SimulationResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateRequest) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *UpdateRequest) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_protos_backend_share_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_share_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_protos_backend_share_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetTTLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	ExpiresAt     uint64                 `protobuf:"varint,3,opt,name=expires_at,proto3" json:"expires_at,omitempty" bson:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTTLRequest) Reset() {
	*x = SetTTLRequest{}
	mi := &file_protos_backend_share_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTTLRequest) ProtoMessage() {}

func (x *SetTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_share_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTTLRequest.ProtoReflect.Descriptor instead.
func (*SetTTLRequest) Descriptor() ([]byte, []int) {
	return file_protos_backend_share_proto_rawDescGZIP(), []int{7}
}

func (x *SetTTLRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetTTLRequest) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type SetTTLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTTLResponse) Reset() {
	*x = SetTTLResponse{}
	mi := &file_protos_backend_share_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTTLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTTLResponse) ProtoMessage() {}

func (x *SetTTLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_share_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTTLResponse.ProtoReflect.Descriptor instead.
func (*SetTTLResponse) Descriptor() ([]byte, []int) {
	return file_protos_backend_share_proto_rawDescGZIP(), []int{8}
}

func (x *SetTTLResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_protos_backend_share_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_share_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_protos_backend_share_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"` //TODO: add deleted data to response in future
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_protos_backend_share_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_share_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_protos_backend_share_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RandomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomRequest) Reset() {
	*x = RandomRequest{}
	mi := &file_protos_backend_share_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomRequest) ProtoMessage() {}

func (x *RandomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_share_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomRequest.ProtoReflect.Descriptor instead.
func (*RandomRequest) Descriptor() ([]byte, []int) {
	return file_protos_backend_share_proto_rawDescGZIP(), []int{11}
}

type RandomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RandomResponse) Reset() {
	*x = RandomResponse{}
	mi := &file_protos_backend_share_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RandomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomResponse) ProtoMessage() {}

func (x *RandomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_share_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomResponse.ProtoReflect.Descriptor instead.
func (*RandomResponse) Descriptor() ([]byte, []int) {
	return file_protos_backend_share_proto_rawDescGZIP(), []int{12}
}

func (x *RandomResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_protos_backend_share_proto protoreflect.FileDescriptor

const file_protos_backend_share_proto_rawDesc = "" +
	"\n" +
	"\x1aprotos/backend/share.proto\x12\x05share\x1a\x19protos/model/result.proto\"\x8c\x01\n" +
	"\n" +
	"ShareEntry\x12\x0f\n" +
	"\x02id\x18\x01 \x01(\tR\x03_id\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.model.SimulationResultR\x06result\x12\x1e\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x04R\n" +
	"expires_at\x12\x1c\n" +
	"\tsubmitter\x18\x04 \x01(\tR\tsubmitter\"~\n" +
	"\rCreateRequest\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.model.SimulationResultR\x06result\x12\x1e\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x04R\n" +
	"expires_at\x12\x1c\n" +
	"\tsubmitter\x18\x03 \x01(\tR\tsubmitter\" \n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1d\n" +
	"\vReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\fReadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.model.SimulationResultR\x06result\x12\x1e\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x04R\n" +
	"expires_at\"\x8e\x01\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.model.SimulationResultR\x06result\x12\x1e\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x04R\n" +
	"expires_at\x12\x1c\n" +
	"\tsubmitter\x18\x04 \x01(\tR\tsubmitter\" \n" +
	"\x0eUpdateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\rSetTTLRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x04R\n" +
	"expires_at\" \n" +
	"\x0eSetTTLResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x0f\n" +
	"\rRandomRequest\" \n" +
	"\x0eRandomResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xdc\x02\n" +
	"\n" +
	"ShareStore\x127\n" +
	"\x06Create\x12\x14.share.CreateRequest\x1a\x15.share.CreateResponse\"\x00\x121\n" +
	"\x04Read\x12\x12.share.ReadRequest\x1a\x13.share.ReadResponse\"\x00\x127\n" +
	"\x06Update\x12\x14.share.UpdateRequest\x1a\x15.share.UpdateResponse\"\x00\x127\n" +
	"\x06SetTTL\x12\x14.share.SetTTLRequest\x1a\x15.share.SetTTLResponse\"\x00\x127\n" +
	"\x06Delete\x12\x14.share.DeleteRequest\x1a\x15.share.DeleteResponse\"\x00\x127\n" +
	"\x06Random\x12\x14.share.RandomRequest\x1a\x15.share.RandomResponse\"\x00B8Z6github.com/genshinsim/gcsim/backend/pkg/services/shareb\x06proto3"

var (
	file_protos_backend_share_proto_rawDescOnce sync.Once
	file_protos_backend_share_proto_rawDescData []byte
)

func file_protos_backend_share_proto_rawDescGZIP() []byte {
	file_protos_backend_share_proto_rawDescOnce.Do(func() {
		file_protos_backend_share_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_backend_share_proto_rawDesc), len(file_protos_backend_share_proto_rawDesc)))
	})
	return file_protos_backend_share_proto_rawDescData
}

var file_protos_backend_share_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_protos_backend_share_proto_goTypes = []any{
	(*ShareEntry)(nil),             // 0: share.ShareEntry
	(*CreateRequest)(nil),          // 1: share.CreateRequest
	(*CreateResponse)(nil),         // 2: share.CreateResponse
	(*ReadRequest)(nil),            // 3: share.ReadRequest
	(*ReadResponse)(nil),           // 4: share.ReadResponse
	(*UpdateRequest)(nil),          // 5: share.UpdateRequest
	(*UpdateResponse)(nil),         // 6: share.UpdateResponse
	(*SetTTLRequest)(nil),          // 7: share.SetTTLRequest
	(*SetTTLResponse)(nil),         // 8: share.SetTTLResponse
	(*DeleteRequest)(nil),          // 9: share.DeleteRequest
	(*DeleteResponse)(nil),         // 10: share.DeleteResponse
	(*RandomRequest)(nil),          // 11: share.RandomRequest
	(*RandomResponse)(nil),         // 12: share.RandomResponse
	(*model.SimulationResult)(nil), // 13: model.SimulationResult
}
var file_protos_backend_share_proto_depIdxs = []int32{
	13, // 0: share.ShareEntry.result:type_name -> model.SimulationResult
	13, // 1: share.CreateRequest.result:type_name -> model.SimulationResult
	13, // 2: share.ReadResponse.result:type_name -> model.SimulationResult
	13, // 3: share.UpdateRequest.result:type_name -> model.SimulationResult
	1,  // 4: share.ShareStore.Create:input_type -> share.CreateRequest
	3,  // 5: share.ShareStore.Read:input_type -> share.ReadRequest
	5,  // 6: share.ShareStore.Update:input_type -> share.UpdateRequest
	7,  // 7: share.ShareStore.SetTTL:input_type -> share.SetTTLRequest
	9,  // 8: share.ShareStore.Delete:input_type -> share.DeleteRequest
	11, // 9: share.ShareStore.Random:input_type -> share.RandomRequest
	2,  // 10: share.ShareStore.Create:output_type -> share.CreateResponse
	4,  // 11: share.ShareStore.Read:output_type -> share.ReadResponse
	6,  // 12: share.ShareStore.Update:output_type -> share.UpdateResponse
	8,  // 13: share.ShareStore.SetTTL:output_type -> share.SetTTLResponse
	10, // 14: share.ShareStore.Delete:output_type -> share.DeleteResponse
	12, // 15: share.ShareStore.Random:output_type -> share.RandomResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protos_backend_share_proto_init() }
func file_protos_backend_share_proto_init() {
	if File_protos_backend_share_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_backend_share_proto_rawDesc), len(file_protos_backend_share_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_backend_share_proto_goTypes,
		DependencyIndexes: file_protos_backend_share_proto_depIdxs,
		MessageInfos:      file_protos_backend_share_proto_msgTypes,
	}.Build()
	File_protos_backend_share_proto = out.File
	file_protos_backend_share_proto_goTypes = nil
	file_protos_backend_share_proto_depIdxs = nil
}
