id: 10000016
key: "diluc"
rarity: QUALITY_ORANGE
body: BODY_MALE
region: ASSOC_TYPE_MONDSTADT
element: Fire
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Diluc"
stats: {
   base_hp: 1010.5192
   base_atk: 26.068
   base_def: 61.0266
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 866.42883
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 52.326
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.34932
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1482.0493
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 89.505
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 38.2291
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2302.8767
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 139.077
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 59.40214
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2918.497
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 176.256
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 75.28192
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3534.1177
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 213.435
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 91.1617
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4149.7383
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 250.614
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 107.04148
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10161
   burst: 10165
   attack: 10160
   burst_energy_cost: 40
}
name_text_hash_map: 3608180322
