use: pipeline
kind: character
name: sethos

talents:
  - attack:
      - attack(1-Hit DMG)
      - - attack(2-Hit DMG)
        - attack(2-Hit DMG|1)
      - attack(3-Hit DMG)
  - aim: attack(Aimed Shot)
  - fullaim: attack(Aimed Shot Charge Level 1)
  - shadowpierceAtk: attack(Shadowpiercing Shot DMG)
  - shadowpierceEM: attack(Shadowpiercing Shot DMG|1)

  - skill: skill(Skill DMG)
  - skillEnergyRegen: skill(Energy Regeneration)

  - burstEM: burst(Dusk Bolt DMG Increase)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1Fxk8KZtVJjY2P9BX5IIy4oNHIcPqCTi6zqrdAn335dY/edit?usp=sharing
      count_credit: ange1o5
      video: https://youtu.be/MYXatbTDbBo
      video_credit: ange1o5

abilities:
  - name: attack
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: N1
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N2-1
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N2-2
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N3
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: Q-N1
        note: This is an approximation because we do not actually know the real AoE. This attack is a line going from the Player to the direction of the Primary Target.
        shape: Box
        center: Player
        box: [0.1, 15]

      - name: Q-N2-1
        note: This is an approximation because we do not actually know the real AoE. This attack is a line going from the Player to the direction of the Primary Target.
        shape: Box
        center: Player
        box: [0.1, 15]

      - name: Q-N2-2
        note: This is an approximation because we do not actually know the real AoE. This attack is a line going from the Player to the direction of the Primary Target.
        shape: Box
        center: Player
        box: [0.1, 15]

      - name: Q-N3
        note: This is an approximation because we do not actually know the real AoE. This attack is a line going from the Player to the direction of the Primary Target.
        shape: Box
        center: Player
        box: [0.1, 15]

  - name: aim
    params:
      hold: 0 for Physical Aimed Shot, 1 for Fully-Charged Aimed Shot (default), 2 for Shadowpiercing Shot.
      travel: Projectile travel time. Default 10 frames.
      weakspot: Hit weakspot with aimed shot. Default 0 (false), 1 for true.
    hitbox:
      - name: Aim
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: Aim-Head
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]
        hitlag: {time: 0.12, scale: 0.01, deployable: true}

      - name: FullAim
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: FullAim-Head
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]
        hitlag: {time: 0.12, scale: 0.01, deployable: true}

      - name: ShadowpiercingShot
        note: This is an approximation because we do not actually know the real AoE. This attack is a line going from the Player to the direction of the Primary Target.
        shape: Box
        center: Player
        box: [0.1, 15]

      - name: ShadowpiercingShot-Head
        note: This is an approximation because we do not actually know the real AoE. This attack is a line going from the Player to the direction of the Primary Target.
        shape: Box
        center: Player
        box: [0.1, 15]
        hitlag: {time: 0.12, scale: 0.01, deployable: true}

  - name: skill
    hitbox:
      - name: E
        shape: Circle
        center: Player
        radius: 4.5

  - name: burst
