package_name: sethos
genshin_id: 10000097
key: sethos
action_param_keys:
  attack:
    - param: "travel"
  aim:
    - param: "hold"
    - param: "travel"
    - param: "weakspot"
skill_data_mapping:
  attack: # Normal Attack: Royal Reed Bowmanship
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}+{param2:F1P}
      - 2 # 2-Hit DMG|{param1:F1P}+{param2:F1P}
    attack_3:
      - 3 # 3-Hit DMG|{param3:F1P}
    aim:
      - 4 # Aimed Shot|{param4:F1P}
    fullaim:
      - 5 # Aimed Shot Charge Level 1|{param5:F1P}
    shadowpierceAtk:
      - 6 # Shadowpiercing Shot DMG|{param6:P} ATK+{param7:P} Elemental Mastery
    shadowpierceEM:
      - 7 # Shadowpiercing Shot DMG|{param6:P} ATK+{param7:P} Elemental Mastery
  skill: # Ancient Rite: Thunderous Roar of Sand
    skill:
      - 0 # Skill DMG|{param0:F1P}
    skillEnergyRegen:
      - 1 # Energy Regeneration|{param1:I}
  burst: # Secret Rite: Twilight Shadowpiercer
    burstEM:
      - 0 # Dusk Bolt DMG Increase|{param0:F1P} Elemental Mastery
