// Code generated by "pipeline"; DO NOT EDIT.

// passive: Overloaded # Weapon_Sword_AttacktUpAfterReaction
//
//	Upon causing an Overloaded, Superconduct, Electro-Charged, Quicken, Aggravate, Hyperbloom,
//	Lunar-Charged, or Electro-infused Swirl reaction, ATK is increased by 20% for 12s.
package darkironsword

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.DarkIronSword, NewWeapon)
}
