package_name: nahida
genshin_id: 10000073
key: nahida
icd_tags:
  - ICDTagNahidaSkill
  - ICDTagNahidaC6
icd_groups:
  - group_name: ICDGroupNahidaSkill
    reset_timer: 60
    ele_app_sequence: [1.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    damage_sequence:
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    attack_4:
      - 3 # 4-Hit DMG|{param3:F1P}
    charge:
      - 4 # Charged Attack DMG|{param4:F1P}
  skill:
    skillHold:
      - 1 # Hold DMG|{param1:F1P}
    skillPress:
      - 0 # #{LAYOUT_MOBILE#Tap}{LAYOUT_PC#Press}{LAYOUT_PS#Press} DMG|{param0:F1P}
    triKarmaAtk:
      - 2 # Tri-Karma Purification DMG|{param2:F1P} ATK+{param3:F1P} Elemental Mastery
    triKarmaEM:
      - 3 # Tri-Karma Purification DMG|{param2:F1P} ATK+{param3:F1P} Elemental Mastery
  burst:
    burstTriKarmaCDReduction:
      - 2 # Electro: Trigger Interval Decrease|1 Character {param2:F2}s
      - 3 # Electro: Trigger Interval Decrease|2 Characters {param3:F2}s
    burstTriKarmaDmgBonus:
      - 0 # Pyro: DMG Bonus|1 Character {param0:F1P}
      - 1 # Pyro: DMG Bonus|2 Characters {param1:F1P}
    burstTriKarmaDurationExtend:
      - 4 # Hydro: Duration Extension|1 Character {param4:F2}s
      - 5 # Hydro: Duration Extension|2 Characters {param5:F2}s
