id: 10000073
key: "nahida"
rarity: QUALITY_ORANGE
body: BODY_LOLI
region: ASSOC_TYPE_SUMERU
element: Grass
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Nahida"
stats: {
   base_hp: 806.5087
   base_atk: 23.275
   base_def: 49.0606
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 691.5083
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 42.066
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 19.95475
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1182.8431
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 71.955
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 34.133125
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 28.8
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1837.9563
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 111.807
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 53.037624
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 57.6
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2329.291
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 141.696
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 67.216
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 57.6
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2820.626
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 171.585
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 81.39438
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 86.4
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3311.961
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 201.474
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 95.57275
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 115.2
      }
   }
}
skill_details: {
   skill: 10732
   burst: 10735
   attack: 10731
   burst_energy_cost: 50
}
name_text_hash_map: 712501082
