// Code generated by "pipeline"; DO NOT EDIT.

// set2: Celestial Gift
//
//	Energy Recharge +20%.
//
// set4: Celestial Gift # Relic_6.6_Nicole
//
//	If the equipping character has completed Witch's Homework, after they use an Elemental
//	Skill, they gain "Light's Guidance" for 20s: All nearby party members gain a 20%
//	Elemental DMG Bonus corresponding to the equipping character's Elemental Type. The
//	equipping character can trigger this effect while off-field. DMG Bonuses provided
//	by Artifact Sets with the same name do not stack.
//	· When your party has the Hexerei: Secret Rite effect, Light's Guidance is upgraded
//	to "Mortal Hymn": All nearby party members gain a 40% Elemental DMG Bonus corresponding
//	to both the equipping character and the current active party member's Elemental Type
//	instead. If both characters have the same Elemental Type, these bonuses will not
//	stack.
package celestialgift

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterSetFunc(keys.CelestialGift, NewSet)
}
