// Code generated by "pipeline"; DO NOT EDIT.

// passive: Pact of Flowing Springs # Weapon_Pole_Isikhulu
//
//	Using an Elemental Skill increases DEF by 16% for 15s.
package footprint

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.FootprintOfTheRainbow, NewWeapon)
}
