package_name: xiao
genshin_id: 10000026
key: xiao
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}+{param1:F1P}
      - 0 # 1-Hit DMG|{param0:F1P}+{param1:F1P}
    attack_2:
      - 2 # 2-Hit DMG|{param2:F1P}
    attack_3:
      - 3 # 3-Hit DMG|{param3:F1P}
    attack_4:
      - 4 # 4-Hit DMG|{param4:F1P}+{param5:F1P}
      - 4 # 4-Hit DMG|{param4:F1P}+{param5:F1P}
    attack_5:
      - 6 # 5-Hit DMG|{param6:F1P}
    attack_6:
      - 7 # 6-Hit DMG|{param7:F1P}
    charge:
      - 8 # Charged Attack DMG|{param8:P}
    plunge:
      - 10 # Plunge DMG|{param10:P}
    lowPlunge:
      - 11 # Low/High Plunge DMG|{param11:P}/{param12:P}
    highPlunge:
      - 12 # Low/High Plunge DMG|{param11:P}/{param12:P}

  skill:
    skill:
      - 0 # Skill DMG|{param0:P}
  burst:
    burstBonus:
      - 0 # Normal/Charged/Plunging Attack DMG Bonus|{param0:F1P}
    burstDrain:
      - 1 # Life Drain|{param1:F1P} Current HP Per Second
icd_groups:
  - group_name: ICDGroupXiaoDash
    reset_timer: 6
    ele_app_sequence: [1, 0, 0, 0, 0, 0, 0]
    damage_sequence: [1, 0, 0, 0, 0, 0, 0]
