use: pipeline
kind: character
name: xiao

override:
  icd_group:
    XiaoDash:
      name: Xiao_DevilDash

combat:
  icd_groups:
    - XiaoDash

talents:
  - attack:
      - - attack(1-Hit DMG)
        - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - - attack(4-Hit DMG)
        - attack(4-Hit DMG)
      - attack(5-Hit DMG)
      - attack(6-Hit DMG)
  - charge: attack(Charged Attack DMG)
  - plunge: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skill: skill(Skill DMG)

  - burstBonus: burst(Normal/Charged/Plunging Attack DMG Bonus)
  - burstDrain: burst(Life Drain)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1WHJy9UjCQY0AO32yluJMhX_ecGO1KGb6SjbOZt9VJDg/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/oadNODbooZQ
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1WHJy9UjCQY0AO32yluJMhX_ecGO1KGb6SjbOZt9VJDg/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/tb1bGGVNJoA?t=174
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ?t=1598
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: kolibri._.
      video: https://youtu.be/jsa2yTQecMA
      video_credit: kolibri._.

abilities:
  - name: attack
    hitbox:
      - name: N1-1
        shape: Circle
        center: Player
        offset: [0, -0.1]
        fan_angle: 150
        radius: 1.8

      - name: N1-2
        shape: Box
        center: Player
        box: [1.4, 2.7]

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 1]
        fan_angle: 300
        radius: 1.6

      - name: N3
        shape: Circle
        center: Player
        offset: [0, 1.1]
        fan_angle: 300
        radius: 1.6

      - name: N4-1
        shape: Circle
        center: Player
        offset: [-0.1, 0.9]
        fan_angle: 320
        radius: 1.6

      - name: N4-2
        shape: Circle
        center: Player
        offset: [0, 0.8]
        fan_angle: 320
        radius: 1.8

      - name: N5
        shape: Box
        center: Player
        box: [1.5, 3]

      - name: N6
        shape: Circle
        center: Player
        offset: [0, 1.1]
        radius: 2

      - name: Q-N1-1
        shape: Circle
        center: Player
        offset: [0, -0.1]
        fan_angle: 150
        radius: 2
        hitlag: {time: 0.01, scale: 0.01}

      - name: Q-N1-2
        shape: Box
        center: Player
        box: [1.6, 3]
        hitlag: {time: 0.01, scale: 0.01, defense_halt: true}

      - name: Q-N2
        shape: Circle
        center: Player
        offset: [0, 1]
        fan_angle: 300
        radius: 1.8
        hitlag: {time: 0.01, scale: 0.01, defense_halt: true}

      - name: Q-N3
        shape: Circle
        center: Player
        offset: [0, 1.1]
        fan_angle: 300
        radius: 1.8
        hitlag: {time: 0.01, scale: 0.01, defense_halt: true}

      - name: Q-N4-1
        shape: Circle
        center: Player
        offset: [-0.1, 0.9]
        fan_angle: 320
        radius: 1.8
        hitlag: {time: 0.02, scale: 0.01}

      - name: Q-N4-2
        shape: Circle
        center: Player
        offset: [0, 0.8]
        fan_angle: 320
        radius: 2
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: Q-N5
        shape: Box
        center: Player
        box: [1.7, 3.2]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: Q-N6
        shape: Circle
        center: Player
        offset: [0, 1.1]
        radius: 2.4
        hitlag: {time: 0.04, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA
        shape: Circle
        center: Player
        fan_angle: 200
        radius: 3
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: Q-CA
        shape: Circle
        center: Player
        fan_angle: 200
        radius: 3.2
        hitlag: {time: 0.04, scale: 0.01, defense_halt: true}

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        radius: 1

      - name: Q-Plunge
        shape: Circle
        center: Player
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        radius: 5

      - name: Q-Low_Plunge
        shape: Circle
        center: Player
        radius: 4

      - name: Q-High_Plunge
        shape: Circle
        center: Player
        radius: 6

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    hitbox:
      - name: E
        shape: Circle
        center: PrimaryTarget
        radius: 0.8

  - name: burst

  - name: walk
    note: No action followed by walk (except low_plunge and high_plunge) has proper frames.
