id: 10000026
key: "xiao"
rarity: QUALITY_ORANGE
body: BODY_BOY
region: ASSOC_TYPE_LIYUE
element: Wind
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Xiao"
stats: {
   base_hp: 991.4528
   base_atk: 27.1852
   base_def: 62.2232
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 850.0811
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 53.352
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.307148
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1454.0862
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 91.26
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.86749
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2259.4263
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 141.804
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.947945
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2863.4312
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 179.712
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 78.508286
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3467.4363
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 217.62
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 95.06863
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4071.4412
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 255.528
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 111.628975
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 70
}
name_text_hash_map: 1021947690
