use: pipeline
kind: weapon
name: theviridescenthunt

shortcuts:
  - vhunt
  - viridescenthunt

abilities:
  - name: default
    hitbox:
      - name: The Viridescent Hunt
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 3
