id: 12101
key: "wastergreatsword"
rarity: 1
weapon_class: WEAPON_CLAYMORE
image_name: "UI_EquipIcon_Claymore_Aniki"
base_stats: {
   base_props: {
      prop_type: FIGHT_PROP_BASE_ATTACK
      initial_value: 23.245
      curve: GROW_CURVE_ATTACK_101
   }
   base_props: {
      curve: GROW_CURVE_CRITICAL_101
   }
   promo_data: {
      max_level: 20
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 11.7
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.3
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 35
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 46.7
      }
   }
}
name_text_hash_map: 2666951267
