// Code generated by "pipeline"; DO NOT EDIT.

// passive: Ashen Sun's Shadow # Weapon_Pole_BloodMoon
//
//	Grants a Bond of Life equal to 25% of Max HP when a Charged Attack hits an opponent.
//	This effect can be triggered up to once every 14s. In addition, when the equipping
//	character has a Bond of Life, they gain a 12% DMG Bonus; if the value of the Bond
//	of Life is greater than or equal to 30% of Max HP, then gain an additional 24% DMG
//	Bonus.
package crimsonmoonssemblance

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.CrimsonMoonsSemblance, NewWeapon)
}
