use: pipeline
kind: character
name: mika

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - - attack(4-Hit DMG)
        - attack(4-Hit DMG)
      - attack(5-Hit DMG)
  - charge: attack(Charged Attack DMG)

  - skillPress: skill(Flowfrost Arrow DMG)
  - skillHold: skill(Rimestar Flare DMG)
  - skillExplode: skill(Rimestar Shard DMG)
  - atkSpdBuff: skill(ATK SPD Bonus)

  - burstHealFirstF: burst(Cast Healing|1)
  - burstHealFirstP: burst(Cast Healing)
  - burstHealF: burst(Eagleplume Healing|1)
  - burstHealP: burst(Eagleplume Healing)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1lSisZA6gmkq6bOBY3NHyqgiyvZfXEYFwAhVrmqiN7xo/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/Jqsvtv39AEY
      video_credit: Kolibri#7675

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Box
        center: Player
        box: [1.8, 2.5]
        hitlag: {time: 0.02, scale: 0.01}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.2]
        radius: 1.6
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Box
        center: Player
        offset: [0, 0.5]
        box: [2.5, 2.5]
        hitlag: {time: 0.02, scale: 0.01}

      - name: N4-1
        shape: Circle
        center: Player
        offset: [0, -0.3]
        fan_angle: 45
        radius: 4
        hitlag: {scale: 0.01, defense_halt: true}

      - name: N4-2
        shape: Circle
        center: Player
        offset: [0, -0.3]
        fan_angle: 45
        radius: 4
        hitlag: {scale: 0.01, defense_halt: true}

      - name: N5
        shape: Box
        center: Player
        offset: [0, 1]
        box: [1.5, 5]
        hitlag: {time: 0.04, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 0.8
        hitlag: {scale: 0.01, defense_halt: true, deployable: true}

  - name: skill
    params:
      hold: 0 for Tap (default), 1 for Hold.
    hitbox:
      - name: E-Arrow
        shape: Box
        center: Player
        offset: [0, 0.4]
        box: [2.5, 10]
        hitlag: {scale: 0.01, defense_halt: true}

      - name: E-Flare
        shape: Single
        center: PrimaryTarget

      - name: E-Shard
        note: Spawns up to 3 attacks on 3 random enemies within 10m radius of Player that were not hit by E-Flare.
        shape: Single
        center: GlobalValue

  - name: burst
