package_name: mika
genshin_id: 10000080
key: mika
action_param_keys:
    skill:
        - param: "hold"
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}+{param4:F1P}
            - 3 # 4-Hit DMG|{param3:F1P}+{param4:F1P}
        attack_5:
            - 5 # 5-Hit DMG|{param5:F1P}
        charge:
            - 6 # Charged Attack DMG|{param6:F1P}
    skill:
        atkSpdBuff:
            - 3 # ATK SPD Bonus|{param3:P}
        skillExplode:
            - 2 # Rimestar Shard DMG|{param2:F2P}
        skillHold:
            - 1 # Rimestar Flare DMG|{param1:F2P}
        skillPress:
            - 0 # Flowfrost Arrow DMG|{param0:F2P}
    burst:
        burstHealF:
            - 2 # Eagleplume Healing|{param3:F1P} Max HP+{param2:I}
        burstHealFirstF:
            - 0 # Cast Healing|{param1:F1P} Max HP+{param0:I}
        burstHealFirstP:
            - 1 # Cast Healing|{param1:F1P} Max HP+{param0:I}
        burstHealP:
            - 3 # Eagleplume Healing|{param3:F1P} Max HP+{param2:I}
