id: 10000080
key: "mika"
rarity: QUALITY_PURPLE
body: BODY_BOY
region: ASSOC_TYPE_MONDSTADT
element: Ice
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Mika"
stats: {
   base_hp: 1048.5597
   base_atk: 18.6984
   base_def: 59.800125
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 783.32776
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 44.67375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 13.96899
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1339.9027
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 76.41563
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.894325
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2082.0027
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 118.73813
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 37.128105
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2638.5776
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 150.48
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 47.05344
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3195.1526
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 182.22188
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 56.978775
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3751.7275
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 213.96375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 66.90411
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10802
   burst: 10805
   attack: 10801
   burst_energy_cost: 70
}
name_text_hash_map: 231911858
