use: pipeline
kind: character
name: dahlia

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG|1)
      - attack(4-Hit DMG)
  - charge:
      - attack(Charged Attack DMG)
      - attack(Charged Attack DMG|1)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skill: skill(Skill DMG)

  - burst: burst(Skill DMG)
  - burstShieldFlat: burst(Shield of Sacred Favor DMG Absorption|1)
  - burstShieldPP: burst(Shield of Sacred Favor DMG Absorption)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1TzEFkSrn0vZ08hBKUMvazkP1A1N82ZQBYrnV3lnvICU/edit?usp=sharing
      count_credit: caramielle.
      video: https://youtu.be/RB9LZ6RpiMo
      video_credit: caramielle.

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 1.5
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 1.7
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3-1
        shape: Circle
        center: Player
        offset: [0, 0.3]
        radius: 1.7
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N3-2
        shape: Circle
        center: Player
        offset: [0, 0.4]
        radius: 1.5
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 2.2
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA-1
        shape: Circle
        center: Player
        radius: 2.2

      - name: CA-2
        shape: Circle
        center: Player
        radius: 2.2

  - name: skill
    params:
      short_hold: 0 for Tap (default), 1 for Short Hold.
    hitbox:
      - name: E
        shape: Circle
        center: Player
        radius: 3

  - name: burst
    hitbox:
      - name: Q
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 5.5
