// Code generated by "pipeline"; DO NOT EDIT.

// passive: Inflorescence Unattainable # Weapon_Bow_Umpakati
//
//	Decreases Gliding Stamina consumption by 15%. When using Aimed Shots, the DMG dealt
//	by Charged Attacks increases by 6% every 0.5s. This effect can stack up to 6 times
//	and will be removed 10s after leaving Aiming Mode.
package flowerwreathedfeathers

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.FlowerWreathedFeathers, NewWeapon)
}
