// Code generated by "enumer -text -json -linecomment -type=Set -output artifact.enumer.dm.go -- artifact.dm.go"; DO NOT EDIT.

package keys

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _SetName = "adaycarvedfromrisingwindsarchaicpetraaubadeofmorningstarandmoonberserkerblizzardstrayerbloodstainedchivalrybraveheartcelestialgiftcrimsonwitchofflamesdeepwoodmemoriesdefenderswilldesertpavilionchronicledisenchantmentindeepshadowechoesofanofferingemblemofseveredfatefinaleofthedeepgalleriesflowerofparadiselostfragmentofharmonicwhimsygamblergildeddreamsgladiatorsfinalegoldentroupeheartofdepthhuskofopulentdreamsinstructorlavawalkerlongnightsoathmaidenbelovedmarechausseehuntermartialartistnightoftheskysunveilingnighttimewhispersintheechoingwoodsnoblesseobligenymphsdreamobsidiancodexoceanhuedclampaleflameresolutionofsojournerretracingbolidescholarscrolloftheheroofcindercityshimenawasreminiscencesilkenmoonsserenadesongofdayspasttenacityofthemilleliththeexilethunderingfurythundersootherunfinishedreverievermillionhereafterviridescentvenerervourukashasglowwandererstroupeinvalidset"

var _SetIndex = [...]uint16{0, 0, 25, 37, 63, 72, 87, 107, 117, 130, 150, 166, 179, 202, 228, 246, 265, 289, 309, 333, 340, 352, 368, 380, 392, 411, 421, 431, 445, 458, 476, 489, 512, 546, 560, 571, 584, 597, 606, 627, 642, 649, 676, 698, 717, 731, 753, 761, 775, 789, 806, 825, 843, 858, 873, 883}

const _SetLowerName = "adaycarvedfromrisingwindsarchaicpetraaubadeofmorningstarandmoonberserkerblizzardstrayerbloodstainedchivalrybraveheartcelestialgiftcrimsonwitchofflamesdeepwoodmemoriesdefenderswilldesertpavilionchronicledisenchantmentindeepshadowechoesofanofferingemblemofseveredfatefinaleofthedeepgalleriesflowerofparadiselostfragmentofharmonicwhimsygamblergildeddreamsgladiatorsfinalegoldentroupeheartofdepthhuskofopulentdreamsinstructorlavawalkerlongnightsoathmaidenbelovedmarechausseehuntermartialartistnightoftheskysunveilingnighttimewhispersintheechoingwoodsnoblesseobligenymphsdreamobsidiancodexoceanhuedclampaleflameresolutionofsojournerretracingbolidescholarscrolloftheheroofcindercityshimenawasreminiscencesilkenmoonsserenadesongofdayspasttenacityofthemilleliththeexilethunderingfurythundersootherunfinishedreverievermillionhereafterviridescentvenerervourukashasglowwandererstroupeinvalidset"

func (i Set) String() string {
	if i < 0 || i >= Set(len(_SetIndex)-1) {
		return fmt.Sprintf("Set(%d)", i)
	}
	return _SetName[_SetIndex[i]:_SetIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SetNoOp() {
	var x [1]struct{}
	_ = x[NoSet-(0)]
	_ = x[ADayCarvedFromRisingWinds-(1)]
	_ = x[ArchaicPetra-(2)]
	_ = x[AubadeOfMorningstarAndMoon-(3)]
	_ = x[Berserker-(4)]
	_ = x[BlizzardStrayer-(5)]
	_ = x[BloodstainedChivalry-(6)]
	_ = x[BraveHeart-(7)]
	_ = x[CelestialGift-(8)]
	_ = x[CrimsonWitchOfFlames-(9)]
	_ = x[DeepwoodMemories-(10)]
	_ = x[DefendersWill-(11)]
	_ = x[DesertPavilionChronicle-(12)]
	_ = x[DisenchantmentInDeepShadow-(13)]
	_ = x[EchoesOfAnOffering-(14)]
	_ = x[EmblemOfSeveredFate-(15)]
	_ = x[FinaleOfTheDeepGalleries-(16)]
	_ = x[FlowerOfParadiseLost-(17)]
	_ = x[FragmentOfHarmonicWhimsy-(18)]
	_ = x[Gambler-(19)]
	_ = x[GildedDreams-(20)]
	_ = x[GladiatorsFinale-(21)]
	_ = x[GoldenTroupe-(22)]
	_ = x[HeartOfDepth-(23)]
	_ = x[HuskOfOpulentDreams-(24)]
	_ = x[Instructor-(25)]
	_ = x[Lavawalker-(26)]
	_ = x[LongNightsOath-(27)]
	_ = x[MaidenBeloved-(28)]
	_ = x[MarechausseeHunter-(29)]
	_ = x[MartialArtist-(30)]
	_ = x[NightOfTheSkysUnveiling-(31)]
	_ = x[NighttimeWhispersInTheEchoingWoods-(32)]
	_ = x[NoblesseOblige-(33)]
	_ = x[NymphsDream-(34)]
	_ = x[ObsidianCodex-(35)]
	_ = x[OceanHuedClam-(36)]
	_ = x[PaleFlame-(37)]
	_ = x[ResolutionOfSojourner-(38)]
	_ = x[RetracingBolide-(39)]
	_ = x[Scholar-(40)]
	_ = x[ScrollOfTheHeroOfCinderCity-(41)]
	_ = x[ShimenawasReminiscence-(42)]
	_ = x[SilkenMoonsSerenade-(43)]
	_ = x[SongOfDaysPast-(44)]
	_ = x[TenacityOfTheMillelith-(45)]
	_ = x[TheExile-(46)]
	_ = x[ThunderingFury-(47)]
	_ = x[Thundersoother-(48)]
	_ = x[UnfinishedReverie-(49)]
	_ = x[VermillionHereafter-(50)]
	_ = x[ViridescentVenerer-(51)]
	_ = x[VourukashasGlow-(52)]
	_ = x[WanderersTroupe-(53)]
	_ = x[InvalidSet-(54)]
}

var _SetValues = []Set{NoSet, ADayCarvedFromRisingWinds, ArchaicPetra, AubadeOfMorningstarAndMoon, Berserker, BlizzardStrayer, BloodstainedChivalry, BraveHeart, CelestialGift, CrimsonWitchOfFlames, DeepwoodMemories, DefendersWill, DesertPavilionChronicle, DisenchantmentInDeepShadow, EchoesOfAnOffering, EmblemOfSeveredFate, FinaleOfTheDeepGalleries, FlowerOfParadiseLost, FragmentOfHarmonicWhimsy, Gambler, GildedDreams, GladiatorsFinale, GoldenTroupe, HeartOfDepth, HuskOfOpulentDreams, Instructor, Lavawalker, LongNightsOath, MaidenBeloved, MarechausseeHunter, MartialArtist, NightOfTheSkysUnveiling, NighttimeWhispersInTheEchoingWoods, NoblesseOblige, NymphsDream, ObsidianCodex, OceanHuedClam, PaleFlame, ResolutionOfSojourner, RetracingBolide, Scholar, ScrollOfTheHeroOfCinderCity, ShimenawasReminiscence, SilkenMoonsSerenade, SongOfDaysPast, TenacityOfTheMillelith, TheExile, ThunderingFury, Thundersoother, UnfinishedReverie, VermillionHereafter, ViridescentVenerer, VourukashasGlow, WanderersTroupe, InvalidSet}

var _SetNameToValueMap = map[string]Set{
	_SetName[0:0]:          NoSet,
	_SetLowerName[0:0]:     NoSet,
	_SetName[0:25]:         ADayCarvedFromRisingWinds,
	_SetLowerName[0:25]:    ADayCarvedFromRisingWinds,
	_SetName[25:37]:        ArchaicPetra,
	_SetLowerName[25:37]:   ArchaicPetra,
	_SetName[37:63]:        AubadeOfMorningstarAndMoon,
	_SetLowerName[37:63]:   AubadeOfMorningstarAndMoon,
	_SetName[63:72]:        Berserker,
	_SetLowerName[63:72]:   Berserker,
	_SetName[72:87]:        BlizzardStrayer,
	_SetLowerName[72:87]:   BlizzardStrayer,
	_SetName[87:107]:       BloodstainedChivalry,
	_SetLowerName[87:107]:  BloodstainedChivalry,
	_SetName[107:117]:      BraveHeart,
	_SetLowerName[107:117]: BraveHeart,
	_SetName[117:130]:      CelestialGift,
	_SetLowerName[117:130]: CelestialGift,
	_SetName[130:150]:      CrimsonWitchOfFlames,
	_SetLowerName[130:150]: CrimsonWitchOfFlames,
	_SetName[150:166]:      DeepwoodMemories,
	_SetLowerName[150:166]: DeepwoodMemories,
	_SetName[166:179]:      DefendersWill,
	_SetLowerName[166:179]: DefendersWill,
	_SetName[179:202]:      DesertPavilionChronicle,
	_SetLowerName[179:202]: DesertPavilionChronicle,
	_SetName[202:228]:      DisenchantmentInDeepShadow,
	_SetLowerName[202:228]: DisenchantmentInDeepShadow,
	_SetName[228:246]:      EchoesOfAnOffering,
	_SetLowerName[228:246]: EchoesOfAnOffering,
	_SetName[246:265]:      EmblemOfSeveredFate,
	_SetLowerName[246:265]: EmblemOfSeveredFate,
	_SetName[265:289]:      FinaleOfTheDeepGalleries,
	_SetLowerName[265:289]: FinaleOfTheDeepGalleries,
	_SetName[289:309]:      FlowerOfParadiseLost,
	_SetLowerName[289:309]: FlowerOfParadiseLost,
	_SetName[309:333]:      FragmentOfHarmonicWhimsy,
	_SetLowerName[309:333]: FragmentOfHarmonicWhimsy,
	_SetName[333:340]:      Gambler,
	_SetLowerName[333:340]: Gambler,
	_SetName[340:352]:      GildedDreams,
	_SetLowerName[340:352]: GildedDreams,
	_SetName[352:368]:      GladiatorsFinale,
	_SetLowerName[352:368]: GladiatorsFinale,
	_SetName[368:380]:      GoldenTroupe,
	_SetLowerName[368:380]: GoldenTroupe,
	_SetName[380:392]:      HeartOfDepth,
	_SetLowerName[380:392]: HeartOfDepth,
	_SetName[392:411]:      HuskOfOpulentDreams,
	_SetLowerName[392:411]: HuskOfOpulentDreams,
	_SetName[411:421]:      Instructor,
	_SetLowerName[411:421]: Instructor,
	_SetName[421:431]:      Lavawalker,
	_SetLowerName[421:431]: Lavawalker,
	_SetName[431:445]:      LongNightsOath,
	_SetLowerName[431:445]: LongNightsOath,
	_SetName[445:458]:      MaidenBeloved,
	_SetLowerName[445:458]: MaidenBeloved,
	_SetName[458:476]:      MarechausseeHunter,
	_SetLowerName[458:476]: MarechausseeHunter,
	_SetName[476:489]:      MartialArtist,
	_SetLowerName[476:489]: MartialArtist,
	_SetName[489:512]:      NightOfTheSkysUnveiling,
	_SetLowerName[489:512]: NightOfTheSkysUnveiling,
	_SetName[512:546]:      NighttimeWhispersInTheEchoingWoods,
	_SetLowerName[512:546]: NighttimeWhispersInTheEchoingWoods,
	_SetName[546:560]:      NoblesseOblige,
	_SetLowerName[546:560]: NoblesseOblige,
	_SetName[560:571]:      NymphsDream,
	_SetLowerName[560:571]: NymphsDream,
	_SetName[571:584]:      ObsidianCodex,
	_SetLowerName[571:584]: ObsidianCodex,
	_SetName[584:597]:      OceanHuedClam,
	_SetLowerName[584:597]: OceanHuedClam,
	_SetName[597:606]:      PaleFlame,
	_SetLowerName[597:606]: PaleFlame,
	_SetName[606:627]:      ResolutionOfSojourner,
	_SetLowerName[606:627]: ResolutionOfSojourner,
	_SetName[627:642]:      RetracingBolide,
	_SetLowerName[627:642]: RetracingBolide,
	_SetName[642:649]:      Scholar,
	_SetLowerName[642:649]: Scholar,
	_SetName[649:676]:      ScrollOfTheHeroOfCinderCity,
	_SetLowerName[649:676]: ScrollOfTheHeroOfCinderCity,
	_SetName[676:698]:      ShimenawasReminiscence,
	_SetLowerName[676:698]: ShimenawasReminiscence,
	_SetName[698:717]:      SilkenMoonsSerenade,
	_SetLowerName[698:717]: SilkenMoonsSerenade,
	_SetName[717:731]:      SongOfDaysPast,
	_SetLowerName[717:731]: SongOfDaysPast,
	_SetName[731:753]:      TenacityOfTheMillelith,
	_SetLowerName[731:753]: TenacityOfTheMillelith,
	_SetName[753:761]:      TheExile,
	_SetLowerName[753:761]: TheExile,
	_SetName[761:775]:      ThunderingFury,
	_SetLowerName[761:775]: ThunderingFury,
	_SetName[775:789]:      Thundersoother,
	_SetLowerName[775:789]: Thundersoother,
	_SetName[789:806]:      UnfinishedReverie,
	_SetLowerName[789:806]: UnfinishedReverie,
	_SetName[806:825]:      VermillionHereafter,
	_SetLowerName[806:825]: VermillionHereafter,
	_SetName[825:843]:      ViridescentVenerer,
	_SetLowerName[825:843]: ViridescentVenerer,
	_SetName[843:858]:      VourukashasGlow,
	_SetLowerName[843:858]: VourukashasGlow,
	_SetName[858:873]:      WanderersTroupe,
	_SetLowerName[858:873]: WanderersTroupe,
	_SetName[873:883]:      InvalidSet,
	_SetLowerName[873:883]: InvalidSet,
}

var _SetNames = []string{
	_SetName[0:0],
	_SetName[0:25],
	_SetName[25:37],
	_SetName[37:63],
	_SetName[63:72],
	_SetName[72:87],
	_SetName[87:107],
	_SetName[107:117],
	_SetName[117:130],
	_SetName[130:150],
	_SetName[150:166],
	_SetName[166:179],
	_SetName[179:202],
	_SetName[202:228],
	_SetName[228:246],
	_SetName[246:265],
	_SetName[265:289],
	_SetName[289:309],
	_SetName[309:333],
	_SetName[333:340],
	_SetName[340:352],
	_SetName[352:368],
	_SetName[368:380],
	_SetName[380:392],
	_SetName[392:411],
	_SetName[411:421],
	_SetName[421:431],
	_SetName[431:445],
	_SetName[445:458],
	_SetName[458:476],
	_SetName[476:489],
	_SetName[489:512],
	_SetName[512:546],
	_SetName[546:560],
	_SetName[560:571],
	_SetName[571:584],
	_SetName[584:597],
	_SetName[597:606],
	_SetName[606:627],
	_SetName[627:642],
	_SetName[642:649],
	_SetName[649:676],
	_SetName[676:698],
	_SetName[698:717],
	_SetName[717:731],
	_SetName[731:753],
	_SetName[753:761],
	_SetName[761:775],
	_SetName[775:789],
	_SetName[789:806],
	_SetName[806:825],
	_SetName[825:843],
	_SetName[843:858],
	_SetName[858:873],
	_SetName[873:883],
}

// SetString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SetString(s string) (Set, error) {
	if val, ok := _SetNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SetNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Set values", s)
}

// SetValues returns all values of the enum
func SetValues() []Set {
	return _SetValues
}

// SetStrings returns a slice of all String values of the enum
func SetStrings() []string {
	strs := make([]string, len(_SetNames))
	copy(strs, _SetNames)
	return strs
}

// IsASet returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Set) IsASet() bool {
	for _, v := range _SetValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Set
func (i Set) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Set
func (i *Set) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Set should be a string, got %s", data)
	}

	var err error
	*i, err = SetString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Set
func (i Set) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Set
func (i *Set) UnmarshalText(text []byte) error {
	var err error
	*i, err = SetString(string(text))
	return err
}
