// Code generated by "pipeline"; DO NOT EDIT.

package keys

import (
	"encoding/json"
	"fmt"
	"slices"
	"strings"
)

type Weapon int

func (v Weapon) String() string               { return _WeaponNames[v] }
func (v Weapon) MarshalJSON() ([]byte, error) { return json.Marshal(v.String()) }
func WeaponStrings() []string                 { return _WeaponNames[:] }
func WeaponValues() []Weapon                  { return _WeaponValues[:] }

func WeaponString(s string) (Weapon, error) {
	s = strings.ToLower(s)
	ind := slices.IndexFunc(_WeaponNames[:], func(i string) bool { return i == s })
	if ind == -1 {
		return 0, fmt.Errorf("%s does not belong to Weapon", s)
	}
	return _WeaponValues[ind], nil
}

func (v *Weapon) UnmarshalJSON(in []byte) error {
	var s string
	if err := json.Unmarshal(in, &s); err != nil {
		return err
	}
	var err error
	*v, err = WeaponString(s)
	return err
}

func _comptime_Weapon() {
	var x [1]struct{}
	_ = x[int(InvalidWeapon+1)-len(_WeaponNames)]
	_ = x[int(InvalidWeapon+1)-len(_WeaponValues)]
}

const (
	NoWeapon                        Weapon = iota //
	Absolution                                    // absolution
	Akuoumaru                                     // akuoumaru
	AlleyHunter                                   // alleyhunter
	AmenomaKageuchi                               // amenomakageuchi
	AmosBow                                       // amosbow
	AngelosHeptades                               // angelosheptades
	ApprenticesNotes                              // apprenticesnotes
	AquaSimulacra                                 // aquasimulacra
	AquilaFavonia                                 // aquilafavonia
	AshGravenDrinkingHorn                         // ashgravendrinkinghorn
	AstralVulturesCrimsonPlumage                  // astralvulturescrimsonplumage
	AthameArtis                                   // athameartis
	AThousandBlazingSuns                          // athousandblazingsuns
	AThousandFloatingDreams                       // athousandfloatingdreams
	Azurelight                                    // azurelight
	BalladOfTheBoundlessBlue                      // balladoftheboundlessblue
	BalladOfTheFjords                             // balladofthefjords
	BeaconOfTheReedSea                            // beaconofthereedsea
	BeginnersProtector                            // beginnersprotector
	BlackcliffAgate                               // blackcliffagate
	BlackcliffLongsword                           // blackclifflongsword
	BlackcliffPole                                // blackcliffpole
	BlackcliffSlasher                             // blackcliffslasher
	BlackcliffWarbow                              // blackcliffwarbow
	BlackmarrowLantern                            // blackmarrowlantern
	BlackTassel                                   // blacktassel
	BloodsoakedRuins                              // bloodsoakedruins
	BloodtaintedGreatsword                        // bloodtaintedgreatsword
	CalamityOfEshu                                // calamityofeshu
	CalamityQueller                               // calamityqueller
	CashflowSupervision                           // cashflowsupervision
	ChainBreaker                                  // chainbreaker
	CinnabarSpindle                               // cinnabarspindle
	Cloudforged                                   // cloudforged
	CompoundBow                                   // compoundbow
	CoolSteel                                     // coolsteel
	CranesEchoingCall                             // cranesechoingcall
	CrescentPike                                  // crescentpike
	CrimsonMoonsSemblance                         // crimsonmoonssemblance
	DarkIronSword                                 // darkironsword
	DawningFrost                                  // dawningfrost
	Deathmatch                                    // deathmatch
	DebateClub                                    // debateclub
	DialoguesOfTheDesertSages                     // dialoguesofthedesertsages
	DodocoTales                                   // dodocotales
	DragonsBane                                   // dragonsbane
	DragonspineSpear                              // dragonspinespear
	DullBlade                                     // dullblade
	EarthShaker                                   // earthshaker
	ElegyForTheEnd                                // elegyfortheend
	EmeraldOrb                                    // emeraldorb
	EndOfTheLine                                  // endoftheline
	EngulfingLightning                            // engulfinglightning
	EtherlightSpindlelute                         // etherlightspindlelute
	EverlastingMoonglow                           // everlastingmoonglow
	EyeOfPerception                               // eyeofperception
	FadingTwilight                                // fadingtwilight
	FangOfTheMountainKing                         // fangofthemountainking
	FavoniusCodex                                 // favoniuscodex
	FavoniusGreatsword                            // favoniusgreatsword
	FavoniusLance                                 // favoniuslance
	FavoniusSword                                 // favoniussword
	FavoniusWarbow                                // favoniuswarbow
	FerrousShadow                                 // ferrousshadow
	FesteringDesire                               // festeringdesire
	FilletBlade                                   // filletblade
	FinaleOfTheDeep                               // finaleofthedeep
	FleuveCendreFerryman                          // fleuvecendreferryman
	FlowerWreathedFeathers                        // flowerwreathedfeathers
	FlowingPurity                                 // flowingpurity
	FluteOfEzpitzal                               // fluteofezpitzal
	FootprintOfTheRainbow                         // footprintoftherainbow
	ForestRegalia                                 // forestregalia
	FracturedHalo                                 // fracturedhalo
	FreedomSworn                                  // freedomsworn
	Frostbearer                                   // frostbearer
	FruitfulHook                                  // fruitfulhook
	FruitOfFulfillment                            // fruitoffulfillment
	GestOfTheMightyWolf                           // gestofthemightywolf
	HakushinRing                                  // hakushinring
	Halberd                                       // halberd
	Hamayumi                                      // hamayumi
	HaranGeppakuFutsu                             // harangeppakufutsu
	HarbingerOfDawn                               // harbingerofdawn
	HuntersBow                                    // huntersbow
	HuntersPath                                   // hunterspath
	IbisPiercer                                   // ibispiercer
	IronPoint                                     // ironpoint
	IronSting                                     // ironsting
	JadefallsSplendor                             // jadefallssplendor
	KagotsurubeIsshin                             // kagotsurubeisshin
	KagurasVerity                                 // kagurasverity
	KatsuragikiriNagamasa                         // katsuragikirinagamasa
	KeyOfKhajNisut                                // keyofkhajnisut
	KingsSquire                                   // kingssquire
	KitainCrossSpear                              // kitaincrossspear
	LightOfFoliarIncision                         // lightoffoliarincision
	LionsRoar                                     // lionsroar
	LithicBlade                                   // lithicblade
	LithicSpear                                   // lithicspear
	LostPrayerToTheSacredWinds                    // lostprayertothesacredwinds
	LumidouceElegy                                // lumidouceelegy
	LuxuriousSeaLord                              // luxurioussealord
	MagicGuide                                    // magicguide
	MailedFlower                                  // mailedflower
	MakhairaAquamarine                            // makhairaaquamarine
	MappaMare                                     // mappamare
	MasterKey                                     // masterkey
	MemoryOfDust                                  // memoryofdust
	Messenger                                     // messenger
	MissiveWindspear                              // missivewindspear
	MistsplitterReforged                          // mistsplitterreforged
	MitternachtsWaltz                             // mitternachtswaltz
	Moonpiercer                                   // moonpiercer
	MoonweaversDawn                               // moonweaversdawn
	MountainBracingBolt                           // mountainbracingbolt
	MouunsMoon                                    // mouunsmoon
	NightweaversLookingGlass                      // nightweaverslookingglass
	NocturnesCurtainCall                          // nocturnescurtaincall
	OathswornEye                                  // oathsworneye
	OldMercsPal                                   // oldmercspal
	OtherworldlyStory                             // otherworldlystory
	PeakPatrolSong                                // peakpatrolsong
	PocketGrimoire                                // pocketgrimoire
	PolarStar                                     // polarstar
	PortablePowerSaw                              // portablepowersaw
	Predator                                      // predator
	PrimordialJadeCutter                          // primordialjadecutter
	PrimordialJadeWingedSpear                     // primordialjadewingedspear
	ProspectorsDrill                              // prospectorsdrill
	ProspectorsShovel                             // prospectorsshovel
	PrototypeAmber                                // prototypeamber
	PrototypeArchaic                              // prototypearchaic
	PrototypeCrescent                             // prototypecrescent
	PrototypeRancour                              // prototyperancour
	PrototypeStarglitter                          // prototypestarglitter
	RainbowSerpentsRainBow                        // rainbowserpentsrainbow
	Rainslasher                                   // rainslasher
	RangeGauge                                    // rangegauge
	RavenBow                                      // ravenbow
	RecurveBow                                    // recurvebow
	RedhornStonethresher                          // redhornstonethresher
	ReliquaryOfTruth                              // reliquaryoftruth
	RightfulReward                                // rightfulreward
	RingOfYaxche                                  // ringofyaxche
	RoyalBow                                      // royalbow
	RoyalGreatsword                               // royalgreatsword
	RoyalGrimoire                                 // royalgrimoire
	RoyalLongsword                                // royallongsword
	RoyalSpear                                    // royalspear
	Rust                                          // rust
	SacrificersStaff                              // sacrificersstaff
	SacrificialBow                                // sacrificialbow
	SacrificialFragments                          // sacrificialfragments
	SacrificialGreatsword                         // sacrificialgreatsword
	SacrificialJade                               // sacrificialjade
	SacrificialSword                              // sacrificialsword
	SapwoodBlade                                  // sapwoodblade
	ScionOfTheBlazingSun                          // scionoftheblazingsun
	SeasonedHuntersBow                            // seasonedhuntersbow
	SequenceOfSolitude                            // sequenceofsolitude
	SerenitysCall                                 // serenityscall
	SerpentSpine                                  // serpentspine
	SharpshootersOath                             // sharpshootersoath
	SilvershowerHeartstrings                      // silvershowerheartstrings
	SilverSword                                   // silversword
	SkyriderGreatsword                            // skyridergreatsword
	SkyriderSword                                 // skyridersword
	SkywardAtlas                                  // skywardatlas
	SkywardBlade                                  // skywardblade
	SkywardHarp                                   // skywardharp
	SkywardPride                                  // skywardpride
	SkywardSpine                                  // skywardspine
	Slingshot                                     // slingshot
	SnareHook                                     // snarehook
	SnowTombedStarsilver                          // snowtombedstarsilver
	SolarPearl                                    // solarpearl
	SongOfBrokenPines                             // songofbrokenpines
	SongOfStillness                               // songofstillness
	SplendorOfTranquilWaters                      // splendoroftranquilwaters
	StaffOfHoma                                   // staffofhoma
	StaffOfTheScarletSands                        // staffofthescarletsands
	StarcallersWatch                              // starcallerswatch
	SturdyBone                                    // sturdybone
	SummitShaper                                  // summitshaper
	SunnyMorningSleepIn                           // sunnymorningsleepin
	SurfsUp                                       // surfsup
	SwordOfDescension                             // swordofdescension
	SwordOfNarzissenkreuz                         // swordofnarzissenkreuz
	SymphonistOfScents                            // symphonistofscents
	TalkingStick                                  // talkingstick
	TamayurateiNoOhanashi                         // tamayurateinoohanashi
	TheAlleyFlash                                 // thealleyflash
	TheBell                                       // thebell
	TheBlackSword                                 // theblacksword
	TheCatch                                      // thecatch
	TheDaybreakChronicles                         // thedaybreakchronicles
	TheDockhandsAssistant                         // thedockhandsassistant
	TheFirstGreatMagic                            // thefirstgreatmagic
	TheFlute                                      // theflute
	TheStringless                                 // thestringless
	TheUnforged                                   // theunforged
	TheViridescentHunt                            // theviridescenthunt
	TheWidsith                                    // thewidsith
	ThrillingTalesOfDragonSlayers                 // thrillingtalesofdragonslayers
	ThunderingPulse                               // thunderingpulse
	TidalShadow                                   // tidalshadow
	TomeOfTheEternalFlow                          // tomeoftheeternalflow
	ToukabouShigure                               // toukaboushigure
	TravelersHandySword                           // travelershandysword
	TulaytullahsRemembrance                       // tulaytullahsremembrance
	TwinNephrite                                  // twinnephrite
	UltimateOverlordsMegaMagicSword               // ultimateoverlordsmegamagicsword
	UrakuMisugiri                                 // urakumisugiri
	Verdict                                       // verdict
	VividNotions                                  // vividnotions
	VortexVanquisher                              // vortexvanquisher
	WanderingEvenstar                             // wanderingevenstar
	WasterGreatsword                              // wastergreatsword
	WavebreakersFin                               // wavebreakersfin
	WaveridingWhirl                               // waveridingwhirl
	Whiteblind                                    // whiteblind
	WhiteIronGreatsword                           // whiteirongreatsword
	WhiteTassel                                   // whitetassel
	WindblumeOde                                  // windblumeode
	WineAndSong                                   // wineandsong
	WolfFang                                      // wolffang
	WolfsGravestone                               // wolfsgravestone
	XiphosMoonlight                               // xiphosmoonlight
	InvalidWeapon                                 // invalidweapon
)

var _WeaponNames = [...]string{
	"",
	"absolution",
	"akuoumaru",
	"alleyhunter",
	"amenomakageuchi",
	"amosbow",
	"angelosheptades",
	"apprenticesnotes",
	"aquasimulacra",
	"aquilafavonia",
	"ashgravendrinkinghorn",
	"astralvulturescrimsonplumage",
	"athameartis",
	"athousandblazingsuns",
	"athousandfloatingdreams",
	"azurelight",
	"balladoftheboundlessblue",
	"balladofthefjords",
	"beaconofthereedsea",
	"beginnersprotector",
	"blackcliffagate",
	"blackclifflongsword",
	"blackcliffpole",
	"blackcliffslasher",
	"blackcliffwarbow",
	"blackmarrowlantern",
	"blacktassel",
	"bloodsoakedruins",
	"bloodtaintedgreatsword",
	"calamityofeshu",
	"calamityqueller",
	"cashflowsupervision",
	"chainbreaker",
	"cinnabarspindle",
	"cloudforged",
	"compoundbow",
	"coolsteel",
	"cranesechoingcall",
	"crescentpike",
	"crimsonmoonssemblance",
	"darkironsword",
	"dawningfrost",
	"deathmatch",
	"debateclub",
	"dialoguesofthedesertsages",
	"dodocotales",
	"dragonsbane",
	"dragonspinespear",
	"dullblade",
	"earthshaker",
	"elegyfortheend",
	"emeraldorb",
	"endoftheline",
	"engulfinglightning",
	"etherlightspindlelute",
	"everlastingmoonglow",
	"eyeofperception",
	"fadingtwilight",
	"fangofthemountainking",
	"favoniuscodex",
	"favoniusgreatsword",
	"favoniuslance",
	"favoniussword",
	"favoniuswarbow",
	"ferrousshadow",
	"festeringdesire",
	"filletblade",
	"finaleofthedeep",
	"fleuvecendreferryman",
	"flowerwreathedfeathers",
	"flowingpurity",
	"fluteofezpitzal",
	"footprintoftherainbow",
	"forestregalia",
	"fracturedhalo",
	"freedomsworn",
	"frostbearer",
	"fruitfulhook",
	"fruitoffulfillment",
	"gestofthemightywolf",
	"hakushinring",
	"halberd",
	"hamayumi",
	"harangeppakufutsu",
	"harbingerofdawn",
	"huntersbow",
	"hunterspath",
	"ibispiercer",
	"ironpoint",
	"ironsting",
	"jadefallssplendor",
	"kagotsurubeisshin",
	"kagurasverity",
	"katsuragikirinagamasa",
	"keyofkhajnisut",
	"kingssquire",
	"kitaincrossspear",
	"lightoffoliarincision",
	"lionsroar",
	"lithicblade",
	"lithicspear",
	"lostprayertothesacredwinds",
	"lumidouceelegy",
	"luxurioussealord",
	"magicguide",
	"mailedflower",
	"makhairaaquamarine",
	"mappamare",
	"masterkey",
	"memoryofdust",
	"messenger",
	"missivewindspear",
	"mistsplitterreforged",
	"mitternachtswaltz",
	"moonpiercer",
	"moonweaversdawn",
	"mountainbracingbolt",
	"mouunsmoon",
	"nightweaverslookingglass",
	"nocturnescurtaincall",
	"oathsworneye",
	"oldmercspal",
	"otherworldlystory",
	"peakpatrolsong",
	"pocketgrimoire",
	"polarstar",
	"portablepowersaw",
	"predator",
	"primordialjadecutter",
	"primordialjadewingedspear",
	"prospectorsdrill",
	"prospectorsshovel",
	"prototypeamber",
	"prototypearchaic",
	"prototypecrescent",
	"prototyperancour",
	"prototypestarglitter",
	"rainbowserpentsrainbow",
	"rainslasher",
	"rangegauge",
	"ravenbow",
	"recurvebow",
	"redhornstonethresher",
	"reliquaryoftruth",
	"rightfulreward",
	"ringofyaxche",
	"royalbow",
	"royalgreatsword",
	"royalgrimoire",
	"royallongsword",
	"royalspear",
	"rust",
	"sacrificersstaff",
	"sacrificialbow",
	"sacrificialfragments",
	"sacrificialgreatsword",
	"sacrificialjade",
	"sacrificialsword",
	"sapwoodblade",
	"scionoftheblazingsun",
	"seasonedhuntersbow",
	"sequenceofsolitude",
	"serenityscall",
	"serpentspine",
	"sharpshootersoath",
	"silvershowerheartstrings",
	"silversword",
	"skyridergreatsword",
	"skyridersword",
	"skywardatlas",
	"skywardblade",
	"skywardharp",
	"skywardpride",
	"skywardspine",
	"slingshot",
	"snarehook",
	"snowtombedstarsilver",
	"solarpearl",
	"songofbrokenpines",
	"songofstillness",
	"splendoroftranquilwaters",
	"staffofhoma",
	"staffofthescarletsands",
	"starcallerswatch",
	"sturdybone",
	"summitshaper",
	"sunnymorningsleepin",
	"surfsup",
	"swordofdescension",
	"swordofnarzissenkreuz",
	"symphonistofscents",
	"talkingstick",
	"tamayurateinoohanashi",
	"thealleyflash",
	"thebell",
	"theblacksword",
	"thecatch",
	"thedaybreakchronicles",
	"thedockhandsassistant",
	"thefirstgreatmagic",
	"theflute",
	"thestringless",
	"theunforged",
	"theviridescenthunt",
	"thewidsith",
	"thrillingtalesofdragonslayers",
	"thunderingpulse",
	"tidalshadow",
	"tomeoftheeternalflow",
	"toukaboushigure",
	"travelershandysword",
	"tulaytullahsremembrance",
	"twinnephrite",
	"ultimateoverlordsmegamagicsword",
	"urakumisugiri",
	"verdict",
	"vividnotions",
	"vortexvanquisher",
	"wanderingevenstar",
	"wastergreatsword",
	"wavebreakersfin",
	"waveridingwhirl",
	"whiteblind",
	"whiteirongreatsword",
	"whitetassel",
	"windblumeode",
	"wineandsong",
	"wolffang",
	"wolfsgravestone",
	"xiphosmoonlight",
	"invalidweapon",
}

var _WeaponValues = [...]Weapon{
	NoWeapon,
	Absolution,
	Akuoumaru,
	AlleyHunter,
	AmenomaKageuchi,
	AmosBow,
	AngelosHeptades,
	ApprenticesNotes,
	AquaSimulacra,
	AquilaFavonia,
	AshGravenDrinkingHorn,
	AstralVulturesCrimsonPlumage,
	AthameArtis,
	AThousandBlazingSuns,
	AThousandFloatingDreams,
	Azurelight,
	BalladOfTheBoundlessBlue,
	BalladOfTheFjords,
	BeaconOfTheReedSea,
	BeginnersProtector,
	BlackcliffAgate,
	BlackcliffLongsword,
	BlackcliffPole,
	BlackcliffSlasher,
	BlackcliffWarbow,
	BlackmarrowLantern,
	BlackTassel,
	BloodsoakedRuins,
	BloodtaintedGreatsword,
	CalamityOfEshu,
	CalamityQueller,
	CashflowSupervision,
	ChainBreaker,
	CinnabarSpindle,
	Cloudforged,
	CompoundBow,
	CoolSteel,
	CranesEchoingCall,
	CrescentPike,
	CrimsonMoonsSemblance,
	DarkIronSword,
	DawningFrost,
	Deathmatch,
	DebateClub,
	DialoguesOfTheDesertSages,
	DodocoTales,
	DragonsBane,
	DragonspineSpear,
	DullBlade,
	EarthShaker,
	ElegyForTheEnd,
	EmeraldOrb,
	EndOfTheLine,
	EngulfingLightning,
	EtherlightSpindlelute,
	EverlastingMoonglow,
	EyeOfPerception,
	FadingTwilight,
	FangOfTheMountainKing,
	FavoniusCodex,
	FavoniusGreatsword,
	FavoniusLance,
	FavoniusSword,
	FavoniusWarbow,
	FerrousShadow,
	FesteringDesire,
	FilletBlade,
	FinaleOfTheDeep,
	FleuveCendreFerryman,
	FlowerWreathedFeathers,
	FlowingPurity,
	FluteOfEzpitzal,
	FootprintOfTheRainbow,
	ForestRegalia,
	FracturedHalo,
	FreedomSworn,
	Frostbearer,
	FruitfulHook,
	FruitOfFulfillment,
	GestOfTheMightyWolf,
	HakushinRing,
	Halberd,
	Hamayumi,
	HaranGeppakuFutsu,
	HarbingerOfDawn,
	HuntersBow,
	HuntersPath,
	IbisPiercer,
	IronPoint,
	IronSting,
	JadefallsSplendor,
	KagotsurubeIsshin,
	KagurasVerity,
	KatsuragikiriNagamasa,
	KeyOfKhajNisut,
	KingsSquire,
	KitainCrossSpear,
	LightOfFoliarIncision,
	LionsRoar,
	LithicBlade,
	LithicSpear,
	LostPrayerToTheSacredWinds,
	LumidouceElegy,
	LuxuriousSeaLord,
	MagicGuide,
	MailedFlower,
	MakhairaAquamarine,
	MappaMare,
	MasterKey,
	MemoryOfDust,
	Messenger,
	MissiveWindspear,
	MistsplitterReforged,
	MitternachtsWaltz,
	Moonpiercer,
	MoonweaversDawn,
	MountainBracingBolt,
	MouunsMoon,
	NightweaversLookingGlass,
	NocturnesCurtainCall,
	OathswornEye,
	OldMercsPal,
	OtherworldlyStory,
	PeakPatrolSong,
	PocketGrimoire,
	PolarStar,
	PortablePowerSaw,
	Predator,
	PrimordialJadeCutter,
	PrimordialJadeWingedSpear,
	ProspectorsDrill,
	ProspectorsShovel,
	PrototypeAmber,
	PrototypeArchaic,
	PrototypeCrescent,
	PrototypeRancour,
	PrototypeStarglitter,
	RainbowSerpentsRainBow,
	Rainslasher,
	RangeGauge,
	RavenBow,
	RecurveBow,
	RedhornStonethresher,
	ReliquaryOfTruth,
	RightfulReward,
	RingOfYaxche,
	RoyalBow,
	RoyalGreatsword,
	RoyalGrimoire,
	RoyalLongsword,
	RoyalSpear,
	Rust,
	SacrificersStaff,
	SacrificialBow,
	SacrificialFragments,
	SacrificialGreatsword,
	SacrificialJade,
	SacrificialSword,
	SapwoodBlade,
	ScionOfTheBlazingSun,
	SeasonedHuntersBow,
	SequenceOfSolitude,
	SerenitysCall,
	SerpentSpine,
	SharpshootersOath,
	SilvershowerHeartstrings,
	SilverSword,
	SkyriderGreatsword,
	SkyriderSword,
	SkywardAtlas,
	SkywardBlade,
	SkywardHarp,
	SkywardPride,
	SkywardSpine,
	Slingshot,
	SnareHook,
	SnowTombedStarsilver,
	SolarPearl,
	SongOfBrokenPines,
	SongOfStillness,
	SplendorOfTranquilWaters,
	StaffOfHoma,
	StaffOfTheScarletSands,
	StarcallersWatch,
	SturdyBone,
	SummitShaper,
	SunnyMorningSleepIn,
	SurfsUp,
	SwordOfDescension,
	SwordOfNarzissenkreuz,
	SymphonistOfScents,
	TalkingStick,
	TamayurateiNoOhanashi,
	TheAlleyFlash,
	TheBell,
	TheBlackSword,
	TheCatch,
	TheDaybreakChronicles,
	TheDockhandsAssistant,
	TheFirstGreatMagic,
	TheFlute,
	TheStringless,
	TheUnforged,
	TheViridescentHunt,
	TheWidsith,
	ThrillingTalesOfDragonSlayers,
	ThunderingPulse,
	TidalShadow,
	TomeOfTheEternalFlow,
	ToukabouShigure,
	TravelersHandySword,
	TulaytullahsRemembrance,
	TwinNephrite,
	UltimateOverlordsMegaMagicSword,
	UrakuMisugiri,
	Verdict,
	VividNotions,
	VortexVanquisher,
	WanderingEvenstar,
	WasterGreatsword,
	WavebreakersFin,
	WaveridingWhirl,
	Whiteblind,
	WhiteIronGreatsword,
	WhiteTassel,
	WindblumeOde,
	WineAndSong,
	WolfFang,
	WolfsGravestone,
	XiphosMoonlight,
	InvalidWeapon,
}
