id: 10000046
key: "hutao"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_LIYUE
element: Fire
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Hutao"
stats: {
   base_hp: 1210.7164
   base_atk: 8.2859
   base_def: 68.2062
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1038.0798
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 58.482
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 7.103891
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1775.6628
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 100.035
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 12.151393
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2759.107
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 155.439
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 18.881393
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3496.69
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 196.992
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.928896
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4234.273
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 238.545
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 28.976398
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4971.856
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 280.098
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 34.0239
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 10462
   burst: 10463
   attack: 10461
   burst_energy_cost: 60
}
name_text_hash_map: 1940919994
