// Code generated by "pipeline"; DO NOT EDIT.

// passive: Essence of Falsity # Weapon_Catalyst_Sistrum
//
//	CRIT Rate is increased by 8%. When the equipping character unleashes an Elemental
//	Skill, they gain the Secret of Lies effect: Elemental Mastery is increased by 80
//	for 12s. When the equipping character deals Lunar-Bloom DMG to an opponent, they
//	gain the Moon of Truth effect: CRIT DMG is increased by 24% for 4s. When both the
//	Secret of Lies and Moon of Truth effects are active at the same time, the results
//	of both effects will be increased by 50%.
package reliquary

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.ReliquaryOfTruth, NewWeapon)
}
