// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protos/backend/preview.proto

package preview

import (
	model "github.com/genshinsim/gcsim/pkg/model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,json=_id,proto3" json:"id,omitempty"`
	Data          *model.SimulationResult `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_protos_backend_preview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_preview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_protos_backend_preview_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRequest) GetData() *model.SimulationResult {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_protos_backend_preview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_backend_preview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_protos_backend_preview_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_protos_backend_preview_proto protoreflect.FileDescriptor

const file_protos_backend_preview_proto_rawDesc = "" +
	"\n" +
	"\x1cprotos/backend/preview.proto\x12\apreview\x1a\x19protos/model/result.proto\"J\n" +
	"\n" +
	"GetRequest\x12\x0f\n" +
	"\x02id\x18\x01 \x01(\tR\x03_id\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.model.SimulationResultR\x04data\"!\n" +
	"\vGetResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data29\n" +
	"\x05Embed\x120\n" +
	"\x03Get\x12\x13.preview.GetRequest\x1a\x14.preview.GetResponseB:Z8github.com/genshinsim/gcsim/backend/pkg/services/previewb\x06proto3"

var (
	file_protos_backend_preview_proto_rawDescOnce sync.Once
	file_protos_backend_preview_proto_rawDescData []byte
)

func file_protos_backend_preview_proto_rawDescGZIP() []byte {
	file_protos_backend_preview_proto_rawDescOnce.Do(func() {
		file_protos_backend_preview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_backend_preview_proto_rawDesc), len(file_protos_backend_preview_proto_rawDesc)))
	})
	return file_protos_backend_preview_proto_rawDescData
}

var file_protos_backend_preview_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_backend_preview_proto_goTypes = []any{
	(*GetRequest)(nil),             // 0: preview.GetRequest
	(*GetResponse)(nil),            // 1: preview.GetResponse
	(*model.SimulationResult)(nil), // 2: model.SimulationResult
}
var file_protos_backend_preview_proto_depIdxs = []int32{
	2, // 0: preview.GetRequest.data:type_name -> model.SimulationResult
	0, // 1: preview.Embed.Get:input_type -> preview.GetRequest
	1, // 2: preview.Embed.Get:output_type -> preview.GetResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_backend_preview_proto_init() }
func file_protos_backend_preview_proto_init() {
	if File_protos_backend_preview_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_backend_preview_proto_rawDesc), len(file_protos_backend_preview_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_backend_preview_proto_goTypes,
		DependencyIndexes: file_protos_backend_preview_proto_depIdxs,
		MessageInfos:      file_protos_backend_preview_proto_msgTypes,
	}.Build()
	File_protos_backend_preview_proto = out.File
	file_protos_backend_preview_proto_goTypes = nil
	file_protos_backend_preview_proto_depIdxs = nil
}
