package_name: aloy
genshin_id: 10000062
key: aloy
skill_data_mapping:
    attack:
        aim:
            - 5 # Aimed Shot|{param5:F1P}
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}+{param1:F1P}
            - 1 # 1-Hit DMG|{param0:F1P}+{param1:F1P}
        attack_2:
            - 2 # 2-Hit DMG|{param2:F1P}
        attack_3:
            - 3 # 3-Hit DMG|{param3:F1P}
        attack_4:
            - 4 # 4-Hit DMG|{param4:F1P}
        fullaim:
            - 6 # Fully-Charged Aimed Shot|{param6:P}
    skill:
        skillAtkDecrease:
            - 2 # ATK Decrease|{param2:P}
        skillBomblets:
            - 1 # Chillwater Bomblet DMG|{param1:F1P}
        skillCoilNABonus:
            - 4 # Coil Normal Attack DMG Bonus|{param4:F1P}/{param5:F1P}/{param6:F1P}
            - 5 # Coil Normal Attack DMG Bonus|{param4:F1P}/{param5:F1P}/{param6:F1P}
            - 6 # Coil Normal Attack DMG Bonus|{param4:F1P}/{param5:F1P}/{param6:F1P}
        skillMain:
            - 0 # Freeze Bomb DMG|{param0:P}
        skillRushingIceNABonus:
            - 7 # Rushing Ice Normal Attack DMG Bonus|{param7:F1P}
    burst:
        burst:
            - 0 # Skill DMG|{param0:P}

documentation:
    fields_data:
        - fields: [.aloy.coil]
          desc: Current number of coil stacks.
