use: pipeline
kind: character
name: aloy

talents:
  - attack:
      - - attack(1-Hit DMG)
        - attack(1-Hit DMG|1)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - aim: attack(Aimed Shot)
  - fullaim: attack(Fully-Charged Aimed Shot)

  - skillMain: skill(Freeze Bomb DMG)
  - skillBomblets: skill(Chillwater Bomblet DMG)
  - skillAtkDecrease: skill(ATK Decrease)
  - skillCoilNABonus:
      - skill(Coil Normal Attack DMG Bonus)
      - skill(Coil Normal Attack DMG Bonus|1)
      - skill(Coil Normal Attack DMG Bonus|2)
  - skillRushingIceNABonus: skill(Rushing Ice Normal Attack DMG Bonus)

  - burst: burst(Skill DMG)

docs:
  fields:
    .aloy.coil: Current number of coil stacks.
  frames:
    - count: https://docs.google.com/spreadsheets/d/11uyES6x6UFGm2bqcsY4dPSqLgsELrdkPv145NmMwTmc/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/mGnzKSsvq9s
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ?t=57
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/187T-SngEZUUordjY_K_tF_DdvHjQju9CoBJdp2eJOis/edit?usp=sharing
      count_credit: bowtae
      video: https://youtu.be/6wz4EZF-BmE
      video_credit: xsylent
    - count: https://docs.google.com/spreadsheets/d/187T-SngEZUUordjY_K_tF_DdvHjQju9CoBJdp2eJOis/edit?usp=sharing
      count_credit: bowtae
      video: https://youtu.be/HCeDppXuSyo
      video_credit: xsylent

abilities:
  - name: attack
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: N1-1
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N1-1-MaxCoil
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N1-2
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N1-2-MaxCoil
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N2
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N2-MaxCoil
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N3
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N3-MaxCoil
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N4
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N4-MaxCoil
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

  - name: aim
    params:
      hold: 0 for Physical Aimed Shot, 1 for Fully-Charged Aimed Shot (default).
      travel: Projectile travel time. Default 10 frames.
      weakspot: Hit weakspot with aimed shot. Default 0 (false), 1 for true.
    hitbox:
      - name: Aim
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: Aim-Head
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]
        hitlag: {time: 0.12, scale: 0.01, deployable: true}

      - name: FullAim
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: FullAim-Head
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]
        hitlag: {time: 0.12, scale: 0.01, deployable: true}

  - name: skill
    params:
      bomb_delay: Determines when Chillwater Bomblets start exploding after projectile hits. Default 0 frames.
      bomblets: Number of Chillwater Bomblets to spawn. Default 2 bomblets.
      travel: Projectile travel time. Default 5 frames.
    hitbox:
      - name: E-FreezeBomb
        shape: Circle
        center: PrimaryTarget
        radius: 4

      - name: E-ChillwaterBomblets
        note: Attacks spawn at same Target as E-FreezeBomb.
        shape: Circle
        center: GlobalValue
        radius: 2
        hitlag: {defense_halt: true, deployable: true}

  - name: burst
    hitbox:
      - name: Q-ElementalBurst
        shape: Circle
        center: Player
        offset: [0, 6.5]
        radius: 6.5

  - name: walk
    note: Only aim followed by walk has proper frames.
