id: 10000062
key: "aloy"
rarity: QUALITY_ORANGE_SP
body: BODY_GIRL
region: ASSOC_TYPE_RANGER
element: Ice
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Aloy"
stats: {
   base_hp: 848.4548
   base_atk: 18.21036
   base_def: 52.6504
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 727.47327
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 45.144
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 15.612596
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1244.3622
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 77.22
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 26.705757
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1933.5474
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 119.988
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 41.49664
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2450.4363
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 152.064
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 52.589798
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2967.3252
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 184.14
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.68296
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3484.214
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 216.216
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 74.77612
      }
      add_props: {
         prop_type: FIGHT_PROP_ICE_ADD_HURT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 10622
   burst: 10625
   attack: 10621
   burst_energy_cost: 40
}
name_text_hash_map: 3689108098
