// Code generated by "enumer -type=AttackTag"; DO NOT EDIT.

package attacks

import (
	"fmt"
	"strings"
)

const _AttackTagName = "AttackTagNoneAttackTagNormalAttackTagExtraAttackTagPlungeAttackTagElementalArtAttackTagElementalArtHoldAttackTagElementalBurstAttackTagWeaponSkillAttackTagMonaBubbleBreakAttackTagNoneStatReactionAttackStartDelimAttackTagOverloadDamageAttackTagSuperconductDamageAttackTagECDamageAttackTagShatterAttackTagSwirlPyroAttackTagSwirlHydroAttackTagSwirlCryoAttackTagSwirlElectroAttackTagBurningDamageAttackTagBloomAttackTagBountifulCoreAttackTagBurgeonAttackTagHyperbloomReactionAttackEndDelimLunarReactionStartDelimAttackTagReactionLunarChargeLunarReactionEndDelimDirectLunarReactionStartDelimAttackTagDirectLunarChargedAttackTagDirectLunarBloomDirectLunarReactionEndDelimAttackTagLength"

var _AttackTagIndex = [...]uint16{0, 13, 28, 42, 57, 78, 103, 126, 146, 170, 187, 211, 234, 261, 278, 294, 312, 331, 349, 370, 392, 406, 428, 444, 463, 485, 508, 536, 557, 586, 613, 638, 665, 680}

const _AttackTagLowerName = "attacktagnoneattacktagnormalattacktagextraattacktagplungeattacktagelementalartattacktagelementalartholdattacktagelementalburstattacktagweaponskillattacktagmonabubblebreakattacktagnonestatreactionattackstartdelimattacktagoverloaddamageattacktagsuperconductdamageattacktagecdamageattacktagshatterattacktagswirlpyroattacktagswirlhydroattacktagswirlcryoattacktagswirlelectroattacktagburningdamageattacktagbloomattacktagbountifulcoreattacktagburgeonattacktaghyperbloomreactionattackenddelimlunarreactionstartdelimattacktagreactionlunarchargelunarreactionenddelimdirectlunarreactionstartdelimattacktagdirectlunarchargedattacktagdirectlunarbloomdirectlunarreactionenddelimattacktaglength"

func (i AttackTag) String() string {
	if i < 0 || i >= AttackTag(len(_AttackTagIndex)-1) {
		return fmt.Sprintf("AttackTag(%d)", i)
	}
	return _AttackTagName[_AttackTagIndex[i]:_AttackTagIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AttackTagNoOp() {
	var x [1]struct{}
	_ = x[AttackTagNone-(0)]
	_ = x[AttackTagNormal-(1)]
	_ = x[AttackTagExtra-(2)]
	_ = x[AttackTagPlunge-(3)]
	_ = x[AttackTagElementalArt-(4)]
	_ = x[AttackTagElementalArtHold-(5)]
	_ = x[AttackTagElementalBurst-(6)]
	_ = x[AttackTagWeaponSkill-(7)]
	_ = x[AttackTagMonaBubbleBreak-(8)]
	_ = x[AttackTagNoneStat-(9)]
	_ = x[ReactionAttackStartDelim-(10)]
	_ = x[AttackTagOverloadDamage-(11)]
	_ = x[AttackTagSuperconductDamage-(12)]
	_ = x[AttackTagECDamage-(13)]
	_ = x[AttackTagShatter-(14)]
	_ = x[AttackTagSwirlPyro-(15)]
	_ = x[AttackTagSwirlHydro-(16)]
	_ = x[AttackTagSwirlCryo-(17)]
	_ = x[AttackTagSwirlElectro-(18)]
	_ = x[AttackTagBurningDamage-(19)]
	_ = x[AttackTagBloom-(20)]
	_ = x[AttackTagBountifulCore-(21)]
	_ = x[AttackTagBurgeon-(22)]
	_ = x[AttackTagHyperbloom-(23)]
	_ = x[ReactionAttackEndDelim-(24)]
	_ = x[LunarReactionStartDelim-(25)]
	_ = x[AttackTagReactionLunarCharge-(26)]
	_ = x[LunarReactionEndDelim-(27)]
	_ = x[DirectLunarReactionStartDelim-(28)]
	_ = x[AttackTagDirectLunarCharged-(29)]
	_ = x[AttackTagDirectLunarBloom-(30)]
	_ = x[DirectLunarReactionEndDelim-(31)]
	_ = x[AttackTagLength-(32)]
}

var _AttackTagValues = []AttackTag{AttackTagNone, AttackTagNormal, AttackTagExtra, AttackTagPlunge, AttackTagElementalArt, AttackTagElementalArtHold, AttackTagElementalBurst, AttackTagWeaponSkill, AttackTagMonaBubbleBreak, AttackTagNoneStat, ReactionAttackStartDelim, AttackTagOverloadDamage, AttackTagSuperconductDamage, AttackTagECDamage, AttackTagShatter, AttackTagSwirlPyro, AttackTagSwirlHydro, AttackTagSwirlCryo, AttackTagSwirlElectro, AttackTagBurningDamage, AttackTagBloom, AttackTagBountifulCore, AttackTagBurgeon, AttackTagHyperbloom, ReactionAttackEndDelim, LunarReactionStartDelim, AttackTagReactionLunarCharge, LunarReactionEndDelim, DirectLunarReactionStartDelim, AttackTagDirectLunarCharged, AttackTagDirectLunarBloom, DirectLunarReactionEndDelim, AttackTagLength}

var _AttackTagNameToValueMap = map[string]AttackTag{
	_AttackTagName[0:13]:         AttackTagNone,
	_AttackTagLowerName[0:13]:    AttackTagNone,
	_AttackTagName[13:28]:        AttackTagNormal,
	_AttackTagLowerName[13:28]:   AttackTagNormal,
	_AttackTagName[28:42]:        AttackTagExtra,
	_AttackTagLowerName[28:42]:   AttackTagExtra,
	_AttackTagName[42:57]:        AttackTagPlunge,
	_AttackTagLowerName[42:57]:   AttackTagPlunge,
	_AttackTagName[57:78]:        AttackTagElementalArt,
	_AttackTagLowerName[57:78]:   AttackTagElementalArt,
	_AttackTagName[78:103]:       AttackTagElementalArtHold,
	_AttackTagLowerName[78:103]:  AttackTagElementalArtHold,
	_AttackTagName[103:126]:      AttackTagElementalBurst,
	_AttackTagLowerName[103:126]: AttackTagElementalBurst,
	_AttackTagName[126:146]:      AttackTagWeaponSkill,
	_AttackTagLowerName[126:146]: AttackTagWeaponSkill,
	_AttackTagName[146:170]:      AttackTagMonaBubbleBreak,
	_AttackTagLowerName[146:170]: AttackTagMonaBubbleBreak,
	_AttackTagName[170:187]:      AttackTagNoneStat,
	_AttackTagLowerName[170:187]: AttackTagNoneStat,
	_AttackTagName[187:211]:      ReactionAttackStartDelim,
	_AttackTagLowerName[187:211]: ReactionAttackStartDelim,
	_AttackTagName[211:234]:      AttackTagOverloadDamage,
	_AttackTagLowerName[211:234]: AttackTagOverloadDamage,
	_AttackTagName[234:261]:      AttackTagSuperconductDamage,
	_AttackTagLowerName[234:261]: AttackTagSuperconductDamage,
	_AttackTagName[261:278]:      AttackTagECDamage,
	_AttackTagLowerName[261:278]: AttackTagECDamage,
	_AttackTagName[278:294]:      AttackTagShatter,
	_AttackTagLowerName[278:294]: AttackTagShatter,
	_AttackTagName[294:312]:      AttackTagSwirlPyro,
	_AttackTagLowerName[294:312]: AttackTagSwirlPyro,
	_AttackTagName[312:331]:      AttackTagSwirlHydro,
	_AttackTagLowerName[312:331]: AttackTagSwirlHydro,
	_AttackTagName[331:349]:      AttackTagSwirlCryo,
	_AttackTagLowerName[331:349]: AttackTagSwirlCryo,
	_AttackTagName[349:370]:      AttackTagSwirlElectro,
	_AttackTagLowerName[349:370]: AttackTagSwirlElectro,
	_AttackTagName[370:392]:      AttackTagBurningDamage,
	_AttackTagLowerName[370:392]: AttackTagBurningDamage,
	_AttackTagName[392:406]:      AttackTagBloom,
	_AttackTagLowerName[392:406]: AttackTagBloom,
	_AttackTagName[406:428]:      AttackTagBountifulCore,
	_AttackTagLowerName[406:428]: AttackTagBountifulCore,
	_AttackTagName[428:444]:      AttackTagBurgeon,
	_AttackTagLowerName[428:444]: AttackTagBurgeon,
	_AttackTagName[444:463]:      AttackTagHyperbloom,
	_AttackTagLowerName[444:463]: AttackTagHyperbloom,
	_AttackTagName[463:485]:      ReactionAttackEndDelim,
	_AttackTagLowerName[463:485]: ReactionAttackEndDelim,
	_AttackTagName[485:508]:      LunarReactionStartDelim,
	_AttackTagLowerName[485:508]: LunarReactionStartDelim,
	_AttackTagName[508:536]:      AttackTagReactionLunarCharge,
	_AttackTagLowerName[508:536]: AttackTagReactionLunarCharge,
	_AttackTagName[536:557]:      LunarReactionEndDelim,
	_AttackTagLowerName[536:557]: LunarReactionEndDelim,
	_AttackTagName[557:586]:      DirectLunarReactionStartDelim,
	_AttackTagLowerName[557:586]: DirectLunarReactionStartDelim,
	_AttackTagName[586:613]:      AttackTagDirectLunarCharged,
	_AttackTagLowerName[586:613]: AttackTagDirectLunarCharged,
	_AttackTagName[613:638]:      AttackTagDirectLunarBloom,
	_AttackTagLowerName[613:638]: AttackTagDirectLunarBloom,
	_AttackTagName[638:665]:      DirectLunarReactionEndDelim,
	_AttackTagLowerName[638:665]: DirectLunarReactionEndDelim,
	_AttackTagName[665:680]:      AttackTagLength,
	_AttackTagLowerName[665:680]: AttackTagLength,
}

var _AttackTagNames = []string{
	_AttackTagName[0:13],
	_AttackTagName[13:28],
	_AttackTagName[28:42],
	_AttackTagName[42:57],
	_AttackTagName[57:78],
	_AttackTagName[78:103],
	_AttackTagName[103:126],
	_AttackTagName[126:146],
	_AttackTagName[146:170],
	_AttackTagName[170:187],
	_AttackTagName[187:211],
	_AttackTagName[211:234],
	_AttackTagName[234:261],
	_AttackTagName[261:278],
	_AttackTagName[278:294],
	_AttackTagName[294:312],
	_AttackTagName[312:331],
	_AttackTagName[331:349],
	_AttackTagName[349:370],
	_AttackTagName[370:392],
	_AttackTagName[392:406],
	_AttackTagName[406:428],
	_AttackTagName[428:444],
	_AttackTagName[444:463],
	_AttackTagName[463:485],
	_AttackTagName[485:508],
	_AttackTagName[508:536],
	_AttackTagName[536:557],
	_AttackTagName[557:586],
	_AttackTagName[586:613],
	_AttackTagName[613:638],
	_AttackTagName[638:665],
	_AttackTagName[665:680],
}

// AttackTagString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AttackTagString(s string) (AttackTag, error) {
	if val, ok := _AttackTagNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AttackTagNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AttackTag values", s)
}

// AttackTagValues returns all values of the enum
func AttackTagValues() []AttackTag {
	return _AttackTagValues
}

// AttackTagStrings returns a slice of all String values of the enum
func AttackTagStrings() []string {
	strs := make([]string, len(_AttackTagNames))
	copy(strs, _AttackTagNames)
	return strs
}

// IsAAttackTag returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AttackTag) IsAAttackTag() bool {
	for _, v := range _AttackTagValues {
		if i == v {
			return true
		}
	}
	return false
}
