package_name: ineffa
genshin_id: 10000116
key: ineffa
skill_data_mapping:
    attack: # Cyclonic Duster
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
            - 3 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
        attack_4:
            - 4 # 4-Hit DMG|{param4:F1P}
        charge:
            - 5 # Charged Attack DMG|{param5:F1P}
        collision:
            - 7 # Plunge DMG|{param7:F1P}
        lowPlunge:
            - 8 # Low/High Plunge DMG|{param8:P}/{param9:P}
        highPlunge:
            - 9 # Low/High Plunge DMG|{param8:P}/{param9:P}
    skill: # Cleaning Mode: Carrier Frequency
        skillInitial:
            - 0 # Skill DMG|{param0:F1P}
        skillShieldAtk:
            - 1 # Shield DMG Absorption|{param1:F1P} ATK+{param2:I}
        skillShieldSFat:
            - 2 # Shield DMG Absorption|{param1:F1P} ATK+{param2:I}
            - 5 # Shield Duration|{param5:F1}s
        skillDoT:
            - 3 # Birgitta Discharge DMG|{param3:F1P}
    burst: # Supreme Instruction: Cyclonic Exterminator
        burstDMG:
            - 0 # Skill DMG|{param0:F1P}
