use: pipeline
kind: character
name: ineffa

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG|1)
      - attack(4-Hit DMG)
  - charge: attack(Charged Attack DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skillInitial: skill(Skill DMG)
  - shieldAtk: skill(Shield DMG Absorption)
  - shieldFlat: skill(Shield DMG Absorption|1)
  - skillDoT: skill(Birgitta Discharge DMG)

  - burst: burst(Skill DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/15hb6buvXkYlTeK8DJijWUFnTk5IWcz4zJEepKUkoxBw/edit?usp=sharing
      count_credit: caramielle.
      video: https://youtu.be/CDebpIOF3t0
      video_credit: caramielle.
    - count: https://docs.google.com/spreadsheets/d/15hb6buvXkYlTeK8DJijWUFnTk5IWcz4zJEepKUkoxBw/edit?usp=sharing
      count_credit: caramielle.
      video: https://youtu.be/jJ6RySx3HFA
      video_credit: caramielle.

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.3]
        radius: 1.6
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 1.6
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N3-1
        shape: Box
        center: Player
        offset: [0, 0.2]
        box: [2.8, 2]

      - name: N3-2
        shape: Box
        center: Player
        offset: [0, -0.2]
        box: [2.8, 2]
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Box
        center: Player
        offset: [0, 0.5]
        box: [2.4, 4]
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        offset: [0, 0.5]
        radius: 2.35
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

  - name: skill
    hitbox:
      - name: E-Summon
        shape: Circle
        center: Player
        radius: 3.5

      - name: E-Discharge
        shape: Circle
        center: PrimaryTarget
        radius: 4

  - name: burst
    hitbox:
      - name: Q-ElementalBurst
        shape: Circle
        center: Player
        radius: 6

  - name: asc
    hitbox:
      - name: A1
        shape: Circle
        center: PrimaryTarget
        radius: 4

  - name: cons
    hitbox:
      - name: C2
        shape: Circle
        center: PrimaryTarget
        radius: 6

      - name: C6
        shape: Circle
        center: Player
        radius: 3
