use: pipeline
kind: weapon
name: snowtombedstarsilver

shortcuts:
  - snowtombed
  - starsilver

abilities:
  - name: default
    hitbox:
      - name: Snow-Tombed Starsilver
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 3
