use: pipeline
kind: character
name: sayu

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG)
      - attack(4-Hit DMG)

  - skillPress: skill(Fuufuu Windwheel DMG)
  - skillAbsorb: skill(Fuufuu Windwheel Elemental DMG)
  - skillPressEnd: skill(Fuufuu Whirlwind Kick Press DMG)
  - skillHoldEnd: skill(Fuufuu Whirlwind Kick Hold DMG)
  - skillAbsorbEnd: skill(Fuufuu Whirlwind Kick Elemental DMG)

  - burst: burst(Skill Activation DMG)
  - initHealFlat: burst(Skill Activation Healing|1)
  - initHealPP: burst(Skill Activation Healing)
  - burstSkill: burst(Muji-Muji Daruma DMG)
  - burstHealFlat: burst(Muji-Muji Daruma Healing|1)
  - burstHealPP: burst(Muji-Muji Daruma Healing)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1vLH6ZiAhb7G-f5ecYy-sPLoCdouA5krMixtgh9ITX2Q/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/w7YDOFDuVC0
      video_credit: Kolibri#7675

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Box
        center: Player
        offset: [0, -0.7]
        box: [2.5, 3.2]
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 2
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

      - name: N3-1
        shape: Box
        center: Player
        offset: [0, -1]
        box: [2.5, 3.5]

      - name: N3-2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 2
        hitlag: {time: 0.08, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Box
        center: Player
        offset: [0, -2]
        box: [2.8, 4.5]
        hitlag: {time: 0.08, scale: 0.01, defense_halt: true}

  - name: charge
    hitbox:
      - name: CA-Spinning
        note: not implemented yet
        shape: Circle
        center: Player
        offset: [0, 0.3]
        radius: 2.8
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true, deployable: true}

      - name: CA-Final
        note: not implemented yet
        shape: Circle
        center: Player
        radius: 3.3
        hitlag: {time: 0.15, scale: 0.01, defense_halt: true, deployable: true}

  - name: skill
    params:
      hold: 0 for Tap (default), value between 1 and 600 for Hold. The number determines the E duration in frames.
      short_hold: 0 for Tap (default), 1 for Short Hold. The Short Hold version is the shortest possible Hold.
    hitbox:
      - name: E-Tap-Kick
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 2.5
        hitlag: {time: 0.02, scale: 0.05}

      - name: E-Hold-Rolling
        note: Rolling mechanics (collision) are not properly implemented yet.
        shape: Circle
        center: Player
        radius: 3
        hitlag: {time: 0.01, scale: 0.05, deployable: true}

      - name: E-Hold-AdditionalElement
        note: Spawns on all enemies hit by E-Hold-Rolling.
        shape: Single
        center: GlobalValue

      - name: E-Hold-Kick
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 3
        hitlag: {time: 0.02, scale: 0.05}

      - name: E-AbsorbCheck
        shape: Circle
        center: Player
        radius: 1.2

  - name: burst
    hitbox:
      - name: Q-Initial
        note: Q has a detection area of 10m around the position of this hitbox.
        shape: Circle
        center: Player
        offset: [0, 1.5]
        radius: 4.5
        hitlag: {time: 0.02, scale: 0.05}

      - name: Q-DoT-PreA4
        note: Spawns at the Q-Initial position.
        shape: Circle
        center: GlobalValue
        radius: 1

      - name: Q-DoT-PostA4
        shape: Circle
        center: GlobalValue
        radius: 3.5

  - name: walk
    note: No action followed by walk has proper frames.
