id: 10000053
key: "sayu"
rarity: QUALITY_PURPLE
body: BODY_LOLI
region: ASSOC_TYPE_INAZUMA
element: Wind
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Sayu"
stats: {
   base_hp: 993.8522
   base_atk: 20.4792
   base_def: 62.432476
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 742.4585
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 46.64025
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 15.29937
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1269.9948
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 79.77937
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 26.169975
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 24
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1973.3765
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 123.964874
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.664116
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2500.9128
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 157.104
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 51.53472
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3028.449
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 190.24312
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 62.405327
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 72
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3555.9854
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 223.38225
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 73.27593
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 96
      }
   }
}
skill_details: {
   skill: 10532
   burst: 10535
   attack: 10531
   burst_energy_cost: 80
}
name_text_hash_map: 2388785242
