id: 10000044
key: "xinyan"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_LIYUE
element: Fire
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Xinyan"
stats: {
   base_hp: 939.1447
   base_atk: 20.83536
   base_def: 66.95325
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 701.5892
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 50.0175
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 15.565446
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1200.0868
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 85.55625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 26.625105
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1864.7502
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 132.94125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 41.37132
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2363.2478
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 168.48
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 52.430977
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2861.7454
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 204.01875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.490635
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3360.243
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 239.5575
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 74.55029
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10442
   burst: 10443
   attack: 10441
   burst_energy_cost: 60
}
name_text_hash_map: 4273845410
