package_name: xinyan
genshin_id: 10000044
key: xinyan
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
    skill:
        shieldLevel1:
            - 1 # Shield Level 1 DMG Absorption|{param1:F1P} DEF+{param2:I}
        shieldLevel1Flat:
            - 2 # Shield Level 1 DMG Absorption|{param1:F1P} DEF+{param2:I}
        shieldLevel2:
            - 3 # Shield Level 2 DMG Absorption|{param3:F1P} DEF+{param4:I}
        shieldLevel2Flat:
            - 4 # Shield Level 2 DMG Absorption|{param3:F1P} DEF+{param4:I}
        shieldLevel3:
            - 5 # Shield Level 3 DMG Absorption|{param5:F1P} DEF+{param6:I}
        shieldLevel3Flat:
            - 6 # Shield Level 3 DMG Absorption|{param5:F1P} DEF+{param6:I}
        skill:
            - 0 # Swing DMG|{param0:P}
        skillDot:
            - 7 # DoT|{param7:F1P}
    burst:
        burstDmg:
            - 0 # Skill DMG|{param0:P}
        burstDot:
            - 1 # Pyro DoT|{param1:P}
