use: pipeline
kind: character
name: aetherhydro

override:
  id: 10000005
  depot: 503

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1_a0KTCdTkvITCoHvLzOzFbcRm1wMtDaHt7zFU9h2aPQ/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/MOyhu5YxeWA
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1_a0KTCdTkvITCoHvLzOzFbcRm1wMtDaHt7zFU9h2aPQ/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/uwnKGID7vSI
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1bvtaF1vt95lRQHxvnOL5jLbKMR683s_eHxx-q91q0Nk/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/3_RxI2hK1l4
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1bvtaF1vt95lRQHxvnOL5jLbKMR683s_eHxx-q91q0Nk/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/tERohQyDgmQ
      video_credit: Kolibri#7675

abilities:
  - name: default
    params:
      base_atk_buff: 0 for no +3 base atk, 1 (default) for +3 base atk. Set via '+params=[base_atk_buff=...]' in the char's line.
      skirk_story_buff: 0 for no buffs, 1 (default) for +7 base atk, +15 EM, +50 base HP. Set via '+params=[skirk_story_buff=...]' in the char's line.

  - name: attack
    hitbox:
      - name: Aether-N1
        shape: Box
        center: Player
        box: [1.4, 2.2]

      - name: Aether-N2
        shape: Circle
        center: Player
        offset: [0, 0.6]
        fan_angle: 180
        radius: 1.7

      - name: Aether-N3
        shape: Box
        center: Player
        offset: [0, 0.4]
        box: [1.5, 2.2]

      - name: Aether-N4
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.7

      - name: Aether-N5
        shape: Circle
        center: Player
        offset: [0, 0.6]
        fan_angle: 240
        radius: 1.75

      - name: Lumine-N1
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1.6

      - name: Lumine-N2
        shape: Box
        center: Player
        box: [1.4, 2.2]

      - name: Lumine-N3
        shape: Circle
        center: Player
        offset: [0, 0.7]
        radius: 1.5

      - name: Lumine-N4
        shape: Circle
        center: Player
        offset: [0, 0.7]
        radius: 1.5

      - name: Lumine-N5
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1.6

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA-1
        shape: Circle
        center: Player
        radius: 2.2

      - name: CA-2
        shape: Circle
        center: Player
        radius: 2.2

  - name: skill
    params:
      hold: 0 for Tap (default), 1 for Hold.
      hold_ticks: Number of ticks for Hold E. Default 22, maximum 22, minimum 0. Only works if hold = 1. If 0, then a shorter version of Tap will be performed.
      travel: Projectile travel time. Default 6 frames. Only works if hold = 1.
    hitbox:
      - name: E-TorrentSurge
        shape: Box
        center: Player
        box: [1.2, 15]

      - name: E-Aligned
        shape: Box
        center: Player
        box: [1.2, 15]

      - name: E-Dewdrop
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.4]
        box: [0.3, 1.3]

  - name: burst
    hitbox:
      - name: Q
        note: Starts at Traveler position + 0.5m in that direction and moves at 1.5m (or 1.05m if Traveler C2+) per attack.
        shape: Circle
        center: GlobalValue
        radius: 0.15

  - name: dash
    params:
      pickup_droplets: Number of picked up Sourcewater Droplets. Default 0.

  - name: walk
    note: Only skill and burst followed by walk have proper frames.
