// Code generated by "pipeline"; DO NOT EDIT.

// passive: Golden Majesty # Weapon_Pole_Kunwu_DamageUpWithShield
//
//	Increases Shield Strength by 20%. Scoring hits on opponents increases ATK by 4% for
//	8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this
//	ATK increase effect is increased by 100%.
package vortex

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.VortexVanquisher, NewWeapon)
}
