// Code generated by "pipeline"; DO NOT EDIT.

// passive: Composed # Weapon_Catalyst_ResetCDWhenSkillHit
//
//	After damaging an opponent with an Elemental Skill, the skill has a 40% chance to
//	end its own CD. Can only occur once every 30s.
package sacrificial

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.SacrificialFragments, NewWeapon)
}
