id: 10000042
key: "keqing"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_LIYUE
element: Electric
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Keqing"
stats: {
   base_hp: 1020.0524
   base_atk: 25.137
   base_def: 62.2232
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 874.6027
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 53.352
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.55113
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1496.0309
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 91.26
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 36.863773
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2324.6018
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 141.804
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 57.280636
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2946.03
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 179.712
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 72.59328
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3567.4585
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 217.62
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 87.90592
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4188.8867
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 255.528
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 103.21857
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 10422
   burst: 10425
   attack: 10421
   burst_energy_cost: 40
}
name_text_hash_map: 1864015138
