use: pipeline
kind: character
name: keqing

shortcuts:
  - keq

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - - attack(4-Hit DMG)
        - attack(4-Hit DMG|1)
      - attack(5-Hit DMG)
  - charge:
      - attack(Charged Attack DMG)
      - attack(Charged Attack DMG|1)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skill: skill(Lightning Stiletto DMG)
  - skillPress: skill(Slashing DMG)
  - skillCA: skill(Thunderclap Slash DMG)

  - burstInitial: burst(Skill DMG)
  - burstDot: burst(Consecutive Slash DMG)
  - burstFinal: burst(Last Attack DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1GAeBzMr0XX89azZhpbjEqPfehgruwI3__GlfEgQ1VvA/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/kI6N3Mn5BQY
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1GAeBzMr0XX89azZhpbjEqPfehgruwI3__GlfEgQ1VvA/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/9xe2nygCtKE
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1GAeBzMr0XX89azZhpbjEqPfehgruwI3__GlfEgQ1VvA/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/bcmpBDTSBgI
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ?t=842
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1ltsZEP0Z6bUlBzhuysmsDP8V_6wU5uwTR94OYXgJ0Tw/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/UhHgaq8dgB4
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: charliex3000
      video: https://youtu.be/5py8uefL3eM
      video_credit: charliex3000

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Box
        center: Player
        box: [1.5, 2.2]
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 1.5
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1.8
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4-1
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.5

      - name: N4-2
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.5
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N5-Target
        shape: Circle
        center: PrimaryTarget
        radius: 0.8

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA-1
        shape: Circle
        center: Player
        offset: [0, 1.5]
        radius: 2.2

      - name: CA-2
        shape: Circle
        center: Player
        offset: [0, 1.8]
        radius: 2.3

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    hitbox:
      - name: E-LightningStiletto
        shape: Circle
        center: PrimaryTarget
        radius: 1.6

      - name: E-Slashing
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3
        hitlag: {time: 0.09, scale: 0.01}

      - name: E-ThunderclapSlash-1
        shape: Circle
        center: Player
        radius: 2.5

      - name: E-ThunderclapSlash-2
        shape: Circle
        center: Player
        radius: 2.5

  - name: burst
    hitbox:
      - name: Q
        shape: Circle
        center: Player
        radius: 8

  - name: cons
    hitbox:
      - name: E-C1-Start
        shape: Circle
        center: Player
        radius: 2

      - name: E-C1-Terminus
        shape: Circle
        center: PrimaryTarget
        offset: [0, 1.5]
        radius: 2

  - name: walk
    note: No action followed by walk (except low_plunge and high_plunge) has proper frames.
