name: "build compute binary"
descripition: "build compute binary; assume go has already been setup"
inputs:
  cmd:
    required: true
    description: "cmd to build"
runs:
  using: composite
  steps:
  - name: build binary
    working-directory: ./backend/cmd/${{ inputs.cmd }}
    shell: bash
    run: "GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build"