use: pipeline
kind: character
name: gorou

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - aim: attack(Aimed Shot)
  - fullaim: attack(Fully-Charged Aimed Shot)

  - skill: skill(Skill DMG)
  - skillDefBonus: skill(DEF Increase)

  - burst: burst(Skill DMG)
  - burstTick: burst(Crystal Collapse DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/15eKpg9ii86ufny24TEZgzWT0xQbzmIfMUCA2fktuaB4/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/pOJnyO91pQ8
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/187T-SngEZUUordjY_K_tF_DdvHjQju9CoBJdp2eJOis/edit?usp=sharing
      count_credit: bowtae
      video: https://youtu.be/iatlnvs614U
      video_credit: bowtae
    - count: https://docs.google.com/spreadsheets/d/187T-SngEZUUordjY_K_tF_DdvHjQju9CoBJdp2eJOis/edit?usp=sharing
      count_credit: bowtae
      video: https://youtu.be/xk17X0k2_V8
      video_credit: bowtae

abilities:
  - name: attack
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: N1
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N2
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N3
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N4
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N5
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

  - name: aim
    params:
      hold: 0 for Physical Aimed Shot, 1 for Fully-Charged Aimed Shot (default).
      travel: Projectile travel time. Default 10 frames.
      weakspot: Hit weakspot with aimed shot. Default 0 (false), 1 for true.
    hitbox:
      - name: Aim
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: Aim-Head
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]
        hitlag: {time: 0.12, scale: 0.01, deployable: true}

      - name: FullAim
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: FullAim-Head
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]
        hitlag: {time: 0.12, scale: 0.01, deployable: true}

  - name: skill
    hitbox:
      - name: E
        note: E has a detection area of 8m around the position of this hitbox.
        shape: Circle
        center: Player
        offset: [0, 2]
        radius: 5

  - name: burst
    hitbox:
      - name: Q-ElementalBurst
        shape: Circle
        center: Player
        radius: 5

      - name: Q-CrystalCollapse
        note: Spawns on enemy within 8m of Player.
        shape: Circle
        center: GlobalValue
        radius: 3.5

  - name: walk
    note: Only aim followed by walk has proper frames.
