id: 10000055
key: "gorou"
rarity: QUALITY_PURPLE
body: BODY_BOY
region: ASSOC_TYPE_INAZUMA
element: Rock
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Gorou"
stats: {
   base_hp: 802.3761
   base_atk: 15.31488
   base_def: 54.36375
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 599.416
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 40.6125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 11.441268
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1025.3169
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 69.46875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 19.57059
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1593.1847
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 107.94375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 30.409685
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2019.0856
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 136.8
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 38.53901
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2444.9863
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 165.65625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 46.66833
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2870.8872
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 194.5125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 54.797653
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10552
   burst: 10555
   attack: 10551
   burst_energy_cost: 80
}
name_text_hash_map: 3400133546
