name = "handlerone-worker"
main = "dist/worker.js"
compatibility_date = "2022-07-21"

account_id = "52a49c744e9fc667b27f32d5d9c746e1"

[build]
command = "npm install && npm run build"


[[kv_namespaces]]
  binding = "USER_TOKENS"
  id = "bed7ee6af0bf4242a031a0c839e5915f"
  preview_id = "bed7ee6af0bf4242a031a0c839e5915f"

[[r2_buckets]]
  binding = 'GCSIM_ASSETS'
  bucket_name = 'gcsim'