use: pipeline
kind: character
name: iansan

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
  - charge: attack(Charged Attack DMG)
  - swift: attack(Swift Stormflight DMG)

  - skill: skill(Skill DMG)

  - burst: burst(Skill DMG)
  - highATK: burst(High Nightsoul Points ATK Conversion Rate)
  - lowATK: burst(Low Nightsoul Points ATK Conversion Rate)
  - maxATK: burst(Max ATK Bonus)
