package_name: iansan
genshin_id: 10000110
key: iansan
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param1:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param2:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param3:F1P}
        charged:
            - 3 # Charged Attack DMG|{param4:F1P}
        swift:
            - 4 # Swift Stormflight DMG|{param5:F1P}
    skill:
        skill:
            - 0 # Skill DMG|{param1:F1P}
    burst:
        burst:
            - 0 # Skill DMG|{param1:F1P}
        highATK:
            - 1 # High Nightsoul Points ATK Conversion Rate|{param2:P} ATK
        lowATK:
            - 2 # Low Nightsoul Points ATK Conversion Rate|{param3:F1P} ATK / Nightsoul Point
        maxATK:
            - 3 # Max ATK Bonus|{param4:F1}
