// Code generated by "pipeline"; DO NOT EDIT.
package iansan

import (
	_ "embed"

	"github.com/genshinsim/gcsim/pkg/model"
	"google.golang.org/protobuf/encoding/prototext"
)

//go:embed data_gen.textproto
var pbData []byte
var base *model.AvatarData

func init() {
	base = &model.AvatarData{}
	err := prototext.Unmarshal(pbData, base)
	if err != nil {
		panic(err)
	}
}

func (x *char) Data() *model.AvatarData {
	return base
}

var (
	attack = [][]float64{
		attack_1,
		attack_2,
		attack_3,
	}
)

var (
	// attack: attack_1 = [0]
	attack_1 = []float64{
		0.469758,
		0.507994,
		0.54623,
		0.600853,
		0.639089,
		0.682787,
		0.742873,
		0.802958,
		0.863043,
		0.928591,
		0.994139,
		1.059686,
		1.125234,
		1.190781,
		1.256329,
	}
	// attack: attack_2 = [1]
	attack_2 = []float64{
		0.427644,
		0.462452,
		0.49726,
		0.546986,
		0.581794,
		0.621575,
		0.676274,
		0.730972,
		0.785671,
		0.845342,
		0.905013,
		0.964684,
		1.024356,
		1.084027,
		1.143698,
	}
	// attack: attack_3 = [2]
	attack_3 = []float64{
		0.643882,
		0.696291,
		0.7487,
		0.82357,
		0.875979,
		0.935875,
		1.018232,
		1.100589,
		1.182946,
		1.27279,
		1.362634,
		1.452478,
		1.542322,
		1.632166,
		1.72201,
	}
	// attack: charged = [3]
	charged = []float64{
		1.00276,
		1.08438,
		1.166,
		1.2826,
		1.36422,
		1.4575,
		1.58576,
		1.71402,
		1.84228,
		1.9822,
		2.12212,
		2.26204,
		2.40196,
		2.54188,
		2.6818,
	}
	// attack: swift = [4]
	swift = []float64{
		0.84194,
		0.91047,
		0.979,
		1.0769,
		1.14543,
		1.22375,
		1.33144,
		1.43913,
		1.54682,
		1.6643,
		1.78178,
		1.89926,
		2.01674,
		2.13422,
		2.2517,
	}
	// skill: skill = [0]
	skill = []float64{
		2.864,
		3.0788,
		3.2936,
		3.58,
		3.7948,
		4.0096,
		4.296,
		4.5824,
		4.8688,
		5.1552,
		5.4416,
		5.728,
		6.086,
		6.444,
		6.802,
	}
	// burst: burst = [0]
	burst = []float64{
		4.304,
		4.6268,
		4.9496,
		5.38,
		5.7028,
		6.0256,
		6.456,
		6.8864,
		7.3168,
		7.7472,
		8.1776,
		8.608,
		9.146,
		9.684,
		10.222,
	}
	// burst: highATK = [1]
	highATK = []float64{
		0.27,
		0.27,
		0.27,
		0.27,
		0.27,
		0.27,
		0.27,
		0.27,
		0.27,
		0.27,
		0.27,
		0.27,
		0.27,
		0.27,
		0.27,
	}
	// burst: lowATK = [2]
	lowATK = []float64{
		0.005,
		0.005,
		0.005,
		0.005,
		0.005,
		0.005,
		0.005,
		0.005,
		0.005,
		0.005,
		0.005,
		0.005,
		0.005,
		0.005,
		0.005,
	}
	// burst: maxATK = [3]
	maxATK = []float64{
		330,
		370,
		410,
		450,
		490,
		530,
		570,
		610,
		650,
		690,
		730,
		770,
		810,
		850,
		890,
	}
)
