// Code generated by "pipeline"; DO NOT EDIT.

// passive: Cull the Weak # Weapon_Bow_HealAmountHPonEnemyKilled
//
//	Defeating an opponent restores 8% HP.
package recurve

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.RecurveBow, NewWeapon)
}
