package_name: mavuika
genshin_id: 10000106
key: mavuika
icd_tags:
    - ICDTagMavuikaFlamestrider
action_param_keys:
    skill:
        - param: "hold"
        - param: "recast"
    low_plunge:
        - param: "collision"
    high_plunge:
        - param: "collision"
    charge:
        - param: "hold"
        - param: "final"
        - param: "buffered"
skill_data_mapping:
    attack: # Normal Attack: Flames Weave Life
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}×2
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}×3
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        charge:
            - 4 # Charged Attack Final DMG|{param4:P}
        collision:
            - 6 # Plunge DMG|{param6:F1P}
        lowPlunge:
            - 7 # Low/High Plunge DMG|{param7:P}/{param8:P}
        highPlunge:
            - 8 # Low/High Plunge DMG|{param7:P}/{param8:P}
    skill: # The Named Moment
        skill:
            - 0 # Activation DMG|{param0:F1P}
        skillRing:
            - 1 # Remote Weapon Interval DMG|{param1:F1P}
        skillAttack_1:
            - 3 # Motorcycle Normal Attack 1-Hit DMG|{param3:F1P}
        skillAttack_2:
            - 4 # Motorcycle Normal Attack 2-Hit DMG|{param4:F1P}
        skillAttack_3:
            - 5 # Motorcycle Normal Attack 3-Hit DMG|{param5:F1P}
        skillAttack_4:
            - 6 # Motorcycle Normal Attack 4-Hit DMG|{param6:F1P}
        skillAttack_5:
            - 7 # Motorcycle Normal Attack 5-Hit DMG|{param7:F1P}
        skillDash:
            - 8 # Motorcycle Sprint DMG|{param8:F1P}
        skillCharge:
            - 9 # Motorcycle Charged Attack Cyclic DMG|{param9:F1P}
        skillChargeFinal:
            - 10 # Motorcycle Charged Attack Final DMG|{param10:F1P}
        skillPlunge:
            - 11 # Motorcycle Plunge DMG|{param11:F1P}
    burst: # Hour of Burning Skies
        burst:
            - 0 # Explosion DMG|{param0:F1P}
        burstQBonus:
            - 2 # Burst DMG Bonus|{param2:F1P} ATK per War God Energy Point
        burstNABonus:
            - 3 # Motorcycle Normal Attack Bonus|{param3:F2P} ATK per War God Energy Point
        burstCABonus:
            - 4 # Motorcycle Charged Attack Bonus|{param4:F2P} ATK per War God Energy Point
