id: 10000106
key: "mavuika"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_NATLAN
element: Fire
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Mavuika"
stats: {
   base_hp: 977.153
   base_atk: 27.93
   base_def: 61.6249
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 837.8203
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 52.839
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.9457
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1433.1138
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 90.3825
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.95975
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2226.8384
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 140.4405
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.64515
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2822.1316
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 177.984
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 80.6592
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3417.425
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 215.5275
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 97.67325
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4012.7185
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 253.071
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 114.6873
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 11062
   burst: 11065
   attack: 11061
}
name_text_hash_map: 113398050
