use: pipeline
kind: character
name: kamisatoayato

shortcuts:
  - ayato

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - - attack(4-Hit DMG)
        - attack(4-Hit DMG)
      - attack(5-Hit DMG)
  - ca: attack(Charged Attack DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - shunsuiken:
      - skill(Shunsuiken 1-Hit DMG)
      - skill(Shunsuiken 2-Hit DMG)
      - skill(Shunsuiken 3-Hit DMG)
  - skillpp: skill(Namisen DMG Bonus)
  - skill: skill(Water Illusion DMG)

  - burst: burst(Bloomwater Blade DMG)
  - burstatkp: burst(Normal Attack DMG Bonus)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1VL6nQvehIj8wTFC6ACC88p3i8lGUZnZV8Lx0G1dZp88/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/NNBdbP4Rn28
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1VL6nQvehIj8wTFC6ACC88p3i8lGUZnZV8Lx0G1dZp88/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/AL2qAaaIvhs
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1VL6nQvehIj8wTFC6ACC88p3i8lGUZnZV8Lx0G1dZp88/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/m0ABsEc-Gaw
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ?t=183
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: kolibri._.
      video: https://youtu.be/Z04xXOTFrCs
      video_credit: kolibri._.

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.7
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 1.7
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Box
        center: Player
        offset: [0, 0.3]
        box: [1.6, 2.8]
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4-1
        shape: Box
        center: Player
        offset: [0, -0.2]
        box: [2, 2.6]

      - name: N4-2
        shape: Box
        center: Player
        offset: [0, -0.2]
        box: [2, 2.6]

      - name: N5
        shape: Box
        center: Player
        offset: [0, 0.6]
        box: [6, 2]
        hitlag: {time: 0.08, scale: 0.01, defense_halt: true}

      - name: E-N1
        shape: Box
        center: Player
        box: [8, 7]
        hitlag: {time: 0.03, scale: 0.01}

      - name: E-N2
        shape: Box
        center: Player
        box: [8, 7]
        hitlag: {time: 0.03, scale: 0.01}

      - name: E-N3
        shape: Box
        center: Player
        box: [8, 7]
        hitlag: {time: 0.03, scale: 0.01}

  - name: charge
    note: Not available in skill state. Need to use attack right before charge.
    hitbox:
      - name: CA-Target
        shape: Circle
        center: PrimaryTarget
        radius: 0.8

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example. Cannot be used while in skill state.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example. Cannot be used while in skill state.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    params:
      illusion_delay: Illusion explosion delay in frames. Default 35 frames.
    hitbox:
      - name: E-WaterIllusion
        note: Spawns at the position Player was at when E was used.
        shape: Circle
        center: GlobalValue
        radius: 3.5

  - name: burst
    hitbox:
      - name: Q-BloomwaterBlade
        note: 'Q has a detection area of 10m around the position of Player when Q was used. At every tick: If there are enemies within the Q detection area that are not currently marked, then it spawns at a random enemy out of those. This random enemy is then marked for 1.45s. Otherwise, it will spawn randomly between 1.5m and 9.5m from the Q center.'
        shape: Circle
        center: GlobalValue
        radius: 2.5

  - name: cons
    hitbox:
      - name: C6-Hit-1
        shape: Box
        center: Player
        box: [8, 7]
        hitlag: {time: 0.03, scale: 0.01, deployable: true}

      - name: C6-Hit-2
        shape: Box
        center: Player
        box: [8, 7]
        hitlag: {time: 0.03, scale: 0.01, deployable: true}

  - name: walk
    note: No action followed by walk (except low_plunge and high_plunge) has proper frames.
