package_name: ayato
genshin_id: 10000066
key: ayato
action_param_keys:
    skill: 
        - param: "illusion_delay"
    low_plunge:
        - param: "collision"
    high_plunge:
        - param: "collision"
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}×2
            - 3 # 4-Hit DMG|{param3:F1P}×2
        attack_5:
            - 4 # 5-Hit DMG|{param4:F1P}
        ca:
            - 5 # Charged Attack DMG|{param5:F1P}
        collision:
            - 7 # Plunge DMG|{param6:F1P}
        lowPlunge:
            - 8 # Low/High Plunge DMG|{param7:P}/{param8:P}
        highPlunge:
            - 9 # Low/High Plunge DMG|{param7:P}/{param8:P}
    skill:
        shunsuiken:
            - 0 # Shunsuiken 1-Hit DMG|{param0:F1P}
            - 1 # Shunsuiken 2-Hit DMG|{param1:F1P}
            - 2 # Shunsuiken 3-Hit DMG|{param2:F1P}
        skill:
            - 5 # Water Illusion DMG|{param5:F1P}
        skillpp:
            - 4 # Namisen DMG Bonus|{param4:F2P}Max HP/Stack
    burst:
        burst:
            - 0 # Bloomwater Blade DMG|{param0:F1P}
        burstatkp:
            - 1 # Normal Attack DMG Bonus|{param1:F1P}
