id: 10000066
key: "ayato"
rarity: QUALITY_ORANGE
body: BODY_MALE
region: ASSOC_TYPE_INAZUMA
element: Water
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Ayato"
stats: {
   base_hp: 1067.7184
   base_atk: 23.275
   base_def: 59.83
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 915.472
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 51.3
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 19.95475
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1565.939
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 87.75
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 34.133125
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2433.2283
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 136.35
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 53.037624
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3083.695
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 172.8
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 67.216
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3734.162
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 209.25
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 81.39438
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4384.629
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 245.7
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 95.57275
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 10662
   burst: 10665
   attack: 10661
   burst_energy_cost: 80
}
name_text_hash_map: 1588620330
