use: pipeline
kind: weapon
name: skywardharp

shortcuts:
  - harp

abilities:
  - name: default
    hitbox:
      - name: Skyward Harp
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 3
