// Code generated by "pipeline"; DO NOT EDIT.

// passive: Echoing Ballad # Weapon_Bow_RangeAttackOnAttackLanded
//
//	Increases CRIT DMG by 20%. Hits have a 60% chance to inflict a small AoE attack,
//	dealing 125% Physical ATK DMG. Can only occur once every 4s.
package skyward

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.SkywardHarp, NewWeapon)
}
