use: pipeline
kind: weapon
name: kagotsurubeisshin

shortcuts:
  - isshin

abilities:
  - name: default
    hitbox:
      - name: Kagotsurube Isshin
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 3
