// Code generated by "pipeline"; DO NOT EDIT.

// passive: Smoke-and-Mirror Mystery # Weapon_Sword_Isikhulu
//
//	Using an Elemental Skill increases DEF by 16% for 15s.
package fluteofezpitzal

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.FluteOfEzpitzal, NewWeapon)
}
