// Code generated by "pipeline"; DO NOT EDIT.

// set2: Shimenawa's Reminiscence
//
//	ATK +18%.
//
// set4: Shimenawa's Reminiscence # Relic_NormalDamageUpIfCostEnergy
//
//	When casting an Elemental Skill, if the character has 15 or more Energy, they lose
//	15 Energy and Normal/Charged/Plunging Attack DMG is increased by 50% for 10s. This
//	effect will not trigger again during that duration.
package reminiscence

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterSetFunc(keys.ShimenawasReminiscence, NewSet)
}
