use: pipeline
kind: character
name: xingqiu

shortcuts:
  - xq

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG)
      - attack(4-Hit DMG)
      - - attack(5-Hit DMG)
        - attack(5-Hit DMG)
  - ca:
      - attack(Charged Attack DMG)
      - attack(Charged Attack DMG|1)

  - rainscreen:
      - skill(Skill DMG)
      - skill(Skill DMG|1)

  - burst: burst(Sword Rain DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1eJDOj2mI3tFSM7ii6hn3E9GLtS6ah5GwCISDyb2i304/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/SqKyJcmZvHY
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1eJDOj2mI3tFSM7ii6hn3E9GLtS6ah5GwCISDyb2i304/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/ITqJoQawsYc
      video_credit: Kolibri#7675

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 1.5
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 1.5
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3-1
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.5
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N3-2
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.5
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Box
        center: Player
        box: [1, 2]
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N5-1
        shape: Box
        center: Player
        box: [1, 2]
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

      - name: N5-2
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 2
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA-1
        shape: Circle
        center: Player
        radius: 2.2

      - name: CA-2
        shape: Circle
        center: Player
        radius: 2.2

  - name: skill
    hitbox:
      - name: E-1
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 3
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: E-2
        shape: Box
        center: Player
        offset: [0, -1.5]
        box: [3.5, 4.5]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: E-Orbital
        shape: Circle
        center: Player
        radius: 1.2

  - name: burst
    hitbox:
      - name: Q-Start
        note: not implemented yet
        shape: Circle
        center: Player
        radius: 3

      - name: Q-SwordRain
        shape: Circle
        center: PrimaryTarget
        radius: 0.5

  - name: walk
    note: No action followed by walk has proper frames.
