package_name: xingqiu
genshin_id: 10000025
key: xingqiu
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
            - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
        attack_4:
            - 4 # 4-Hit DMG|{param4:F1P}
        attack_5:
            - 5 # 5-Hit DMG|{param5:F1P}+{param6:F1P}
            - 5 # 5-Hit DMG|{param5:F1P}+{param6:F1P}
        ca:
            - 7 # Charged Attack DMG|{param7:F1P}+{param8:F1P}
            - 8 # Charged Attack DMG|{param7:F1P}+{param8:F1P}
    skill:
        rainscreen:
            - 0 # Skill DMG|{param0:P}+{param1:P}
            - 1 # Skill DMG|{param0:P}+{param1:P}
    burst:
        burst:
            - 0 # Sword Rain DMG|{param0:F1P}
