id: 10000025
key: "xingqiu"
rarity: QUALITY_PURPLE
body: BODY_BOY
region: ASSOC_TYPE_LIYUE
element: Water
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Xingqiu"
stats: {
   base_hp: 857.08356
   base_atk: 16.9176
   base_def: 63.51975
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 640.2853
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 47.4525
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 12.63861
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1095.2249
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 81.16875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.618675
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1701.8109
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 126.12375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 33.592094
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2156.7505
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 159.84
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 42.57216
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2611.69
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 193.55624
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 51.552223
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3066.6296
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 227.2725
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 60.53229
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10382
   burst: 10385
   attack: 10381
   burst_energy_cost: 80
}
name_text_hash_map: 4197635682
