use: pipeline
kind: weapon
name: endoftheline

abilities:
  - name: default
    hitbox:
      - name: End of the Line
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 2.5
