id: 10000086
key: "wriothesley"
rarity: QUALITY_ORANGE
body: BODY_MALE
region: ASSOC_TYPE_FONTAINE
element: Ice
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Wriothesley"
stats: {
   base_hp: 1058.1852
   base_atk: 24.206
   base_def: 59.41119
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 907.29816
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 50.9409
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 20.75294
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1551.9573
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 87.13575
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 35.49845
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2411.503
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 135.39555
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 55.15913
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3056.162
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 171.5904
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 69.90464
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3700.8213
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 207.78525
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 84.65015
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4345.4805
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 243.9801
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 99.39566
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
}
skill_details: {
   skill: 10862
   burst: 10865
   attack: 10861
   burst_energy_cost: 60
}
name_text_hash_map: 370151050
