package_name: barbara
genshin_id: 10000014
key: barbara
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        charge:
            - 4 # Charged Attack DMG|{param4:P}
    skill:
        prochp:
            - 3 # HP Regeneration Per Hit|{param2:F2P} Max HP+{param3:I}
        prochpp:
            - 2 # HP Regeneration Per Hit|{param2:F2P} Max HP+{param3:I}
        skill:
            - 4 # Droplet DMG|{param4:F1P}
        skillhp:
            - 1 # Continuous Regeneration|{param0:F2P} Max HP+{param1:I}
        skillhpp:
            - 0 # Continuous Regeneration|{param0:F2P} Max HP+{param1:I}
    burst:
        bursthp:
            - 1 # Regeneration|{param0:F1P} Max HP+{param1:I}
        bursthpp:
            - 0 # Regeneration|{param0:F1P} Max HP+{param1:I}
