id: 10000014
key: "barbara"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_MONDSTADT
element: Water
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Barbara"
stats: {
   base_hp: 820.6119
   base_atk: 13.356
   base_def: 56.0805
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 613.0391
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 41.895
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 9.97785
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1048.6195
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 71.6625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 17.067375
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1629.3934
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 111.3525
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 26.520075
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2064.9739
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 141.12
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 33.6096
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2500.5542
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 170.8875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.699123
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2936.1348
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 200.655
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 47.78865
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10071
   burst: 10072
   attack: 10070
   burst_energy_cost: 80
}
name_text_hash_map: 3775299170
