// Code generated by "pipeline"; DO NOT EDIT.

// set2: Unfinished Reverie
//
//	ATK +18%.
//
// set4: Unfinished Reverie # Relic_CheckBuringDamageUp
//
//	After leaving combat for 3s, DMG dealt increased by 50%. In combat, if no Burning
//	opponents are nearby for more than 6s, this DMG Bonus will decrease by 10% per second
//	until it reaches 0%. When a Burning opponent exists, it will increase by 10% instead
//	until it reaches 50%. This effect still triggers if the equipping character is off-field.
package unfinishedreverie

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterSetFunc(keys.UnfinishedReverie, NewSet)
}
