use: pipeline
kind: character
name: kamisatoayaka

shortcuts:
  - ayaka

combat:
  icd_groups:
    - AyakaExtraAttack

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - - attack(4-Hit DMG)
        - attack(4-Hit DMG)
        - attack(4-Hit DMG)
      - attack(5-Hit DMG)
  - ca: attack(Charged Attack DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skill: skill(Skill DMG)

  - burstCut: burst(Cutting DMG)
  - burstBloom: burst(Bloom DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1WPxQ7vf0_dp5g96aqGF0_JZSqjtYHOJC0b89zRS_WrA/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/63AA7Q_U7nI
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1WPxQ7vf0_dp5g96aqGF0_JZSqjtYHOJC0b89zRS_WrA/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/-Ujt8mGb_0k
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1WPxQ7vf0_dp5g96aqGF0_JZSqjtYHOJC0b89zRS_WrA/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/ulTSQRrR4n8
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ?t=117
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: charliex3000
      video: https://youtu.be/LzTNQvETTXI
      video_credit: charliex3000

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 1.6
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 1.2
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Circle
        center: Player
        offset: [0, -0.5]
        fan_angle: 60
        radius: 2.8
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4-1
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.6

      - name: N4-2
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.6

      - name: N4-3
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 1.6
        hitlag: {time: 0.03, scale: 0.05, defense_halt: true}

      - name: N5-Target
        shape: Circle
        center: PrimaryTarget
        radius: 0.8

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA-1
        note: There are up to 5 possible instances of CA-1, CA-2, CA-3. It looks for an anchor enemy in 5m radius around player. If such an enemy exists, then it looks for additional enemies in 4m radius around the anchor enemy. If less than 5 enemies were targeted, then it checks for gadgets to target.
        shape: Circle
        center: Player
        radius: 1

      - name: CA-2
        shape: Circle
        center: Player
        radius: 1

      - name: CA-3
        shape: Circle
        center: Player
        radius: 1

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    hitbox:
      - name: E-Skill
        shape: Circle
        center: Player
        radius: 4.5

  - name: burst
    hitbox:
      - name: Q-ElementalBurst-Cutting
        shape: Circle
        center: PrimaryTarget
        offset: [0, 0.3]
        radius: 3

      - name: Q-ElementalBurst-Bloom
        shape: Circle
        center: PrimaryTarget
        radius: 5

  - name: cons
    hitbox:
      - name: Q-C2-Cutting
        shape: Circle
        center: PrimaryTarget
        offset: [0, 0.3]
        radius: 1.5

      - name: Q-C2-Bloom
        shape: Circle
        center: PrimaryTarget
        radius: 3

  - name: dash
    params:
      f: Number of frames to add to minimum dash length. Default 0 frames.
    hitbox:
      - name: Dash
        shape: Circle
        center: Player
        offset: [0, 0.1]
        radius: 2

  - name: walk
    note: No action followed by walk (except low_plunge and high_plunge) has proper frames.
