id: 10000035
key: "qiqi"
rarity: QUALITY_ORANGE
body: BODY_LOLI
region: ASSOC_TYPE_LIYUE
element: Ice
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Qiqi"
stats: {
   base_hp: 962.8532
   base_atk: 22.344
   base_def: 71.796
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 825.5596
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 61.56
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 19.15656
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1412.1414
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 105.3
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 32.7678
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
         value: 0.0554
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2194.2505
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 163.62
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 50.91612
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
         value: 0.1108
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2780.8323
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 207.36
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 64.52736
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
         value: 0.1108
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3367.414
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 251.1
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 78.1386
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
         value: 0.1662
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3953.9958
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 294.84
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 91.74984
      }
      add_props: {
         prop_type: FIGHT_PROP_HEAL_ADD
         value: 0.2215
      }
   }
}
skill_details: {
   skill: 10352
   burst: 10353
   attack: 10351
   burst_energy_cost: 80
}
name_text_hash_map: 168956722
