package_name: freminet
genshin_id: 10000085
key: freminet
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        collision:
            - 8 # Plunge DMG|{param6:F1P}
        lowPlunge:
            - 9 # Low/High Plunge DMG|{param7:P}/{param8:P}
        highPlunge:
            - 10 # Low/High Plunge DMG|{param7:P}/{param8:P}
    skill:
        skillAddNA:
            - 2 # Frost DMG|{param2:F1P}
        skillBreath:
            - 1 # Spiritbreath Thorn DMG|{param1:F1P}
        skillPressureCryo:
            - 3 # Level 0 Shattering Pressure DMG|{param3:F1P}
            - 4 # Level 1 Shattering Pressure DMG|{param4:F1P} Cryo + {param5:F1P} Physical
            - 6 # Level 2 Shattering Pressure DMG|{param6:F1P} Cryo + {param7:F1P} Physical
            - 8 # Level 3 Shattering Pressure DMG|{param8:F1P} Cryo + {param9:F1P} Physical
            - -1 # Level 4 Shattering Pressure DMG|{param10:F1P}
        skillPressurePhys:
            - -1 # Level 0 Shattering Pressure DMG|{param3:F1P}
            - 5 # Level 1 Shattering Pressure DMG|{param4:F1P} Cryo + {param5:F1P} Physical
            - 7 # Level 2 Shattering Pressure DMG|{param6:F1P} Cryo + {param7:F1P} Physical
            - 9 # Level 3 Shattering Pressure DMG|{param8:F1P} Cryo + {param9:F1P} Physical
            - 10 # Level 4 Shattering Pressure DMG|{param10:F1P}
        skillThrust:
            - 0 # Upward Thrust DMG|{param0:F1P}
    burst:
        burst:
            - 0 # Skill DMG|{param0:F1P}
