id: 10000085
key: "freminet"
rarity: QUALITY_PURPLE
body: BODY_BOY
region: ASSOC_TYPE_FONTAINE
element: Ice
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Freminet"
stats: {
   base_hp: 1012.088
   base_atk: 21.3696
   base_def: 59.39955
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 756.08154
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 44.3745
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 15.96456
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1293.2974
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 75.90375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 27.3078
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2009.5852
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 117.94275
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 42.43212
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2546.801
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 149.472
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 53.77536
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3084.0168
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 181.00125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 65.1186
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3621.2327
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 212.5305
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 76.46184
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10852
   burst: 10855
   attack: 10851
   burst_energy_cost: 60
}
name_text_hash_map: 4201964354
