package_name: tartaglia
genshin_id: 10000033
key: tartaglia
skill_data_mapping:
    attack:
        aim:
            - 6 # Aimed Shot|{param6:F1P}
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        attack_5:
            - 4 # 5-Hit DMG|{param4:F1P}
        attack_6:
            - 5 # 6-Hit DMG|{param5:F1P}
        fullaim:
            - 7 # Fully-Charged Aimed Shot|{param7:P}
        rtBurst:
            - 9 # Riptide Burst DMG|{param9:F1P}
        rtFlash:
            - 8 # Riptide Flash DMG|{param8:F1P}×3
    skill:
        attackE_1:
            - 1 # 1-Hit DMG|{param1:F1P}
        attackE_2:
            - 2 # 2-Hit DMG|{param2:F1P}
        attackE_3:
            - 3 # 3-Hit DMG|{param3:F1P}
        attackE_4:
            - 4 # 4-Hit DMG|{param4:F1P}
        attackE_5:
            - 5 # 5-Hit DMG|{param5:F1P}
        attackE_6:
            - 6 # 6-Hit DMG|{param6:F1P}+{param7:F1P}
            - 7 # 6-Hit DMG|{param6:F1P}+{param7:F1P}
        eCharge:
            - 8 # Charged Attack DMG|{param8:F1P}+{param9:F1P}
            - 9 # Charged Attack DMG|{param8:F1P}+{param9:F1P}
        rtSlash:
            - 8 # Charged Attack DMG|{param8:F1P}+{param9:F1P}
        skill:
            - 0 # Stance Change DMG|{param0:P}
    burst:
        burst:
            - 2 # Skill DMG: Ranged|{param2:P}
        meleeBurst:
            - 0 # Skill DMG: Melee|{param0:P}
        rtBlast:
            - 1 # Riptide Blast DMG|{param1:P}
