id: 10000033
key: "tartaglia"
rarity: QUALITY_ORANGE
body: BODY_MALE
region: ASSOC_TYPE_FATUI
element: Water
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Tartaglia"
stats: {
   base_hp: 1020.0524
   base_atk: 23.4612
   base_def: 63.4198
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 874.6027
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 54.378
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 20.114388
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1496.0309
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 93.015
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 34.40619
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2324.6018
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 144.531
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 53.461926
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2946.03
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 183.168
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 67.75373
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3567.4585
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 221.805
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 82.04553
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4188.8867
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 260.442
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 96.33733
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 10332
   burst: 10333
   attack: 10331
   burst_energy_cost: 60
}
name_text_hash_map: 3847143266
