// Code generated by "pipeline"; DO NOT EDIT.

// set2: Echoes of an Offering
//
//	ATK +18%.
//
// set4: Echoes of an Offering # Relic_AttackWithExtraDamage
//
//	When Normal Attacks hit opponents, there is a 36% chance that it will trigger Valley
//	Rite, which will increase Normal Attack DMG by 70% of ATK. This effect will be dispelled
//	0.05s after a Normal Attack deals DMG. If a Normal Attack fails to trigger Valley
//	Rite, the odds of it triggering the next time will increase by 20%. This trigger
//	can occur once every 0.2s.
package echoes

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterSetFunc(keys.EchoesOfAnOffering, NewSet)
}
