package_name: kirara
genshin_id: 10000061
key: kirara
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
            - 3 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
        attack_4:
            - 4 # 4-Hit DMG|{param4:F1P}
        charge:
            - 5 # Charged Attack DMG|{param5:F1P}+{param6:F1P}+{param7:F1P}
            - 6 # Charged Attack DMG|{param5:F1P}+{param6:F1P}+{param7:F1P}
            - 6 # Charged Attack DMG|{param5:F1P}+{param6:F1P}+{param7:F1P}
    skill:
        catDmg:
            - 6 # Urgent Neko Parcel Hit DMG|{param6:F1P}
        flipclawDmg:
            - 8 # Flipclaw Strike DMG|{param8:F1P}
        maxShieldFlat:
            - 4 # Max Shield DMG Absorption|{param3:F1P} Max HP+{param4:I}
        maxShieldPP:
            - 3 # Max Shield DMG Absorption|{param3:F1P} Max HP+{param4:I}
        shieldFlat:
            - 2 # Shield DMG Absorption|{param1:F1P} Max HP+{param2:I}
        shieldPP:
            - 1 # Shield DMG Absorption|{param1:F1P} Max HP+{param2:I}
        skillPress:
            - 0 # Tail-Flicking Flying Kick DMG|{param0:F1P}
    burst:
        burst:
            - 0 # Skill DMG|{param0:F1P}
        cardamom:
            - 1 # Cat Grass Cardamom Explosion DMG|{param1:F1P}
