id: 10000061
key: "kirara"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_INAZUMA
element: Grass
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Momoka"
stats: {
   base_hp: 1021.20593
   base_atk: 18.6984
   base_def: 45.78
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 762.8931
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 34.2
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 13.96899
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1304.9487
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 58.5
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.894325
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2027.6896
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 90.9
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 37.128105
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2569.745
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 115.2
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 47.05344
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3111.8008
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 139.5
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 56.978775
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3653.8564
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 163.8
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 66.90411
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10612
   burst: 10615
   attack: 10611
   burst_energy_cost: 60
}
name_text_hash_map: 1456643042
