package_name: "lumine"
genshin_id: 10000007
sub_id: 702
key: luminepyro
key_var_name: LuminePyro
pretty_name: Lumine Pyro
action_param_keys:
  skill:
    - param: "hold"
  low_plunge:
    - param: "collision"
  high_plunge:
    - param: "collision"
