package_name: shenhe
genshin_id: 10000063
key: shenhe
action_param_keys:
    skill:
        - param: "hold"
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}+{param4:F1P}
            - 3 # 4-Hit DMG|{param3:F1P}+{param4:F1P}
        attack_5:
            - 5 # 5-Hit DMG|{param5:F1P}
        charged:
            - 6 # Charged Attack DMG|{param6:F1P}
    skill:
        skillHold:
            - 1 # Hold Skill DMG|{param1:F1P}
        skillPress:
            - 0 # #{LAYOUT_MOBILE#Tap}{LAYOUT_PC#Press}{LAYOUT_PS#Press} Skill DMG|{param0:P}
        skillpp:
            - 2 # DMG Bonus|{param2:F1P} ATK
    burst:
        burst:
            - 0 # Skill DMG|{param0:P}
        burstdot:
            - 2 # DoT|{param2:F1P}
        burstrespp:
            - 1 # RES Decrease|{param1:F1P}
