id: 10000063
key: "shenhe"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_LIYUE
element: Ice
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Shenhe"
stats: {
   base_hp: 1011.47253
   base_atk: 23.6474
   base_def: 64.6164
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 867.2462
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 55.404
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 20.274027
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1483.4475
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 94.77
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 34.679256
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2305.049
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 147.258
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 53.886227
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2921.2505
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 186.624
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 68.29146
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3537.4517
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 225.99
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 82.696686
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4153.653
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 265.356
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 97.10191
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 10632
   burst: 10635
   attack: 10631
   burst_energy_cost: 80
}
name_text_hash_map: 334242634
