// Code generated by "pipeline"; DO NOT EDIT.

// passive: Courage # Weapon_Claymore_AttackUpBuff
//
//	On hit, Normal or Charged Attacks increase ATK by 6% for 6s. Max 4 stacks. Can occur
//	once every 0.5s.
package skyrider

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.SkyriderGreatsword, NewWeapon)
}
