use: pipeline
kind: character
name: thoma

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - charged: attack(Charged Attack DMG)

  - skill: skill(Skill DMG)
  - shieldpp: skill(Shield DMG Absorption)
  - shieldflat: skill(Shield DMG Absorption|1)
  - shieldppmax: skill(Max Shield DMG Absorption)
  - shieldflatmax: skill(Max Shield DMG Absorption|1)

  - burst: burst(Skill DMG)
  - burstproc: burst(Fiery Collapse DMG)
  - burstshieldpp: burst(Shield DMG Absorption)
  - burstshieldflat: burst(Shield DMG Absorption|1)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1QtllZ_QKQIJNGnD4FILZCB307aA8YtDfpG6pcYndl5E/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/wnOvlhq8us4
      video_credit: Kolibri#7675

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.8]
        fan_angle: 270
        radius: 2
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.8]
        fan_angle: 270
        radius: 2
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: N3-1
        shape: Box
        center: Player
        offset: [0, -1]
        box: [2.6, 3.5]

      - name: N3-2
        shape: Box
        center: Player
        offset: [0, -1]
        box: [2.6, 3.5]

      - name: N4
        shape: Box
        center: Player
        offset: [0, 0.5]
        box: [2.2, 6.5]

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 0.8
        hitlag: {scale: 0.01, defense_halt: true, deployable: true}

  - name: skill
    hitbox:
      - name: E-Skill
        shape: Circle
        center: Player
        offset: [0, 1]
        fan_angle: 270
        radius: 3
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

  - name: burst
    hitbox:
      - name: Q-Initial
        shape: Circle
        center: Player
        radius: 4

      - name: Q-FieryCollapse
        shape: Box
        center: Player
        box: [4.5, 8]

  - name: walk
    note: No action followed by walk has proper frames.
