id: 10000050
key: "thoma"
rarity: QUALITY_PURPLE
body: BODY_MALE
region: ASSOC_TYPE_INAZUMA
element: Fire
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Tohma"
stats: {
   base_hp: 866.2015
   base_atk: 16.9176
   base_def: 62.9475
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 647.0968
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 47.025
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 12.63861
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1106.8762
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 80.4375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.618675
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1719.9153
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 124.9875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 33.592094
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2179.6946
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 158.4
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 42.57216
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2639.4739
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 191.8125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 51.552223
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3099.2532
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 225.225
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 60.53229
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10502
   burst: 10505
   attack: 10501
   burst_energy_cost: 80
}
name_text_hash_map: 3555115602
