package_name: faruzan
genshin_id: 10000076
key: faruzan
action_param_keys:
    attack:
        - param: "travel"
    aim:
        - param: "hold"
        - param: "travel"
        - param: "weakspot"
skill_data_mapping:
    attack:
        aim:
            - 4 # Aimed Shot|{param4:F1P}
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        fullaim:
            - 5 # Fully-Charged Aimed Shot|{param5:P}
    skill:
        skill:
            - 0 # Skill DMG|{param0:F1P}
        vortexDmg:
            - 1 # Pressurized Collapse Vortex DMG|{param1:F1P}
    burst:
        burst:
            - 0 # Skill DMG|{param0:F1P}
        burstBuff:
            - 1 # Anemo DMG Bonus|{param1:F1P}

documentation:
    fields_data:
        - fields: [.faruzan.hurricane-count]
          desc: Current number of Hurricane Arrows that Faruzan can fire off.
