id: 10000076
key: "faruzan"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_SUMERU
element: Wind
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Faruzan"
stats: {
   base_hp: 802.3761
   base_atk: 16.4724
   base_def: 52.647
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 599.416
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 39.33
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 12.306015
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1025.3169
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 67.275
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.049763
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1593.1847
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 104.535
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 32.70809
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2019.0856
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 132.48
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 41.45184
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2444.9863
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 160.425
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 50.195587
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2870.8872
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 188.37
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 58.939335
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10762
   burst: 10765
   attack: 10761
   burst_energy_cost: 80
}
name_text_hash_map: 2387711994
