package_name: ningguang
genshin_id: 10000027
key: ningguang
skill_data_mapping:
    attack:
        attack:
            - 0 # Normal Attack DMG|{param0:F1P}
        charge:
            - 1 # Charged Attack DMG|{param1:P}
        jade:
            - 2 # DMG per Star Jade|{param2:F1P}
    skill:
        skill:
            - 1 # Skill DMG|{param1:P}
    burst:
        burst:
            - 0 # DMG Per Gem|{param0:F1P}
