use: pipeline
kind: character
name: ningguang

shortcuts:
  - ning

talents:
  - attack: attack(Normal Attack DMG)
  - charge: attack(Charged Attack DMG)
  - jade: attack(DMG per Star Jade)

  - skill: skill(Skill DMG)

  - burst: burst(DMG Per Gem)

docs:
  fields:
    .ningguang.jadeCount: Number of Star Jades.
    .ningguang.prevAttack: 'Returns a number representing the previous N1 version. Possible values are: 0 = Left, 1 = Right, 2 = Twirl.'
  frames:
    - count: https://docs.google.com/spreadsheets/d/12y2e2JkN55UOpbMeTpx1EmqqN9zdfPf3jLLpo9YKxnE/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/r_NAO1Lld3Q
      video_credit: Kolibri#7675

abilities:
  - name: attack
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: N1-PreC1
        shape: Circle
        center: PrimaryTarget
        radius: 0.5

      - name: N1-PostC1
        shape: Circle
        center: PrimaryTarget
        radius: 3.5

  - name: charge
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 1.5

      - name: CA-StarJade
        shape: Circle
        center: PrimaryTarget
        radius: 0.5
        hitlag: {defense_halt: true, deployable: true}

  - name: skill
    params:
      noscreen: If 1, destroy the Jade Screen on cast. Default 0.
    hitbox:
      - name: E-Skill
        note: Screen construct spawns at the same position.
        shape: Circle
        center: Player
        offset: [0, 3]
        radius: 5
        hitlag: {time: 0.05, scale: 0.05, defense_halt: true, deployable: true}

  - name: burst
    params:
      jade: Number of Jade attacks from burst. Default 6.
      screen: Number of Jade attacks from Jade Screen snapshot. Default 6.
      travel: Projectile travel time. Default 0 frames.
    hitbox:
      - name: Q-Gem
        shape: Circle
        center: PrimaryTarget
        radius: 0.5
        hitlag: {defense_halt: true, deployable: true}
