id: 10000027
key: "ningguang"
rarity: QUALITY_PURPLE
body: BODY_LADY
region: ASSOC_TYPE_LIYUE
element: Rock
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Ningguang"
stats: {
   base_hp: 820.6119
   base_atk: 17.808
   base_def: 48.069
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 613.0391
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 35.91
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 13.3038
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1048.6195
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 61.425
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.7565
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1629.3934
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 95.445
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 35.3601
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2064.9739
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 120.96
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 44.8128
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2500.5542
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 146.475
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 54.2655
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2936.1348
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 171.99
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.7182
      }
      add_props: {
         prop_type: FIGHT_PROP_ROCK_ADD_HURT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10272
   burst: 10274
   attack: 10271
   burst_energy_cost: 40
}
name_text_hash_map: 4127888970
