// Code generated by "pipeline"; DO NOT EDIT.

// passive: The Way of Sunfire # Weapon_Bow_Gurabad
//
//	After a Charged Attack hits an opponent, a Sunfire Arrow will descend upon the opponent
//	hit, dealing 60% ATK as DMG, and applying the Heartsearer effect to the opponent
//	damaged by said Arrow for 10s. Opponents affected by Heartsearer take 28% more Charged
//	Attack DMG from the wielder. A Sunfire Arrow can be triggered once every 10s.
package scionoftheblazingsun

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.ScionOfTheBlazingSun, NewWeapon)
}
