use: pipeline
kind: character
name: sangonomiyakokomi

shortcuts:
  - koko
  - kokomi

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
  - charge: attack(Charged Attack DMG)

  - skillHealPct: skill(Regeneration)
  - skillHealFlat: skill(Regeneration|1)
  - skillDmg: skill(Ripple DMG)

  - burstDmg: burst(Skill DMG)
  - burstHealPct: burst(HP Regeneration Per Hit)
  - burstHealFlat: burst(HP Regeneration Per Hit|1)
  - burstBonusNormal: burst(Normal Attack DMG Bonus)
  - burstBonusCharge: burst(Charged Attack DMG Bonus)
  - burstBonusSkill: burst(Bake-Kurage DMG Bonus)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1j3Hzo25qSqo-ZbQBiBqcejR1aa91igSVTxH1xoKYrfc/edit
      count_credit: Shizuka#7791
      video: https://youtu.be/Rp8-WwtFxSY
      video_credit: Shizuka#7791
    - count: https://docs.google.com/spreadsheets/d/1j3Hzo25qSqo-ZbQBiBqcejR1aa91igSVTxH1xoKYrfc/edit
      count_credit: Shizuka#7791
      video: https://youtu.be/WqvtcGyMd54
      video_credit: Shizuka#7791
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ?t=1000
      video_credit: Kolibri#7675

abilities:
  - name: attack
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: N1
        shape: Circle
        center: PrimaryTarget
        radius: 0.7

      - name: N2
        shape: Circle
        center: PrimaryTarget
        radius: 0.7

      - name: N3
        shape: Circle
        center: PrimaryTarget
        radius: 0.7

      - name: Q-N1
        shape: Circle
        center: PrimaryTarget
        radius: 1.2

      - name: Q-N2
        shape: Circle
        center: PrimaryTarget
        radius: 1.2

      - name: Q-N3
        shape: Circle
        center: PrimaryTarget
        radius: 1.2

  - name: charge
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 3.5

      - name: Q-CA
        shape: Circle
        center: PrimaryTarget
        radius: 4

  - name: skill
    hitbox:
      - name: E-Ripple
        note: E has a detection area that is the same as this hitbox.
        shape: Circle
        center: Player
        offset: [0, 3]
        radius: 6

  - name: burst
    hitbox:
      - name: Q-Initial
        shape: Circle
        center: Player
        radius: 5

  - name: cons
    hitbox:
      - name: C1
        shape: Circle
        center: PrimaryTarget
        radius: 1.2
