id: 10000054
key: "kokomi"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_INAZUMA
element: Water
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Kokomi"
stats: {
   base_hp: 1048.652
   base_atk: 18.2476
   base_def: 51.15465
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 899.12427
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 43.8615
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 15.644524
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1537.9757
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 75.02625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 26.76037
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2389.7776
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 116.57925
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 41.581497
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3028.6292
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 147.744
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 52.697346
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3667.4805
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 178.90875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 63.81319
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4306.332
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 210.0735
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 74.92904
      }
      add_props: {
         prop_type: FIGHT_PROP_WATER_ADD_HURT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 10542
   burst: 10545
   attack: 10541
   burst_energy_cost: 70
}
name_text_hash_map: 3914045794
