// Code generated by "pipeline"; DO NOT EDIT.

// passive: Spotless Heart # Weapon_Sword_Opus
//
//	Elemental Skill DMG is increased by 40% of DEF. The effect will be triggered no more
//	than once every 1.5s and will be cleared 0.1s after the Elemental Skill deals DMG.
package cinnabar

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.CinnabarSpindle, NewWeapon)
}
