use: pipeline
kind: character
name: baizhu

override:
  icd_group:
    BaizhuC2:
      name: Baizhuer_Talent

combat:
  icd_groups:
    - BaizhuC2

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - charge: attack(Charged Attack DMG)

  - skillDamage: skill(Skill DMG)
  - skillHealPP: skill(Healing)
  - skillHealFlat: skill(Healing|1)

  - burstShieldPP: burst(Seamless Shield DMG Absorption)
  - burstShieldFlat: burst(Seamless Shield DMG Absorption|1)
  - burstHealPP: burst(Seamless Shield Healing)
  - burstHealFlat: burst(Seamless Shield Healing|1)
  - burstAtk: burst(Spiritvein DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1u74NvNfOgKS6B0cZYOFUArqA133Kqjr3bjT-KXKUMq0/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/DvAeMykwiwo
      video_credit: Kolibri#7675

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Box
        center: Player
        offset: [0, -0.2]
        box: [2, 3]

      - name: N2
        shape: Box
        center: Player
        offset: [0, -0.2]
        box: [2, 3]

      - name: N3
        shape: Box
        center: Player
        offset: [0, -0.2]
        box: [2.4, 3]

      - name: N4
        shape: Box
        center: Player
        offset: [0, -0.2]
        box: [3.2, 3]

  - name: charge
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 2.3

  - name: skill
    hitbox:
      - name: E
        note: Is done as a chain of attacks starting at PrimaryTarget and moving on to a random enemy within 10m radius of the current enemy (including current enemy) if such an enemy exists.
        shape: Circle
        center: PrimaryTarget
        radius: 0.6

  - name: burst
    hitbox:
      - name: Q-Start
        note: not implemented yet
        shape: Circle
        center: Player
        radius: 3

      - name: Q-Spiritvein
        shape: Circle
        center: PrimaryTarget
        radius: 1.5

  - name: cons
    hitbox:
      - name: C2
        note: Spawns on target that C2 proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 0.6
