id: 10000082
key: "baizhu"
rarity: QUALITY_ORANGE
body: BODY_MALE
region: ASSOC_TYPE_LIYUE
element: Grass
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Baizhuer"
stats: {
   base_hp: 1039.1188
   base_atk: 14.9891
   base_def: 38.8895
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 890.95044
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 33.345
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 12.850859
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1523.9941
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 57.0375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.981731
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2368.0525
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 88.6275
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 34.15623
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3001.0962
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 112.32
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 43.287106
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3634.14
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 136.0125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 52.417976
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4267.1836
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 159.705
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.54885
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 10822
   burst: 10825
   attack: 10821
   burst_energy_cost: 80
}
name_text_hash_map: 2984815066
