id: 10000036
key: "chongyun"
rarity: QUALITY_PURPLE
body: BODY_BOY
region: ASSOC_TYPE_LIYUE
element: Ice
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Chongyun"
stats: {
   base_hp: 920.90894
   base_atk: 18.6984
   base_def: 54.36375
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 687.9661
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 40.6125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 13.96899
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1176.7842
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 69.46875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.894325
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1828.5415
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 107.94375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 37.128105
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2317.3596
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 136.8
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 47.05344
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2806.1775
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 165.65625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 56.978775
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3294.9956
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 194.5125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 66.90411
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10402
   burst: 10403
   attack: 10401
   burst_energy_cost: 40
}
name_text_hash_map: 2876340530
