/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvancedRouteImport } from './routes/advanced'
import { Route as LocalRouteImport } from './routes/local'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimpleRouteImport } from './routes/simple'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as WebRouteImport } from './routes/web'
import { Route as DbIdRouteImport } from './routes/db/$id'
import { Route as SIdRouteImport } from './routes/s/$id'
import { Route as SampleLocalRouteImport } from './routes/sample/local'
import { Route as SampleUploadRouteImport } from './routes/sample/upload'
import { Route as ShIdRouteImport } from './routes/sh/$id'
import { Route as ViewerIndexRouteImport } from './routes/viewer/index'
import { Route as ViewerLocalRouteImport } from './routes/viewer/local'
import { Route as ViewerWebRouteImport } from './routes/viewer/web'
import { Route as ViewerShareIdRouteImport } from './routes/viewer/share/$id'
import { Route as V3ViewerShareIdRouteImport } from './routes/v3/viewer/share/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedRoute = AdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleRoute = SimpleRouteImport.update({
  id: '/simple',
  path: '/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const WebRoute = WebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => rootRouteImport,
} as any)
const DbIdRoute = DbIdRouteImport.update({
  id: '/db/$id',
  path: '/db/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleLocalRoute = SampleLocalRouteImport.update({
  id: '/sample/local',
  path: '/sample/local',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleUploadRoute = SampleUploadRouteImport.update({
  id: '/sample/upload',
  path: '/sample/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ShIdRoute = ShIdRouteImport.update({
  id: '/sh/$id',
  path: '/sh/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerIndexRoute = ViewerIndexRouteImport.update({
  id: '/viewer/',
  path: '/viewer/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerLocalRoute = ViewerLocalRouteImport.update({
  id: '/viewer/local',
  path: '/viewer/local',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerWebRoute = ViewerWebRouteImport.update({
  id: '/viewer/web',
  path: '/viewer/web',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewerShareIdRoute = ViewerShareIdRouteImport.update({
  id: '/viewer/share/$id',
  path: '/viewer/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const V3ViewerShareIdRoute = V3ViewerShareIdRouteImport.update({
  id: '/v3/viewer/share/$id',
  path: '/v3/viewer/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/local': typeof LocalRoute
  '/settings': typeof SettingsRoute
  '/simple': typeof SimpleRoute
  '/simulator': typeof SimulatorRoute
  '/web': typeof WebRoute
  '/db/$id': typeof DbIdRoute
  '/s/$id': typeof SIdRoute
  '/sample/local': typeof SampleLocalRoute
  '/sample/upload': typeof SampleUploadRoute
  '/sh/$id': typeof ShIdRoute
  '/viewer/local': typeof ViewerLocalRoute
  '/viewer/web': typeof ViewerWebRoute
  '/viewer/': typeof ViewerIndexRoute
  '/viewer/share/$id': typeof ViewerShareIdRoute
  '/v3/viewer/share/$id': typeof V3ViewerShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/local': typeof LocalRoute
  '/settings': typeof SettingsRoute
  '/simple': typeof SimpleRoute
  '/simulator': typeof SimulatorRoute
  '/web': typeof WebRoute
  '/db/$id': typeof DbIdRoute
  '/s/$id': typeof SIdRoute
  '/sample/local': typeof SampleLocalRoute
  '/sample/upload': typeof SampleUploadRoute
  '/sh/$id': typeof ShIdRoute
  '/viewer/local': typeof ViewerLocalRoute
  '/viewer/web': typeof ViewerWebRoute
  '/viewer': typeof ViewerIndexRoute
  '/viewer/share/$id': typeof ViewerShareIdRoute
  '/v3/viewer/share/$id': typeof V3ViewerShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advanced': typeof AdvancedRoute
  '/local': typeof LocalRoute
  '/settings': typeof SettingsRoute
  '/simple': typeof SimpleRoute
  '/simulator': typeof SimulatorRoute
  '/web': typeof WebRoute
  '/db/$id': typeof DbIdRoute
  '/s/$id': typeof SIdRoute
  '/sample/local': typeof SampleLocalRoute
  '/sample/upload': typeof SampleUploadRoute
  '/sh/$id': typeof ShIdRoute
  '/viewer/local': typeof ViewerLocalRoute
  '/viewer/web': typeof ViewerWebRoute
  '/viewer/': typeof ViewerIndexRoute
  '/viewer/share/$id': typeof ViewerShareIdRoute
  '/v3/viewer/share/$id': typeof V3ViewerShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advanced'
    | '/local'
    | '/settings'
    | '/simple'
    | '/simulator'
    | '/web'
    | '/db/$id'
    | '/s/$id'
    | '/sample/local'
    | '/sample/upload'
    | '/sh/$id'
    | '/viewer/local'
    | '/viewer/web'
    | '/viewer/'
    | '/viewer/share/$id'
    | '/v3/viewer/share/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advanced'
    | '/local'
    | '/settings'
    | '/simple'
    | '/simulator'
    | '/web'
    | '/db/$id'
    | '/s/$id'
    | '/sample/local'
    | '/sample/upload'
    | '/sh/$id'
    | '/viewer/local'
    | '/viewer/web'
    | '/viewer'
    | '/viewer/share/$id'
    | '/v3/viewer/share/$id'
  id:
    | '__root__'
    | '/'
    | '/advanced'
    | '/local'
    | '/settings'
    | '/simple'
    | '/simulator'
    | '/web'
    | '/db/$id'
    | '/s/$id'
    | '/sample/local'
    | '/sample/upload'
    | '/sh/$id'
    | '/viewer/local'
    | '/viewer/web'
    | '/viewer/'
    | '/viewer/share/$id'
    | '/v3/viewer/share/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancedRoute: typeof AdvancedRoute
  LocalRoute: typeof LocalRoute
  SettingsRoute: typeof SettingsRoute
  SimpleRoute: typeof SimpleRoute
  SimulatorRoute: typeof SimulatorRoute
  WebRoute: typeof WebRoute
  DbIdRoute: typeof DbIdRoute
  SIdRoute: typeof SIdRoute
  SampleLocalRoute: typeof SampleLocalRoute
  SampleUploadRoute: typeof SampleUploadRoute
  ShIdRoute: typeof ShIdRoute
  ViewerLocalRoute: typeof ViewerLocalRoute
  ViewerWebRoute: typeof ViewerWebRoute
  ViewerIndexRoute: typeof ViewerIndexRoute
  ViewerShareIdRoute: typeof ViewerShareIdRoute
  V3ViewerShareIdRoute: typeof V3ViewerShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced': {
      id: '/advanced'
      path: '/advanced'
      fullPath: '/advanced'
      preLoaderRoute: typeof AdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple': {
      id: '/simple'
      path: '/simple'
      fullPath: '/simple'
      preLoaderRoute: typeof SimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web': {
      id: '/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof WebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/$id': {
      id: '/db/$id'
      path: '/db/$id'
      fullPath: '/db/$id'
      preLoaderRoute: typeof DbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample/local': {
      id: '/sample/local'
      path: '/sample/local'
      fullPath: '/sample/local'
      preLoaderRoute: typeof SampleLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample/upload': {
      id: '/sample/upload'
      path: '/sample/upload'
      fullPath: '/sample/upload'
      preLoaderRoute: typeof SampleUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sh/$id': {
      id: '/sh/$id'
      path: '/sh/$id'
      fullPath: '/sh/$id'
      preLoaderRoute: typeof ShIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/': {
      id: '/viewer/'
      path: '/viewer'
      fullPath: '/viewer/'
      preLoaderRoute: typeof ViewerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/local': {
      id: '/viewer/local'
      path: '/viewer/local'
      fullPath: '/viewer/local'
      preLoaderRoute: typeof ViewerLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/web': {
      id: '/viewer/web'
      path: '/viewer/web'
      fullPath: '/viewer/web'
      preLoaderRoute: typeof ViewerWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewer/share/$id': {
      id: '/viewer/share/$id'
      path: '/viewer/share/$id'
      fullPath: '/viewer/share/$id'
      preLoaderRoute: typeof ViewerShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v3/viewer/share/$id': {
      id: '/v3/viewer/share/$id'
      path: '/v3/viewer/share/$id'
      fullPath: '/v3/viewer/share/$id'
      preLoaderRoute: typeof V3ViewerShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancedRoute: AdvancedRoute,
  LocalRoute: LocalRoute,
  SettingsRoute: SettingsRoute,
  SimpleRoute: SimpleRoute,
  SimulatorRoute: SimulatorRoute,
  WebRoute: WebRoute,
  DbIdRoute: DbIdRoute,
  SIdRoute: SIdRoute,
  SampleLocalRoute: SampleLocalRoute,
  SampleUploadRoute: SampleUploadRoute,
  ShIdRoute: ShIdRoute,
  ViewerLocalRoute: ViewerLocalRoute,
  ViewerWebRoute: ViewerWebRoute,
  ViewerIndexRoute: ViewerIndexRoute,
  ViewerShareIdRoute: ViewerShareIdRoute,
  V3ViewerShareIdRoute: V3ViewerShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
