// Code generated by "pipeline"; DO NOT EDIT.

// passive: Crag-Chiseled Forge # Weapon_Bow_Ultimatum
//
//	After Elemental Energy is decreased, the equipping character's Elemental Mastery
//	will increase by 40 for 18s. Max 2 stacks.
package cloudforged

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.Cloudforged, NewWeapon)
}
