name: "Build UI"
description: "builds the gcsim UI into ui/packages/web/dist for the consolidated Worker to upload as assets. Assumes pnpm setup has already ran"
inputs:
  branch:
    required: true
    description: name of the branch

runs:
  using: composite
  steps:
  - name: Build UI
    working-directory: ./ui
    shell: bash
    run: pnpm build:web
    env:
      VITE_BRANCH: ${{ inputs.branch }}

  - name: List UI dist
    working-directory: ./ui/packages/web/dist
    shell: bash
    run: ls -lh
