use: pipeline
kind: character
name: rosaria

shortcuts:
  - rosa

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG)
      - attack(4-Hit DMG)
      - - attack(5-Hit DMG)
        - attack(5-Hit DMG|1)
  - nc: attack(Charged Attack DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skill:
      - skill(Skill DMG)
      - skill(Skill DMG|1)

  - burst:
      - burst(Skill DMG)
      - burst(Skill DMG|1)
  - burstDot: burst(Ice Lance DoT)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1buBVBvlgfNcRA09XA3BLm-oA7hpCVRYkGt_7kPBYJu0/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/_FVJTwjKW4A
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1ieBa344vhM42FvxmlZLMSzlGm5PEykV8VMGQk9Haelk/edit?usp=sharing
      count_credit: GaspNAwe
      video: https://youtu.be/4YxyI1q0-ds
      video_credit: GaspNAwe

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        fan_angle: 270
        radius: 2.5
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        fan_angle: 270
        radius: 2.5
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N3-1
        shape: Box
        center: Player
        box: [2.2, 3.6]

      - name: N3-2
        shape: Box
        center: Player
        box: [2.2, 3.6]
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Circle
        center: Player
        offset: [0, 2]
        radius: 2.3
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: N5-1
        shape: Box
        center: Player
        box: [2, 3]
        hitlag: {time: 0.06, scale: 0.01}

      - name: N5-2
        shape: Circle
        center: Player
        offset: [0, 1.5]
        radius: 2.5
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 0.8
        hitlag: {scale: 0.01, defense_halt: true, deployable: true}

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    params:
      nobehind: Default 0. 1 for disabling striking behind for A1 purposes.
    hitbox:
      - name: E-1
        shape: Box
        center: Player
        offset: [0, -1]
        box: [2, 4]
        hitlag: {time: 0.06, scale: 0.01}

      - name: E-2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 2.8
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

  - name: burst
    hitbox:
      - name: Q-1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 3.5
        hitlag: {time: 0.06, scale: 0.01}

      - name: Q-2
        shape: Circle
        center: Player
        radius: 6

      - name: Q-DoT
        shape: Circle
        center: Player
        radius: 6.5

  - name: walk
    note: No action followed by walk (except low_plunge and high_plunge) has proper frames.
