package_name: rosaria
genshin_id: 10000045
key: rosaria
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}×2
            - 2 # 3-Hit DMG|{param2:F1P}×2
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        attack_5:
            - 4 # 5-Hit DMG|{param4:F1P}+{param5:F1P}
            - 5 # 5-Hit DMG|{param4:F1P}+{param5:F1P}
        nc:
            - 6 # Charged Attack DMG|{param6:P}
    skill:
        skill:
            - 0 # Skill DMG|{param0:P}+{param1:P}
            - 1 # Skill DMG|{param0:P}+{param1:P}
    burst:
        burst:
            - 0 # Skill DMG|{param0:P}+{param1:P}
            - 1 # Skill DMG|{param0:P}+{param1:P}
        burstDot:
            - 2 # Ice Lance DoT|{param2:P}
