id: 10000045
key: "rosaria"
rarity: QUALITY_PURPLE
body: BODY_LADY
region: ASSOC_TYPE_MONDSTADT
element: Ice
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Rosaria"
stats: {
   base_hp: 1030.3239
   base_atk: 20.12304
   base_def: 59.514
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 769.70465
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 44.46
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 15.033294
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1316.6001
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 76.05
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 25.714846
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2045.794
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 118.17
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.956913
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2592.6895
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 149.76
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 50.638466
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3139.5847
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 181.35
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.320015
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3686.4802
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 212.94
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 72.001564
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10452
   burst: 10453
   attack: 10451
   burst_energy_cost: 60
}
name_text_hash_map: 4260733330
