package_name: layla
genshin_id: 10000074
key: layla
icd_groups:
  - group_name: ICDGroupLayla
    reset_timer: 180
    ele_app_sequence: [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
  attack:
    auto_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    auto_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    auto_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    charge:
      - 3 # Charged Attack DMG|{param3:F1P}+{param4:F1P}
      - 4 # Charged Attack DMG|{param3:F1P}+{param4:F1P}
  skill:
    shieldBase:
      - 3 # Base Shield DMG Absorption|{param2:F1P} Max HP+{param3:I}
    shieldPer:
      - 2 # Base Shield DMG Absorption|{param2:F1P} Max HP+{param3:I}
    skill:
      - 0 # Skill DMG|{param0:F1P}
    starDmg:
      - 1 # Shooting Star DMG|{param1:F1P}
  burst:
    burst:
      - 0 # Starlight Slug DMG|{param0:F1P} Max HP
