use: pipeline
kind: character
name: layla

override:
  icd_group:
    Layla:
      name: Layla_ElementalArt_Bullet

combat:
  icd_groups:
    - Layla

talents:
  - auto:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
  - charge:
      - attack(Charged Attack DMG)
      - attack(Charged Attack DMG|1)

  - skill: skill(Skill DMG)
  - starDmg: skill(Shooting Star DMG)
  - shieldPer: skill(Base Shield DMG Absorption)
  - shieldBase: skill(Base Shield DMG Absorption|1)

  - burst: burst(Starlight Slug DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/19ZO_rbo6V2n-yWVjM8LqN1lGT2aKoQCbdjB_RX__InY/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/p2XLIrIddiQ
      video_credit: Kolibri#7675

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 1.5
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Box
        center: Player
        offset: [0, -0.6]
        box: [2.2, 3]
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Box
        center: Player
        box: [3, 4.5]
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA-1
        shape: Circle
        center: Player
        offset: [0, 0.3]
        radius: 2.8

      - name: CA-2
        shape: Circle
        center: Player
        offset: [0, 0.3]
        radius: 2.8
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

  - name: skill
    hitbox:
      - name: E-Initial
        shape: Circle
        center: Player
        radius: 2.5

      - name: E-ShootingStar
        note: 'At every tick: Look for the closest enemy within 10m radius of Player. If no enemy was found, then check again in 0.1s. Otherwise, spawn the attack in 0.5s.'
        shape: Circle
        center: GlobalValue
        radius: 0.8

  - name: burst
    params:
      travel: Projectile travel time for Starlight Slugs. Default 22 frames.
    hitbox:
      - name: Q
        note: 'At every tick: Look for the closest enemy within 12m radius of Player with offsetY: 1. If an enemy was found, spawn the attack at their position.'
        shape: Circle
        center: GlobalValue
        radius: 1.5
