id: 10000074
key: "layla"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_SUMERU
element: Ice
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Layla"
stats: {
   base_hp: 930.0268
   base_atk: 18.16416
   base_def: 54.936
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 694.77765
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 41.04
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 13.569876
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1188.4354
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 70.2
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.21163
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1846.6459
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 109.08
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 36.067303
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2340.3037
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 138.24
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 45.709057
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2833.9614
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 167.4
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 55.35081
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3327.6194
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 196.56
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 64.99256
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10742
   burst: 10745
   attack: 10741
   burst_energy_cost: 40
}
name_text_hash_map: 2889777514
