use: pipeline
kind: weapon
name: prototypearchaic

shortcuts:
  - archaic

abilities:
  - name: default
    hitbox:
      - name: Prototype Archaic
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 3
