use: pipeline
kind: character
name: xianyun

shortcuts:
  - cloudretainer
  - liuyun

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - charged: attack(Charged Attack DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skillPress: skill(Skill DMG)
  - leap:
      - skill(Driftcloud Wave DMG)
      - skill(Driftcloud Wave DMG|1)
      - skill(Driftcloud Wave DMG|2)

  - burst: burst(Skill DMG)
  - burstDot: burst(Starwicker DMG)
  - healInstantFlat: burst(Healing|1)
  - healInstantP: burst(Healing)
  - healDotFlat: burst(Continuous Healing|1)
  - healDotP: burst(Continuous Healing)

docs:
  issues:
    - Not all characters can plunge after a Adeptal Assistance boosted jump
  fields:
    .xianyun.adeptal-assistance: Number of Adeptal Assistance stacks.
  frames:
    - count: https://docs.google.com/spreadsheets/d/1LkWYcksW1T2JpyMiJsa24O7rZTFWG5HZoQ8rtvD_x7U/edit?usp=sharing
      count_credit: caramielle.
      video: https://youtu.be/HhyU2N8RlLA
      video_credit: caramielle.
    - count: https://docs.google.com/spreadsheets/d/1LkWYcksW1T2JpyMiJsa24O7rZTFWG5HZoQ8rtvD_x7U/edit?usp=sharing
      count_credit: caramielle.
      video: https://youtu.be/13sL723GdN8
      video_credit: caramielle.
    - count: https://docs.google.com/spreadsheets/d/1LkWYcksW1T2JpyMiJsa24O7rZTFWG5HZoQ8rtvD_x7U/edit?usp=sharing
      count_credit: caramielle.
      video: https://youtu.be/SryZPN06PHQ
      video_credit: caramielle.
    - count: https://docs.google.com/spreadsheets/d/1LkWYcksW1T2JpyMiJsa24O7rZTFWG5HZoQ8rtvD_x7U/edit?usp=sharing
      count_credit: caramielle.
      video: https://youtu.be/9cC7m4lDgC0
      video_credit: caramielle.
    - count: https://docs.google.com/spreadsheets/d/1LkWYcksW1T2JpyMiJsa24O7rZTFWG5HZoQ8rtvD_x7U/edit?usp=sharing
      count_credit: caramielle.
      video: https://youtu.be/5P3JuDcXaKI
      video_credit: caramielle.
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: caramielle.
      video: https://youtu.be/D10blp5aqG4
      video_credit: caramielle.

abilities:
  - name: attack
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: N1
        shape: Circle
        center: PrimaryTarget
        radius: 0.8

      - name: N2
        shape: Circle
        center: PrimaryTarget
        radius: 0.8

      - name: N3
        shape: Circle
        center: PrimaryTarget
        radius: 0.8

      - name: N4
        shape: Circle
        center: PrimaryTarget
        radius: 1

  - name: charge
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: CA
        note: This is an approximation because the projectile does single target damage to every enemy it collides with on the path.
        shape: Circle
        center: PrimaryTarget
        radius: 3

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        radius: 1.5

      - name: Low_Plunge
        shape: Circle
        center: Player
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        radius: 3.5

  - name: low_plunge
    note: Previous action must be jump buffed via Xianyun's burst for example or must be still in Cloud Transmogrification state (Xianyun E).
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be jump buffed via Xianyun's burst for example or must be still in Cloud Transmogrification state (Xianyun E).
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    hitbox:
      - name: E
        note: This is an approximation because we do not simulate E damage triggering on collision between character model and enemy.
        shape: Circle
        center: Player
        radius: 1.5

      - name: E-Plunge
        shape: Circle
        center: Player
        radius: 4

      - name: EE-Plunge
        shape: Circle
        center: Player
        radius: 5

      - name: EEE-Plunge
        shape: Circle
        center: Player
        radius: 6.5

  - name: burst
    hitbox:
      - name: Q-Initial
        shape: Circle
        center: Player
        radius: 7

      - name: Q-Starwicker
        shape: Circle
        center: Player
        radius: 4.8
