package_name: xianyun
genshin_id: 10000093
key: xianyun
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    attack_4:
      - 3 # 4-Hit DMG|{param3:F1P}
    charged:
      - 4 # Charged Attack DMG|{param4:F1P}
    collision:
      - 6 # Plunge DMG|{param6:F1P}
    highPlunge:
      - 8 # Low/High Plunge DMG|{param7:P}/{param8:P}
    lowPlunge:
      - 7 # Low/High Plunge DMG|{param7:P}/{param8:P}
  skill:
    leap:
      - 1 # Driftcloud Wave DMG|{param1:F1P}/{param2:F1P}/{param3:F1P}
      - 2 # Driftcloud Wave DMG|{param1:F1P}/{param2:F1P}/{param3:F1P}
      - 3 # Driftcloud Wave DMG|{param1:F1P}/{param2:F1P}/{param3:F1P}
    skillPress:
      - 0 # Skill DMG|{param0:F2P}
  burst:
    burst:
      - 0 # Skill DMG|{param0:F1P}
    burstDot:
      - 1 # Starwicker DMG|{param1:F1P}
    healDotFlat:
      - 4 # Continuous Healing|{param5:F1P} ATK+{param4:I}
    healDotP:
      - 5 # Continuous Healing|{param5:F1P} ATK+{param4:I}
    healInstantFlat:
      - 2 # Healing|{param3:F1P} ATK+{param2:I}
    healInstantP:
      - 3 # Healing|{param3:F1P} ATK+{param2:I}

documentation:
  fields_data:
    - fields: [.xianyun.adeptal-assistance]
      desc: Number of Adeptal Assistance stacks.
