id: 10000026
key: "xianyun"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_LIYUE
element: Wind
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Xianyun"
stats: {
   base_hp: 991.4528198242188
   base_atk: 27.185199737548828
   base_def: 62.223201751708984
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 850.0811157226562
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 53.35200119018555
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.307147979736328
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1454.086181640625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 91.26000213623047
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.867488861083984
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.04800000041723251
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2259.42626953125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 141.8040008544922
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.94794464111328
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.09600000083446503
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2863.43115234375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 179.71200561523438
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 78.50828552246094
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.09600000083446503
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3467.436279296875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 217.6199951171875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 95.0686264038086
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.14399999380111694
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4071.441162109375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 255.5279998779297
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 111.62897491455078
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.19200000166893005
      }
   }
}
skill_details: {
   skill: 10262
   burst: 10265
   attack: 10261
   burst_energy_cost: 70
}
name_text_hash_map: 1021947690
