id: 10000093
key: "xianyun"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_LIYUE
element: Wind
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Liuyun"
stats: {
   base_hp: 810.322
   base_atk: 26.068
   base_def: 44.57335
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 694.77783
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 38.2185
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.34932
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1188.4358
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 65.37375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 38.2291
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1846.6464
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 101.58075
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 59.40214
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2340.3042
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 128.736
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 75.28192
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2833.9622
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 155.89125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 91.1617
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3327.62
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 183.0465
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 107.04148
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 10932
   burst: 10935
   attack: 10931
   burst_energy_cost: 70
}
name_text_hash_map: 3648220770
