id: 10000093
key: "xianyun"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_LIYUE
element: Wind
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Liuyun"
stats: {
   base_hp: 810.322021484375
   base_atk: 26.06800079345703
   base_def: 44.57334899902344
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 694.77783203125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 38.21849822998047
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.349319458007812
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1188.435791015625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 65.37374877929688
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 38.22909927368164
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.07199999690055847
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1846.6463623046875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 101.58074951171875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 59.40214157104492
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.14399999380111694
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2340.30419921875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 128.73599243164062
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 75.28192138671875
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.14399999380111694
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2833.962158203125
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 155.89125061035156
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 91.16169738769531
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.2160000056028366
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3327.6201171875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 183.04649353027344
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 107.0414810180664
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.2879999876022339
      }
   }
}
skill_details: {
   skill: 10932
   burst: 10935
   attack: 10931
   burst_energy_cost: 70
}
name_text_hash_map: 3648220770
