// Code generated by "pipeline"; DO NOT EDIT.

// set2: Aubade of Morningstar and Moon
//
//	Increases Elemental Mastery by 80.
//
// set4: Aubade of Morningstar and Moon # Relic_6.3_Columbia
//
//	When the equipping character is off-field, Lunar Reaction DMG is increased by 20%.
//	When the party's Moonsign Level is at least Ascendant Gleam, Lunar Reaction DMG will
//	be further increased by 40%. This effect will disappear after the equipping character
//	is active for 3s.
package aubade

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterSetFunc(keys.AubadeOfMorningstarAndMoon, NewSet)
}
