use: pipeline
kind: character
name: chevreuse

override:
  icd_group:
    ChevreuseBurstMines:
      damage: [1, 1, 1, 1, 1, 1, 1, 1]
      durability: [1, 0, 0, 1, 0, 0, 0, 0]
      timer: 5

shortcuts:
  - chev

combat:
  icd_groups:
    - ChevreuseBurstMines

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG|1)
      - attack(4-Hit DMG)
  - charge: attack(Charged Attack DMG)

  - skillPress: skill(Press DMG)
  - skillHold: skill(Hold DMG)
  - skillOvercharged: skill(Overcharged Ball DMG)
  - skillHpRegen: skill(HP Regeneration Over Time)
  - skillHpFlat: skill(HP Regeneration Over Time|1)
  - arkhe: skill(Surging Blade DMG)

  - burst: burst(Explosive Grenade DMG)
  - burstSecondary: burst(Secondary Explosive Shell DMG)

docs:
  fields:
    .chevreuse.overcharged-ball: Whether Chevreuse has an Overcharged Ball or not.
  frames:
    - count: https://docs.google.com/spreadsheets/d/1-fEnJy6XauKeLU0lhKSIgs3FDHPB_pZ_X6M19DFDv9I/edit#gid=0
      count_credit: caramielle
      video: https://youtu.be/s1n34crsOeA
      video_credit: charliex3000
    - count: https://docs.google.com/spreadsheets/d/1-fEnJy6XauKeLU0lhKSIgs3FDHPB_pZ_X6M19DFDv9I/edit#gid=0
      count_credit: caramielle
      video: https://youtu.be/EfdAPYmsgEE
      video_credit: caramielle
    - count: https://docs.google.com/spreadsheets/d/1-fEnJy6XauKeLU0lhKSIgs3FDHPB_pZ_X6M19DFDv9I/edit#gid=0
      count_credit: caramielle
      video: https://youtu.be/5rZmXDeMw0E
      video_credit: caramielle

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Box
        center: Player
        box: [1.6, 2]
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.4]
        radius: 1.6
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N3-1
        shape: Box
        center: Player
        box: [1.6, 2]

      - name: N3-2
        shape: Circle
        center: Player
        offset: [0, 0.4]
        radius: 1.6
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Box
        center: Player
        offset: [0, 1]
        box: [1.5, 4]
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 0.8
        hitlag: {scale: 0.01, defense_halt: true, deployable: true}

  - name: skill
    params:
      hold: 0 for Tap (default), value between 1 and 301 for Hold. The number determines the E duration in frames.
    hitbox:
      - name: E-Tap
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [2, 6]

      - name: E-Hold
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [3, 7]

      - name: E-Overcharged-Ball
        shape: Circle
        center: PrimaryTarget
        radius: 5

      - name: E-Surging-Blade
        note: Spawns on the first enemy hit by E.
        shape: Circle
        center: GlobalValue
        radius: 2

  - name: burst
    hitbox:
      - name: Q
        shape: Circle
        center: PrimaryTarget
        radius: 6

      - name: Q-Explosive-Shell
        note: There are 8 shells which split the 6m radius around the Q hit pos into 8 equal parts. Each shell attack extends to the edge of the radius.
        shape: Circle
        center: GlobalValue
        fan_angle: 60
        radius: 6

  - name: cons
    hitbox:
      - name: C2
        note: 'Spawns at X: -1.5/1.5m offset from the target that the C2 proc''d on.'
        shape: Circle
        center: GlobalValue
        radius: 3
