id: 10000090
key: "chevreuse"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_FONTAINE
element: Fire
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Chevreuse"
stats: {
   base_hp: 1002.9701
   base_atk: 16.20528
   base_def: 50.70135
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 749.27
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 37.8765
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 12.106458
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1281.6461
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 64.78875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 20.708414
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1991.4808
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 100.67175
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 32.177692
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2523.857
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 127.584
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.779648
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3056.233
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 154.49625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 49.381603
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3588.6091
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 181.4085
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 57.983562
      }
      add_props: {
         prop_type: FIGHT_PROP_HP_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10902
   burst: 10905
   attack: 10901
   burst_energy_cost: 60
}
name_text_hash_map: 540313842
