use: pipeline
kind: character
name: klee

combat:
  icd_tags:
    - KleeFireDamage

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
  - charge: attack(Charged Attack DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - jumpy: skill(Jumpy Dumpty DMG)
  - mine: skill(Mine DMG)

  - burst: burst(Sparks 'n' Splash DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1cRHRn2iR8knyzcioUGGoMFNZgaNJQdlpkUqjeIPowCM/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/jDQDx1hhzkc
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ?t=915
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: kolibri._.
      video: https://youtu.be/Tjw7RLJaxko
      video_credit: kolibri._.

abilities:
  - name: attack
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: N1
        shape: Circle
        center: PrimaryTarget
        radius: 1

      - name: N2
        shape: Circle
        center: PrimaryTarget
        radius: 1

      - name: N3
        shape: Circle
        center: PrimaryTarget
        radius: 1.5

  - name: charge
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 3

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        radius: 1.5

      - name: Low_Plunge
        shape: Circle
        center: Player
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        radius: 3.5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    params:
      bounce: Number of bounce hits. Default 1 hit.
      mine: Number of mines hits. Default 2 hits.
      mine_delay: Time until all mines explode. Default 240 frames.
      release: 0 for Skill cancel (relevant for 4pc Crimson Witch stacks), 1 for Skill (default).
    hitbox:
      - name: E-JumptyDumpty-Bounce1
        shape: Circle
        center: PrimaryTarget
        radius: 4

      - name: E-JumptyDumpty-Bounce2
        shape: Circle
        center: PrimaryTarget
        radius: 4

      - name: E-JumptyDumpty-Bounce3
        shape: Circle
        center: PrimaryTarget
        radius: 4

      - name: E-Mine
        note: Mine mechanics are not properly implemented yet.
        shape: Circle
        center: PrimaryTarget
        radius: 2
        hitlag: {defense_halt: true, deployable: true}

  - name: burst
    hitbox:
      - name: Q
        note: 'At every tick: Spawn 3 waves with 3-5 attacks total: 1. 1 attack; 2. 1 attack + 30% chance at +1; 3. 1 attack + 50% chance at +1.'
        shape: Circle
        center: PrimaryTarget
        radius: 1.5
        hitlag: {defense_halt: true, deployable: true}

  - name: cons
    hitbox:
      - name: C1
        shape: Circle
        center: PrimaryTarget
        radius: 1.5
        hitlag: {defense_halt: true, deployable: true}

      - name: C4
        shape: Circle
        center: Player
        radius: 5
        hitlag: {defense_halt: true, deployable: true}
