package_name: klee
genshin_id: 10000029
key: klee
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        charge:
            - 3 # Charged Attack DMG|{param3:P}
        collision:
            - 5 # Plunge DMG|{param6:F1P}
        lowPlunge:
            - 6 # Low/High Plunge DMG|{param7:P}/{param8:P}
        highPlunge:
            - 7 # Low/High Plunge DMG|{param7:P}/{param8:P}
    skill:
        jumpy:
            - 0 # Jumpy Dumpty DMG|{param0:F1P}
        mine:
            - 3 # Mine DMG|{param3:F1P}
    burst:
        burst:
            - 0 # Sparks ''n'' Splash DMG|{param0:F1P}
