id: 10000029
key: "klee"
rarity: QUALITY_ORANGE
body: BODY_LOLI
region: ASSOC_TYPE_MONDSTADT
element: Fire
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Klee"
stats: {
   base_hp: 800.7888
   base_atk: 24.206
   base_def: 47.864
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 686.604
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 41.04
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 20.75294
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1174.4542
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 70.2
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 35.49845
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1824.9211
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 109.08
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 55.15913
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2312.7712
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 138.24
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 69.90464
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2800.6216
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 167.4
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 84.65015
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3288.4717
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 196.56
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 99.39566
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 10292
   burst: 10295
   attack: 10291
   burst_energy_cost: 60
}
name_text_hash_map: 3339083250
