// Code generated by "pipeline"; DO NOT EDIT.

// passive: Strong-Willed # Weapon_Bow_RiseDMGWithTime
//
//	Increases Normal and Charged Attack DMG by 12%. After a Normal or Charged Attack
//	is fired, DMG dealt increases by a further 8% every 0.1s the arrow is in the air
//	for up to 5 times.
package amos

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.AmosBow, NewWeapon)
}
