// Code generated by "pipeline"; DO NOT EDIT.

// passive: Infusion Scroll # Weapon_Catalyst_ElementUpAfterReaction
//
//	Triggering an Elemental reaction grants a 8% Elemental DMG Bonus for 10s. Max 2 stacks.
package mappa

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.MappaMare, NewWeapon)
}
