package_name: itto
genshin_id: 10000057
key: itto
action_param_keys:
    skill:
      - param: "travel"
      - param: "ushihit"
    burst:
      - param: prestack
    low_plunge:
      - param: "collision"
    high_plunge:
      - param: "collision"
skill_data_mapping:
    attack:
        akCombo:
            - 5 # Arataki Kesagiri Combo Slash DMG|{param5:F1P}
        akFinal:
            - 6 # Arataki Kesagiri Final Slash DMG|{param6:F1P}
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        saichiSlash:
            - 4 # Saichimonji Slash DMG|{param4:F1P}
        collision:
            - 8 # Plunge DMG|{param6:F1P}
        lowPlunge:
            - 9 # Low/High Plunge DMG|{param7:P}/{param8:P}
        highPlunge:
            - 10 # Low/High Plunge DMG|{param7:P}/{param8:P}
    skill:
        skill:
            - 0 # Skill DMG|{param0:P}
    burst:
        defconv:
            - 1 # ATK Bonus|{param1:F1P} DEF

documentation:
    fields_data:
        - fields: [.itto.slash.current]
          desc: Returns the current CA Slash. Perform checks on this by using the values under .itto.slash-type.
        - fields: [.itto.slash.next]
          desc: Returns the next CA Slash that will be performed based on the stack count at the time that this is evaluated. Perform checks on this by using the values under .itto.slash-type.
        - fields: [.itto.slash-type.idle]
          desc: Returns the number that represents the CA Idle state.
        - fields: [.itto.slash-type.saichi]
          desc: Returns the number that represents the CA Saichimonji Slash state.
        - fields: [.itto.slash-type.left]
          desc: Returns the number that represents the CA Left Combo Slash state.
        - fields: [.itto.slash-type.right]
          desc: Returns the number that represents the CA Right Combo Slash state.
        - fields: [.itto.slash-type.final]
          desc: Returns the number that represents the CA Final Slash state.
        - fields: [.itto.will-c6-proc]
          desc: Returns whether C6 will proc for the upcoming CA.
