use: pipeline
kind: character
name: aratakiitto

shortcuts:
  - aratakitheoneandoniitto
  - itto

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - saichiSlash: attack(Saichimonji Slash DMG)
  - akCombo: attack(Arataki Kesagiri Combo Slash DMG)
  - akFinal: attack(Arataki Kesagiri Final Slash DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skill: skill(Skill DMG)

  - defconv: burst(ATK Bonus)

docs:
  fields:
    .itto.slash-type.final: Returns the number that represents the CA Final Slash state.
    .itto.slash-type.idle: Returns the number that represents the CA Idle state.
    .itto.slash-type.left: Returns the number that represents the CA Left Combo Slash state.
    .itto.slash-type.right: Returns the number that represents the CA Right Combo Slash state.
    .itto.slash-type.saichi: Returns the number that represents the CA Saichimonji Slash state.
    .itto.slash.current: Returns the current CA Slash. Perform checks on this by using the values under .itto.slash-type.
    .itto.slash.next: Returns the next CA Slash that will be performed based on the stack count at the time that this is evaluated. Perform checks on this by using the values under .itto.slash-type.
    .itto.will-c6-proc: Returns whether C6 will proc for the upcoming CA.
  frames:
    - count: https://docs.google.com/spreadsheets/d/13ad3uH2DazxotwjQE6qvWRfcQJpmhkxN4nsbc3vUx78/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/1slUOvTY9c0
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/13ad3uH2DazxotwjQE6qvWRfcQJpmhkxN4nsbc3vUx78/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/6Yq8StVQFOk
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ?t=634
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: kolibri._.
      video: https://youtu.be/ADSLv-IRX4w
      video_credit: kolibri._.

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 2.5

      - name: Q-N1
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 3.5
        hitlag: {time: 0.08, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 2.5

      - name: Q-N2
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 3.5
        hitlag: {time: 0.08, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Circle
        center: Player
        offset: [0, 0.85]
        radius: 2.5

      - name: Q-N3
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 3.5
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Box
        center: Player
        offset: [0, -1.5]
        box: [3.2, 6]

      - name: Q-N4
        shape: Box
        center: Player
        offset: [0, -1.7]
        box: [3.8, 8]
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

  - name: charge
    hitbox:
      - name: CA-SaichimonjiSlash
        shape: Circle
        center: Player
        radius: 3

      - name: Q-CA-SaichimonjiSlash
        shape: Circle
        center: Player
        radius: 4
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

      - name: CA-AratakiKesagiriFinal
        shape: Circle
        center: Player
        offset: [0, 0.6]
        radius: 3.5

      - name: Q-CA-AratakiKesagiriFinal
        shape: Circle
        center: Player
        offset: [0, 0.8]
        radius: 4.3
        hitlag: {time: 0.1, scale: 0.01, defense_halt: true}

      - name: CA-AratakiKesagiriCombo
        shape: Box
        center: Player
        offset: [0, -2]
        box: [3.8, 5.5]

      - name: Q-CA-AratakiKesagiriCombo
        shape: Box
        center: Player
        offset: [0, -2.5]
        box: [5, 7]

      - name: Q-CA-AratakiKesagiriCombo-FirstCS
        shape: Box
        center: Player
        offset: [0, -2.5]
        box: [5, 7]
        hitlag: {time: 0.07, scale: 0.01, defense_halt: true}

      - name: Q-CA-AratakiKesagiriCombo-SecondCS
        shape: Box
        center: Player
        offset: [0, -2.5]
        box: [5, 7]
        hitlag: {time: 0.05, scale: 0.01, defense_halt: true}

      - name: Q-CA-AratakiKesagiriCombo-Third+CS
        shape: Box
        center: Player
        offset: [0, -2.5]
        box: [5, 7]
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Q-Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

      - name: Q-Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 4

      - name: Q-High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 6

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    params:
      travel: Projectile travel time. Default 4 frames.
      ushihit: Number of stacks gained via Ushi getting hit. Max 3 stacks. Stacks are gained at random points during Ushi uptime while respecting 2s stack gain cooldown. Default 0.
    hitbox:
      - name: E-Skill
        shape: Circle
        center: PrimaryTarget
        radius: 3.5
        hitlag: {time: 0.02, scale: 0.01, deployable: true}

  - name: burst
    params:
      prestack: Whether to grant a stack from performing N1 right before Q. 0 for no prestack, 1 for prestack. Default 0.

  - name: walk
    note: No action followed by walk (except low_plunge and high_plunge) has proper frames.
