id: 10000057
key: "itto"
rarity: QUALITY_ORANGE
body: BODY_MALE
region: ASSOC_TYPE_INAZUMA
element: Rock
weapon_class: WEAPON_CLAYMORE
icon_name: "UI_AvatarIcon_Itto"
stats: {
   base_hp: 1000.986
   base_atk: 17.689
   base_def: 74.66784
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 858.255
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 64.0224
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 15.16561
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1468.0677
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 109.512
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 25.941175
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2281.1514
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 170.1648
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.308594
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2890.964
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 215.6544
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 51.08416
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3500.7769
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 261.144
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.859726
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4110.59
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 306.6336
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 72.63529
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10572
   burst: 10575
   attack: 10571
   burst_energy_cost: 70
}
name_text_hash_map: 3068316954
