use: pipeline
kind: character
name: eula

talents:
  - auto:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG)
      - attack(4-Hit DMG)
      - - attack(5-Hit DMG)
        - attack(5-Hit DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skillPress: skill(Press DMG)
  - icewhirl: skill(Icewhirl Brand DMG)
  - resRed: skill(Physical RES Decrease)

  - burstInitial: burst(Skill DMG)
  - skillHold: burst(Skill DMG)
  - burstExplodeBase: burst(Lightfall Sword Base DMG)
  - burstExplodeStack: burst(DMG Per Stack)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1NCDFtvqFdXlVRd_0eH2tPw7xMD50AxUCvbWDh1XGhEw/edit
      count_credit: Shizuka#7791
      video: https://youtu.be/Bj7C6zs4Xsc
      video_credit: Shizuka#7791
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ?t=411
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: kolibri._.
      video: https://youtu.be/9dtr-xVaPAo
      video_credit: kolibri._.

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        fan_angle: 270
        radius: 2
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        fan_angle: 270
        radius: 2
        hitlag: {time: 0.12, scale: 0.01, defense_halt: true}

      - name: N3-1
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 2

      - name: N3-2
        shape: Circle
        center: Player
        offset: [0, 0.5]
        radius: 2
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Circle
        center: Player
        fan_angle: 270
        radius: 2
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: N5-1
        shape: Box
        center: Player
        box: [2, 3]

      - name: N5-2
        shape: Box
        center: Player
        box: [2, 3]
        hitlag: {time: 0.12, scale: 0.01, defense_halt: true}

  - name: charge
    hitbox:
      - name: CA-Spinning
        note: not implemented yet
        shape: Circle
        center: Player
        offset: [0, 0.3]
        radius: 3
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true, deployable: true}

      - name: CA-Final
        note: not implemented yet
        shape: Circle
        center: Player
        radius: 3.5
        hitlag: {time: 0.15, scale: 0.01, defense_halt: true, deployable: true}

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    params:
      hold: 0 for Tap (default), 1 for Hold.
    hitbox:
      - name: E-Tap
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3.5
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: E-Hold
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5.5
        hitlag: {time: 0.12, scale: 0.01, defense_halt: true}

      - name: E-IcewhirlBrand-1
        shape: Circle
        center: GlobalValue
        radius: 3.5

      - name: E-IcewhirlBrand-2
        shape: Circle
        center: GlobalValue
        radius: 3.5

  - name: burst
    hitbox:
      - name: Q-Start
        note: not implemented yet
        shape: Circle
        center: Player
        radius: 4

      - name: Q-Initial
        shape: Circle
        center: Player
        radius: 8

      - name: Q-LightfallSword
        shape: Circle
        center: Player
        radius: 6.5

  - name: asc
    hitbox:
      - name: E-A1
        shape: Circle
        center: Player
        offset: [0, 2]
        radius: 6.5

  - name: walk
    note: Everything except normal followed by walk has proper frames.
