package_name: eula
genshin_id: 10000051
key: eula
skill_data_mapping:
    attack:
        auto_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        auto_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        auto_3:
            - 2 # 3-Hit DMG|{param2:F1P}+{param2:F1P}
            - 2 # 3-Hit DMG|{param2:F1P}+{param2:F1P}
        auto_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        auto_5:
            - 4 # 5-Hit DMG|{param4:F1P}+{param4:F1P}
            - 4 # 5-Hit DMG|{param4:F1P}+{param4:F1P}

        collision:
            - 9 # Plunge DMG|{param6:F1P}
        lowPlunge:
            - 10 # Low/High Plunge DMG|{param7:P}/{param8:P}
        highPlunge:
            - 11 # Low/High Plunge DMG|{param7:P}/{param8:P}
    skill:
        icewhirl:
            - 2 # Icewhirl Brand DMG|{param2:P}
        resRed:
            - 3 # Physical RES Decrease|{param3:P}
        skillPress:
            - 0 # #{LAYOUT_MOBILE#Tap}{LAYOUT_PC#Press}{LAYOUT_PS#Press} DMG|{param0:P}
    burst:
        burstExplodeBase:
            - 1 # Lightfall Sword Base DMG|{param1:F1P}
        burstExplodeStack:
            - 2 # DMG Per Stack|{param2:F1P}
        burstInitial:
            - 0 # Skill DMG|{param0:P}
        skillHold:
            - 0 # Skill DMG|{param0:P}
