// Code generated by "pipeline"; DO NOT EDIT.

// passive: Unreturning # Weapon_Bow_AttackGainSPDAKTBuff
//
//	Charged Attack hits on weak points increase Movement SPD by 10% and ATK by 36% for
//	10s.
package prototype

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.PrototypeCrescent, NewWeapon)
}
