use: pipeline
kind: character
name: neuvillette

shortcuts:
  - chiefjusticeoffontaine
  - neuv

combat:
  icd_tags:
    - NeuvilletteC6

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
  - charge: attack(Charged Attack DMG)
  - chargeJudgement: 'attack(Charged Attack: Equitable Judgment)'

  - skill: skill(Skill DMG)
  - thorn: skill(Spiritbreath Thorn DMG)

  - burst: burst(Skill DMG)
  - burstWaterfall: burst(Waterfall DMG)

docs:
  fields:
    .neuvillette.droplets: 'Number of Sourcewater droplets in range for Charged Attack Empowerment: Legal Evaluation.'
    .neuvillette.droplets-c6: Number of Sourcewater droplets in range for C6.
  frames:
    - count: https://docs.google.com/spreadsheets/d/1-gPxRq_NX8hBXLijRYroabSgT85S0ND6WiFLjwc2b_k/edit#usp=sharing
      count_credit: dejaroo
      video: https://youtu.be/I4nCOk2g17o
      video_credit: charliex3000
    - count: https://docs.google.com/spreadsheets/d/1-gPxRq_NX8hBXLijRYroabSgT85S0ND6WiFLjwc2b_k/edit#usp=sharing
      count_credit: charliex3000
      video: https://youtu.be/HViQwc6zGrs
      video_credit: charliex3000

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: PrimaryTarget
        radius: 1

      - name: N2
        shape: Circle
        center: PrimaryTarget
        radius: 1

      - name: N3
        shape: Circle
        center: PrimaryTarget
        radius: 1.5

  - name: charge
    params:
      short: '0 for Charged Attack: Equitable Judgment (default), 1 for Charged Attack. Charged Attack will still absorb droplets if possible. This mirrors in game behaviour.'
      ticks: 'Number of ticks for Charged Attack: Equitable Judgment. Default is maximum number of ticks, minimum 1. Only works if short = 0. If the number of ticks is not the maximum, the next action must be Burst, Skill, Dash, or Jump.'
    hitbox:
      - name: CA-Judgement
        shape: Box
        center: Player
        box: [3.5, 15]

      - name: CA
        shape: Box
        center: Player
        box: [3, 8]

  - name: skill
    hitbox:
      - name: E-Initial
        shape: Circle
        center: PrimaryTarget
        radius: 6

      - name: E-Spiritbreath-Thorn
        shape: Circle
        center: PrimaryTarget
        radius: 4.5
        hitlag: {scale: 0.01, defense_halt: true}

  - name: burst
    hitbox:
      - name: Q-Initial
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 8

      - name: Q-Waterfall
        note: There are 2 attacks. If there is a target within 10m, they will spawn with centers randomly placed in a 1.5m radius circle from target pos, with offsetX -1.5/1.5, respectively, using the target's direction. Otherwise, the two attacks will spawn on the player with offsetX -3/4 and offsetY 7.5/6, respectively.
        shape: Circle
        center: GlobalValue
        radius: 5

  - name: cons
    hitbox:
      - name: C6
        note: C6 projectile mechanics (collision) are not properly implemented yet.
        shape: Circle
        center: PrimaryTarget
        radius: 0.5
