package_name: neuvillette
genshin_id: 10000087
key: neuvillette
icd_tags:
  - ICDTagNeuvilletteC6
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    charge:
      - 3 # Charged Attack DMG|{param3:F1P}
    chargeJudgement:
      - 4 # Charged Attack: Equitable Judgment|{param4:F2P} Max HP
  skill:
    skill:
      - 0 # Skill DMG|{param0:F2P} Max HP
    thorn:
      - 1 # Spiritbreath Thorn DMG|{param1:F1P}
  burst:
    burst:
      - 0 # Skill DMG|{param0:F2P} Max HP
    burstWaterfall:
      - 1 # Waterfall DMG|{param1:F2P} Max HP
