// Code generated by "pipeline"; DO NOT EDIT.

package illuga

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Illuga, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Illuga, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: OathkeepersSpear - 1-Hit DMG: {0}
			0.473662,
			0.512216,
			0.55077,
			0.605847,
			0.644401,
			0.688462,
			0.749047,
			0.809632,
			0.870217,
			0.936309,
			1.002401,
			1.068494,
			1.134586,
			1.200679,
			1.266771,
		}},
		{{ // attack: OathkeepersSpear - 2-Hit DMG: {1}
			0.485255,
			0.524753,
			0.56425,
			0.620675,
			0.660172,
			0.705313,
			0.76738,
			0.829448,
			0.891515,
			0.959225,
			1.026935,
			1.094645,
			1.162355,
			1.230065,
			1.297775,
		}},
		{
			{ // attack: OathkeepersSpear - 3-Hit DMG: {2}+{3}
				0.31433,
				0.339915,
				0.3655,
				0.40205,
				0.427635,
				0.456875,
				0.49708,
				0.537285,
				0.57749,
				0.62135,
				0.66521,
				0.70907,
				0.75293,
				0.79679,
				0.84065,
			},
			{ // attack: OathkeepersSpear - 3-Hit DMG: {2}+{3}
				0.31433,
				0.339915,
				0.3655,
				0.40205,
				0.427635,
				0.456875,
				0.49708,
				0.537285,
				0.57749,
				0.62135,
				0.66521,
				0.70907,
				0.75293,
				0.79679,
				0.84065,
			},
		},
		{{ // attack: OathkeepersSpear - 4-Hit DMG: {4}
			0.762786,
			0.824873,
			0.88696,
			0.975656,
			1.037743,
			1.1087,
			1.206266,
			1.303831,
			1.401397,
			1.507832,
			1.614267,
			1.720702,
			1.827138,
			1.933573,
			2.040008,
		}},
	}
	// attack: OathkeepersSpear - Charged Attack DMG: {5}
	charge = []float64{
		1.11026,
		1.20063,
		1.291,
		1.4201,
		1.51047,
		1.61375,
		1.75576,
		1.89777,
		2.03978,
		2.1947,
		2.34962,
		2.50454,
		2.65946,
		2.81438,
		2.9693,
	}
	// attack: OathkeepersSpear - Plunge DMG: {7}
	collision = []float64{
		0.639324,
		0.691362,
		0.7434,
		0.81774,
		0.869778,
		0.92925,
		1.011024,
		1.092798,
		1.174572,
		1.26378,
		1.352988,
		1.442196,
		1.531404,
		1.620612,
		1.70982,
	}
	// attack: OathkeepersSpear - Low/High Plunge DMG: {8}/{9}
	plunge_low = []float64{
		1.278377,
		1.382431,
		1.486485,
		1.635134,
		1.739187,
		1.858106,
		2.02162,
		2.185133,
		2.348646,
		2.527025,
		2.705403,
		2.883781,
		3.062159,
		3.240537,
		3.418915,
	}
	// attack: OathkeepersSpear - Low/High Plunge DMG: {8}/{9}
	plunge_high = []float64{
		1.596762,
		1.726731,
		1.8567,
		2.04237,
		2.172339,
		2.320875,
		2.525112,
		2.729349,
		2.933586,
		3.15639,
		3.379194,
		3.601998,
		3.824802,
		4.047606,
		4.27041,
	}
	// skill: DawnbearingSongbird - Press DMG: {0} Elemental Mastery+{1} DEF
	skill_tap_em = []float64{
		4.8256,
		5.18752,
		5.54944,
		6.032,
		6.39392,
		6.75584,
		7.2384,
		7.72096,
		8.20352,
		8.68608,
		9.16864,
		9.6512,
		10.2544,
		10.8576,
		11.4608,
	}
	// skill: DawnbearingSongbird - Press DMG: {0} Elemental Mastery+{1} DEF
	skill_tap_def = []float64{
		2.4128,
		2.59376,
		2.77472,
		3.016,
		3.19696,
		3.37792,
		3.6192,
		3.86048,
		4.10176,
		4.34304,
		4.58432,
		4.8256,
		5.1272,
		5.4288,
		5.7304,
	}
	// skill: DawnbearingSongbird - Hold DMG: {2} Elemental Mastery+{3} DEF
	hold_tap_em = []float64{
		6.032,
		6.4844,
		6.9368,
		7.54,
		7.9924,
		8.4448,
		9.048,
		9.6512,
		10.2544,
		10.8576,
		11.4608,
		12.064,
		12.818,
		13.572,
		14.326,
	}
	// skill: DawnbearingSongbird - Hold DMG: {2} Elemental Mastery+{3} DEF
	hold_tap_def = []float64{
		3.016,
		3.2422,
		3.4684,
		3.77,
		3.9962,
		4.2224,
		4.524,
		4.8256,
		5.1272,
		5.4288,
		5.7304,
		6.032,
		6.409,
		6.786,
		7.163,
	}
	// burst: ShadowlessReflection - Skill DMG: {0} Elemental Mastery+{1} DEF
	burst_em = []float64{
		8.272,
		8.8924,
		9.5128,
		10.34,
		10.9604,
		11.5808,
		12.408,
		13.2352,
		14.0624,
		14.8896,
		15.7168,
		16.544,
		17.578,
		18.612,
		19.646,
	}
	// burst: ShadowlessReflection - Skill DMG: {0} Elemental Mastery+{1} DEF
	burst_def = []float64{
		4.136,
		4.4462,
		4.7564,
		5.17,
		5.4802,
		5.7904,
		6.204,
		6.6176,
		7.0312,
		7.4448,
		7.8584,
		8.272,
		8.789,
		9.306,
		9.823,
	}
	// burst: ShadowlessReflection - Geo DMG Bonus: {2} Elemental Mastery
	burst_buff_geo = []float64{
		0.336,
		0.3612,
		0.3864,
		0.42,
		0.4452,
		0.4704,
		0.504,
		0.5376,
		0.5712,
		0.6048,
		0.6384,
		0.672,
		0.714,
		0.756,
		0.798,
	}
	// burst: ShadowlessReflection - Lunar-Crystallize Reaction DMG Bonus: {3} Elemental Mastery
	burst_buff_lcr = []float64{
		2.2592,
		2.42864,
		2.59808,
		2.824,
		2.99344,
		3.16288,
		3.3888,
		3.61472,
		3.84064,
		4.06656,
		4.29248,
		4.5184,
		4.8008,
		5.0832,
		5.3656,
	}
)
