// Code generated by "pipeline"; DO NOT EDIT.

// passive: Guerilla Tactics # Weapon_Catalyst_SpeedUponEnemeyKilled
//
//	Defeating an opponent increases Movement SPD and ATK by 12% for 15s.
package twin

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.TwinNephrite, NewWeapon)
}
