// Code generated by "pipeline"; DO NOT EDIT.

// set2: A Day Carved From Rising Winds
//
//	ATK +18%.
//
// set4: A Day Carved From Rising Winds # Relic_6.3_MajoKai
//
//	After a Normal Attack, Charged Attack, Elemental Skill, or Elemental Burst hits an
//	opponent, gain the Blessing of Pastoral Winds effect for 6s: ATK is increased by
//	25%. If the equipping character has completed Witch's Homework, Blessing of Pastoral
//	Winds will be upgraded to Resolve of Pastoral Winds, which additionally increases
//	the CRIT Rate of the equipping character by 20%. This effect can be triggered even
//	when the character is off-field.
package adaycarvedfromrisingwinds

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterSetFunc(keys.ADayCarvedFromRisingWinds, NewSet)
}
