package_name: kinich
genshin_id: 10000101
key: kinich
action_param_keys:
  attack:
    - param: "direction"
  skill:
    - param: "hold"
    - param: "travel"
    - param: "c6-travel"
icd_tags:
  - ICDTagKinichLoopShot
  - ICDTagKinichScalespikerCannon
icd_groups:
  - group_name: ICDGroupKinichLoopShot
    reset_timer: 120
    ele_app_sequence: [1, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1]
  - group_name: ICDGroupKinichScalespikerCannon
    reset_timer: 72
    ele_app_sequence: [1, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1]
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    charge:
      - 3 # Charged Attack DMG|{param3:F1P}x3
    collision:
      - 5 # Plunge DMG|{param5:F1P}
    lowPlunge:
      - 6 # Low/High Plunge DMG|{param6:P}/{param7:P}
    highPlunge:
      - 7 # Low/High Plunge DMG|{param6:P}/{param7:P}
  skill:
    loopShot:
      - 0 # Loop Shot DMG|{param0:F2P}x2
    scalespikerCannon:
      - 1 # Scalespiker Cannon DMG|{param1:F2P}
  burst:
    burst:
      - 0 # Skill DMG|{param0:F2P}
    dragonBreath:
      - 1 # Dragon Breath DMG|{param1:F2P}
documentation:
  fields_data:
    - fields: [.kinich.blind_spot]
      desc: The direction of the Blind Spot relatively to Kinich. -1 - in clock-wise direction; 1 - in counter clock-wise direction; 0 - does not exist at the moment.
