package_name: sucrose
genshin_id: 10000043
key: sucrose
action_param_keys:
    low_plunge:
        - param: "collision"
    high_plunge:
        - param: "collision"
skill_data_mapping:
    attack:
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        attack_4:
            - 3 # 4-Hit DMG|{param3:F1P}
        charge:
            - 4 # Charged Attack DMG|{param4:P}
        collision:
            - 6 # Plunge DMG|{param6:F1P}
        lowPlunge:
            - 7 # Low/High Plunge DMG|{param7:P}/{param8:P}
        highPlunge:
            - 8 # Low/High Plunge DMG|{param7:P}/{param8:P}
    skill:
        skill:
            - 0 # Skill DMG|{param0:P}
    burst:
        burstAbsorb:
            - 1 # Additional Elemental DMG|{param1:F1P}
        burstDot:
            - 0 # DoT|{param0:P}
