id: 10000043
key: "sucrose"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_MONDSTADT
element: Wind
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Sucrose"
stats: {
   base_hp: 775.02234
   base_atk: 14.2464
   base_def: 58.94175
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 578.9814
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 44.0325
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 10.64304
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 990.36285
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 75.31875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 18.2052
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1538.8716
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 117.03375
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 28.28808
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1950.253
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 148.32
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 35.85024
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2361.6345
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 179.60625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 43.4124
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2773.016
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 210.8925
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 50.97456
      }
      add_props: {
         prop_type: FIGHT_PROP_WIND_ADD_HURT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10432
   burst: 10435
   attack: 10431
   burst_energy_cost: 80
}
name_text_hash_map: 1053433018
