// Code generated by "pipeline"; DO NOT EDIT.

// passive: Primordial Jade Regalia # Weapon_Catalyst_Morax
//
//	For 3s after using an Elemental Burst or creating a shield, the equipping character
//	can gain the Primordial Jade Regalia effect: Restore 4.5 Energy every 2.5s, and gain
//	0.3% Elemental DMG Bonus for their corresponding Elemental Type for every 1,000 Max
//	HP they possess, up to 12%. Primordial Jade Regalia will still take effect even if
//	the equipping character is not on the field.
package jadefallssplendor

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.JadefallsSplendor, NewWeapon)
}
