// Code generated by "pipeline"; DO NOT EDIT.

package beginners

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.BeginnersProtector, NewWeapon)
}
