id: 10000060
key: "yelan"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_LIYUE
element: Water
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Yelan"
stats: {
   base_hp: 1124.9176
   base_atk: 18.9924
   base_def: 42.65879
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 964.51514
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 36.5769
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 16.283075
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1649.8285
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 62.56575
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 27.85263
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2563.5796
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 97.21755
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 43.2787
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3248.893
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 123.2064
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 54.848255
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3934.2065
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 149.19525
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 66.41781
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4619.52
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 175.1841
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 77.987366
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10607
   burst: 10610
   attack: 10606
   burst_energy_cost: 70
}
name_text_hash_map: 2848374378
