// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protos/model/data.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvatarDataMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]*AvatarData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" bson:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarDataMap) Reset() {
	*x = AvatarDataMap{}
	mi := &file_protos_model_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarDataMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarDataMap) ProtoMessage() {}

func (x *AvatarDataMap) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarDataMap.ProtoReflect.Descriptor instead.
func (*AvatarDataMap) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{0}
}

func (x *AvatarDataMap) GetData() map[string]*AvatarData {
	if x != nil {
		return x.Data
	}
	return nil
}

type AvatarData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	SubId           int32                  `protobuf:"varint,2,opt,name=sub_id,proto3" json:"sub_id,omitempty" bson:"sub_id,omitempty"`
	Key             string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty" bson:"key,omitempty"`
	Rarity          QualityType            `protobuf:"varint,4,opt,name=rarity,proto3,enum=model.QualityType" json:"rarity,omitempty" bson:"rarity,omitempty"`
	Body            BodyType               `protobuf:"varint,5,opt,name=body,proto3,enum=model.BodyType" json:"body,omitempty" bson:"body,omitempty"`
	Region          ZoneType               `protobuf:"varint,6,opt,name=region,proto3,enum=model.ZoneType" json:"region,omitempty" bson:"region,omitempty"`
	Element         Element                `protobuf:"varint,7,opt,name=element,proto3,enum=model.Element" json:"element,omitempty" bson:"element,omitempty"`
	WeaponClass     WeaponClass            `protobuf:"varint,8,opt,name=weapon_class,proto3,enum=model.WeaponClass" json:"weapon_class,omitempty" bson:"weapon_class,omitempty"`
	IconName        string                 `protobuf:"bytes,9,opt,name=icon_name,proto3" json:"icon_name,omitempty" bson:"icon_name,omitempty"`
	Stats           *AvatarStatsData       `protobuf:"bytes,10,opt,name=stats,proto3" json:"stats,omitempty" bson:"stats,omitempty"`
	SkillDetails    *AvatarSkillsData      `protobuf:"bytes,11,opt,name=skill_details,proto3" json:"skill_details,omitempty" bson:"skill_details,omitempty"`
	NameTextHashMap int64                  `protobuf:"varint,12,opt,name=name_text_hash_map,json=name_text_hash_map ,proto3" json:"name_text_hash_map,omitempty" bson:"name_text_hash_map,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AvatarData) Reset() {
	*x = AvatarData{}
	mi := &file_protos_model_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarData) ProtoMessage() {}

func (x *AvatarData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarData.ProtoReflect.Descriptor instead.
func (*AvatarData) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{1}
}

func (x *AvatarData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AvatarData) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *AvatarData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AvatarData) GetRarity() QualityType {
	if x != nil {
		return x.Rarity
	}
	return QualityType_INVALID_QUALITY_TYPE
}

func (x *AvatarData) GetBody() BodyType {
	if x != nil {
		return x.Body
	}
	return BodyType_INVALID_BODY_TYPE
}

func (x *AvatarData) GetRegion() ZoneType {
	if x != nil {
		return x.Region
	}
	return ZoneType_INVALID_ZONE_TYPE
}

func (x *AvatarData) GetElement() Element {
	if x != nil {
		return x.Element
	}
	return Element_INVALID_ELEMENT
}

func (x *AvatarData) GetWeaponClass() WeaponClass {
	if x != nil {
		return x.WeaponClass
	}
	return WeaponClass_INVALID_WEAPON_CLASS
}

func (x *AvatarData) GetIconName() string {
	if x != nil {
		return x.IconName
	}
	return ""
}

func (x *AvatarData) GetStats() *AvatarStatsData {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *AvatarData) GetSkillDetails() *AvatarSkillsData {
	if x != nil {
		return x.SkillDetails
	}
	return nil
}

func (x *AvatarData) GetNameTextHashMap() int64 {
	if x != nil {
		return x.NameTextHashMap
	}
	return 0
}

type AvatarStatsData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO: base stat should be refactor to just an array of stats
	// there is no requirement that base stat can only be 3 stats; in fact
	// ER/cr/cd can be considered as base
	BaseHp        float64          `protobuf:"fixed64,1,opt,name=base_hp,proto3" json:"base_hp,omitempty" bson:"base_hp,omitempty"`
	BaseAtk       float64          `protobuf:"fixed64,2,opt,name=base_atk,proto3" json:"base_atk,omitempty" bson:"base_atk,omitempty"`
	BaseDef       float64          `protobuf:"fixed64,3,opt,name=base_def,proto3" json:"base_def,omitempty" bson:"base_def,omitempty"`
	HpCurve       AvatarCurveType  `protobuf:"varint,4,opt,name=hp_curve,proto3,enum=model.AvatarCurveType" json:"hp_curve,omitempty" bson:"hp_curve,omitempty"`
	AtkCurve      AvatarCurveType  `protobuf:"varint,5,opt,name=atk_curve,proto3,enum=model.AvatarCurveType" json:"atk_curve,omitempty" bson:"atk_curve,omitempty"`
	DefCruve      AvatarCurveType  `protobuf:"varint,6,opt,name=def_cruve,proto3,enum=model.AvatarCurveType" json:"def_cruve,omitempty" bson:"def_cruve,omitempty"`
	PromoData     []*PromotionData `protobuf:"bytes,7,rep,name=promo_data,proto3" json:"promo_data,omitempty" bson:"promo_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarStatsData) Reset() {
	*x = AvatarStatsData{}
	mi := &file_protos_model_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarStatsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarStatsData) ProtoMessage() {}

func (x *AvatarStatsData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarStatsData.ProtoReflect.Descriptor instead.
func (*AvatarStatsData) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{2}
}

func (x *AvatarStatsData) GetBaseHp() float64 {
	if x != nil {
		return x.BaseHp
	}
	return 0
}

func (x *AvatarStatsData) GetBaseAtk() float64 {
	if x != nil {
		return x.BaseAtk
	}
	return 0
}

func (x *AvatarStatsData) GetBaseDef() float64 {
	if x != nil {
		return x.BaseDef
	}
	return 0
}

func (x *AvatarStatsData) GetHpCurve() AvatarCurveType {
	if x != nil {
		return x.HpCurve
	}
	return AvatarCurveType_INVALID_AVATAR_CURVE
}

func (x *AvatarStatsData) GetAtkCurve() AvatarCurveType {
	if x != nil {
		return x.AtkCurve
	}
	return AvatarCurveType_INVALID_AVATAR_CURVE
}

func (x *AvatarStatsData) GetDefCruve() AvatarCurveType {
	if x != nil {
		return x.DefCruve
	}
	return AvatarCurveType_INVALID_AVATAR_CURVE
}

func (x *AvatarStatsData) GetPromoData() []*PromotionData {
	if x != nil {
		return x.PromoData
	}
	return nil
}

type AvatarSkillsData struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	Skill           int32                        `protobuf:"varint,1,opt,name=skill,proto3" json:"skill,omitempty" bson:"skill,omitempty"`
	Burst           int32                        `protobuf:"varint,2,opt,name=burst,proto3" json:"burst,omitempty" bson:"burst,omitempty"`
	Attack          int32                        `protobuf:"varint,3,opt,name=attack,proto3" json:"attack,omitempty" bson:"attack,omitempty"`
	A1              int32                        `protobuf:"varint,10,opt,name=a1,proto3" json:"a1,omitempty" bson:"a1,omitempty"`
	A4              int32                        `protobuf:"varint,11,opt,name=a4,proto3" json:"a4,omitempty" bson:"a4,omitempty"`
	BurstEnergyCost float64                      `protobuf:"fixed64,4,opt,name=burst_energy_cost,proto3" json:"burst_energy_cost,omitempty" bson:"burst_energy_cost,omitempty"`
	AttackScaling   []*AvatarSkillExcelIndexData `protobuf:"bytes,5,rep,name=attack_scaling,proto3" json:"attack_scaling,omitempty" bson:"attack_scaling,omitempty"`
	SkillScaling    []*AvatarSkillExcelIndexData `protobuf:"bytes,6,rep,name=skill_scaling,proto3" json:"skill_scaling,omitempty" bson:"skill_scaling,omitempty"`
	BurstScaling    []*AvatarSkillExcelIndexData `protobuf:"bytes,7,rep,name=burst_scaling,proto3" json:"burst_scaling,omitempty" bson:"burst_scaling,omitempty"`
	A1Scaling       []*AvatarSkillExcelIndexData `protobuf:"bytes,8,rep,name=a1_scaling,proto3" json:"a1_scaling,omitempty" bson:"a1_scaling,omitempty"`
	A4Scaling       []*AvatarSkillExcelIndexData `protobuf:"bytes,9,rep,name=a4_scaling,proto3" json:"a4_scaling,omitempty" bson:"a4_scaling,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AvatarSkillsData) Reset() {
	*x = AvatarSkillsData{}
	mi := &file_protos_model_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarSkillsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarSkillsData) ProtoMessage() {}

func (x *AvatarSkillsData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarSkillsData.ProtoReflect.Descriptor instead.
func (*AvatarSkillsData) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{3}
}

func (x *AvatarSkillsData) GetSkill() int32 {
	if x != nil {
		return x.Skill
	}
	return 0
}

func (x *AvatarSkillsData) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *AvatarSkillsData) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *AvatarSkillsData) GetA1() int32 {
	if x != nil {
		return x.A1
	}
	return 0
}

func (x *AvatarSkillsData) GetA4() int32 {
	if x != nil {
		return x.A4
	}
	return 0
}

func (x *AvatarSkillsData) GetBurstEnergyCost() float64 {
	if x != nil {
		return x.BurstEnergyCost
	}
	return 0
}

func (x *AvatarSkillsData) GetAttackScaling() []*AvatarSkillExcelIndexData {
	if x != nil {
		return x.AttackScaling
	}
	return nil
}

func (x *AvatarSkillsData) GetSkillScaling() []*AvatarSkillExcelIndexData {
	if x != nil {
		return x.SkillScaling
	}
	return nil
}

func (x *AvatarSkillsData) GetBurstScaling() []*AvatarSkillExcelIndexData {
	if x != nil {
		return x.BurstScaling
	}
	return nil
}

func (x *AvatarSkillsData) GetA1Scaling() []*AvatarSkillExcelIndexData {
	if x != nil {
		return x.A1Scaling
	}
	return nil
}

func (x *AvatarSkillsData) GetA4Scaling() []*AvatarSkillExcelIndexData {
	if x != nil {
		return x.A4Scaling
	}
	return nil
}

type AvatarSkillExcelIndexData struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	GroupId       int32                        `protobuf:"varint,1,opt,name=group_id,proto3" json:"group_id,omitempty" bson:"group_id,omitempty"`
	Index         int32                        `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty" bson:"index,omitempty"` // position in the param list
	LevelData     []*AvatarSkillExcelLevelData `protobuf:"bytes,3,rep,name=level_data,proto3" json:"level_data,omitempty" bson:"level_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarSkillExcelIndexData) Reset() {
	*x = AvatarSkillExcelIndexData{}
	mi := &file_protos_model_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarSkillExcelIndexData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarSkillExcelIndexData) ProtoMessage() {}

func (x *AvatarSkillExcelIndexData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarSkillExcelIndexData.ProtoReflect.Descriptor instead.
func (*AvatarSkillExcelIndexData) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{4}
}

func (x *AvatarSkillExcelIndexData) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *AvatarSkillExcelIndexData) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *AvatarSkillExcelIndexData) GetLevelData() []*AvatarSkillExcelLevelData {
	if x != nil {
		return x.LevelData
	}
	return nil
}

type AvatarSkillExcelLevelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty" bson:"level,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty" bson:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarSkillExcelLevelData) Reset() {
	*x = AvatarSkillExcelLevelData{}
	mi := &file_protos_model_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarSkillExcelLevelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarSkillExcelLevelData) ProtoMessage() {}

func (x *AvatarSkillExcelLevelData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarSkillExcelLevelData.ProtoReflect.Descriptor instead.
func (*AvatarSkillExcelLevelData) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{5}
}

func (x *AvatarSkillExcelLevelData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *AvatarSkillExcelLevelData) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type WeaponDataMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]*WeaponData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" bson:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeaponDataMap) Reset() {
	*x = WeaponDataMap{}
	mi := &file_protos_model_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeaponDataMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeaponDataMap) ProtoMessage() {}

func (x *WeaponDataMap) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeaponDataMap.ProtoReflect.Descriptor instead.
func (*WeaponDataMap) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{6}
}

func (x *WeaponDataMap) GetData() map[string]*WeaponData {
	if x != nil {
		return x.Data
	}
	return nil
}

type WeaponData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	Key             string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty" bson:"key,omitempty"`
	Rarity          int32                  `protobuf:"varint,3,opt,name=rarity,proto3" json:"rarity,omitempty" bson:"rarity,omitempty"` // for whatever reason weapon rarity is a number
	WeaponClass     WeaponClass            `protobuf:"varint,4,opt,name=weapon_class,proto3,enum=model.WeaponClass" json:"weapon_class,omitempty" bson:"weapon_class,omitempty"`
	ImageName       string                 `protobuf:"bytes,5,opt,name=image_name,proto3" json:"image_name,omitempty" bson:"image_name,omitempty"`
	BaseStats       *WeaponStatsData       `protobuf:"bytes,6,opt,name=base_stats,proto3" json:"base_stats,omitempty" bson:"base_stats,omitempty"`
	NameTextHashMap int64                  `protobuf:"varint,7,opt,name=name_text_hash_map,json=name_text_hash_map ,proto3" json:"name_text_hash_map,omitempty" bson:"name_text_hash_map,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WeaponData) Reset() {
	*x = WeaponData{}
	mi := &file_protos_model_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeaponData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeaponData) ProtoMessage() {}

func (x *WeaponData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeaponData.ProtoReflect.Descriptor instead.
func (*WeaponData) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{7}
}

func (x *WeaponData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WeaponData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WeaponData) GetRarity() int32 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *WeaponData) GetWeaponClass() WeaponClass {
	if x != nil {
		return x.WeaponClass
	}
	return WeaponClass_INVALID_WEAPON_CLASS
}

func (x *WeaponData) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *WeaponData) GetBaseStats() *WeaponStatsData {
	if x != nil {
		return x.BaseStats
	}
	return nil
}

func (x *WeaponData) GetNameTextHashMap() int64 {
	if x != nil {
		return x.NameTextHashMap
	}
	return 0
}

type WeaponStatsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseProps     []*WeaponProp          `protobuf:"bytes,1,rep,name=base_props,proto3" json:"base_props,omitempty" bson:"base_props,omitempty"`
	PromoData     []*PromotionData       `protobuf:"bytes,2,rep,name=promo_data,proto3" json:"promo_data,omitempty" bson:"promo_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeaponStatsData) Reset() {
	*x = WeaponStatsData{}
	mi := &file_protos_model_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeaponStatsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeaponStatsData) ProtoMessage() {}

func (x *WeaponStatsData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeaponStatsData.ProtoReflect.Descriptor instead.
func (*WeaponStatsData) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{8}
}

func (x *WeaponStatsData) GetBaseProps() []*WeaponProp {
	if x != nil {
		return x.BaseProps
	}
	return nil
}

func (x *WeaponStatsData) GetPromoData() []*PromotionData {
	if x != nil {
		return x.PromoData
	}
	return nil
}

type WeaponProp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropType      StatType               `protobuf:"varint,1,opt,name=prop_type,proto3,enum=model.StatType" json:"prop_type,omitempty" bson:"prop_type,omitempty"`
	InitialValue  float64                `protobuf:"fixed64,2,opt,name=initial_value,proto3" json:"initial_value,omitempty" bson:"initial_value,omitempty"`
	Curve         WeaponCurveType        `protobuf:"varint,3,opt,name=curve,proto3,enum=model.WeaponCurveType" json:"curve,omitempty" bson:"curve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeaponProp) Reset() {
	*x = WeaponProp{}
	mi := &file_protos_model_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeaponProp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeaponProp) ProtoMessage() {}

func (x *WeaponProp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeaponProp.ProtoReflect.Descriptor instead.
func (*WeaponProp) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{9}
}

func (x *WeaponProp) GetPropType() StatType {
	if x != nil {
		return x.PropType
	}
	return StatType_INVALID_STAT_TYPE
}

func (x *WeaponProp) GetInitialValue() float64 {
	if x != nil {
		return x.InitialValue
	}
	return 0
}

func (x *WeaponProp) GetCurve() WeaponCurveType {
	if x != nil {
		return x.Curve
	}
	return WeaponCurveType_INVALID_WEAPON_CURVE
}

type ArtifactDataMap struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Data          map[string]*ArtifactData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" bson:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactDataMap) Reset() {
	*x = ArtifactDataMap{}
	mi := &file_protos_model_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactDataMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactDataMap) ProtoMessage() {}

func (x *ArtifactDataMap) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactDataMap.ProtoReflect.Descriptor instead.
func (*ArtifactDataMap) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{10}
}

func (x *ArtifactDataMap) GetData() map[string]*ArtifactData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ArtifactData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetId         int64                  `protobuf:"varint,1,opt,name=set_id,json=id,proto3" json:"set_id,omitempty" bson:"id,omitempty"`
	TextMapId     int64                  `protobuf:"varint,2,opt,name=text_map_id,proto3" json:"text_map_id,omitempty" bson:"text_map_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty" bson:"key,omitempty"`
	ImageNames    *ArtifactImageData     `protobuf:"bytes,4,opt,name=image_names,proto3" json:"image_names,omitempty" bson:"image_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactData) Reset() {
	*x = ArtifactData{}
	mi := &file_protos_model_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactData) ProtoMessage() {}

func (x *ArtifactData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactData.ProtoReflect.Descriptor instead.
func (*ArtifactData) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{11}
}

func (x *ArtifactData) GetSetId() int64 {
	if x != nil {
		return x.SetId
	}
	return 0
}

func (x *ArtifactData) GetTextMapId() int64 {
	if x != nil {
		return x.TextMapId
	}
	return 0
}

func (x *ArtifactData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ArtifactData) GetImageNames() *ArtifactImageData {
	if x != nil {
		return x.ImageNames
	}
	return nil
}

type ArtifactImageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flower        string                 `protobuf:"bytes,1,opt,name=flower,proto3" json:"flower,omitempty" bson:"flower,omitempty"`
	Plume         string                 `protobuf:"bytes,2,opt,name=plume,proto3" json:"plume,omitempty" bson:"plume,omitempty"`
	Sands         string                 `protobuf:"bytes,3,opt,name=sands,proto3" json:"sands,omitempty" bson:"sands,omitempty"`
	Goblet        string                 `protobuf:"bytes,4,opt,name=goblet,proto3" json:"goblet,omitempty" bson:"goblet,omitempty"`
	Circlet       string                 `protobuf:"bytes,5,opt,name=circlet,proto3" json:"circlet,omitempty" bson:"circlet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactImageData) Reset() {
	*x = ArtifactImageData{}
	mi := &file_protos_model_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactImageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactImageData) ProtoMessage() {}

func (x *ArtifactImageData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactImageData.ProtoReflect.Descriptor instead.
func (*ArtifactImageData) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{12}
}

func (x *ArtifactImageData) GetFlower() string {
	if x != nil {
		return x.Flower
	}
	return ""
}

func (x *ArtifactImageData) GetPlume() string {
	if x != nil {
		return x.Plume
	}
	return ""
}

func (x *ArtifactImageData) GetSands() string {
	if x != nil {
		return x.Sands
	}
	return ""
}

func (x *ArtifactImageData) GetGoblet() string {
	if x != nil {
		return x.Goblet
	}
	return ""
}

func (x *ArtifactImageData) GetCirclet() string {
	if x != nil {
		return x.Circlet
	}
	return ""
}

type PromotionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxLevel      int32                  `protobuf:"varint,1,opt,name=max_level,proto3" json:"max_level,omitempty" bson:"max_level,omitempty"`
	AddProps      []*PromotionAddProp    `protobuf:"bytes,2,rep,name=add_props,proto3" json:"add_props,omitempty" bson:"add_props,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotionData) Reset() {
	*x = PromotionData{}
	mi := &file_protos_model_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionData) ProtoMessage() {}

func (x *PromotionData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionData.ProtoReflect.Descriptor instead.
func (*PromotionData) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{13}
}

func (x *PromotionData) GetMaxLevel() int32 {
	if x != nil {
		return x.MaxLevel
	}
	return 0
}

func (x *PromotionData) GetAddProps() []*PromotionAddProp {
	if x != nil {
		return x.AddProps
	}
	return nil
}

type PromotionAddProp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PropType      StatType               `protobuf:"varint,1,opt,name=prop_type,proto3,enum=model.StatType" json:"prop_type,omitempty" bson:"prop_type,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty" bson:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotionAddProp) Reset() {
	*x = PromotionAddProp{}
	mi := &file_protos_model_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionAddProp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionAddProp) ProtoMessage() {}

func (x *PromotionAddProp) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionAddProp.ProtoReflect.Descriptor instead.
func (*PromotionAddProp) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{14}
}

func (x *PromotionAddProp) GetPropType() StatType {
	if x != nil {
		return x.PropType
	}
	return StatType_INVALID_STAT_TYPE
}

func (x *PromotionAddProp) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MonsterData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	Key             string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty" bson:"key,omitempty"`
	BaseStats       *MonsterStatsData      `protobuf:"bytes,3,opt,name=base_stats,proto3" json:"base_stats,omitempty" bson:"base_stats,omitempty"`
	NameTextHashMap int64                  `protobuf:"varint,4,opt,name=name_text_hash_map,proto3" json:"name_text_hash_map,omitempty" bson:"name_text_hash_map,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MonsterData) Reset() {
	*x = MonsterData{}
	mi := &file_protos_model_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterData) ProtoMessage() {}

func (x *MonsterData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterData.ProtoReflect.Descriptor instead.
func (*MonsterData) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{15}
}

func (x *MonsterData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MonsterData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MonsterData) GetBaseStats() *MonsterStatsData {
	if x != nil {
		return x.BaseStats
	}
	return nil
}

func (x *MonsterData) GetNameTextHashMap() int64 {
	if x != nil {
		return x.NameTextHashMap
	}
	return 0
}

type MonsterStatsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseHp        float64                `protobuf:"fixed64,1,opt,name=base_hp,proto3" json:"base_hp,omitempty" bson:"base_hp,omitempty"`
	HpCurve       MonsterCurveType       `protobuf:"varint,2,opt,name=hp_curve,proto3,enum=model.MonsterCurveType" json:"hp_curve,omitempty" bson:"hp_curve,omitempty"`
	Resist        *MonsterResistData     `protobuf:"bytes,3,opt,name=resist,proto3" json:"resist,omitempty" bson:"resist,omitempty"`
	FreezeResist  float64                `protobuf:"fixed64,4,opt,name=freeze_resist,proto3" json:"freeze_resist,omitempty" bson:"freeze_resist,omitempty"`
	HpDrop        []*MonsterHPDrop       `protobuf:"bytes,5,rep,name=hp_drop,proto3" json:"hp_drop,omitempty" bson:"hp_drop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterStatsData) Reset() {
	*x = MonsterStatsData{}
	mi := &file_protos_model_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterStatsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterStatsData) ProtoMessage() {}

func (x *MonsterStatsData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterStatsData.ProtoReflect.Descriptor instead.
func (*MonsterStatsData) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{16}
}

func (x *MonsterStatsData) GetBaseHp() float64 {
	if x != nil {
		return x.BaseHp
	}
	return 0
}

func (x *MonsterStatsData) GetHpCurve() MonsterCurveType {
	if x != nil {
		return x.HpCurve
	}
	return MonsterCurveType_INVALID_MONSTER_CURVE
}

func (x *MonsterStatsData) GetResist() *MonsterResistData {
	if x != nil {
		return x.Resist
	}
	return nil
}

func (x *MonsterStatsData) GetFreezeResist() float64 {
	if x != nil {
		return x.FreezeResist
	}
	return 0
}

func (x *MonsterStatsData) GetHpDrop() []*MonsterHPDrop {
	if x != nil {
		return x.HpDrop
	}
	return nil
}

type MonsterResistData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FireResist     float64                `protobuf:"fixed64,1,opt,name=fire_resist,proto3" json:"fire_resist,omitempty" bson:"fire_resist,omitempty"`
	GrassResist    float64                `protobuf:"fixed64,2,opt,name=grass_resist,proto3" json:"grass_resist,omitempty" bson:"grass_resist,omitempty"`
	WaterResist    float64                `protobuf:"fixed64,3,opt,name=water_resist,proto3" json:"water_resist,omitempty" bson:"water_resist,omitempty"`
	ElectricResist float64                `protobuf:"fixed64,4,opt,name=electric_resist,proto3" json:"electric_resist,omitempty" bson:"electric_resist,omitempty"`
	WindResist     float64                `protobuf:"fixed64,5,opt,name=wind_resist,proto3" json:"wind_resist,omitempty" bson:"wind_resist,omitempty"`
	IceResist      float64                `protobuf:"fixed64,6,opt,name=ice_resist,proto3" json:"ice_resist,omitempty" bson:"ice_resist,omitempty"`
	RockResist     float64                `protobuf:"fixed64,7,opt,name=rock_resist,proto3" json:"rock_resist,omitempty" bson:"rock_resist,omitempty"`
	PhysicalResist float64                `protobuf:"fixed64,8,opt,name=physical_resist,proto3" json:"physical_resist,omitempty" bson:"physical_resist,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MonsterResistData) Reset() {
	*x = MonsterResistData{}
	mi := &file_protos_model_data_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterResistData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterResistData) ProtoMessage() {}

func (x *MonsterResistData) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterResistData.ProtoReflect.Descriptor instead.
func (*MonsterResistData) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{17}
}

func (x *MonsterResistData) GetFireResist() float64 {
	if x != nil {
		return x.FireResist
	}
	return 0
}

func (x *MonsterResistData) GetGrassResist() float64 {
	if x != nil {
		return x.GrassResist
	}
	return 0
}

func (x *MonsterResistData) GetWaterResist() float64 {
	if x != nil {
		return x.WaterResist
	}
	return 0
}

func (x *MonsterResistData) GetElectricResist() float64 {
	if x != nil {
		return x.ElectricResist
	}
	return 0
}

func (x *MonsterResistData) GetWindResist() float64 {
	if x != nil {
		return x.WindResist
	}
	return 0
}

func (x *MonsterResistData) GetIceResist() float64 {
	if x != nil {
		return x.IceResist
	}
	return 0
}

func (x *MonsterResistData) GetRockResist() float64 {
	if x != nil {
		return x.RockResist
	}
	return 0
}

func (x *MonsterResistData) GetPhysicalResist() float64 {
	if x != nil {
		return x.PhysicalResist
	}
	return 0
}

type MonsterHPDrop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DropId        int32                  `protobuf:"varint,1,opt,name=drop_id,proto3" json:"drop_id,omitempty" bson:"drop_id,omitempty"`
	HpPercent     float64                `protobuf:"fixed64,2,opt,name=hp_percent,proto3" json:"hp_percent,omitempty" bson:"hp_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterHPDrop) Reset() {
	*x = MonsterHPDrop{}
	mi := &file_protos_model_data_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterHPDrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterHPDrop) ProtoMessage() {}

func (x *MonsterHPDrop) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_data_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterHPDrop.ProtoReflect.Descriptor instead.
func (*MonsterHPDrop) Descriptor() ([]byte, []int) {
	return file_protos_model_data_proto_rawDescGZIP(), []int{18}
}

func (x *MonsterHPDrop) GetDropId() int32 {
	if x != nil {
		return x.DropId
	}
	return 0
}

func (x *MonsterHPDrop) GetHpPercent() float64 {
	if x != nil {
		return x.HpPercent
	}
	return 0
}

var File_protos_model_data_proto protoreflect.FileDescriptor

const file_protos_model_data_proto_rawDesc = "" +
	"\n" +
	"\x17protos/model/data.proto\x12\x05model\x1a\x18protos/model/enums.proto\"\x8f\x01\n" +
	"\rAvatarDataMap\x122\n" +
	"\x04data\x18\x01 \x03(\v2\x1e.model.AvatarDataMap.DataEntryR\x04data\x1aJ\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.model.AvatarDataR\x05value:\x028\x01\"\xde\x03\n" +
	"\n" +
	"AvatarData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06sub_id\x18\x02 \x01(\x05R\x06sub_id\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12*\n" +
	"\x06rarity\x18\x04 \x01(\x0e2\x12.model.QualityTypeR\x06rarity\x12#\n" +
	"\x04body\x18\x05 \x01(\x0e2\x0f.model.BodyTypeR\x04body\x12'\n" +
	"\x06region\x18\x06 \x01(\x0e2\x0f.model.ZoneTypeR\x06region\x12(\n" +
	"\aelement\x18\a \x01(\x0e2\x0e.model.ElementR\aelement\x126\n" +
	"\fweapon_class\x18\b \x01(\x0e2\x12.model.WeaponClassR\fweapon_class\x12\x1c\n" +
	"\ticon_name\x18\t \x01(\tR\ticon_name\x12,\n" +
	"\x05stats\x18\n" +
	" \x01(\v2\x16.model.AvatarStatsDataR\x05stats\x12=\n" +
	"\rskill_details\x18\v \x01(\v2\x17.model.AvatarSkillsDataR\rskill_details\x12/\n" +
	"\x12name_text_hash_map\x18\f \x01(\x03R\x13name_text_hash_map \"\xb9\x02\n" +
	"\x0fAvatarStatsData\x12\x18\n" +
	"\abase_hp\x18\x01 \x01(\x01R\abase_hp\x12\x1a\n" +
	"\bbase_atk\x18\x02 \x01(\x01R\bbase_atk\x12\x1a\n" +
	"\bbase_def\x18\x03 \x01(\x01R\bbase_def\x122\n" +
	"\bhp_curve\x18\x04 \x01(\x0e2\x16.model.AvatarCurveTypeR\bhp_curve\x124\n" +
	"\tatk_curve\x18\x05 \x01(\x0e2\x16.model.AvatarCurveTypeR\tatk_curve\x124\n" +
	"\tdef_cruve\x18\x06 \x01(\x0e2\x16.model.AvatarCurveTypeR\tdef_cruve\x124\n" +
	"\n" +
	"promo_data\x18\a \x03(\v2\x14.model.PromotionDataR\n" +
	"promo_data\"\x82\x04\n" +
	"\x10AvatarSkillsData\x12\x14\n" +
	"\x05skill\x18\x01 \x01(\x05R\x05skill\x12\x14\n" +
	"\x05burst\x18\x02 \x01(\x05R\x05burst\x12\x16\n" +
	"\x06attack\x18\x03 \x01(\x05R\x06attack\x12\x0e\n" +
	"\x02a1\x18\n" +
	" \x01(\x05R\x02a1\x12\x0e\n" +
	"\x02a4\x18\v \x01(\x05R\x02a4\x12,\n" +
	"\x11burst_energy_cost\x18\x04 \x01(\x01R\x11burst_energy_cost\x12H\n" +
	"\x0eattack_scaling\x18\x05 \x03(\v2 .model.AvatarSkillExcelIndexDataR\x0eattack_scaling\x12F\n" +
	"\rskill_scaling\x18\x06 \x03(\v2 .model.AvatarSkillExcelIndexDataR\rskill_scaling\x12F\n" +
	"\rburst_scaling\x18\a \x03(\v2 .model.AvatarSkillExcelIndexDataR\rburst_scaling\x12@\n" +
	"\n" +
	"a1_scaling\x18\b \x03(\v2 .model.AvatarSkillExcelIndexDataR\n" +
	"a1_scaling\x12@\n" +
	"\n" +
	"a4_scaling\x18\t \x03(\v2 .model.AvatarSkillExcelIndexDataR\n" +
	"a4_scaling\"\x8f\x01\n" +
	"\x19AvatarSkillExcelIndexData\x12\x1a\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\bgroup_id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12@\n" +
	"\n" +
	"level_data\x18\x03 \x03(\v2 .model.AvatarSkillExcelLevelDataR\n" +
	"level_data\"G\n" +
	"\x19AvatarSkillExcelLevelData\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\x8f\x01\n" +
	"\rWeaponDataMap\x122\n" +
	"\x04data\x18\x01 \x03(\v2\x1e.model.WeaponDataMap.DataEntryR\x04data\x1aJ\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.model.WeaponDataR\x05value:\x028\x01\"\x87\x02\n" +
	"\n" +
	"WeaponData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06rarity\x18\x03 \x01(\x05R\x06rarity\x126\n" +
	"\fweapon_class\x18\x04 \x01(\x0e2\x12.model.WeaponClassR\fweapon_class\x12\x1e\n" +
	"\n" +
	"image_name\x18\x05 \x01(\tR\n" +
	"image_name\x126\n" +
	"\n" +
	"base_stats\x18\x06 \x01(\v2\x16.model.WeaponStatsDataR\n" +
	"base_stats\x12/\n" +
	"\x12name_text_hash_map\x18\a \x01(\x03R\x13name_text_hash_map \"z\n" +
	"\x0fWeaponStatsData\x121\n" +
	"\n" +
	"base_props\x18\x01 \x03(\v2\x11.model.WeaponPropR\n" +
	"base_props\x124\n" +
	"\n" +
	"promo_data\x18\x02 \x03(\v2\x14.model.PromotionDataR\n" +
	"promo_data\"\x8f\x01\n" +
	"\n" +
	"WeaponProp\x12-\n" +
	"\tprop_type\x18\x01 \x01(\x0e2\x0f.model.StatTypeR\tprop_type\x12$\n" +
	"\rinitial_value\x18\x02 \x01(\x01R\rinitial_value\x12,\n" +
	"\x05curve\x18\x03 \x01(\x0e2\x16.model.WeaponCurveTypeR\x05curve\"\x95\x01\n" +
	"\x0fArtifactDataMap\x124\n" +
	"\x04data\x18\x01 \x03(\v2 .model.ArtifactDataMap.DataEntryR\x04data\x1aL\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.model.ArtifactDataR\x05value:\x028\x01\"\x92\x01\n" +
	"\fArtifactData\x12\x12\n" +
	"\x06set_id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vtext_map_id\x18\x02 \x01(\x03R\vtext_map_id\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12:\n" +
	"\vimage_names\x18\x04 \x01(\v2\x18.model.ArtifactImageDataR\vimage_names\"\x89\x01\n" +
	"\x11ArtifactImageData\x12\x16\n" +
	"\x06flower\x18\x01 \x01(\tR\x06flower\x12\x14\n" +
	"\x05plume\x18\x02 \x01(\tR\x05plume\x12\x14\n" +
	"\x05sands\x18\x03 \x01(\tR\x05sands\x12\x16\n" +
	"\x06goblet\x18\x04 \x01(\tR\x06goblet\x12\x18\n" +
	"\acirclet\x18\x05 \x01(\tR\acirclet\"d\n" +
	"\rPromotionData\x12\x1c\n" +
	"\tmax_level\x18\x01 \x01(\x05R\tmax_level\x125\n" +
	"\tadd_props\x18\x02 \x03(\v2\x17.model.PromotionAddPropR\tadd_props\"W\n" +
	"\x10PromotionAddProp\x12-\n" +
	"\tprop_type\x18\x01 \x01(\x0e2\x0f.model.StatTypeR\tprop_type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\x98\x01\n" +
	"\vMonsterData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x127\n" +
	"\n" +
	"base_stats\x18\x03 \x01(\v2\x17.model.MonsterStatsDataR\n" +
	"base_stats\x12.\n" +
	"\x12name_text_hash_map\x18\x04 \x01(\x03R\x12name_text_hash_map\"\xe9\x01\n" +
	"\x10MonsterStatsData\x12\x18\n" +
	"\abase_hp\x18\x01 \x01(\x01R\abase_hp\x123\n" +
	"\bhp_curve\x18\x02 \x01(\x0e2\x17.model.MonsterCurveTypeR\bhp_curve\x120\n" +
	"\x06resist\x18\x03 \x01(\v2\x18.model.MonsterResistDataR\x06resist\x12$\n" +
	"\rfreeze_resist\x18\x04 \x01(\x01R\rfreeze_resist\x12.\n" +
	"\ahp_drop\x18\x05 \x03(\v2\x14.model.MonsterHPDropR\ahp_drop\"\xb5\x02\n" +
	"\x11MonsterResistData\x12 \n" +
	"\vfire_resist\x18\x01 \x01(\x01R\vfire_resist\x12\"\n" +
	"\fgrass_resist\x18\x02 \x01(\x01R\fgrass_resist\x12\"\n" +
	"\fwater_resist\x18\x03 \x01(\x01R\fwater_resist\x12(\n" +
	"\x0felectric_resist\x18\x04 \x01(\x01R\x0felectric_resist\x12 \n" +
	"\vwind_resist\x18\x05 \x01(\x01R\vwind_resist\x12\x1e\n" +
	"\n" +
	"ice_resist\x18\x06 \x01(\x01R\n" +
	"ice_resist\x12 \n" +
	"\vrock_resist\x18\a \x01(\x01R\vrock_resist\x12(\n" +
	"\x0fphysical_resist\x18\b \x01(\x01R\x0fphysical_resist\"I\n" +
	"\rMonsterHPDrop\x12\x18\n" +
	"\adrop_id\x18\x01 \x01(\x05R\adrop_id\x12\x1e\n" +
	"\n" +
	"hp_percent\x18\x02 \x01(\x01R\n" +
	"hp_percentB'Z%github.com/genshinsim/gcsim/pkg/modelb\x06proto3"

var (
	file_protos_model_data_proto_rawDescOnce sync.Once
	file_protos_model_data_proto_rawDescData []byte
)

func file_protos_model_data_proto_rawDescGZIP() []byte {
	file_protos_model_data_proto_rawDescOnce.Do(func() {
		file_protos_model_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_model_data_proto_rawDesc), len(file_protos_model_data_proto_rawDesc)))
	})
	return file_protos_model_data_proto_rawDescData
}

var file_protos_model_data_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_protos_model_data_proto_goTypes = []any{
	(*AvatarDataMap)(nil),             // 0: model.AvatarDataMap
	(*AvatarData)(nil),                // 1: model.AvatarData
	(*AvatarStatsData)(nil),           // 2: model.AvatarStatsData
	(*AvatarSkillsData)(nil),          // 3: model.AvatarSkillsData
	(*AvatarSkillExcelIndexData)(nil), // 4: model.AvatarSkillExcelIndexData
	(*AvatarSkillExcelLevelData)(nil), // 5: model.AvatarSkillExcelLevelData
	(*WeaponDataMap)(nil),             // 6: model.WeaponDataMap
	(*WeaponData)(nil),                // 7: model.WeaponData
	(*WeaponStatsData)(nil),           // 8: model.WeaponStatsData
	(*WeaponProp)(nil),                // 9: model.WeaponProp
	(*ArtifactDataMap)(nil),           // 10: model.ArtifactDataMap
	(*ArtifactData)(nil),              // 11: model.ArtifactData
	(*ArtifactImageData)(nil),         // 12: model.ArtifactImageData
	(*PromotionData)(nil),             // 13: model.PromotionData
	(*PromotionAddProp)(nil),          // 14: model.PromotionAddProp
	(*MonsterData)(nil),               // 15: model.MonsterData
	(*MonsterStatsData)(nil),          // 16: model.MonsterStatsData
	(*MonsterResistData)(nil),         // 17: model.MonsterResistData
	(*MonsterHPDrop)(nil),             // 18: model.MonsterHPDrop
	nil,                               // 19: model.AvatarDataMap.DataEntry
	nil,                               // 20: model.WeaponDataMap.DataEntry
	nil,                               // 21: model.ArtifactDataMap.DataEntry
	(QualityType)(0),                  // 22: model.QualityType
	(BodyType)(0),                     // 23: model.BodyType
	(ZoneType)(0),                     // 24: model.ZoneType
	(Element)(0),                      // 25: model.Element
	(WeaponClass)(0),                  // 26: model.WeaponClass
	(AvatarCurveType)(0),              // 27: model.AvatarCurveType
	(StatType)(0),                     // 28: model.StatType
	(WeaponCurveType)(0),              // 29: model.WeaponCurveType
	(MonsterCurveType)(0),             // 30: model.MonsterCurveType
}
var file_protos_model_data_proto_depIdxs = []int32{
	19, // 0: model.AvatarDataMap.data:type_name -> model.AvatarDataMap.DataEntry
	22, // 1: model.AvatarData.rarity:type_name -> model.QualityType
	23, // 2: model.AvatarData.body:type_name -> model.BodyType
	24, // 3: model.AvatarData.region:type_name -> model.ZoneType
	25, // 4: model.AvatarData.element:type_name -> model.Element
	26, // 5: model.AvatarData.weapon_class:type_name -> model.WeaponClass
	2,  // 6: model.AvatarData.stats:type_name -> model.AvatarStatsData
	3,  // 7: model.AvatarData.skill_details:type_name -> model.AvatarSkillsData
	27, // 8: model.AvatarStatsData.hp_curve:type_name -> model.AvatarCurveType
	27, // 9: model.AvatarStatsData.atk_curve:type_name -> model.AvatarCurveType
	27, // 10: model.AvatarStatsData.def_cruve:type_name -> model.AvatarCurveType
	13, // 11: model.AvatarStatsData.promo_data:type_name -> model.PromotionData
	4,  // 12: model.AvatarSkillsData.attack_scaling:type_name -> model.AvatarSkillExcelIndexData
	4,  // 13: model.AvatarSkillsData.skill_scaling:type_name -> model.AvatarSkillExcelIndexData
	4,  // 14: model.AvatarSkillsData.burst_scaling:type_name -> model.AvatarSkillExcelIndexData
	4,  // 15: model.AvatarSkillsData.a1_scaling:type_name -> model.AvatarSkillExcelIndexData
	4,  // 16: model.AvatarSkillsData.a4_scaling:type_name -> model.AvatarSkillExcelIndexData
	5,  // 17: model.AvatarSkillExcelIndexData.level_data:type_name -> model.AvatarSkillExcelLevelData
	20, // 18: model.WeaponDataMap.data:type_name -> model.WeaponDataMap.DataEntry
	26, // 19: model.WeaponData.weapon_class:type_name -> model.WeaponClass
	8,  // 20: model.WeaponData.base_stats:type_name -> model.WeaponStatsData
	9,  // 21: model.WeaponStatsData.base_props:type_name -> model.WeaponProp
	13, // 22: model.WeaponStatsData.promo_data:type_name -> model.PromotionData
	28, // 23: model.WeaponProp.prop_type:type_name -> model.StatType
	29, // 24: model.WeaponProp.curve:type_name -> model.WeaponCurveType
	21, // 25: model.ArtifactDataMap.data:type_name -> model.ArtifactDataMap.DataEntry
	12, // 26: model.ArtifactData.image_names:type_name -> model.ArtifactImageData
	14, // 27: model.PromotionData.add_props:type_name -> model.PromotionAddProp
	28, // 28: model.PromotionAddProp.prop_type:type_name -> model.StatType
	16, // 29: model.MonsterData.base_stats:type_name -> model.MonsterStatsData
	30, // 30: model.MonsterStatsData.hp_curve:type_name -> model.MonsterCurveType
	17, // 31: model.MonsterStatsData.resist:type_name -> model.MonsterResistData
	18, // 32: model.MonsterStatsData.hp_drop:type_name -> model.MonsterHPDrop
	1,  // 33: model.AvatarDataMap.DataEntry.value:type_name -> model.AvatarData
	7,  // 34: model.WeaponDataMap.DataEntry.value:type_name -> model.WeaponData
	11, // 35: model.ArtifactDataMap.DataEntry.value:type_name -> model.ArtifactData
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_protos_model_data_proto_init() }
func file_protos_model_data_proto_init() {
	if File_protos_model_data_proto != nil {
		return
	}
	file_protos_model_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_model_data_proto_rawDesc), len(file_protos_model_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_model_data_proto_goTypes,
		DependencyIndexes: file_protos_model_data_proto_depIdxs,
		MessageInfos:      file_protos_model_data_proto_msgTypes,
	}.Build()
	File_protos_model_data_proto = out.File
	file_protos_model_data_proto_goTypes = nil
	file_protos_model_data_proto_depIdxs = nil
}
