// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protos/model/notification.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComputeFailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbId          string                 `protobuf:"bytes,1,opt,name=db_id,json=dbId,proto3" json:"db_id,omitempty" bson:"dbId,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty" bson:"config,omitempty"`
	Submitter     string                 `protobuf:"bytes,3,opt,name=submitter,proto3" json:"submitter,omitempty" bson:"submitter,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty" bson:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeFailedEvent) Reset() {
	*x = ComputeFailedEvent{}
	mi := &file_protos_model_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeFailedEvent) ProtoMessage() {}

func (x *ComputeFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeFailedEvent.ProtoReflect.Descriptor instead.
func (*ComputeFailedEvent) Descriptor() ([]byte, []int) {
	return file_protos_model_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeFailedEvent) GetDbId() string {
	if x != nil {
		return x.DbId
	}
	return ""
}

func (x *ComputeFailedEvent) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *ComputeFailedEvent) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

func (x *ComputeFailedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ComputeCompletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbId          string                 `protobuf:"bytes,1,opt,name=db_id,json=dbId,proto3" json:"db_id,omitempty" bson:"dbId,omitempty"`
	ShareId       string                 `protobuf:"bytes,2,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty" bson:"shareId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeCompletedEvent) Reset() {
	*x = ComputeCompletedEvent{}
	mi := &file_protos_model_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeCompletedEvent) ProtoMessage() {}

func (x *ComputeCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeCompletedEvent.ProtoReflect.Descriptor instead.
func (*ComputeCompletedEvent) Descriptor() ([]byte, []int) {
	return file_protos_model_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ComputeCompletedEvent) GetDbId() string {
	if x != nil {
		return x.DbId
	}
	return ""
}

func (x *ComputeCompletedEvent) GetShareId() string {
	if x != nil {
		return x.ShareId
	}
	return ""
}

type SubmissionDeleteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbId          string                 `protobuf:"bytes,1,opt,name=db_id,json=dbId,proto3" json:"db_id,omitempty" bson:"dbId,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty" bson:"config,omitempty"`
	Submitter     string                 `protobuf:"bytes,3,opt,name=submitter,proto3" json:"submitter,omitempty" bson:"submitter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmissionDeleteEvent) Reset() {
	*x = SubmissionDeleteEvent{}
	mi := &file_protos_model_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmissionDeleteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionDeleteEvent) ProtoMessage() {}

func (x *SubmissionDeleteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionDeleteEvent.ProtoReflect.Descriptor instead.
func (*SubmissionDeleteEvent) Descriptor() ([]byte, []int) {
	return file_protos_model_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SubmissionDeleteEvent) GetDbId() string {
	if x != nil {
		return x.DbId
	}
	return ""
}

func (x *SubmissionDeleteEvent) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *SubmissionDeleteEvent) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

type EntryReplaceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbId          string                 `protobuf:"bytes,1,opt,name=db_id,json=dbId,proto3" json:"db_id,omitempty" bson:"dbId,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty" bson:"config,omitempty"`
	OldConfig     string                 `protobuf:"bytes,3,opt,name=old_config,json=oldConfig,proto3" json:"old_config,omitempty" bson:"oldConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryReplaceEvent) Reset() {
	*x = EntryReplaceEvent{}
	mi := &file_protos_model_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryReplaceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryReplaceEvent) ProtoMessage() {}

func (x *EntryReplaceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryReplaceEvent.ProtoReflect.Descriptor instead.
func (*EntryReplaceEvent) Descriptor() ([]byte, []int) {
	return file_protos_model_notification_proto_rawDescGZIP(), []int{3}
}

func (x *EntryReplaceEvent) GetDbId() string {
	if x != nil {
		return x.DbId
	}
	return ""
}

func (x *EntryReplaceEvent) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *EntryReplaceEvent) GetOldConfig() string {
	if x != nil {
		return x.OldConfig
	}
	return ""
}

type DescReplaceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbId          string                 `protobuf:"bytes,1,opt,name=db_id,json=dbId,proto3" json:"db_id,omitempty" bson:"dbId,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty" bson:"desc,omitempty"`
	OldDesc       string                 `protobuf:"bytes,3,opt,name=old_desc,json=oldDesc,proto3" json:"old_desc,omitempty" bson:"oldDesc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescReplaceEvent) Reset() {
	*x = DescReplaceEvent{}
	mi := &file_protos_model_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescReplaceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescReplaceEvent) ProtoMessage() {}

func (x *DescReplaceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_model_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescReplaceEvent.ProtoReflect.Descriptor instead.
func (*DescReplaceEvent) Descriptor() ([]byte, []int) {
	return file_protos_model_notification_proto_rawDescGZIP(), []int{4}
}

func (x *DescReplaceEvent) GetDbId() string {
	if x != nil {
		return x.DbId
	}
	return ""
}

func (x *DescReplaceEvent) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *DescReplaceEvent) GetOldDesc() string {
	if x != nil {
		return x.OldDesc
	}
	return ""
}

var File_protos_model_notification_proto protoreflect.FileDescriptor

const file_protos_model_notification_proto_rawDesc = "" +
	"\n" +
	"\x1fprotos/model/notification.proto\x12\x05model\"w\n" +
	"\x12ComputeFailedEvent\x12\x13\n" +
	"\x05db_id\x18\x01 \x01(\tR\x04dbId\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12\x1c\n" +
	"\tsubmitter\x18\x03 \x01(\tR\tsubmitter\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"G\n" +
	"\x15ComputeCompletedEvent\x12\x13\n" +
	"\x05db_id\x18\x01 \x01(\tR\x04dbId\x12\x19\n" +
	"\bshare_id\x18\x02 \x01(\tR\ashareId\"b\n" +
	"\x15SubmissionDeleteEvent\x12\x13\n" +
	"\x05db_id\x18\x01 \x01(\tR\x04dbId\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12\x1c\n" +
	"\tsubmitter\x18\x03 \x01(\tR\tsubmitter\"_\n" +
	"\x11EntryReplaceEvent\x12\x13\n" +
	"\x05db_id\x18\x01 \x01(\tR\x04dbId\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\x12\x1d\n" +
	"\n" +
	"old_config\x18\x03 \x01(\tR\toldConfig\"V\n" +
	"\x10DescReplaceEvent\x12\x13\n" +
	"\x05db_id\x18\x01 \x01(\tR\x04dbId\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x19\n" +
	"\bold_desc\x18\x03 \x01(\tR\aoldDescB'Z%github.com/genshinsim/gcsim/pkg/modelb\x06proto3"

var (
	file_protos_model_notification_proto_rawDescOnce sync.Once
	file_protos_model_notification_proto_rawDescData []byte
)

func file_protos_model_notification_proto_rawDescGZIP() []byte {
	file_protos_model_notification_proto_rawDescOnce.Do(func() {
		file_protos_model_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_model_notification_proto_rawDesc), len(file_protos_model_notification_proto_rawDesc)))
	})
	return file_protos_model_notification_proto_rawDescData
}

var file_protos_model_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_model_notification_proto_goTypes = []any{
	(*ComputeFailedEvent)(nil),    // 0: model.ComputeFailedEvent
	(*ComputeCompletedEvent)(nil), // 1: model.ComputeCompletedEvent
	(*SubmissionDeleteEvent)(nil), // 2: model.SubmissionDeleteEvent
	(*EntryReplaceEvent)(nil),     // 3: model.EntryReplaceEvent
	(*DescReplaceEvent)(nil),      // 4: model.DescReplaceEvent
}
var file_protos_model_notification_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_model_notification_proto_init() }
func file_protos_model_notification_proto_init() {
	if File_protos_model_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_model_notification_proto_rawDesc), len(file_protos_model_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_model_notification_proto_goTypes,
		DependencyIndexes: file_protos_model_notification_proto_depIdxs,
		MessageInfos:      file_protos_model_notification_proto_msgTypes,
	}.Build()
	File_protos_model_notification_proto = out.File
	file_protos_model_notification_proto_goTypes = nil
	file_protos_model_notification_proto_depIdxs = nil
}
