use: pipeline
kind: character
name: yunjin

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG|1)
      - - attack(4-Hit DMG)
        - attack(4-Hit DMG|1)
      - attack(5-Hit DMG)
  - charge: attack(Charged Attack)

  - skillShieldPct: skill(Shield DMG Absorption)
  - skillShieldFlat: skill(Shield DMG Absorption|1)
  - skillDmg:
      - skill(Press DMG)
      - skill(Charge Level 1 DMG)
      - skill(Charge Level 2 DMG)

  - burstDmg: burst(Skill DMG)
  - burstBuff: burst(DMG Increase)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1rDQZ8TJd6JAzD3C6pg_JZrgkYr-LIp36mmXE8XVMj4s/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/dIlxs5zi1e0
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1rDQZ8TJd6JAzD3C6pg_JZrgkYr-LIp36mmXE8XVMj4s/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/tb1bGGVNJoA?t=201
      video_credit: Kolibri#7675

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: Player
        offset: [0, 0.8]
        fan_angle: 220
        radius: 2
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Circle
        center: Player
        offset: [0, 0.8]
        fan_angle: 220
        radius: 2
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N3-1
        shape: Circle
        center: Player
        offset: [0, 0.8]
        fan_angle: 220
        radius: 2

      - name: N3-2
        shape: Circle
        center: Player
        offset: [0, 0.8]
        fan_angle: 220
        radius: 2
        hitlag: {time: 0.03, scale: 0.01, defense_halt: true}

      - name: N4-1
        shape: Box
        center: Player
        offset: [0, -1.2]
        box: [2, 3.2]

      - name: N4-2
        shape: Box
        center: Player
        offset: [0, -1.2]
        box: [2, 3.2]
        hitlag: {time: 0.03, scale: 0.01}

      - name: N5
        shape: Circle
        center: Player
        offset: [0, 1.1]
        radius: 2.4
        hitlag: {time: 0.04, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 0.8
        hitlag: {scale: 0.01, defense_halt: true, deployable: true}

  - name: skill
    params:
      hold: 0 for Tap (default), 1 for Hold Lv. 1, 2 for Hold Lv. 2.
      perfect: If 1, perform perfect counter (Hold Lv. 2 frames). Default 0.
    hitbox:
      - name: E-Tap
        shape: Circle
        center: Player
        radius: 4
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: E-Hold-Lv.1
        shape: Circle
        center: Player
        radius: 6
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

      - name: E-Hold-Lv.2
        note: Also used for perfect counter.
        shape: Circle
        center: Player
        radius: 8
        hitlag: {time: 0.12, scale: 0.01, defense_halt: true}

  - name: burst
    hitbox:
      - name: Q-ElementalBurst
        shape: Circle
        center: Player
        radius: 6

  - name: walk
    note: No action followed by walk has proper frames.
