id: 10000064
key: "yunjin"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_LIYUE
element: Rock
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Yunjin"
stats: {
   base_hp: 893.5552
   base_atk: 16.0272
   base_def: 61.5741
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 667.5315
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 45.999
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 11.97342
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1141.8302
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 78.6825
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 20.48085
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.0667
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1774.2284
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 122.2605
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 31.82409
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.1333
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2248.527
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 154.944
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.33152
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.1333
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2722.8257
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 187.6275
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 48.83895
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.2
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3197.1245
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 220.311
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 57.34638
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.2667
      }
   }
}
skill_details: {
   skill: 10642
   burst: 10643
   attack: 10641
   burst_energy_cost: 60
}
name_text_hash_map: 655825874
