// Code generated by "pipeline"; DO NOT EDIT.

// passive: Dryas's Nocturne # Weapon_Bow_Arcdange
//
//	The equipping character can gain the Remedy effect. When they possess 1/2/3 Remedy
//	stacks, Max HP will increase by 12%/24%/40%. 1 stack may be gained when the following
//	conditions are met: 1 stack for 25s when using an Elemental Skill; 1 stack for 25s
//	when the value of a Bond of Life value increases; 1 stack for 20s for performing
//	healing. Stacks can still be triggered when the equipping character is not on the
//	field. Each stack's duration is counted independently. In addition, when 3 stacks
//	are active, Elemental Burst CRIT Rate will be increased by 28%. This effect will
//	be canceled 4s after falling under 3 stacks.
package heartstrings

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterWeaponFunc(keys.SilvershowerHeartstrings, NewWeapon)
}
