package_name: mualani
genshin_id: 10000102
key: mualani
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    charge:
      - 3 # Charged Attack DMG|{param3:F1P}
  skill:
    bite:
      - 0 # Sharky's Bite Base DMG|{param0:F2P} Max HP
    momentumBonus:
      - 1 # Wave Momentum DMG Bonus|{param1:F2P} Max HP/Stack
    surgingBite:
      - 2 # Sharky's Surging Bite Additional DMG Bonus|{param2:F2P} Max HP
  burst:
    burst:
      - 0 # Skill DMG|{param0:F2P} Max HP
