use: pipeline
kind: character
name: mualani

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
  - charge: attack(Charged Attack DMG)

  - bite: skill(Sharky's Bite Base DMG)
  - momentumBonus: skill(Wave Momentum DMG Bonus)
  - surgingBite: skill(Sharky's Surging Bite Additional DMG Bonus)

  - burst: burst(Skill DMG)

docs:
  fields:
    .mualani.momentum: Number of Wave Momentum stacks.
  frames:
    - count: https://docs.google.com/spreadsheets/d/1jFoJ_Xyz5iidLfE4RnGotElXWZc8HivfQkYO3Na6RSM/edit?usp=sharing
      count_credit: yamitoka
      video: https://www.youtube.com/watch?v=neTuo5SAuZg
      video_credit: yamitoka
    - count: https://docs.google.com/spreadsheets/d/1jFoJ_Xyz5iidLfE4RnGotElXWZc8HivfQkYO3Na6RSM/edit?usp=sharing
      count_credit: yamitoka
      video: https://www.youtube.com/watch?v=uZXoiiRVcSk
      video_credit: yamitoka
    - count: https://docs.google.com/spreadsheets/d/1jFoJ_Xyz5iidLfE4RnGotElXWZc8HivfQkYO3Na6RSM/edit?usp=sharing
      count_credit: yamitoka
      video: https://www.youtube.com/watch?v=sE5sGTOrQYU
      video_credit: yamitoka

abilities:
  - name: attack
    params:
      travel: Projectile travel time for Shark Missiles. Default 10 frames.
    hitbox:
      - name: N1
        shape: Circle
        center: PrimaryTarget
        radius: 0.7

      - name: N2
        shape: Circle
        center: PrimaryTarget
        radius: 0.7

      - name: N3
        shape: Circle
        center: PrimaryTarget
        radius: 0.7

      - name: Shark-Bite
        note: Spawns on the Primary Target.
        shape: Single
        center: GlobalValue

      - name: Surging-Bite
        note: Spawns on the Primary Target.
        shape: Single
        center: GlobalValue

  - name: charge
    hitbox:
      - name: CA
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3.5

  - name: skill
    hitbox:
      - name: Surfing
        shape: Box
        center: Player
        offset: [0, 0.9]
        box: [0, 1]
        hitlag: {scale: 0.01, defense_halt: true, deployable: true}

  - name: burst
    params:
      travel: Projectile travel time for the Super Shark Missile. Default 70 frames.
    hitbox:
      - name: Q
        shape: Circle
        center: PrimaryTarget
        radius: 5
