id: 10000102
key: "mualani"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_NATLAN
element: Water
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Mualani"
stats: {
   base_hp: 1182.1168
   base_atk: 14.1512
   base_def: 44.39386
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1013.5583
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 38.0646
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 12.132488
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1733.7181
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 65.1105
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 20.75294
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2693.9312
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 101.1717
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 32.246876
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3414.091
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 128.2176
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 40.86733
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4134.251
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 155.2635
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 49.48778
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4854.4106
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 182.3094
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 58.10823
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 30002
   burst: 30007
   attack: 30000
   burst_energy_cost: 60
}
name_text_hash_map: 3949670506
