// Code generated by "pipeline"; DO NOT EDIT.

// set2: Husk of Opulent Dreams
//
//	DEF +30%
//
// set4: Husk of Opulent Dreams # Relic_RaiseDefenceAndRock
//
//	A character equipped with this Artifact set will obtain the Curiosity effect in the
//	following conditions: When on the field, the character gains 1 stack after hitting
//	an opponent with a Geo attack, triggering a maximum of once every 0.3s. When off
//	the field, the character gains 1 stack every 3s. Curiosity can stack up to 4 times,
//	each providing 6% DEF and a 6% Geo DMG Bonus. When 6 seconds pass without gaining
//	a Curiosity stack, 1 stack is lost.
package huskofopulentdreams

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterSetFunc(keys.HuskOfOpulentDreams, NewSet)
}
