// Code generated by "pipeline"; DO NOT EDIT.

// set2: Disenchantment in Deep Shadow
//
//	ATK +18%.
//
// set4: Disenchantment in Deep Shadow # Relic_6.6_Superconductor
//
//	Increases Superconduct Reaction DMG by 80% and Stellar-Conduct Reaction DMG by 40%.
//	When the wielder attacks opponents affected by Superconduct or Stellar-Conduct, this
//	attack's CRIT Rate is increased by 16%.
package disenchantmentinthedeepshadow

import (
	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/keys"
)

func init() {
	core.RegisterSetFunc(keys.DisenchantmentInDeepShadow, NewSet)
}
