id: 10000023
key: "xiangling"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_LIYUE
element: Fire
weapon_class: WEAPON_POLE
icon_name: "UI_AvatarIcon_Xiangling"
stats: {
   base_hp: 911.791
   base_atk: 18.87648
   base_def: 56.0805
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 681.15454
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 41.895
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 14.102028
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1165.1328
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 71.6625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 24.12189
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 24
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1810.4371
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 111.3525
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 37.481705
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2294.4153
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 141.12
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 47.501568
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 48
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2778.3936
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 170.8875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 57.52143
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 72
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3262.3718
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 200.655
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 67.54129
      }
      add_props: {
         prop_type: FIGHT_PROP_ELEMENT_MASTERY
         value: 96
      }
   }
}
skill_details: {
   skill: 10232
   burst: 10235
   attack: 10231
   burst_energy_cost: 80
}
name_text_hash_map: 1130996346
