id: 10000122
key: "nefer"
rarity: QUALITY_ORANGE
body: BODY_LADY
region: ASSOC_TYPE_NODKRAI
element: Grass
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Nefer"
stats: {
   base_hp: 988.9742
   base_atk: 26.8128
   base_def: 62.2232
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 847.95593
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 53.352
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 22.987871
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1450.4509
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 91.26
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.32136
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.096
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2253.7776
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 141.804
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.099342
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2856.2727
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 179.712
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 77.43283
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.192
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3458.7676
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 217.62
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 93.76632
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.288
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4061.2627
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 255.528
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 110.09981
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL_HURT
         value: 0.384
      }
   }
   element_mastery: 100
}
skill_details: {
   skill: 11222
   burst: 11225
   attack: 11221
   burst_energy_cost: 60
}
name_text_hash_map: 2745786202
