package_name: alhaitham
genshin_id: 10000078
key: alhaitham
icd_groups:
  - group_name: ICDGroupAlhaithamProjectionAttack
    reset_timer: 720
    ele_app_sequence:
      [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  - group_name: ICDGroupAlhaithamExtraAttack
    reset_timer: 120
    ele_app_sequence: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
      - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
    attack_4:
      - 4 # 4-Hit DMG|{param4:F1P}
    attack_5:
      - 5 # 5-Hit DMG|{param5:F1P}
    charge:
      - 6 # Charged Attack DMG|{param6:F1P}+{param7:F1P}
      - 6 # Charged Attack DMG|{param6:F1P}+{param7:F1P}
    collision:
      - 9 # Plunge DMG|{param6:F1P}
    lowPlunge:
      - 10 # Low/High Plunge DMG|{param7:P}/{param8:P}
    highPlunge:
      - 11 # Low/High Plunge DMG|{param7:P}/{param8:P}
  skill:
    mirrorAtk:
      - 3 # 1-Mirror Projection Attack DMG|{param3:F1P} ATK+{param4:F1P} Elemental Mastery
    mirrorEm:
      - 4 # 1-Mirror Projection Attack DMG|{param3:F1P} ATK+{param4:F1P} Elemental Mastery
    rushAtk:
      - 0 # Rush Attack DMG|{param0:F1P} ATK+{param1:F1P} Elemental Mastery
    rushEm:
      - 1 # Rush Attack DMG|{param0:F1P} ATK+{param1:F1P} Elemental Mastery
  burst:
    burstAtk:
      - 0 # Single-Instance DMG|{param0:F1P} ATK+{param1:F1P} Elemental Mastery
    burstEm:
      - 1 # Single-Instance DMG|{param0:F1P} ATK+{param1:F1P} Elemental Mastery
