use: pipeline
kind: character
name: alhaitham

override:
  icd_group:
    AlhaithamExtraAttack:
      name: Alhatham_ExtraAttack
    AlhaithamProjectionAttack:
      name: Alhatham_ForlornLotus

shortcuts:
  - haitham

combat:
  icd_groups:
    - AlhaithamExtraAttack
    - AlhaithamProjectionAttack

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG)
      - attack(4-Hit DMG)
      - attack(5-Hit DMG)
  - charge:
      - attack(Charged Attack DMG)
      - attack(Charged Attack DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - rushAtk: skill(Rush Attack DMG)
  - rushEm: skill(Rush Attack DMG|1)
  - mirrorAtk: skill(1-Mirror Projection Attack DMG)
  - mirrorEm: skill(1-Mirror Projection Attack DMG|1)

  - burstAtk: burst(Single-Instance DMG)
  - burstEm: burst(Single-Instance DMG|1)

docs:
  fields:
    .alhaitham.c2-stacks: Number of C2 stacks that are currently active.
    .alhaitham.mirrors: Current number of Mirrors that Alhaitham has.
  frames:
    - count: https://docs.google.com/spreadsheets/d/1qznqZMkFRRFKpzEXvQ_bJAXoleI2BrV-nKNAusJoYrU/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/zqm1ypb3qUo
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: kolibri._.
      video: https://youtu.be/Y4y_fElmrmo
      video_credit: kolibri._.

abilities:
  - name: attack
    hitbox:
      - name: E-N1
        shape: Circle
        center: Player
        offset: [0, -0.1]
        fan_angle: 180
        radius: 2.5
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: E-N2
        shape: Box
        center: Player
        offset: [0, -0.1]
        box: [2, 2.5]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: E-N3-1
        shape: Box
        center: Player
        box: [2, 3]

      - name: E-N3-2
        shape: Box
        center: Player
        box: [2, 3]
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

      - name: E-N4
        shape: Box
        center: Player
        box: [3, 4.5]

      - name: E-N5
        shape: Circle
        center: Player
        offset: [0, 2.2]
        radius: 2.5
        hitlag: {time: 0.02, scale: 0.01, defense_halt: true}

  - name: charge
    note: Need to use attack right before charge.
    hitbox:
      - name: E-CA-1
        shape: Circle
        center: Player
        radius: 2.5

      - name: E-CA-2
        shape: Circle
        center: Player
        radius: 2.5

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: E-Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: E-Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

      - name: E-High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be skill[hold=1] or a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg. Does not apply to low_plunge from skill[hold=1].
      short: 0 for normal low plunge (default), 1 for short low plunge. The short version is 20 frames shorter.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    params:
      hold: 0 for Tap (default), 1 for Hold.
    hitbox:
      - name: E-Initial
        shape: Circle
        center: Player
        offset: [0.01, 1]
        radius: 2.25
        hitlag: {time: 0.04, scale: 0.01, defense_halt: true}

      - name: E-1-Mirror
        shape: Box
        center: Player
        box: [7, 3]

      - name: E-2-Mirror-1
        shape: Circle
        center: Player
        offset: [0, -0.1]
        fan_angle: 180
        radius: 5.5

      - name: E-2-Mirror-2
        shape: Circle
        center: Player
        offset: [0, -0.1]
        fan_angle: 180
        radius: 5.5

      - name: E-3-Mirror-1
        shape: Circle
        center: Player
        offset: [0, 4]
        radius: 4

      - name: E-3-Mirror-2
        shape: Circle
        center: Player
        offset: [0, 4]
        radius: 4

      - name: E-3-Mirror-3
        shape: Circle
        center: Player
        offset: [0, 4]
        radius: 4

  - name: burst
    hitbox:
      - name: Q
        shape: Circle
        center: Player
        offset: [0, 7.1]
        radius: 6.8
