id: 10000078
key: "alhaitham"
rarity: QUALITY_ORANGE
body: BODY_MALE
region: ASSOC_TYPE_SUMERU
element: Grass
weapon_class: WEAPON_SWORD_ONE_HAND
icon_name: "UI_AvatarIcon_Alhatham"
stats: {
   base_hp: 1039.1188
   base_atk: 24.3922
   base_def: 60.84711
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_GRASS_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 890.95044
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 52.1721
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 20.912579
      }
      add_props: {
         prop_type: FIGHT_PROP_GRASS_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1523.9941
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 89.24175
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 35.771515
      }
      add_props: {
         prop_type: FIGHT_PROP_GRASS_ADD_HURT
         value: 0.072
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2368.0525
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 138.66795
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 55.58343
      }
      add_props: {
         prop_type: FIGHT_PROP_GRASS_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3001.0962
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 175.7376
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 70.44237
      }
      add_props: {
         prop_type: FIGHT_PROP_GRASS_ADD_HURT
         value: 0.144
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3634.14
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 212.80725
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 85.30131
      }
      add_props: {
         prop_type: FIGHT_PROP_GRASS_ADD_HURT
         value: 0.216
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 4267.1836
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 249.8769
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 100.16024
      }
      add_props: {
         prop_type: FIGHT_PROP_GRASS_ADD_HURT
         value: 0.288
      }
   }
}
skill_details: {
   skill: 10782
   burst: 10785
   attack: 10781
   burst_energy_cost: 70
}
name_text_hash_map: 4002157418
