name: "Deploy WASM"
description: "builds and deploys the gcsim WASM binary to cloudflare R2"
inputs:
  rcloneConfig:
    required: true
    description: rclone config for cloudflare R2
  branch:
    required: true
    description: name of the branch
  shareKey:
    required: true
    description: "key for signing share results"

runs:
  using: composite
  steps:
  - name: Build WASM
    working-directory: ./cmd/wasm
    shell: bash
    run: ./build.sh -o ./dist/$GITHUB_SHA/main.wasm
    env:
      GCSIM_SHARE_KEY: ${{ inputs.shareKey }}

  - name: Upload to R2
    uses: AnimMouse/setup-rclone@v1 
    env:
      RCLONE_CONF: ${{ inputs.rcloneConfig }}
  - name: sync
    shell: bash
    run: rclone sync ./cmd/wasm/dist/ r2rclone:wasm/${{ inputs.branch }}/ --progress 