use: pipeline
kind: weapon
name: messenger

abilities:
  - name: default
    hitbox:
      - name: Messenger
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Single
        center: GlobalValue
