use: pipeline
kind: weapon
name: filletblade

abilities:
  - name: default
    hitbox:
      - name: Fillet Blade
        note: Spawns on the enemy that the weapon proc'd on.
        shape: Single
        center: GlobalValue
