name: "Deploy Taghelper"
description: "builds and deploys the simpact taghelper to cloudflare. Assumes pnpm setup has already ran"
inputs:
  apiToken:
    required: true
    description: cloudflare api token
  accountId:
    required: true
    description: cloudflare account id

runs:
  using: composite
  steps:
    - name: Build UI
      working-directory: ./ui
      shell: bash
      run: pnpm build:taghelper

    - name: List UI dist
      working-directory: ./ui/packages/taghelper/dist
      shell: bash
      run: ls -lh

    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@v4
      with:
        apiToken: ${{ inputs.apiToken }}
        accountId: ${{ inputs.accountId }}
        workingDirectory: "./ui/packages/taghelper"
        packageManager: pnpm
        command: deploy --keep-vars
