id: 10000021
key: "amber"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_MONDSTADT
element: Fire
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Ambor"
stats: {
   base_hp: 793.2582
   base_atk: 18.6984
   base_def: 50.358
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 592.6045
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 37.62
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 13.96899
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1013.6655
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 64.35
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 23.894325
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1575.0803
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 99.99
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 37.128105
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1996.1414
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 126.72
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 47.05344
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2417.2024
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 153.45
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 56.978775
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2838.2634
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 180.18
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 66.90411
      }
      add_props: {
         prop_type: FIGHT_PROP_ATTACK_PERCENT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10032
   burst: 10017
   attack: 10041
   burst_energy_cost: 40
}
name_text_hash_map: 1966438658
