use: pipeline
kind: character
name: yanfei

combat:
  icd_tags:
    - YanfeiFire

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
  - charge:
      - attack(Charged Attack)
      - attack(Charged Attack|1)
      - attack(Charged Attack|2)
      - attack(Charged Attack|3)
      - attack(Charged Attack|4)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skill: skill(Skill DMG)

  - burst: burst(Skill DMG)
  - burstBonus: burst(Charged Attack DMG Bonus)

docs:
  fields:
    .yanfei.seal-count: Number of Scarlet Seals.
  frames:
    - count: https://docs.google.com/spreadsheets/d/1NslqbafUoW4rhl1D2oVeSsn0SXfvAwnxAlIlwvKY_5Q/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/O43Ws1bgyXY
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/16ZDmEBZOD4xeUcodxFJVuLC7IIqM9LGLilkct65mElg/edit?usp=sharing
      count_credit: kolibri._.
      video: https://youtu.be/SRfExbRwUx4
      video_credit: kolibri._.

abilities:
  - name: attack
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: N1
        shape: Circle
        center: PrimaryTarget
        radius: 0.75

      - name: N2
        shape: Circle
        center: PrimaryTarget
        radius: 0.75

      - name: N3
        shape: Circle
        center: PrimaryTarget
        radius: 0.75

  - name: charge
    hitbox:
      - name: CA-0Stack
        shape: Circle
        center: PrimaryTarget
        radius: 2.5

      - name: CA-1Stack
        shape: Circle
        center: PrimaryTarget
        radius: 3

      - name: CA-2Stack
        shape: Circle
        center: PrimaryTarget
        radius: 3.5

      - name: CA-3Stack
        shape: Circle
        center: PrimaryTarget
        radius: 4

      - name: CA-4Stack
        shape: Circle
        center: PrimaryTarget
        radius: 4

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        radius: 1.5

      - name: Low_Plunge
        shape: Circle
        center: Player
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        radius: 3.5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    hitbox:
      - name: E-Skill
        shape: Circle
        center: PrimaryTarget
        radius: 3.5

  - name: burst
    hitbox:
      - name: Q-ElementalBurst
        shape: Circle
        center: Player
        radius: 6.5
        hitlag: {scale: 0.01, defense_halt: true}

  - name: asc
    hitbox:
      - name: A4
        note: Spawns on target that A4 proc'd on.
        shape: Circle
        center: GlobalValue
        radius: 3.5
        hitlag: {scale: 0.05, defense_halt: true}

  - name: walk
    note: No action followed by walk (except low_plunge and high_plunge) has proper frames.
