package_name: yanfei
genshin_id: 10000048
key: yanfei
action_param_keys:
  attack:
    - param: "travel"
  low_plunge:
    - param: "collision"
  high_plunge:
    - param: "collision"
icd_tags:
  - ICDTagYanfeiFire
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    charge:
      - 3 # Charged Attack|{param3:P}/{param4:P}/{param5:P}/{param6:P}/{param7:P}
      - 4 # Charged Attack|{param3:P}/{param4:P}/{param5:P}/{param6:P}/{param7:P}
      - 5 # Charged Attack|{param3:P}/{param4:P}/{param5:P}/{param6:P}/{param7:P}
      - 6 # Charged Attack|{param3:P}/{param4:P}/{param5:P}/{param6:P}/{param7:P}
      - 7 # Charged Attack|{param3:P}/{param4:P}/{param5:P}/{param6:P}/{param7:P}
    collision:
      - 15 # Plunge DMG|{param6:F1P}
    lowPlunge:
      - 16 # Low/High Plunge DMG|{param7:P}/{param8:P}
    highPlunge:
      - 17 # Low/High Plunge DMG|{param7:P}/{param8:P}
  skill:
    skill:
      - 0 # Skill DMG|{param0:P}
  burst:
    burst:
      - 0 # Skill DMG|{param0:P}
    burstBonus:
      - 1 # Charged Attack DMG Bonus|{param1:P}

documentation:
  fields_data:
    - fields: [.yanfei.seal-count]
      desc: Number of Scarlet Seals.
