id: 10000048
key: "yanfei"
rarity: QUALITY_PURPLE
body: BODY_GIRL
region: ASSOC_TYPE_LIYUE
element: Fire
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Feiyan"
stats: {
   base_hp: 784.14026
   base_atk: 20.12304
   base_def: 49.2135
   hp_curve: GROW_CURVE_HP_S4
   atk_curve: GROW_CURVE_ATTACK_S4
   def_cruve: GROW_CURVE_HP_S4
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 585.7929
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 36.765
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 15.033294
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1002.0142
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 62.8875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 25.714846
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
         value: 0.06
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1556.976
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 97.7175
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 39.956913
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1973.1973
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 123.84
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 50.638466
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
         value: 0.12
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2389.4185
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 149.9625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 61.320015
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
         value: 0.18
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2805.64
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 176.085
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 72.001564
      }
      add_props: {
         prop_type: FIGHT_PROP_FIRE_ADD_HURT
         value: 0.24
      }
   }
}
skill_details: {
   skill: 10482
   burst: 10485
   attack: 10481
   burst_energy_cost: 80
}
name_text_hash_map: 697277554
