name: Mirror branch

on:
  push:
    branches: [ main ]

jobs:
  mirror-to-master:
    runs-on: ubuntu-latest
    steps:
    - uses: zofrex/mirror-branch@v1
      with:
        # mirror main to v2
        target-branch: v2