name: "build cmd line tool"
on:
  push:
    branches:
      - main

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: go-setup-and-test
        uses: ./.github/actions/go-setup-and-test
      - name: deploy-binary
        uses: ./.github/actions/deploy-binary
        with:
          prerelease: true
          shareKey: ${{ secrets.AES_KEY }}