name: run tests

on: [push, pull_request]

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: go-setup-and-test
      uses: ./.github/actions/go-setup-and-test
  test-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: yarn-setup-and-test
      uses: ./.github/actions/yarn-setup-and-test