name: run tests

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.txt"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.txt"

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - name: go-setup-and-test
      uses: ./.github/actions/go-setup-and-test
  test-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - name: yarn-setup-and-test
      uses: ./.github/actions/yarn-setup-and-test