name: run tests

on:
  pull_request:

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/go-setup-and-test
  test-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/yarn-setup-and-test