name: "update web"
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: http request
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{secrets.PAT_TOKEN}}" \
            https://api.github.com/repos/genshinsim/gcsim.app/dispatches \
            -d '{"event_type":"backend_automation"}'
