use: pipeline
kind: character
name: wanderer

override:
  icd_group:
    WandererA4:
      name: Wanderer_PermanentSkill_2
    WandererC6:
      name: Wanderer_Constellation_6

shortcuts:
  - kabukimono
  - kuni
  - kunikuzushi
  - scara
  - scaramouche

combat:
  icd_tags:
    - WandererA4
    - WandererC6
  icd_groups:
    - WandererA4
    - WandererC6

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - - attack(3-Hit DMG)
        - attack(3-Hit DMG)
  - charge: attack(Charged Attack DMG)
  - plunge: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skill: skill(Skill DMG)
  - skillNABonus: 'skill(Kuugo: Fushoudan DMG)'
  - skillCABonus: 'skill(Kuugo: Toufukai DMG)'

  - burst: burst(Skill DMG)

docs:
  fields:
    .wanderer.skydweller-points: Amount of Kuugoryoku Points that Wanderer has. A value greater than 0 indicates that Wanderer is in the Windfavored state.
  frames:
    - count: https://docs.google.com/spreadsheets/d/1UaDmefkw0AsA-sV1oc6Ya4SYRUZEv_deExY4H30RV4U/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/PrGKTV3cOm4
      video_credit: Kolibri#7675

abilities:
  - name: attack
    params:
      travel: Projectile travel time. Default 5 frames.
    hitbox:
      - name: N1
        shape: Circle
        center: PrimaryTarget
        radius: 1

      - name: N2
        shape: Circle
        center: PrimaryTarget
        radius: 1

      - name: N3-1
        shape: Circle
        center: PrimaryTarget
        radius: 1

      - name: N3-2
        shape: Circle
        center: PrimaryTarget
        radius: 1

      - name: E-N1
        shape: Circle
        center: PrimaryTarget
        radius: 2.5

      - name: E-N2
        shape: Circle
        center: PrimaryTarget
        radius: 2.5

      - name: E-N3-1
        shape: Circle
        center: PrimaryTarget
        radius: 3

      - name: E-N3-2
        shape: Circle
        center: PrimaryTarget
        radius: 3

  - name: charge
    hitbox:
      - name: CA
        shape: Circle
        center: PrimaryTarget
        radius: 2.5

      - name: E-CA
        shape: Circle
        center: PrimaryTarget
        radius: 3.5

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        radius: 1.5

      - name: Low_Plunge
        shape: Circle
        center: Player
        radius: 3

  - name: low_plunge
    note: Only available for a short time after Windfavored state ends.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    hitbox:
      - name: E-Initial
        shape: Circle
        center: Player
        radius: 6

  - name: burst
    hitbox:
      - name: Q
        shape: Circle
        center: PrimaryTarget
        radius: 5

  - name: asc
    hitbox:
      - name: A1-AbsorbCheck
        shape: Circle
        center: Player
        radius: 6

      - name: A4
        shape: Circle
        center: Player
        radius: 1

  - name: cons
    hitbox:
      - name: C6-N1
        note: Spawns at the target hit by the N1.
        shape: Circle
        center: GlobalValue
        radius: 2

      - name: C6-N2
        shape: Circle
        center: GlobalValue
        radius: 2

      - name: C6-N3-1
        shape: Circle
        center: GlobalValue
        radius: 2

      - name: C6-N3-2
        shape: Circle
        center: GlobalValue
        radius: 2

  - name: swap
    note: Swapping while Windfavored state is active is not legal.
