id: 10000075
key: "wanderer"
rarity: QUALITY_ORANGE
body: BODY_BOY
region: ASSOC_TYPE_SUMERU
element: Wind
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Wanderer"
stats: {
   base_hp: 791.2556
   base_atk: 25.5094
   base_def: 47.2657
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 678.4301
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 40.527
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.870405
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1160.4725
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 69.3225
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 37.409904
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1803.1959
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 107.7165
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 58.12924
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2285.2383
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 136.512
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 73.66874
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2767.2808
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 165.3075
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 89.20824
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3249.3232
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 194.103
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 104.747734
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10752
   burst: 10755
   attack: 10751
   burst_energy_cost: 60
}
name_text_hash_map: 3230559562
