use: pipeline
kind: character
name: yoimiya

shortcuts:
  - yoi

talents:
  - attack:
      - - attack(1-Hit DMG)
        - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - - attack(4-Hit DMG)
        - attack(4-Hit DMG)
      - attack(5-Hit DMG)
  - aim: attack(Aimed Shot)
  - fullaim: attack(Fully-Charged Aimed Shot)
  - aimExtra: attack(Kindling Arrow DMG)

  - skill: skill(Blazing Arrow DMG)

  - burst: burst(Skill DMG)
  - burstExplode: burst(Aurous Blaze Explosion DMG)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/1DYYiGSNeFekVt3eQQC_MujkLCd_8rgPIIlpPNvwHKTA/edit?usp=sharing
      count_credit: Kurt#5846
      video: https://youtu.be/UNo3Q-DPmbM
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/1zCwdd6_KYFqMD4OQ_llGLdDshoZTu_1pmAMysxGDQvs/edit?usp=sharing
      count_credit: Kolibri#7675
      video: https://youtu.be/KlgZlck5kQQ?t=1773
      video_credit: Kolibri#7675
    - count: https://docs.google.com/spreadsheets/d/187T-SngEZUUordjY_K_tF_DdvHjQju9CoBJdp2eJOis/edit?usp=sharing
      count_credit: bowtae
      video: https://youtu.be/qU2qR_ypyeo
      video_credit: bowtae
    - count: https://docs.google.com/spreadsheets/d/187T-SngEZUUordjY_K_tF_DdvHjQju9CoBJdp2eJOis/edit?usp=sharing
      count_credit: bowtae
      video: https://youtu.be/jGrnAhwqMGE
      video_credit: bowtae
    - count: https://docs.google.com/spreadsheets/d/187T-SngEZUUordjY_K_tF_DdvHjQju9CoBJdp2eJOis/edit?usp=sharing
      count_credit: bowtae
      video: https://youtu.be/6xpVvqU8ma4
      video_credit: bowtae

abilities:
  - name: attack
    params:
      travel: Projectile travel time. Default 10 frames.
    hitbox:
      - name: N1
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N2
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N3
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N4
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: N5
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: E-N1
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: E-N2
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: E-N3
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: E-N4
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: E-N5
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

  - name: aim
    params:
      hold: 0 for Physical Aimed Shot, 1 for Fully-Charged Aimed Shot (default), 2/3/4 for Fully-Charged Aimed Shot (1/2/3 Kindling Arrow).
      kindling_travel: Kindling Arrow travel time. Default 30 frames.
      travel: Projectile travel time. Default 10 frames.
      weakspot: Hit weakspot with aimed shot. Default 0 (false), 1 for true.
    hitbox:
      - name: Aim
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: Aim-Head
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]
        hitlag: {time: 0.12, scale: 0.01, deployable: true}

      - name: FullAim-Lv.1
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]

      - name: FullAim-Lv.1-Head
        shape: Box
        center: PrimaryTarget
        offset: [0, -0.5]
        box: [0.1, 1]
        hitlag: {time: 0.12, scale: 0.01, deployable: true}

      - name: FullAim-Lv.2
        shape: Circle
        center: PrimaryTarget
        radius: 0.6

  - name: skill
    hitbox:
      - name: E-Start
        note: not implemented yet
        shape: Circle
        center: Player
        radius: 2

  - name: burst
    hitbox:
      - name: Q-Initial
        shape: Circle
        center: PrimaryTarget
        radius: 6

      - name: Q-AurousBlaze
        note: Spawns on first target hit by Q-Initial.
        shape: Circle
        center: GlobalValue
        radius: 3

  - name: walk
    note: Only aim followed by walk has proper frames.
