id: 10000049
key: "yoimiya"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_INAZUMA
element: Fire
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Yoimiya"
stats: {
   base_hp: 791.2556
   base_atk: 25.137
   base_def: 47.864
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 678.4301
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 41.04
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.55113
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1160.4725
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 70.2
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 36.863773
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1803.1959
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 109.08
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 57.280636
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2285.2383
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 138.24
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 72.59328
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2767.2808
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 167.4
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 87.90592
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3249.3232
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 196.56
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 103.21857
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10492
   burst: 10495
   attack: 10491
   burst_energy_cost: 60
}
name_text_hash_map: 2504399314
