id: 10000084
key: "lyney"
rarity: QUALITY_ORANGE
body: BODY_BOY
region: ASSOC_TYPE_FONTAINE
element: Fire
weapon_class: WEAPON_BOW
icon_name: "UI_AvatarIcon_Liney"
stats: {
   base_hp: 857.988
   base_atk: 24.7646
   base_def: 41.881
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 735.64716
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 35.91
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 21.231853
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1258.3438
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 61.425
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 36.317646
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.048
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1955.2726
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 95.445
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 56.432034
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2477.9692
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 120.96
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 71.51782
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.096
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3000.666
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 146.475
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 86.603615
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.144
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3523.3625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 171.99
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 101.68941
      }
      add_props: {
         prop_type: FIGHT_PROP_CRITICAL
         value: 0.192
      }
   }
}
skill_details: {
   skill: 10842
   burst: 10845
   attack: 10841
   burst_energy_cost: 60
}
name_text_hash_map: 2472444970
