id: 10000041
key: "mona"
rarity: QUALITY_ORANGE
body: BODY_GIRL
region: ASSOC_TYPE_MONDSTADT
element: Water
weapon_class: WEAPON_CATALYST
icon_name: "UI_AvatarIcon_Mona"
stats: {
   base_hp: 810.322
   base_atk: 22.344
   base_def: 50.8555
   hp_curve: GROW_CURVE_HP_S5
   atk_curve: GROW_CURVE_ATTACK_S5
   def_cruve: GROW_CURVE_HP_S5
   promo_data: {
      max_level: 20
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
      }
   }
   promo_data: {
      max_level: 40
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 694.77783
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 43.605
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 19.15656
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
      }
   }
   promo_data: {
      max_level: 50
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1188.4358
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 74.5875
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 32.7678
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.08
      }
   }
   promo_data: {
      max_level: 60
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 1846.6464
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 115.8975
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 50.91612
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.16
      }
   }
   promo_data: {
      max_level: 70
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2340.3042
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 146.88
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 64.52736
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.16
      }
   }
   promo_data: {
      max_level: 80
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 2833.9622
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 177.8625
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 78.1386
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.24
      }
   }
   promo_data: {
      max_level: 90
      add_props: {
         prop_type: FIGHT_PROP_BASE_HP
         value: 3327.62
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_DEFENSE
         value: 208.845
      }
      add_props: {
         prop_type: FIGHT_PROP_BASE_ATTACK
         value: 91.74984
      }
      add_props: {
         prop_type: FIGHT_PROP_CHARGE_EFFICIENCY
         value: 0.32
      }
   }
}
skill_details: {
   skill: 10412
   burst: 10415
   attack: 10411
   burst_energy_cost: 60
}
name_text_hash_map: 1113306282
