package_name: mona
genshin_id: 10000041
key: mona
action_param_keys:
  dash:
    - param: "f"
  skill:
    - param: "hold"
icd_tags:
  - ICDTagMonaWaterDamage
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    attack_4:
      - 3 # 4-Hit DMG|{param3:F1P}
    charge:
      - 4 # Charged Attack DMG|{param4:P}
  skill:
    skill:
      - 1 # Explosion DMG|{param1:P}
    skillDot:
      - 0 # DoT|{param0:F1P}
  burst:
    dmgBonus:
      - 9 # DMG Bonus|{param9:P}
    explosion:
      - 1 # Illusory Bubble Explosion DMG|{param1:P}
    omenDuration:
      - 3 # Omen Duration|{param3:F1}s
