use: pipeline
kind: character
name: emilie

override:
  icd_group:
    EmilieLumidouce:
      damage: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
      durability: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
      timer: 2

combat:
  icd_tags:
    - EmilieLumidouce
  icd_groups:
    - EmilieLumidouce

talents:
  - attack:
      - attack(1-Hit DMG)
      - attack(2-Hit DMG)
      - attack(3-Hit DMG)
      - attack(4-Hit DMG)
  - charge: attack(Charged Attack DMG)
  - collision: attack(Plunge DMG)
  - lowPlunge: attack(Low/High Plunge DMG)
  - highPlunge: attack(Low/High Plunge DMG|1)

  - skillDMG: skill(Skill DMG)
  - skillLumidouce:
      - skill(Level 1 Lumidouce Case Attack DMG)
      - skill(Level 2 Lumidouce Case Attack DMG)
  - skillDuration: skill(Lumidouce Case Duration)
  - skillArke: skill(Spiritbreath Thorn DMG)
  - skillArkeCD: skill(Spiritbreath Thorn Interval)
  - skillCD: skill(Skill CD)

  - burstDMG: burst(Level 3 Lumidouce Case Attack DMG)
  - burstDuration: burst(Level 3 Lumidouce Case Duration)
  - burstCD: burst(CD)

docs:
  frames:
    - count: https://docs.google.com/spreadsheets/d/13BRInR8UcX7PAn4yj7sVx9OQo6IGgyO7lweNMdAfjpU/edit?usp=sharing
      count_credit: imring
      video: https://youtu.be/TOWAdEeSXPc
      video_credit: ._keng

abilities:
  - name: attack
    hitbox:
      - name: N1
        shape: Circle
        center: PrimaryTarget
        offset: [0, 0.4]
        radius: 2
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N2
        shape: Box
        center: PrimaryTarget
        box: [1.6, 3]
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N3
        shape: Circle
        center: PrimaryTarget
        offset: [0, 0.4]
        radius: 2.5
        hitlag: {time: 0.06, scale: 0.01, defense_halt: true}

      - name: N4
        shape: Circle
        center: PrimaryTarget
        offset: [0, 0.4]
        radius: 3
        hitlag: {time: 0.09, scale: 0.01, defense_halt: true}

  - name: charge
    hitbox:
      - name: CA
        shape: Box
        center: PrimaryTarget
        offset: [0, -1.2]
        box: [3.3, 3.5]

  - name: plunge
    hitbox:
      - name: Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 1

      - name: Low_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 3

      - name: High_Plunge
        shape: Circle
        center: Player
        offset: [0, 1]
        radius: 5

  - name: low_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: high_plunge
    note: Previous action must be a jump buffed via Xianyun's burst for example.
    params:
      collision: 0 for no collision dmg (default), 1 for collision dmg.

  - name: skill
    params:
      travel: Level 1/2 Lumidouce Case Attack travel time. Default 5 frames.
    hitbox:
      - name: E-Summon
        shape: Circle
        center: Player
        offset: [0, 2.6]
        radius: 4.5

      - name: E-Spiritbreath-Thorn
        shape: Circle
        center: PrimaryTarget
        offset: [0, 2.6]
        radius: 4.5

      - name: E-Level1
        shape: Hit
        center: PrimaryTarget
        radius: 1

      - name: E-Level2
        shape: Hit
        center: PrimaryTarget
        radius: 1

  - name: burst
    params:
      travel: Level 1/2 Lumidouce Case Attack travel time. Default 5 frames.
    hitbox:
      - name: Q-Level3
        note: 'At every tick: If there are enemies within the Q detection area that are not currently marked, then it spawns at a random enemy out of those. This random enemy is then marked for 0.7s. Otherwise, it will spawn randomly between 0.5m and 12m from the Q center.'
        shape: Circle
        center: GlobalValue
        radius: 2.5

  - name: asc
    hitbox:
      - name: E-A1
        shape: Circle
        center: PrimaryTarget
        radius: 3
